### ISSUE TITLE
FR:  Add support for Debian 12

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1005]
##### SUMMARY
Debian 12 gets released on June 10th.  I fully expect Zabbix will start to support it shortly thereafter.
 
##### ISSUE TYPE
- Feature Idea

**Comment by Thulium-Drake** [comment]
It might be useful to also consider changing the format from ```.list``` to ```.sources```. In my other playbooks I use the following task:

```
- name: 'Configure Debian main repos'
  # yamllint disable rule:line-length
  ansible.builtin.copy:
    content: |
      # This file is managed by Ansible.
      # YOUR CHANGES WILL BE LOST!
      Types: deb
      URIs: {{ debian_repo_mirror }}/debian
      Suites: {{ ansible_facts['distribution_release'] }} {{ (debian_testing) | ternary('', ansible_facts['distribution_release'] + '-updates') }} {{ (debian_backports_enabled) | ternary(ansible_facts['distribution_release'] + '-backports', '') }}
      Components: {{ debian_repo_components }}

      Types: deb
      URIs: {{ debian_repo_mirror }}/debian-security
      Suites: {{ ansible_facts['distribution_release'] }}-security
      Components: {{ debian_repo_components }}
    dest: '/etc/apt/sources.list.d/debian.sources'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Update apt cache'
```
