### ISSUE TITLE
FR: Use deb file and rpm file to update repo info

### ISSUE THREAD

**Issue by masa-orca** [ansible-collections/community.zabbix#1031]
##### SUMMARY

I read [Zabbix official install document](https://www.zabbix.com/download?zabbix=6.4&os_distribution=alma_linux&os_version=9&components=agent&db=&ws=).
In this document, we use rpm file for RHEL family and deb file for Debian to updtate repo info. I think we should follow this. 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- all role
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by pyrodie18** [comment]
We do that already.  I suspect you are talking about the step:
```
# rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
# dnf clean all
```
In the agent documentation for example.  All this RPM does is simply add the repo to the apt or yum configuration which is what we're doing at the top of the RedHat.yml file in the agents role

```
- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    mode: "{{ item.mode | default('0644') }}"
    priority: "{{ item.priority | default('98') }}"
    state: "{{ item.state | default('present') }}"
    proxy: "{{ zabbix_http_proxy | default(omit) }}"
  with_items: "{{ zabbix_repo_yum }}"
  register: yum_repo_installed
  become: true
  notify:
    - "clean repo files from proxy creds"
  tags:
    - install
```

After that we use the yum or apt module in ansible to install the actual program RPMs.  This is done this way to allow additional configurations of the repo for various use cases that fall outside of the default install of the repo RPM, but the end result is exactly the same.

If I'm off though, please let me knowl.
