### ISSUE TITLE
Improve security by creating multiple roles when using the default Ansible-created database tables

### ISSUE THREAD

**Issue by beargiles** [ansible-collections/community.zabbix#1032]
##### SUMMARY

Improve security by creating multiple roles when using the default Ansible-created database tables.

##### ISSUE TYPE
- Feature Idea
- Security enhancement

##### COMPONENT NAME

zabbix_server

##### ADDITIONAL INFORMATION

A standard mechanism to reduce the damage due to SQL injection attacks - and even attacks by attackers with access to valid credentials - is to use (at least) three different database roles that each have the minimum privileges required for their work.

Zabbix should follow the same convention since it contains information that can be used to detect and remediate successful attacks on any monitored systems. It is easy for a sophisticated attacker to detect the presence of the **zabbix agent** and (with sufficient access) use those credentials in an attempt to remove evidence of their presence.

(They could still push bogus data, e.g., to incriminate innocent third parties.)

The usual three roles are:

- **app_owner** - this role owns the database and all tables but is only used to create and update the schema. This role is only used by a dedicated app - never the application. It will often lack any access to the actual contents of the table, although it might require temporary access for hardcoded tables (e.g., a list of states that's used in a pulldown menu.)
- **app_user** - this role has CRUD privileges for most files but absolutely no ability to modify the schema. It should only have **READ** access to any tables used in the UI, e.g., a list of states used in a pulldown menu.
- **app_reader** - this role is limited to SELECT statements. It should often be the default role but the implication can be complicated if a caching database abstraction layer is used.

In an ideal world applications would use additional roles that allow access to be limited to specific tables. E.g., the authentication details could be accessed by a role only used when creating or updating authentication details. The other accounts in the application will not have access to this role. (Even better would be authentication handled by a separate microservice! No role available in the application would have access to this information.)

Another example - I'm a big proponent of separate **app_ui_owner** and **app_ui** roles that has exclusive access to anything that is used by the UI. It prevents defacement of the website via SQL injection.

For zabbix it's clear that the **user** role can be split into

- **agent** - can **READ** records for configuration details and can **CREATE** records in appropriate tables but nothing else. This is important since the **agent** credentials need to be widely distributed.
- **server** - can **CRUD** configuration details but only **READ** or **DELETE** the records created by the **agent** role. Can **CRUD** accounts, etc.
- **website** - can **READ** configuration details and **agent** records. Can request the server to perform **CRUD** on accounts, etc.

(The latter might not be possible without refactoring the code - I haven't checked whether it's already making REST calls or directly updating the database.  Any REST calls would still need to perform input validation to avoid SQL injection attacks but that's easier to enforce since it makes it impossible for someone to add a "temporary" SQL query that isn't properly vetted and isn't removed when it's no longer needed.)

A possible improvement is removing the **DELETE** access for records created by the **agent** role. It would be replaced by a separate **reaper** role and app that periodically deletes old records. A successful attacker might be able to modify or remove alerts but would not be able to delete the underlying data. 

Note: the examples assume all roles are now defined in a list. A dict would probably
be better since we could use "db_roles['owner']" when creating the schema and
privileges.

```yaml
- name: "Define users"
  ansible.builtin.set_fact:
      - name: "{{ zabbix_server_dbowner | default(zabbix_server_dbuser) }}"
        password: "{{ zabbix_server_dbowner_password | default(zabbix_server_dbpassword }}"
        priv: '{{ zabbix_server_dbowner_priv | default('ALL') }}"
      - name: "{{ zabbix_server_dbuser }}"
        password: "{{ zabbix_server_dbpassword) }}"
        priv: '{{ zabbix_server_dbuser_priv | default('ALL') }}"
      - name: "{{ zabbix_server_dbagent | default(zabbix_server_dbuser) }}"
        password: "{{ zabbix_server_dbagent_password | default(zabbix_server_dbuser) }}"
        priv: '{{ zabbix_server_dbagent_priv | default('ALL') }}"
      - name: "{{ zabbix_server_dbwebsite | default(zabbix_server_dbuser) }}"
        password: "{{ zabbix_server_dbwebsite_password | default(zabbix_server_dbuser) }}"
        priv: '{{ zabbix_server_dbwebsite_priv | default('ALL') }}"
```

For backwards compatibility the privileges are defaulting to 'ALL' but they should match
the discussion above. Since some are table-specific the privileges must be provided **after**
the schema and tables have been created.

Updated plays to create users and schema.

```yaml
- name: "PostgreSQL | Delegated"
  block:
    - name: "PostgreSQL | Delegated | Create database"
      community.postgresql.postgresql_db:
        name: "{{ zabbix_server_dbname }}"
        port: "{{ zabbix_server_dbport }}"
        state: present
    - name: "PostgreSQL | Delegated | Create timescaledb extension"
      community.postgresql.postgresql_ext:
        db: "{{ zabbix_server_dbname }}"
        name: timescaledb
      when: zabbix_server_database_timescaledb

    # This is now a loop
    - name: "PostgreSQL | Delegated | Create database users"
      community.postgresql.postgresql_user:
        db: "{{ zabbix_server_dbname }}"
        name: "{{ role.name }}"
        password: "md5{{ (role.password + role.name)|hash('md5') }}"
        port: "{{ zabbix_server_dbport }}"
        # priv: "{{ role.priv }}"  <-- do not set privileges here!
        state: present
        encrypted: true
    loop: '{{ db_roles }}'
    loop_control:
      loop_var: role
  become: true
  become_user: postgres
  delegate_to: "{{ delegated_dbhost }}"
  when:
    - zabbix_server_database_creation
    - zabbix_server_pgsql_login_host is not defined
  tags:
    - database

- name: "PostgreSQL | Create schema"
  shell: |
    set -euxo pipefail
    FILE={{ 'create.sql' if zabbix_server_version is version('6.0', '<') else 'server.sql' }}
    cd {{ datafiles_path }}
    if [ -f ${FILE}.gz ]
      then zcat ${FILE}.gz > /tmp/create.sql
    else
      cp ${FILE} /tmp/create.sql
    fi
    cat /tmp/create.sql | psql -h '{{ zabbix_server_dbhost }}' \
    -U '{{ zabbix_server_dbowner | default(zabbix_server_dbuser) }}' \
    -d '{{ zabbix_server_dbname }}' \
    -p '{{ zabbix_server_dbport }}'
    touch /etc/zabbix/schema.done
    rm -f /tmp/create.sql
  args:
    creates: /etc/zabbix/schema.done
    executable: /bin/bash
    warn: "{{ produce_warn | default(omit) }}"
  environment:
    PGPASSWORD: "{{ zabbix_server_dbowner_password  | default(zabbix_server_dbpassword) }}"
  become: true
  when:
    - zabbix_server_database_sqlload
  tags:
    - database

# It would be better to handle this in the 'server.sql' script. It would
# need to become a template that performs the required substitutions
# for the role names.
- name: "PostgreSQL | Delegated"
  block:
    - name: "PostgreSQL | Delegated | Update user privileges"
      community.postgresql.postgresql_user:
        db: "{{ zabbix_server_dbname }}"
        name: "{{ role.name }}"
        priv: "{{ role.priv }}"  <-- set privileges here
    loop: '{{ db_roles }}'
    loop_control:
      loop_var: role
  become: true
  become_user: postgres
  delegate_to: "{{ delegated_dbhost }}"
  when:
    - zabbix_server_database_creation
    - zabbix_server_pgsql_login_host is not defined
  tags:
    - database
```

I don't think the applications will need to be modified - if the privileges are accurate it should be enough for the respective configuration files to provide the appropriate credentials for the 'agent', 'server', or 'web'.
