### ISSUE TITLE
Convert Debian sources to Deb822 format

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-collections/community.zabbix#1034]
##### SUMMARY

As mentioned in #1005, Debian is adopting a new format for the APT source lists, called "Deb822"
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

All Debian repo related tasks
##### ADDITIONAL INFORMATION

In my other playbooks where I set APT sources I use the following task/template:

```
- name: 'Configure Debian main repos'
  # yamllint disable rule:line-length
  ansible.builtin.copy:
    content: |
      # This file is managed by Ansible.
      # YOUR CHANGES WILL BE LOST!
      Types: deb
      URIs: {{ debian_repo_mirror }}/debian
      Suites: {{ ansible_facts['distribution_release'] }} {{ (debian_testing) | ternary('', ansible_facts['distribution_release'] + '-updates') }} {{ (debian_backports_enabled) | ternary(ansible_facts['distribution_release'] + '-backports', '') }}
      Components: {{ debian_repo_components }}

      Types: deb
      URIs: {{ debian_repo_mirror }}/debian-security
      Suites: {{ ansible_facts['distribution_release'] }}-security
      Components: {{ debian_repo_components }}
    dest: '/etc/apt/sources.list.d/debian.sources'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Update apt cache'
```

The full description of the format is here: https://repolib.readthedocs.io/en/latest/deb822-format.html

TL;DR, One-line is supposed to be deprecated in the (near?) future, Deb822 format is the way to go. I think it's related to the deprecation of ```apt-key```. As you're now supposed to save your GPG keys and/or keyrings in ```/etc/apt/keyrings``` and use something like this:

```
deb [signed-by=/usr/share/keyrings/deriv-archive-keyring.pgp] https://deriv.example.net/debian/ stable main
```

Or in Deb822 format:

```
Types: deb
URIs: https://deriv.example.net/debian/
Suites: stable
Components: main
Signed-By: /usr/share/keyrings/deriv-archive-keyring.pgp
```

And I guess I understand, especially with all the other possible options, the one-line format is getting a bit cramped, and the multiline format allows for clearer management of sources. Though I'm not sure _when_ APT started supporting this (as to which version of Debian started supporting this and if any 'legacy' support should be maintained for now)
