### ISSUE TITLE
Problem with zabbix_agent role variables and host group vars

### ISSUE THREAD

**Issue by Kulgar** [ansible-collections/community.zabbix#1039]
For an unknown reason, some of my host group variables are "undefined" when the agent role gets executed...

By setting passwords here: 

```
    - name: "Run zabbix agent role"
      include_role:
        name: community.zabbix.zabbix_agent
      vars:
        zabbix_api_login_pass: "pwd"
        ansible_httpapi_pass: "pwd"
```

It works... 

But if I do sth like this: 

```
    - debug:
        msg: "{{ zabbix_admin_password }}"

    - name: "Run zabbix agent role"
      include_role:
        name: community.zabbix.zabbix_agent
      vars:
        zabbix_api_login_pass: "{{ zabbix_admin_password }}"
        ansible_httpapi_pass: "{{ zabbix_admin_password }}"
```

It says "zabbix_admin_password" is undefined when reaching host group creation. 
Even though the previous debug msg is totally working and displaying my password. 

But it works if I put the password variable in the "all" vars.yml file. So... the role would be ignoring my group variables? 

I digged a bit more and it is even weirder, I have the following inventory: 

```
[app]
server1

[db]
server2

[log]
server3

[preproduction]
server1
server2
server3
```

The variables set in the app/db/log groups are properly used in the zabbix agent role. 
But the ones set in the preproduction group aren't... and only for the zabbix agent role. The other roles from the collection work fine with that inventory and my group vars.

Maybe it is something silly - I don't know. If you have any clue or any idea, let me know :-)

_Originally posted by @Kulgar in https://github.com/ansible-collections/community.zabbix/issues/972#issuecomment-1564107696_

**Comment by pyrodie18** [comment]
OK, I guess I'm a little bit confused.  What file (full path) is the variable `zabbix_admin_password ` set in?  Which server(s) in your inventory are you running the agent role against?

**Comment by Kulgar** [comment]
@pyrodie18 : 

the `zabbix_admin_password` is set in the file: `group_vars/preproduction/vault.yml`
I'm running the agent role on all the servers `hosts: all` so, servers 1, 2 and 3.

In the `group_vars/app/vars.yml` file, I also have some zabbix settings, like `zabbix_host_groups` and these variables are properly used in the zabbix_agent role (host groups are properly set when running the role). 

But all the variables set for the group `preproduction` seem to be ignored, I added some debug messages when running the role, and it says the variables are undefined. 

Here are the variables I set for the preproduction group: 

```
zabbix_agent_server: "127.0.0.1,server_ip"
zabbix_admin_password: "pwd"
zabbix_api_login_pass: "{{ zabbix_admin_password }}"
ansible_httpapi_pass: "{{ zabbix_api_login_pass }}"

zabbix_agent_tags:
  - tag: environment
    value: "preproduction"
```

When running the role, zabbix_api_login_pass is undefined. 

Right now, I have to set the var files in my playbook: 

```
- name: Zabbix agents install
  hosts: all
  vars_files:
    - "../group_vars/preproduction/vars.yml"
    - "../group_vars/preproduction/vault.yml"

  become: yes

  tasks:
    - name: "Run zabbix webapp role"
      include_role:
        name: community.zabbix.zabbix_agent
```

So that the role properly uses the variables set for the preproduction group. 

Weird, isn't it?
