### ISSUE TITLE
zabbix_inventory: object has no attribute '_zapi'

### ISSUE THREAD

**Issue by gitbock** [ansible-collections/community.zabbix#1042]
After upgrading to Zabbix 6.4 and community.zabbix 2.0.1 my inventory integration stopped working with error code

```
[WARNING]:  * Failed to parse /etc/ansible/zabbix_inventory.yml with ansible_collections.community.zabbix.plugins.inventory.zabbix_inventory plugin: 'InventoryModule'
object has no attribute '_zapi'
  File "/home/xxx/.local/lib/python3.10/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/xxx/.ansible/collections/ansible_collections/community/zabbix/plugins/inventory/zabbix_inventory.py", line 449, in parse
    content = self._zapi.host.get({'selectGroups': ['name']})
```
I did some research on the code and I have now idea where the "_zapi" attribute should come from / where it should be initialized (?)
After commenting out the line
```
content = self._zapi.host.get({'selectGroups': ['name']})
```
it worked well again 👍 

<details>
  <summary>ansible-inventory -vvvv</summary>

```
ansible-inventory -vvvvv --list -i /etc/ansible/zabbix_inventory.yml 
ansible-inventory [core 2.15.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/username/.local/bin/ansible-inventory
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Reading vault password file: /home/username/.ssh/vault_pw.txt
setting up inventory plugins
Loading collection community.zabbix from /home/username/.ansible/collections/ansible_collections/community/zabbix
Loading collection ansible.builtin from 
Sending request to https://zabbix.dmz.domainname.de/api_jsonrpc.php
Sending request to https://zabbix.dmz.domainname.de/api_jsonrpc.php
Sending request to https://zabbix.dmz.domainname.de/api_jsonrpc.php
[WARNING]:  * Failed to parse /etc/ansible/zabbix_inventory.yml with ansible_collections.community.zabbix.plugins.inventory.zabbix_inventory plugin: 'InventoryModule'
object has no attribute '_zapi'
  File "/home/username/.local/lib/python3.10/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/username/.ansible/collections/ansible_collections/community/zabbix/plugins/inventory/zabbix_inventory.py", line 449, in parse
    content = self._zapi.host.get({'selectGroups': ['name']})
[WARNING]: Unable to parse /etc/ansible/zabbix_inventory.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}

```

</details>
 

<details>
  <summary>zabbix_inventory.yml</summary>

```
plugin: community.zabbix.zabbix_inventory
server_url: https://zabbix.myzabbixdomain.com
login_user: reader_zbx_user
login_password: xxxxxx
validate_certs: false
add_zabbix_groups: true
host_zapi_query:
  
  selectGroups: 'extend'
  selectInterfaces: 'extend'

    

groups:
  #linux: "ansible_linux" in zbx_groups['name']
  

compose:
  ansible_host_direct: zbx_interfaces[0].ip
  ansible_port_direct: 5986 # not from zabbix, but default for winrms
  
  # if ssh tunnel used. connect IP stored in zabbix IF #2  
  ansible_host_tunnel: zbx_interfaces[1].ip
  ansible_port_tunnel: zbx_interfaces[1].port
```

</details>

<details>
  <summary>zabbix version</summary>

```
zabbix_server (Zabbix) 6.4.3
Revision a6c7751b021 30 May 2023, compilation time: May 26 2023 08:06:08

Copyright (C) 2023 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 3.0.2 15 Mar 2022
Running with OpenSSL 3.0.2 15 Mar 2022

```` 

</details>

<details>
  <summary>zabbix community version</summary>

```
ansible-galaxy collection list | grep zabbix
community.zabbix              2.0.1  
community.zabbix              2.0.1  
```
</details>

Referenced line:

https://github.com/ansible-collections/community.zabbix/blob/b89f54b353e2c74398f89abf11304c6602fa43cf/plugins/inventory/zabbix_inventory.py#L448C39-L448C39
