### ISSUE TITLE
Delete items created by discovery rules

### ISSUE THREAD

**Issue by rabin-io** [ansible-collections/community.zabbix#1045]
##### SUMMARY
I would like to remove many discovered items which are not removed when I unlink the template from the host.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I assume item it `item` base together with host item list.

##### ADDITIONAL INFORMATION
I would like to select by host or host group or even host which match search criteria, 
and for each host, remove all item which match a pattern.

```yaml
- name: Delete items
  community.zabbix.zabbix_item:
    host_name: ExampleHost
    item: "Discovered item xyz*"
    state: absent

```
