### ISSUE TITLE
community.zabbix.zabbix_user_info doesn't work with some supported releases

### ISSUE THREAD

**Issue by ironbishop** [ansible-collections/community.zabbix#1049]
In most Zabbix releases, the user object has an `alias` property, that became `username` in the latest ones. The module should request the correct parameter based on Zabbix release. Currently supported versions are:
* v6.4: username
* v6.0: username
* v5.0: alias
* v4.0: alias

Using zabbix_user_info on Zabbix 5.0 always respond with the existing user with the lowest ID, usually Admin with id=1.

https://github.com/ansible-collections/community.zabbix/blob/4b48b1a636a96d24d213609e7c54007bc9fccc5c/plugins/modules/zabbix_user_info.py#L120C19-L120C19

task:
```
    - name: check the user
      delegate_to: zabbix_server_api # this host has the correct variables for httpapi
      community.zabbix.zabbix_user_info:
        username: "example@example.com"
```

expected result:
```
ok: [localhost -> zabbix_server_api(...)] => {
    "changed": false,
    "zabbix_user": {
        "alias": "example",
        "attempt_clock": "1653760274",
        "attempt_failed": "3",
...
}
```

actual result:
```
ok: [localhost -> zabbix_server_api(...)] => {
    "changed": false,
    "zabbix_user": {
        "alias": "Admin",
        "attempt_clock": "1653760274",
        "attempt_failed": "3",
        "medias": [],
...
}
```
