### ISSUE TITLE
PSK issues on Proxy Registration using zabbix.zabbix_proxy module

### ISSUE THREAD

**Issue by ericsysmin** [ansible-collections/community.zabbix#1057]
##### SUMMARY
The Zabbix Proxy object on Zabbix API does not use PSK it uses 1,2,3 for it's values.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_proxy 

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Any use of this module against 6.4 will product this error when PSK is enabled.

```yaml

```

##### EXPECTED RESULTS
Success

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/var/folders/d7/9m55_frs7jsc_tk_gcl7dvh00000gr/T/ansible_community.zabbix.zabbix_proxy_payload_2o0zl63p/ansible_community.zabbix.zabbix_proxy_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 29, in _httpapi_error_handle
    code, response = self.connection.send_request(data=payload)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/d7/9m55_frs7jsc_tk_gcl7dvh00000gr/T/ansible_community.zabbix.zabbix_proxy_payload_2o0zl63p/ansible_community.zabbix.zabbix_proxy_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [zabbix-proxy -> zabbix.local]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "description": null,
            "http_login_password": null,
            "http_login_user": null,
            "interface": {
                "dns": "zabbix-proxy.local",
                "ip": "10.132.21.59",
                "port": "10051",
                "useip": 1
            },
            "proxy_address": null,
            "proxy_name": "zabbix-proxy",
            "state": "present",
            "status": "active",
            "tls_accept": "PSK",
            "tls_connect": "PSK",
            "tls_psk": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tls_psk_identity": "zabbix-proxy-identity",
            "tls_subject": null
        }
    },
    "msg": "connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter \"/1/tls_connect\": value must be 1.'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"proxy.create\", \"id\": \"98eaf73a-c858-41ad-b1f3-4e9002b0920a\", \"params\": {\"host\": \"zabbix-proxy\", \"status\": \"5\", \"tls_connect\": \"2\", \"tls_accept\": \"2\", \"tls_psk_identity\": \"zabbix-proxy-identity\", \"tls_psk\": \"********\"}, \"auth\": \"43f8aeb72b9b66ecdd70dd871086aeb0\"}"
```

**Comment by chemnic** [comment]
I hit this problem with zabbix 6.0, ansible-core 2.14.10, and community.zabbix cloned from main branch.

It looks like you cannot create a new proxy with PSK, but only update it.

My workaround is first create it without PSK and then update it with PSK:

```yaml
    - name: Manage proxy server
      community.zabbix.zabbix_proxy:
        state: present
        status: active
        proxy_name: proxy-server
        proxy_address: 192.168.1.99

    - name: Manage proxy server
      community.zabbix.zabbix_proxy:
        state: present
        status: active
        proxy_name: proxy-server
        proxy_address: 192.168.1.99
        tls_accept: PSK
        tls_connect: PSK
        tls_psk_identity: proxy-server-identity
        tls_psk: 8d85b5a8ca3fd81f54402f1911c7f33a2253b33af3722720287315ad2e5012a7
```
If there are other ideas please let me know.

To devs: Is this a bug?

**Comment by invisibleninja06** [comment]
Wondering if you figured out this issue as we have something similar.
It does seem thought that the module sent the value 2 to API and it was actually the Zabbix api that refused 2 as it only accept 1.

```"tls_connect\": \"2\", \"tls_accept\": \"2\"```

**Comment by mjhgthb** [comment]
We are facing the same. However, for ur it works, when initially adding the proxy without any TLS, and add TLS in de next task. See:

```
    - name: Create Zabbix proxies NO TLS yet, as add incl TLS does not work
      community.zabbix.zabbix_proxy:
        proxy_name: "{{ item.proxy_name }}"
        description: "{{ item.description }}"
        #tls_psk: "{{ conf_PSK }}"
        #tls_psk_identity: "{{ conf_TLSPSKIdentity }}"
        #tls_connect: "{{ conf_TLSConnect }}"
        #tls_accept: "{{ conf_TLSConnect }}" # same as connect
        state: present
      with_items: "{{ zabbix_proxies }}"
      run_once: true
      register: zabbix_api_response_proxy

    - name: Edit Zabbix proxies to include TLS, as, strangely, editing an existing proxy to include TLS does work
      community.zabbix.zabbix_proxy:
        proxy_name: "{{ item.proxy_name }}"
        description: "{{ item.description }}"
        tls_psk: "{{ conf_PSK }}"
        tls_psk_identity: "{{ conf_TLSPSKIdentity }}"
        tls_connect: "{{ conf_TLSConnect }}"
        tls_accept: "{{ conf_TLSConnect }}" # same as connect
        state: present
      with_items: "{{ zabbix_proxies }}"
      run_once: true
      register: zabbix_api_response_proxy

```
