### ISSUE TITLE
API Usage in module changed with 2.0, no valid documentation

### ISSUE THREAD

**Issue by solick** [ansible-collections/community.zabbix#1073]
I used to set templates to specific hosts with the zabbix_host module until 1.9.3 with out problems like this:

```

- name: add template to host
  community.zabbix.zabbix_host:  
    host_name: "{{ inventory_hostname }}"
    link_templates: "{{ template_list }}"
    server_url: "{{ zabbix_api_server_url }}"
    login_user: "{{ zabbix_api_login_user }}"
    login_password: "{{ zabbix_api_login_pass }}". 
  become: true

```

With change to 2.0 and 2.1 this does not work anymore and I cannot find any valid documentation how to do it now.

Could anyone please help out? 

Thanks!

**Comment by awsmaythem** [comment]
i have the same problem but on adding tag
am trying the httpapi connection but not working
and the server url is on 
delegate_to: zabbix.example.com
or ansible_host: zabbix.example.com
and hosts: zabbix.example.com
all not working
`---
- name: zabbix add tag
  hosts: localhost
  become: false
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "" 
    ansible_user: "{{ zbx_user }}"
    ansible_httpapi_pass: "{{ zbx_pass }}"
  tasks:
    - name: Adding Tag to the host 
      community.zabbix.zabbix_host:
        http_login_user: "{{ zbx_user }}"
        http_login_password: "{{ zbx_pass }}"
        host_name: "{{ zabbix_host_name }}"
        tags:
          - tag: IPA
            value: Joined
          - tag: Owner
            value: IT
          - tag: OS
            value: Linux
          - tag: Type
            value: Server
          - tag: Service
            value: "{{ service_tag }}"
      delegate_to: zabbix.example.com`
please help me and @solick

**Comment by AlexSSP** [comment]
It seems that the parameter "server_url" was forgotten in the version above 2. Or it is supposed that on the Zabbix server it is necessary to install ansible with community.zabbix collection?

**Comment by solick** [comment]
does no one uses the collection like this? Ist surprising that the collection is at version 2.1 and we are the first to encounter the problem

**Comment by BGmot** [comment]
See EXAMPLES section here for zabbix_host (and for all other modules in respective files)
https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_host.py#L337

**Comment by solick** [comment]
ok i understand I have to set those variables for the task to connect to the REST API now (which looks much more complicated than before. It would be helpful to understand the reason for this.

I know want to access th API with Token but get the error password is empty. From the error it looks like it tries to authenticate with ansible user and a not set password to the API. From the example it looks like not setting ansible user and password instead setting only the ansible_zabbix_auth_key as fact before the task would be enough. Anything else I need to do to force API Token Auth instead of user/password?

**Comment by BGmot** [comment]
try
```
- name: Set API token
  set_fact:
    ansible_zabbix_auth_key: "{{ zabbix_api_token }}"

- name: add template to host
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true  # Set to true for HTTPS
    ansible_httpapi_validate_certs: true  # For HTTPS et to true to validate server's certificate
  community.zabbix.zabbix_host:
    host_name: "{{ inventory_hostname }}"
    link_templates: "{{ template_list }}"
  become: false
  delegate_to: "{{ zabbix_api_server_host }}"
```
When you set `ansible_zabbix_auth_key` then username and password are ignored.

**Comment by solick** [comment]
@BGmot as you can see in my post before I exactly did set the auth key and still get the error.

**Comment by BGmot** [comment]
Are you sure you are on 2.1 version?
Did you try my code? You missed crucial `delegate_to` and for some reason re-defined `ansible_host`.
This functionality has been tested a lot and works as expected.

**Comment by solick** [comment]
@BGmot yes I checked that community.zabbix collection 2.1.0 is installed and copy pasted your code and tested. Same result: The task tries to authenticate with username and password where username is my current ansible user and password is empty.

**Comment by BGmot** [comment]
Looks like I reproduced the issue, for some reason `set_fact` for ansible_zabbix_auth_key is not working.
Following ways to define the key work.
1. I'd recommend to put all Zabbix API related variables into `group_vars`, there are multiple ways of doing that, if you have one flat inventory file then it should be something like this:
```
---
all:
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8080
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_auth_key: "9c05f86dd0c17a83a827c0654df4381862588d9cf5c4e027acf6e07c8f00c544"
    ansible_zabbix_url_path: ""
  hosts:
    zabbix-server:
      ansible_host: 2.2.2.2
    some-host:
      ansible_host: 3.3.3.3
```
2. You can define Zabbix API variables only for Zabbix host, there are multiple ways of doing that, if you have one flat inventory file then it should be something like this:

```
---
all:
  hosts:
    zabbix-server:
      ansible_host: 2.2.2.2
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 8080
      ansible_httpapi_use_ssl: false
      ansible_httpapi_validate_certs: false
      ansible_zabbix_auth_key: "9c05f86dd0c17a83a827c0654df4381862588d9cf5c4e027acf6e07c8f00c544"
      ansible_zabbix_url_path: ""
    some-host:
      ansible_host: 3.3.3.3
```
3. Define all the variables when you execute `zabbix_host` module:
```
- hosts: all
  gather_facts: false
  tasks:
  - name: Create host in Zabbix
    vars:
      ansible_zabbix_auth_key: "9c05f86dd0c17a83a827c0654df4381862588d9cf5c4e027acf6e07c8f00c544"
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 8080
      ansible_httpapi_use_ssl: false
      ansible_httpapi_validate_certs: false
      ansible_zabbix_url_path: ""
    community.zabbix.zabbix_host:
      host_name: "{{ ansible_host }}"
      link_templates: Linux by Zabbix agent
      host_groups: Linux servers
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{ ansible_host }}"
    become: false
    delegate_to: zabbix-server
```
