### ISSUE TITLE
Zabbix server role: zabbix_server_dbpassword_hash_method is never used

### ISSUE THREAD

**Issue by loricvdt** [ansible-collections/community.zabbix#1074]
##### SUMMARY
`zabbix_server_dbpassword_hash_method` is mentioned in the server role docs but is not present in the role tasks and therefore has no effect

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix server role

##### ANSIBLE VERSION
```paste below
ansible [core 2.15.0]
  config file = /home/user/project/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
##### CONFIGURATION
```paste below
CONFIG_FILE() = /home/user/project/ansible.cfg
DEFAULT_JINJA2_EXTENSIONS(/home/user/project/ansible.cfg) = jinja2.ext.do
DEFAULT_REMOTE_USER(/home/user/project/ansible.cfg) = ansible
INTERPRETER_PYTHON(/home/user/project/ansible.cfg) = auto
```
##### OS / ENVIRONMENT / Zabbix Version
Zabbix Server 6.0
PostgreSQL database
Debian 12

##### STEPS TO REPRODUCE
```yaml
- name: Install Zabbix Server
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_server
  vars:
    zabbix_server_version: 6.0
    zabbix_server_database: pgsql
    zabbix_server_dbpassword: dbpassword
    zabbix_server_dbpassword_hash_method: scram-sha-256
```
##### EXPECTED RESULTS

Password gets saved with the SCRAM-SHA-256 hash method in the PostgreSQL database

##### ACTUAL RESULTS

Password gets saved as MD5

```bash
psql -c "SELECT rolname, rolpassword FROM pg_authid WHERE rolname='zabbix-server'"
    rolname    |             rolpassword             
---------------+-------------------------------------
 zabbix-server | md5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
