### ISSUE TITLE
zabbix_proxy role: Allow using remote dbhost without delegation

### ISSUE THREAD

**Issue by lupupitkanen** [ansible-collections/community.zabbix#108]
##### SUMMARY

At the moment delegation is always assumed, if zabbix_proxy_dbhost is not localhost.

```
# task file for mysql
- name: "Set the correct delegated_dbhost (to support MySQL db deployment on a remote dbhost)"
  set_fact:
    delegated_dbhost: "{{ zabbix_proxy_dbhost if (zabbix_proxy_dbhost != 'localhost') else inventory_hostname }}"
```

In our case, the remote MySQL server is only accessible from the actual zabbix proxy host, not from the Ansible control host. Therefore forced delegation means we are not able to use the role.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

roles/zabbix_proxy

##### ADDITIONAL INFORMATION

```
playbook.yml
- hosts: zabbix-proxy
    roles:
      - role: community.zabbix.zabbix_proxy
        zabbix_proxy_dbhost: 10.20.30.40
        zabbix_proxy_database: mysql
        zabbix_proxy_database_long: mysql
        zabbix_proxy_delegated_dbhost: False
```
