### ISSUE TITLE
zabbix_proxy role: zabbix_proxy_tls_config default not mapped from config to API

### ISSUE THREAD

**Issue by lupupitkanen** [ansible-collections/community.zabbix#109]
##### SUMMARY

Default value of the zabbix_proxy_tls_config variable does not map to zabbix_proxy config file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

roles/zabbix_proxy

##### ANSIBLE VERSION

```ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/home/user/project/ansible/inventory']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed file, DO NOT modify directly
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /usr/local/bin/vaultmaster
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'host_list', u'script', u'gcp_compute', u'hcloud', u'auto', u'yaml', u'ini', u't
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

Ansible module zabbix_proxy allows the following values for tls_accept and tls_connect paramters:

- no_encryption
- PSK
- certificate

https://docs.ansible.com/ansible/latest/modules/zabbix_proxy_module.html

But the Zabbix proxy configuration file (zabbix_proxy.conf) allows these values for TLSAccept and TLSConnect paramters instead:

- unencrypted
- psk
- cert

https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_proxy

Create proxy task cleverly tries to map the config file values to the API values here:

```
tls_accept: "{{ zabbix_proxy_tls_config[zabbix_proxy_tlsaccept if zabbix_proxy_tlsaccept else 'no_encryption'] }}"
tls_connect: "{{ zabbix_proxy_tls_config[zabbix_proxy_tlsconnect if zabbix_proxy_tlsconnect else 'no_encryption'] }}"
```

Unfortunately the zabbix_proxy_tls_config dict has incorrect keys by default and it will never work:

```
zabbix_proxy_tls_config:
  no_encryption: 'no_encryption'
  PSK: 'PSK'
  certificate: 'certificate'
```

```yaml
playbook.yml
- hosts: zabbix-proxy
    roles:
      - role: community.zabbix.zabbix_proxy
        zabbix_proxy_tlsconnect: psk
        zabbix_proxy_tlspskfile: /etc/zabbix/zabbix_proxy.psk
        zabbix_proxy_tlspsk_secret: MySecretValue
        zabbix_proxy_tlspskidentity: MySecretPSK
```

##### EXPECTED RESULTS

Zabbix Proxy created to Zabbix Server via API when zabbix_proxy_tlsconnect or zabbix_proxy_tlsaccept is set.

##### ACTUAL RESULTS

Proxy is not created because there's not match in zabbix_proxy_tls_config.

```
TASK [zabbix_proxy : Create proxy] *********************************************************************************************
fatal: [zabbixproxy-prod]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute u'psk'\n\nThe error appears to be in '/home/user/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_proxy/tasks/main.yml': line 104, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Create proxy\"\n  ^ here\n"}
```

**Comment by rockaut** [comment]
Sorry if i overlooked it but which Zabbix Version do you use?

**Comment by rockaut** [comment]
Maybe also allow the zabbix_proxy.cfg values in the modules directly and just map them to the api keys in `zabbix_proxy.py:402`
https://github.com/ansible-collections/community.zabbix/blob/dc584280b71bedf542cc487a2ea5e310f6b0a7cd/plugins/modules/zabbix_proxy.py#L402

This way @dj-wasabi wouldn't need the hackery?

**Comment by lupupitkanen** [comment]
Good thought, but I'm not sure about it. Zabbix have chosen different keys for config and API for some reason. Maybe it would be best to keep the module tied to the API to avoid confusion.

I like the mapping in zabbix_proxy_tls_config, the default just contains bug in not using the correct config file keys.

My workaround was always specifying zabbix_proxy_tlsconnect and zabbix_proxy_tlsaccept in addition to overwriting the zabbix_proxy_tls_config variable with correct keys:

```
zabbix_proxy_tlsconnect: psk
zabbix_proxy_tlsaccept: psk
zabbix_proxy_tls_config:
  unencrypted: 'no_encryption'
  psk: 'PSK'
  cert: 'certificate'
```

I think this should be simply fixed by matching what is done in the zabbix_agent role in this regard. Thanks.
