### ISSUE TITLE
zabbix_host module: updating host inventory data causes IPMI values to be reset

### ISSUE THREAD

**Issue by Stivi** [ansible-collections/community.zabbix#1110]
##### SUMMARY
Using zabbix_host module to update a host inventory data produces a bug because IPMI values (ipmi_authtype, ipmi_privilege, ipmi_username, ipmi_password) are set to default.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.10]
  config file = /home/ansible/playbooks/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/ansible/playbooks/ansible.cfg) = ['/home/ansible/playbooks/hosts']
DEFAULT_REMOTE_USER(/home/ansible/playbooks/ansible.cfg) = ansible
HOST_KEY_CHECKING(/home/ansible/playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
```
Operating System: Ubuntu 20.04.4 LTS
Zabbix Version: 6.0.8
```

##### STEPS TO REPRODUCE
Run playbook

```yaml
- name: Update an existing host's info
  vars:
    ansible_zabbix_auth_key: 1a921b00a0b482a9e26a45e6fbea7dad
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: true
    ansible_zabbix_url_path: ""
  become: false
  delegate_to: zabbix.hosting.ecnl.ru
  community.zabbix.zabbix_host:
    host_name:  "{{ ansible_facts['nodename'] }}"
    inventory_mode: manual
    inventory_zabbix:
      notes: "Platform: {{ ansible_facts['board_vendor'] }} {{ ansible_facts['board_name'] }}\nbios_version: {{ ansible_facts['bios_version'] }}\nbios_date: {{ ansible_facts['bios_date'] }}"
```

##### EXPECTED RESULTS
Only the inventory values should be updated on the zabbix server host.

##### ACTUAL RESULTS
The inventory values is updated successfully, **but** the IPMI values is reset to default (even though they were set).

![изображение](https://github.com/ansible-collections/community.zabbix/assets/587947/b145c892-1ec9-472a-aa2a-f55c705057b5)
