### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by josoko12** [ansible-collections/community.zabbix#1116]
##### SUMMARY

https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_host_info_module.html
The parameter does not exist in ver. 2.1.0 for zabbi_host_info or zabbix_host
- timeout

##### ISSUE TYPE
- A more accurate documentation would help a lot.

##### COMPONENT NAME

- community.zabbix.zabbix_host_info.

##### ADDITIONAL INFORMATION

Parameters should be described more accurate.

```yaml
- name: Get host info
  # set task level variables as we change ansible_connection plugin here
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "zabbixeu"  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
    ansible_host: zabbix-example-fqdn.org
  community.zabbix.zabbix_host_info:
    host_name: ExampleHost
    host_ip: 127.0.0.1
    timeout: 10
    exact_match: no
    remove_duplicate: yes
```
This task will e.g. not work without  these parameters:
      http_login_user: "<USERNAME>"
      http_login_password: "<PASSWORD>"

Output Ansible:

```bash
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.zabbix.zabbix_host_info) module: timeout. Supported parameters include: remove_duplicate, exact_match, host_inventory, host_ip, http_login_user, host_name, http_login_password."}
```

```yaml
  - name: Get host info
    # set task level variables as we change ansible_connection plugin here
    vars:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: <TCP-PORT>
      ansible_httpapi_use_ssl: true
      ansible_httpapi_validate_certs: false
      ansible_zabbix_url_path: ""  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
      ansible_host: "<FQDN-ZABBIX-SERVER | IP>"
    community.zabbix.zabbix_host_info:
      host_name: "Zabbix server"
      host_ip: "127.0.0.1"
      # timeout: "10"
      exact_match: false
      remove_duplicate: false
      http_login_user: ""<USERNAME>"
      http_login_password: "<PASSWORD>"
```

none
