### ISSUE TITLE
A zabbix_service module has no idempotency with Zabbix 5.0

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#112]
##### SUMMARY

The `changed` occur when executing the task of creating a new service twice.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

modules/zabbix_service.py

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.11.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/collection.zabbix/PR/xxx/ansible/lib/ansible
  executable location = /root/collection.zabbix/PR/xxx/ansible/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
# ansible-config dump --only-changed
```

##### OS / ENVIRONMENT / Zabbix Version

* Zabbix Version 5.0

##### STEPS TO REPRODUCE

Execute the following playbook twice.

```yaml
- name: example
  hosts: localhost
  gather_facts: no
  vars:
    zabbix_server_url: http://127.0.0.1:8080
    zabbix_login_user: Admin
    zabbix_login_password: zabbix
  tasks:
    - name: "test - Create a new service"
      zabbix_service:
        server_url: "{{ zabbix_server_url }}"
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        name: ExampleServiceForServiceModule
        sla: 99.99
        state: present
      register: create_service_idempotency_check_result
```

##### EXPECTED RESULTS

No `changed` occurs the second time.

##### ACTUAL RESULTS

The `changed` occurs twice in a row.
