### ISSUE TITLE
zabbix_user_directory applies changes in dry run

### ISSUE THREAD

**Issue by xchotard-talentsoft** [ansible-collections/community.zabbix#1144]
##### SUMMARY
Running a playbook with the `--check` (dry run) parameter will apply changes such as `bind_password`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_user_directory:

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.6]
  config file = /home/freeman/myansibleproject/ansible.cfg
  configured module search path = ['/home/freeman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/freeman.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/freeman/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/freeman/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
$ ansible-galaxy collection install community.zabbix --force

Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-zabbix-2.2.0.tar.gz to /home/freeman/.ansible/tmp/ansible-local-5482t7qyu960/tmpqc_occ4l/community-zabbix-2.2.0-ezx4cvjq
Installing 'community.zabbix:2.2.0' to '/home/freeman/.ansible/collections/ansible_collections/community/zabbix'
community.zabbix:2.2.0 was installed successfully
'ansible.posix:1.5.4' is already installed, skipping.
'ansible.windows:1.14.0' is already installed, skipping.
'community.mysql:3.8.0' is already installed, skipping.
'ansible.netcommon:5.3.0' is already installed, skipping.
'community.general:7.5.1' is already installed, skipping.
'community.postgresql:2.4.3' is already installed, skipping.
'ansible.utils:2.11.0' is already installed, skipping.
```

##### OS / ENVIRONMENT / Zabbix Version
- Zabbix 6.4.7

##### STEPS TO REPRODUCE

Minimal myplaybook.yaml example (ommited credentials and httpapi variables):

```yaml
- name: Break my LDAP configuration even in dry run
  community.zabbix.zabbix_user_directory:
    name: "myldapconf"
    base_dn: "ou=zabbixusers,dc=example,dc=com"
    bind_password: "wrongsecret"
    idp_type: ldap
    host: "ldaps://dc01.example.com"
    port: 636
    search_attribute: "saMAccountName"
```

Run with:
```
ansible-playbook myplaybook.yaml --check
```

##### EXPECTED RESULTS

No actual change on Zabbix configuration

##### ACTUAL RESULTS

Broken LDAP authentication, I have to manually set the correct "bind_password" in the UI.
