### ISSUE TITLE
Support for Template Groups with zabbix_template_group

### ISSUE THREAD

**Issue by cjohannsen81** [ansible-collections/community.zabbix#1147]
##### SUMMARY
The collection does not support the creation of template groups in Ansible 6.4 right now. When adding templates without a template group, the group becomes mandatory.

##### ISSUE TYPE
- Feature Request

##### COMPONENT NAME
zabbix_template_group module

##### ADDITIONAL INFORMATION
The creation of a template group becomes mandatory when adding templates to a special template group that's not the standard one. Template Groups are different than Host Groups which have their own module.

```yaml
  community.zabbix.zabbix_template:
    template_name: ExampleHost
    template_groups:
      - Role
      - Role2
    link_templates:
      - Example template1
      - Example template2
    macros:
      - macro: "{$EXAMPLE_MACRO1}"
        value: 30000
      - macro: "{$EXAMPLE_MACRO2}"
        value: 3
      - macro: "{$EXAMPLE_MACRO3}"
        value: "Example"
    state: present
```

Leads to:

```
fatal: [ubuntu]: FAILED! => {"changed": false, "msg": "template_groups are required when creating a new Zabbix template"}
```

Screenshots (6.0 vs 6.4)

![03_14_12](https://github.com/ansible-collections/community.zabbix/assets/2995339/1d3487a0-b259-454c-a9bf-21138262fecb)

<img width="181" alt="Screenshot 2023-12-13 at 8 02 34 AM" src="https://github.com/ansible-collections/community.zabbix/assets/2995339/2dfd6cb4-39a6-4da6-bfea-978e2fbeaecb">
