### ISSUE TITLE
zabbix_host_info: return all the hosts

### ISSUE THREAD

**Issue by BGmot** [ansible-collections/community.zabbix#1151]
##### SUMMARY
A user should be able to use zabbix_host_info module to get all the hosts configured in Zabbix.

##### COMPONENT NAME
zabbix_host_info module

##### ADDITIONAL INFORMATION
Proposed approach: if neither `host_name` nor `host_ip` defined then all the hosts should be returned. 
```yaml
- name: Get all hosts
  community.zabbix.zabbix_host_info:
  register: get_all_hosts_result
```
