### ISSUE TITLE
'Invalid params.', 'data': 'Invalid parameter \"/rules\": unexpected parameter \"templateDashboards\".'}

### ISSUE THREAD

**Issue by whitethemight** [ansible-collections/community.zabbix#1160]
##### SUMMARY
Has problem when import template json/xml
```
'Invalid params.', 'data': 'Invalid parameter \"/rules\": unexpected parameter \"templateDashboards\".'}
```
playbook.yml
```
  - name: Create a new Zabbix template PostgreSQL
    community.zabbix.zabbix_template:
      template_json:
        zabbix_export:
          version: "5.0"
          templates:
            - name: PostgreSQL
              description: "PostgreSQL template"
              template: PostgreSQL
              groups:
                - name: Templates
      state: present
```
group_vars/all.yml
```
ansible_user: myuser
ansible_password: mypass
ansible_network_os: community.zabbix.zabbix
ansible_connection: httpapi
ansible_httpapi_port: 80
ansible_httpapi_use_ssl: false
ansible_httpapi_validate_certs: false
ansible_host: myip
```

collection version: ```community.zabbix 2.3.0```
ansible version: ```ansible [core 2.15.3]```
python version: ```python version = 3.11.6```
zabbix version: ```5.0.7```
