### ISSUE TITLE
ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/username": a character string is expected.'}

### ISSUE THREAD

**Issue by tuxmartin** [ansible-collections/community.zabbix#1164]
##### ISSUE TYPE
- Bug Report / Question?

##### COMPONENT NAME
zabbix_hostmacro

##### ANSIBLE VERSION

```
ansible [core 2.13.13]
  config file = None
  configured module search path = ['/home/martin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/martin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
  jinja version = 3.1.3
  libyaml = True
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_CALLBACK_PLUGIN_PATH(/home/martin/ansible/test/ansible.cfg) = ['/home/martin/ansible/test/.callbacks']
DEFAULT_MANAGED_STR(/home/martin/ansible/test/ansible.cfg) = This file is managed by Ansible.
DEFAULT_ROLES_PATH(/home/martin/ansible/test/ansible.cfg) = ['/home/martin/ansible/test/roles']
DEFAULT_STDOUT_CALLBACK(/home/martin/ansible/test/ansible.cfg) = anstomlog
DEFAULT_TIMEOUT(/home/martin/ansible/test/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/martin/ansible/test/ansible.cfg) = /home/martin/ansible/test/.vault.pass
DEPRECATION_WARNINGS(/home/martin/ansible/test/ansible.cfg) = True
HOST_KEY_CHECKING(/home/martin/ansible/test/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/martin/ansible/test/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
- Ubuntu 22.04.3 LTS x64
- Zabbix 6.0.25
- community.zabbix 2.3.1

##### STEPS TO REPRODUCE
```bash
ansible-playbook -i production/ zabbix_hostmacro.yml  --check
```

```yaml
collections:
  - name: community.zabbix
    version: 2.3.1
    source: https://galaxy.ansible.com

  - name: ansible.netcommon
    version: 5.3.0
    source: https://galaxy.ansible.com

  - name: ansible.utils
    version: 2.12.0
```

```yaml
- name: set zabbix host macros
  hosts: all
  gather_facts: False

  collections:
    - community.zabbix

  tasks:
    - name: Set credentials to access Zabbix Server API
      ansible.builtin.set_fact:
        ansible_user: "{{ zabbix_host_server_username }}"
        ansible_httpapi_pass: "{{ zabbix_host_server_password }}"

    - name: create new host macro or update an existing macro's value
      delegate_to: localhost
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: true
        ansible_zabbix_url_path: "/"
        ansible_host: "{{ zabbix_host_server_url }}"
      community.zabbix.zabbix_hostmacro:
        host_name: "{{ inventory_hostname }}"
        macro_name: "{{ item.name }}"
        macro_value: "{{ item.value }}"
        macro_description: "{{ item.description | default('') }}"
        macro_type: "{{ item.description | default('text') }}"
        state: present
        force: False
      with_items: "{{ zabbix_host_macros }}"
      tags:
        - zabbix_update_macro

  vars:
    zabbix_host_macros:
      - name: ZABBIX_AGENT_WARNING
        value: 0
```

Variables `zabbix_host_server_username`, `zabbix_host_server_password` and `zabbix_host_server_url` are defined in another file.

##### EXPECTED RESULTS

It should work :-)

With older versions `community.zabbix:1.7.0` and `ansible 2.10` it worked.

##### ACTUAL RESULTS

```
ansible-playbook [core 2.13.13]
  config file = /home/martin/ansible/test/ansible.cfg
  configured module search path = ['/home/martin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/martin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
  jinja version = 3.1.3
  libyaml = True
Using /home/martin/ansible/test/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/martin/ansible/test/production/hosts as it did not pass its verify_file() method
script declined parsing /home/martin/ansible/test/production/hosts as it did not pass its verify_file() method
auto declined parsing /home/martin/ansible/test/production/hosts as it did not pass its verify_file() method
Parsed /home/martin/ansible/test/production/hosts inventory source with ini plugin
Loading collection community.zabbix from /home/martin/.ansible/collections/ansible_collections/community/zabbix
Loading callback plugin anstomlog of type stdout, v2.0 from /home/martin/ansible/test/.callbacks/anstomlog.py
Skipping callback 'anstomlog', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
1 plays in zabbix_hostmacro.yml
META: ran handlers
[23:33:58] Set credentials to access Zabbix Server API | server.example.net | SUCCESS | 27ms
{
  - ansible_facts: {
    - ansible_user: XXXXXXXX
    - ansible_httpapi_pass: XXXXXXXXXXXXX
  }
  - changed: False
}
[23:33:58] create new host macro or update an existing macro's value ...redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /home/martin/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /home/martin/.ansible/collections/ansible_collections/ansible/utils
<zabbix.server.net> attempting to start connection
<zabbix.server.net> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /usr/local/bin/ansible-connection
<zabbix.server.net> local domain socket does not exist, starting it
<zabbix.server.net> control socket path is /home/martin/.ansible/pc/2e13ee80a9
<zabbix.server.net> redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<zabbix.server.net> Loading collection ansible.netcommon from /home/martin/.ansible/collections/ansible_collections/ansible/netcommon
<zabbix.server.net> Loading collection ansible.utils from /home/martin/.ansible/collections/ansible_collections/ansible/utils
<zabbix.server.net> Loading collection community.zabbix from /home/martin/.ansible/collections/ansible_collections/community/zabbix
<zabbix.server.net> local domain socket listeners started successfully
<zabbix.server.net> loaded API plugin ansible_collections.community.zabbix.plugins.httpapi.zabbix from path /home/martin/.ansible/collections/ansible_collections/community/zabbix/plugins/httpapi/zabbix.py for platform type community.zabbix.zabbix
<zabbix.server.net> 
<zabbix.server.net> local domain socket path is /home/martin/.ansible/pc/2e13ee80a9
<zabbix.server.net> ESTABLISH LOCAL CONNECTION FOR USER: martin
<zabbix.server.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3 `"&& mkdir "` echo /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226 `" && echo ansible-tmp-1705098839.0674055-17783-225052490104226="` echo /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226 `" ) && sleep 0'
Using module file /home/martin/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_hostmacro.py
<zabbix.server.net> PUT /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/tmpq_ffds80 TO /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py
<zabbix.server.net> EXEC /bin/sh -c 'chmod u+x /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/ /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py && sleep 0'
<zabbix.server.net> EXEC /bin/sh -c '/usr/bin/python3 /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py && sleep 0'
<zabbix.server.net> EXEC /bin/sh -c 'rm -f -r /home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/ > /dev/null 2>&1 && sleep 0'
 | server.example.net | FAILED | 1612ms
{
  - msg: One or more items failed
  - results: [ {
    - rc: 1
    - msg: MODULE FAILURE
           See stdout/stderr for the exact error
    - failed: True
    - module_stdout: ""
    - module_stderr: Traceback (most recent call last):
    File "/home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py", line 107, in <module>
      _ansiballz_main()
    File "/home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py", line 99, in _ansiballz_main
      invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
    File "/home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py", line 47, in invoke_module
      runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_hostmacro', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_hostmacro', _modlib_path=modlib_path),
    File "/usr/lib/python3.10/runpy.py", line 224, in run_module
      return _run_module_code(code, init_globals, run_name, mod_spec)
    File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_hostmacro.py", line 277, in <module>
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_hostmacro.py", line 253, in main
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
  ansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/username": a character string is expected.'} when sending {"jsonrpc": "2.0", "method": "user.login", "id": "4b8d49a9-5f02-40cf-9ad0-527d7cecd739", "params": {"username": null, "password": null}}
  
    - exception: Traceback (most recent call last):
    File "/home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py", line 107, in <module>
      _ansiballz_main()
    File "/home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py", line 99, in _ansiballz_main
      invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
    File "/home/martin/.ansible/tmp/ansible-local-17777bu0sqwg3/ansible-tmp-1705098839.0674055-17783-225052490104226/AnsiballZ_zabbix_hostmacro.py", line 47, in invoke_module
      runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_hostmacro', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_hostmacro', _modlib_path=modlib_path),
    File "/usr/lib/python3.10/runpy.py", line 224, in run_module
      return _run_module_code(code, init_globals, run_name, mod_spec)
    File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_hostmacro.py", line 277, in <module>
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_hostmacro.py", line 253, in main
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
    File "/tmp/ansible_community.zabbix.zabbix_hostmacro_payload_u417omim/ansible_community.zabbix.zabbix_hostmacro_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
  ansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/username": a character string is expected.'} when sending {"jsonrpc": "2.0", "method": "user.login", "id": "4b8d49a9-5f02-40cf-9ad0-527d7cecd739", "params": {"username": null, "password": null}}
  
    - changed: False
    - item: {
      - name: ZABBIX_AGENT_WARNING
      - value: 0
    }
    - ansible_loop_var: item
    - _ansible_item_label: {
      - name: ZABBIX_AGENT_WARNING
      - value: 0
    }
  } ]
  - changed: False
}
[23:33:59] system | -- Play recap --
server.example.net     : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by tuxmartin** [comment]
I probably found a solution. When I set `ansible_user` and `ansible_httpapi_pass` in task `vars`, it works.

But if I use task `set_facts` [according to documentation](https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_hostmacro_module.html#examples):
```yaml
- name: Set credentials to access Zabbix Server API
  ansible.builtin.set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix
```
it will crash on error (as in this issue).

This is ok:

```yaml
- name: set zabbix host macros
  hosts: all
  gather_facts: False

  collections:
    - community.zabbix

  tasks:

    - name: create new host macro or update an existing macro's value
      delegate_to: localhost
      vars:
        ansible_user: "{{ zabbix_host_server_username }}"
        ansible_httpapi_pass: "{{ zabbix_host_server_password }}"
        ansible_host: "{{ zabbix_host_server_url }}"
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: true
        ansible_zabbix_url_path: "/"
      community.zabbix.zabbix_hostmacro:
        host_name: "{{ inventory_hostname }}"
        macro_name: "{{ item.name }}"
        macro_value: "{{ item.value }}"
        macro_description: "{{ item.description | default('') }}"
        macro_type: "{{ item.description | default('text') }}"
        state: present
        force: False
      with_items: "{{ zabbix_host_macros }}"
      tags:
        - zabbix_update_macro

  vars:
    zabbix_host_macros:
      - name: ZABBIX_AGENT_WARNING
        value: 0
```
