### ISSUE TITLE
zabbix_hostmacro_module: diff doesn't work, always shows as changed

### ISSUE THREAD

**Issue by tuxmartin** [ansible-collections/community.zabbix#1171]
##### SUMMARY

`zabbix_hostmacro_module`: diff doesn't work, always shows as changed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.zabbix.zabbix_hostmacro`

##### ANSIBLE VERSION
```
ansible [core 2.13.13]
  config file = None
  configured module search path = ['/home/martin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/martin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
  jinja version = 3.1.3
  libyaml = True
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_CALLBACK_PLUGIN_PATH(/home/martin/ansible/test/ansible.cfg) = ['/home/martin/ansible/test/.callbacks']
DEFAULT_MANAGED_STR(/home/martin/ansible/test/ansible.cfg) = This file is managed by Ansible.
DEFAULT_ROLES_PATH(/home/martin/ansible/test/ansible.cfg) = ['/home/martin/ansible/test/roles']
DEFAULT_STDOUT_CALLBACK(/home/martin/ansible/test/ansible.cfg) = anstomlog
DEFAULT_TIMEOUT(/home/martin/ansible/test/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/martin/ansible/test/ansible.cfg) = /home/martin/ansible/test/.vault.pass
DEPRECATION_WARNINGS(/home/martin/ansible/test/ansible.cfg) = True
HOST_KEY_CHECKING(/home/martin/ansible/test/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/martin/ansible/test/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
- Ubuntu 22.04.3 LTS x64
- Zabbix 6.0.25
- community.zabbix 2.3.1
- ansible-core 2.13.13

##### STEPS TO REPRODUCE

Just use `zabbix_hostmacro_module`

##### EXPECTED RESULTS
Do not show as changed servers where nothing has changed.

##### ACTUAL RESULTS
All server are shown as changed.

**Comment by masa-orca** [comment]
Will you show parameters?

If you don't set `text` as macro_type, the module cannot compare Zabbix's data with parameter (Zabbix hides values).
Therefore, the module will call update API  regardless of without changes and return changed as the result of a task.

**Comment by tuxmartin** [comment]
@masa-orca Hello, this is my task:

```yaml

- name: set host macros
  delegate_to: localhost
  community.zabbix.zabbix_hostmacro:
    host_name: "{{ inventory_hostname }}"
    macro_name: "{{ item.name }}"
    macro_value: "{{ item.value }}"
    macro_description: "{{ item.description | default('') | trim }}"
    macro_type: "{{ item.type | default('text') }}"
    state: "{{ item.state | default('present') }}"
    force: True
  with_items: "{{ zabbix_host_macros }}"
```

and `host_vars` config:
```yaml
zabbix_host_macros:
  - name: '{$AWS.ACCESS.KEY.ID}'
    value: AKIAxxxxxxxxxxx

  - name: '{$AWS.EC2.INSTANCE.ID}'
    value: i-0cxxxxxxxxx53e

  - name: '{$AWS.EC2.INSTANCE.ID}'
    value: eu-west-1

  - name: '{$AWS.SECRET.ACCESS.KEY}'
    value:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            6132396xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9306135373730
            6131356xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4626463613361
            3566393xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx43465
    type: secret
```

it doesn't work.
