### ISSUE TITLE
zabbix proxy resource reported changed on every apply

### ISSUE THREAD

**Issue by vamshi8** [ansible-collections/community.zabbix#1181]
##### SUMMARY
we are using zabbix_proxy resource to create passive proxy and whenever we apply we see the resource is been changed although here is no change to the code. 
Tried to run in debug mode, did not see any clue why this is happening.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_proxy

##### ANSIBLE VERSION

```ansible [core 2.15.8]
  config file = /opt/ansible/config/ansible-config-cansible0.cert.motive.com.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv-ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/venv-ansible/bin/ansible
  python version = 3.9.16 (main, Sep 22 2023, 17:57:55) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/opt/venv-ansible/bin/python3.9)
  jinja version = 3.1.3
  libyaml = True


```

##### CONFIGURATION

```CONFIG_FILE() = /opt/ansible/config/ansible-config-xxxxxxxxxx.cfg
DEFAULT_FORKS(/opt/ansible/config/ansible-config-xxxxxxxxxxxx.cfg) = 100
DEFAULT_HOST_LIST(/opt/ansible/config/ansible-config-xxxxxxxxxxxx.cfg) = ['/opt/ansible/inventory/cert/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/opt/ansible/config/ansible-config-xxxxxxxxx.cfg) = /opt/ansible/keys/vault_token-nonprod
HOST_KEY_CHECKING(/opt/ansible/config/ansible-xxxxxxxxx.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible/config/ansible-config-xxxxxxxxxx.cfg) = False


```

##### OS / ENVIRONMENT / Zabbix Version
Os version: RHEL 9/ zabbix version 6.4

##### STEPS TO REPRODUCE

```yaml

- name: Update Zabbix passive proxies for RHEL9
  module_defaults:
    zabbix_proxy:
      state: present
  zabbix_proxy:
    proxy_name: "xxx"
    state: "present"
    status: "passive"
    interface:
      useip: 1
      ip: "xxxxx"
    tls_connect: "xxx"
    tls_psk_identity: "xxx-proxy"
    tls_psk: "xxxxxxxxx"
  become: false
  vars:
    ansible_connection: httpapi
    ansible_user: zbx_api_cli
  tags: passive_proxies
  when: ansible_distribution_major_version == "9"


```

##### EXPECTED RESULTS

Resource is not changed on every apply .

##### ACTUAL RESULTS

It showed the resource is changed even though there is no change in code.
No hints from debug logs
