### ISSUE TITLE
Maintenance: Support time periods types other than "one time only"

### ISSUE THREAD

**Issue by oldmanhere** [ansible-collections/community.zabbix#1201]
##### SUMMARY
Maintenance: Support time periods types other than "one time only" : weekly at least, next daily and monthly

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_maintenance

##### ADDITIONAL INFORMATION

We need to set, for example, a maintenance period started at 1h00, every monday, for 3 hours.
Actually, the module only set a "one time period" maintenance.

To accomplish what we need, the zabbix reference provide a "time period" object that can take a timeperiod_type of 3, a dayofweek of 1  and a start_time 3600.
The minutes of 180 give the 3 hours already.
We can add a variable start_at_minutes that give the 1h start, and a variable day_of_week for the day. If day_of_week exist, then the weekly timeperiod_type can be chosen correctly and other values calculated.

No proposition for daily and monthly. you are free.

```yaml
  community.zabbix.zabbix_maintenance:
    name: "Monday maintenance"
    host_groups: "Sample_group"
    state: present
    collect_data: true
    minutes: 180
    start_at_minutes: 60
    day_of_week: "monday"
```
