### ISSUE TITLE
Request: Implement item module

### ISSUE THREAD

**Issue by ljvdhooft** [ansible-collections/community.zabbix#1203]
##### SUMMARY
Just like the commands to create a host, being able to create an item for the host.

##### COMPONENT NAME
community.zabbix.zabbix_item

##### ADDITIONAL INFORMATION
Use it to create items on a host to make provisioning easier. Right now this could be done via the HTTP API but it's pretty complicated since there are no checks if the items already exists, so the tasksfile gets quite big.

```yaml

- community.zabbix.zabbix_item:
  item_name: item1
  host_name: parent_host
  state: present
  type: http_agent
  url: "google.com"
  preprocessing: [
  { -- add some params -- }
  ]
  
```
