### ISSUE TITLE
Zabbix server role fails on selinux task, module script does not take become argument

### ISSUE THREAD

**Issue by chladic** [ansible-collections/community.zabbix#1208]
##### SUMMARY
Version 2.3.0
Task copying selinux script in zabbix server role is failing and complaining `become` is not supported parameter
```
TASK [community.zabbix.zabbix_server : SELinux | RedHat | Add SEmodule to fix SELinux issue: zabbix_server_alerter.sock] **********************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [test-zabbix-r1.mgmt.mdit.services]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible_collections.ansible.builtin.plugins.action.script) module: become. Supported parameters include: _raw_params, chdir, cmd, creates, executable, removes."}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_server role, file tasks/selinux.yml. Task: SELinux | RedHat | Add SEmodule to fix SELinux issue: zabbix_server_alerter.sock

##### ANSIBLE VERSION
```
ansible [core 2.16.5]
  config file = /Users/user/github/project/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/9.4.0_1/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/9.4.0_1/libexec/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

##### CONFIGURATION
```
CONFIG_FILE() = /Users/user/github/project/ansible.cfg
DEFAULT_HOST_LIST(/Users/user/github/project/ansible.cfg) = ['/Users/user/github/project/inventory']
DEFAULT_PRIVATE_KEY_FILE(/Users/user/github/project/ansible.cfg) = /Users/user/.ssh/ansible.rsa
DEFAULT_REMOTE_USER(/Users/user/github/project/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/Users/user/github/project/ansible.cfg) = ['/Users/user/github/project/roles']
HOST_KEY_CHECKING(/Users/user/github/project/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
MacOS 14.4.1

##### STEPS TO REPRODUCE
Run playbook what calls community.zabbix.zabbix_server role, Version 2.3.0

**Comment by chladic** [comment]
Ouu, now I can see that version 2.3.0 is ok

**Comment by chladic** [comment]
Task in repository:
```
- name: "SELinux | RedHat | Add SEmodule to fix SELinux issue: zabbix_server_alerter.sock"
  ansible.builtin.script:
    cmd: files/install_semodule.bsx
  args:
    creates: /etc/selinux/targeted/active/modules/400/zabbix_server_add/cil
  become: true
  tags:
    - config
 ```

Task when I install via ansible-gallaxy:
```
- name: "SELinux | RedHat | Add SEmodule to fix SELinux issue: zabbix_server_alerter.sock"
  ansible.builtin.script:
    cmd: files/install_semodule.bsx
  args:
    creates: /etc/selinux/targeted/active/modules/400/zabbix_server_add/cil
    become: true
  tags:
    - config
 ```
