### ISSUE TITLE
Zabbix httpapi does not honor reset_connection

### ISSUE THREAD

**Issue by aivarsV** [ansible-collections/community.zabbix#1209]
##### SUMMARY
I'm working on Zabbix server bootstrap script, which, among other things, creates new Super admin user and disables default Admin user. Issue, that I'm facing is that zabbix httpapi is unable to drop current connection and reconnect with different credentials.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix httpapi – HttpApi Plugin for Zabbix

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.5]
  config file = None
  configured module search path = ['/home/vaivis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/vaivis/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801] (/usr/bin/python)
  jinja version = 3.1.3
  libyaml = True

```
```paste below
Collection           Version
-------------------- -------
ansible.netcommon    6.1.0  
ansible.posix        1.5.4  
ansible.utils        4.0.0  
ansible.windows      2.3.0  
community.docker     3.4.8  
community.general    5.7.0  
community.mysql      3.9.0  
community.postgresql 3.0.0  
community.zabbix     2.3.1  

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim

```

##### OS / ENVIRONMENT / Zabbix Version

* Zabbix server 6.4.13 in Ubuntu Docker container
* Zabbix web nginx 6.4.13 in Ubuntu Docker container
* Play is run just after database initialization

##### STEPS TO REPRODUCE

My approach is to try to connect with new credentials `super` `verysecretpass` and check status of default `Admin` user. If `Admin` is __not disabled__, I expect user `super` to not exist, so connect with default credentials and create user `super`. After that `Admin` can be disabled, so I drop current connection and reconnect as `super` user and disable `Admin`.

```yaml
---
- name: Ensure telemetry server is set up and running
  hosts: all
  tasks:

    - name: Configure zabbix server
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 8182
        ansible_httpapi_use_ssl: no
        ansible_zabbix_url_path: ""
        ansible_user: "super"
        ansible_httpapi_pass: "verysecretpass"
      block:
        - name: Ensure default admin is deactivated
          block:
            - name: Check status of default admin
              community.zabbix.zabbix_user_info:
                username: Admin
              register: zbx_admin
              failed_when: zbx_admin.zabbix_user.users_status | int == 0

          rescue:
            - name: Reset connection
              meta: reset_connection

            - name: Configure primary admin user
              vars:
                ansible_user: "Admin"
                ansible_httpapi_pass: "zabbix"
              community.zabbix.zabbix_user:
                username: "super"
                state: present
                name: "New Super"
                surname: "User"
                passwd: "verysecretpass"
                role_name: Super admin role
                usrgrps:
                  - Zabbix administrators
                  - Internal
                autologin: no
                autologout: "0"

            - name: Reset connection
              meta: reset_connection

            - name: Disable default admin user
              community.zabbix.zabbix_user:
                username: "Admin"
                passwd: "zabbix"
                usrgrps:
                  - "Disabled"

```

##### EXPECTED RESULTS

I expect this play to fail on `Ensure default admin is deactivated` and be rescued by subsequent tasks. After this play I expect super users `Admin` (disabled) and `super` (enabled). 
Subsequent runs of this play shold make no changes to user accounts. 

##### ACTUAL RESULTS

On first run play proceeds as expected until task `Disable default admin user`, at which point play fails with following output.
[Play output](https://gist.github.com/aivarsV/eb9d39a73f2c8329cc7976d55d24e77b)

After first run I'm left with two working super admin accounts - `Admin` and `super`.
Second run proceeds till the end and `Admin` get's disabled.

My assumption is that `Reset connection` task has no actual effect on zabbix httpapi module.

**Comment by pyrodie18** [comment]
Were you able to get this working?

**Comment by BGmot** [comment]
According to docs it probably applies to SSH connections
> reset_connection (added in Ansible 2.3) interrupts a persistent connection (i.e. ssh + control persist)

Have you played with disabling persistent connection?

**Comment by pyrodie18** [comment]
No response heard....closing ticket

**Comment by BGmot** [comment]
Re-opening the ticket as it seems to be a valid use case.

**Comment by BGmot** [comment]
@CircuitCipher were you able to actually resolve this issue with these changes (from the PR you proposed) somewhere in your local dev environment?
I spent half a day yesterday (it was a holiday in Canada) trying to resolve this on our HttpApi implementation level and failed. The roots of this problem go deep into the netcommon collection we are inheriting from.
Then I added "logout" state to zabbix_user and even after explicitely logging out Admin you still cannot do anything with new user as HttpApi is implemented in a way that authentication done only once - as a first step before executing anything on freshly created unix socket (persistent connection).
Still digging though, haven't given up yet. Looking at how Zabbix treats session ids (our culprit here).

**Comment by CircuitCipher** [comment]
@BGmot This issue could be avoided with the changes from my PR.  One portion of my changes updates the login() method of the HTTPAPI so that anytime login fails, the connection is marked as disconnected.  This means future attempts at the API will still try to login.

```python
try:
	# Zabbix <= 6.2
	payload = self.payload_builder("user.login", user=username, password=password)
	code, response = self.send_request(data=payload)
except ConnectionError:
	# Zabbix >= 6.4
	try:
		payload = self.payload_builder("user.login", username=username, password=password)
		code, response = self.send_request(data=payload)
	 except ConnectionError:
		# If this task fails to login, we mark the connection as disconnected so that
		# future tasks can try to reauth
		self.connection._connected = False
		raise
```

This allows you to write playbooks where logins can be tested:
```yaml
 - name: Has the admin password been changed check
    vars:
      ansible_httpapi_username: "superuser"
      ansible_httpapi_pass: "{{ new_pass }}" 
    community.zabbix.zabbix_user_info:
      username: "{{ zabbix_api_login_user }}"
    register: user_info
    failed_when: false
    
 -  name: set is_superadmin_created
    #vars:
      #ansible_network_os: ''
      #ansible_connection: local
    set_fact:
      is_superadmin_created: "{{ user_info.exception is not defined }}"
 ```

**Comment by CircuitCipher** [comment]
@BGmot I also tried to go down the route of making the api respond to reset_connection but it turned into a deeper rabbit hole than I liked.

For instance... These lines here control the reset_connection logic:
https://github.com/ansible/ansible/blob/dec49e62882b0f36f613a22ef8d07b8c13064cca/lib/ansible/plugins/strategy/__init__.py#L1064
```python
if target_host in self._active_connections:
                connection = Connection(self._active_connections[target_host])
                del self._active_connections[target_host]
            else:
                connection = plugin_loader.connection_loader.get(play_context.connection, play_context, os.devnull)
                connection.set_options(task_keys=task.dump_attrs(), var_options=all_vars)
                play_context.set_attributes_from_plugin(connection)
```

 I'm running my playbook locally on the server I want to install zabbix on.  So because of this, the reset_connection logic, doesn't care about the Zabbix Httpapi connection and only goes to close the SSH local connection.    
 
 So I had to force the else branch of logic to happen to even start working on that.

**Comment by BGmot** [comment]
@CircuitCipher please test my ugly code from the PR above. Works for me.
Important thing we don't touch any other module (zabbix_user)

**Comment by CircuitCipher** [comment]
@BGmot Great! I will check it out in a moment

**Comment by CircuitCipher** [comment]
@BGmot Unfortunately, it seems to fail for my use-case.

In my zabbix provisioning setup I have a set of tasks like the following:
```yaml
- name: Determine if admin password already set
  block:
  - name: A request with our desired admin creds
    vars: &zabbix_api_args
      ansible_user: "{{ zabbix_admin_user }}"
      ansible_httpapi_pass: "{{ zabbix_admin_pass }}"
      ansible_httpapi_port: "{{ zabbix_web_port }}"
      ansible_httpapi_use_ssl: "{{ zabbix_ansible_httpapi_use_ssl }}"
      ansible_httpapi_validate_certs: "{{ zabbix_ansible_httpapi_validate_certs }}"
      ansible_host: "localhost"
      ansible_network_os: "{{ zabbix_ansible_network_os }}"
      ansible_connection: "{{ zabbix_ansible_connection }}"
    community.zabbix.zabbix_user_info:
      username: "{{ zabbix_admin_user }}"
    register: new_creds_req
    failed_when: false

  - name: set is_admin_pass_set
    set_fact:
      is_admin_pass_set: "{{ new_creds_req.exception is not defined }}"
  
  - debug:
      msg: "{{ zabbix_admin_pass if is_admin_pass_set else zabbix_default_admin_pass }}"
    
- name: Configure E-mail
  vars: *zabbix_api_args
  block:
  - name: "Create an email mediatype with SMTP authentication"
    vars:
      ansible_httpapi_pass: "{{ zabbix_admin_pass if is_admin_pass_set else zabbix_default_admin_pass }}"
```


1. Do a test login to see if we changed the "Admin" user's password yet
2. Create an e-mail template and pass in either the default admin password or new pass based on results above
    a. I create the email template so that Its available before doing the next task of modifying the admin user
    
The e-mail template task fails with:
```json
  ...
  "msg": "connection error occurred: REST API returned {'code': -32500, 'message': 'Application error.',
 'data': 'Incorrect user name or password or account is temporarily blocked.'} 
when sending {\"jsonrpc\": \"2.0\", \"method\": \"user.login\", 
\"id\": \"2d14071e-16f0-4587-a976-d9974645f65b\", 
\"params\": {\"username\": \"Admin\", \"password\": \"TheNewPassword\"}}"
}
```
It seems its still using the cached new password from the login check
