### ISSUE TITLE
Template import problem. Fails on unavailable trigger.

### ISSUE THREAD

**Issue by djdejawu** [ansible-collections/community.zabbix#1214]
Today I've exported a few templates from one Zabbix server to make same in another. This playbook works perfect to save requested template from old one.
```
---
- name: Dump playbook
  hosts: old_zabbix
  tasks:
    - name: Get zabbix template
      community.zabbix.zabbix_template_info:
        template_name: AAA_Weather
        format: xml
        omit_date: true
      register: template
    - name: Print template
      ansible.builtin.debug:
        msg: "{{ template.template_xml }}"
    - name: Write template to file
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ template.template_xml }}"
        dest: weather.xml
        mode: '0644'
```
But when I'm trying to import saved template what have a trigger with dependcies it's fails with message what `trigger doesn't exist`. Depended trigger in imported XML. How to figure out this problem?

Task:
```
      community.zabbix.zabbix_template:
        state: present
        template_xml: "{{ lookup('file', 'weather.xml') }}"
```

Error:
```
connection error occurred: REST API returned {'code': -32500, 'message': 'Application error.', 'data': 'Trigger \"Device: {ITEM.VALUE}\" depends on trigger \"Device: {ITEM.VALUE}\", which does not exist.
```
Seriously, when I'm open GUI, selecting template and `Import` it's works perfectly! idk wtd
