### ISSUE TITLE
Cannot create host with group -- Zabbix 7.0

### ISSUE THREAD

**Issue by kerryland** [ansible-collections/community.zabbix#1286]
##### SUMMARY
community.zabbix.zabbix_host fails with error complaining about unexpected "name" property for the group.

```
    community.zabbix.zabbix_host:
        host_name: "Example"
     ...
        host_groups:
          - "Linux servers"
```

'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter \"/1/groups/1\": unexpected parameter \"name\".'} 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_host

##### ANSIBLE VERSION

```paste below

ansible [core 2.17.0]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/root/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION

```paste below
root@blackbox:~/ansible# ansible-config dump --only-changed
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
```

##### OS / ENVIRONMENT / Zabbix Version
Debian bookworm  aarch64 (Raspberry Pi 4).
Zabbix 7 via docker zabbix/zabbix-web-nginx-pgsql:latest

##### STEPS TO REPRODUCE
Run the example below

```yaml
- name: Add hosts to Zabbix
  hosts: blackbox
  gather_facts: no

  vars:

    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8080
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_user: "Admin"
    ansible_httpapi_pass: "zabbix"
    ansible_zabbix_url_path: "/"

  tasks:

    - name: Ensure Zabbix hosts are present
      community.zabbix.zabbix_host:
        state: present
        host_name: "Example"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "192.168.1.111"
            dns: ""
            port: "10050"
        host_groups:
          - "Linux servers"
        link_templates:
          - "ICMP Ping"
```

##### EXPECTED RESULTS
Host should be added

##### ACTUAL RESULTS
Errors, complaining about unexpected parameter "name" in the group definition.

```paste below
ansible-playbook [core 2.17.0]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible-playbook
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/root/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
No config file found; using defaults
host_list declined parsing /root/ansible/hosts.ini as it did not pass its verify_file() method
script declined parsing /root/ansible/hosts.ini as it did not pass its verify_file() method
auto declined parsing /root/ansible/hosts.ini as it did not pass its verify_file() method
yaml declined parsing /root/ansible/hosts.ini as it did not pass its verify_file() method
Parsed /root/ansible/hosts.ini inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: minimal.yaml ***************************************************************************************************************************************
1 plays in minimal.yaml

PLAY [Add hosts to Zabbix] ***********************************************************************************************************************************

TASK [Ensure Zabbix hosts are present] ***********************************************************************************************************************
task path: /root/ansible/minimal.yaml:18
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<192.168.1.4> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.1.4> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-765317m2aojvnh `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-765317m2aojvnh/ansible-tmp-1717987590.8468134-765320-12883147314374 `" && echo ansible-tmp-1717987590.8468134-765320-12883147314374="` echo /root/.ansible/tmp/ansible-local-765317m2aojvnh/ansible-tmp-1717987590.8468134-765320-12883147314374 `" ) && sleep 0'
Using module file /root/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<192.168.1.4> PUT /root/.ansible/tmp/ansible-local-765317m2aojvnh/tmpgl35is9q TO /root/.ansible/tmp/ansible-local-765317m2aojvnh/ansible-tmp-1717987590.8468134-765320-12883147314374/AnsiballZ_zabbix_host.py
<192.168.1.4> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-765317m2aojvnh/ansible-tmp-1717987590.8468134-765320-12883147314374/ /root/.ansible/tmp/ansible-local-765317m2aojvnh/ansible-tmp-1717987590.8468134-765320-12883147314374/AnsiballZ_zabbix_host.py && sleep 0'
<192.168.1.4> EXEC /bin/sh -c '/root/.local/pipx/venvs/ansible/bin/python /root/.ansible/tmp/ansible-local-765317m2aojvnh/ansible-tmp-1717987590.8468134-765320-12883147314374/AnsiballZ_zabbix_host.py && sleep 0'
<192.168.1.4> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-765317m2aojvnh/ansible-tmp-1717987590.8468134-765320-12883147314374/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_tk0glq_p/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 29, in _httpapi_error_handle
    code, response = self.connection.send_request(data=payload)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_tk0glq_p/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py", line 199, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [192.168.1.4]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "description": null,
            "force": true,
            "host_groups": [
                "Linux servers"
            ],
            "host_name": "Example",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": [
                {
                    "details": {},
                    "dns": "",
                    "ip": "192.168.1.111",
                    "main": 1,
                    "port": "10050",
                    "type": 1,
                    "useip": 1
                }
            ],
            "inventory_mode": null,
            "inventory_zabbix": null,
            "ipmi_authtype": null,
            "ipmi_password": null,
            "ipmi_privilege": null,
            "ipmi_username": null,
            "link_templates": [
                "ICMP Ping"
            ],
            "macros": null,
            "proxy": null,
            "state": "present",
            "status": "enabled",
            "tags": null,
            "tls_accept": null,
            "tls_connect": null,
            "tls_psk": null,
            "tls_psk_identity": null,
            "tls_subject": null,
            "visible_name": null
        }
    },
    "msg": "connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter \"/1/groups/1\": unexpected parameter \"name\".'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"host.create\", \"id\": \"c88d865c-3bdb-44ed-afe3-e5ad71ba56ab\", \"params\": {\"host\": \"Example\", \"interfaces\": [{\"type\": 1, \"main\": 1, \"useip\": 1, \"ip\": \"192.168.1.111\", \"dns\": \"\", \"port\": \"10050\", \"details\": {}}], \"groups\": [{\"groupid\": \"2\", \"name\": \"Linux servers\", \"flags\": \"0\", \"uuid\": \"dc579cd7a1a34222933f24f52a68bcd8\"}], \"status\": 0}, \"auth\": \"533006ff313344ac53f4efaafb436445\"}"
}

PLAY RECAP ***************************************************************************************************************************************************
192.168.1.4                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
