### ISSUE TITLE
zabbix proxy doesn't configure itself properly on zabbix server

### ISSUE THREAD

**Issue by lsThaTaSuPra** [ansible-collections/community.zabbix#1313]
##### SUMMARY

we are able to create a proxy on zabbix server but cant configure it, mode, address and it create itself in active mode with no address. We would like to create it in passive with a dns address
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_proxy 
##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/glepape/Projects/iac/ansible.cfg) = ['/home/glepape/Projects/iac/.galaxy/collections', '/home/glepape/Pro>
CONFIG_FILE() = /home/glepape/Projects/iac/ansible.cfg
DEFAULT_FORKS(/home/glepape/Projects/iac/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/glepape/Projects/iac/ansible.cfg) = ['/home/glepape/Projects/iac/:']
DEFAULT_JINJA2_EXTENSIONS(/home/glepape/Projects/iac/ansible.cfg) = jinja2.ext.do
DEFAULT_ROLES_PATH(/home/glepape/Projects/iac/ansible.cfg) = ['/home/glepape/Projects/iac/.galaxy/roles']
DEFAULT_STDOUT_CALLBACK(/home/glepape/Projects/iac/ansible.cfg) = ansible.posix.debug
HOST_KEY_CHECKING(/home/glepape/Projects/iac/ansible.cfg) = False
INVENTORY_ENABLED(/home/glepape/Projects/iac/ansible.cfg) = ['sowi.awx.hybrid', 'host_list', 'script', 'auto', 'sowi.awx.yaml', '>
VARIABLE_PRECEDENCE(/home/glepape/Projects/iac/ansible.cfg) = ['all_plugins_inventory', 'all_plugins_play', 'all_inventory', 'gro>
```

##### OS / ENVIRONMENT / Zabbix Version

Almalinux 9.4 -comunity.zabbix = 3.0.0

##### STEPS TO REPRODUCE

starting a playbook on a zabbix proxy to create itself on the zabbix server with a config provided
playbook : 

```yaml
- name: 10_install | Update zabbix_server data
  vars:
    ansible_user: "{{ zabbix_login_user }}"
    ansible_httpapi_pass: "{{  zabbix_login_password }}"
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: "{{ zabbix_proxy_server_host }}"
  block:
    - name: 10_install | create zabbix proxy
      community.zabbix.zabbix_proxy:
        status: passive
        state: present
        interface:
          dns:  "{{ ansible_fqdn }}"
          port: 10051
        proxy_name: proxy-test
        description: test
        tls_connect: PSK
        tls_accept: PSK
        tls_psk_identity:
      delegate_to: monitoring-doc.iac.lan
```

##### EXPECTED RESULTS

create a zabbix proxy on the web interface with the provided settings

##### ACTUAL RESULTS

creates a proxy without the provided settings here active mode with no dns address

```paste below
No error in terminal 
```
