### ISSUE TITLE
community.zabbix.zabbix_host: The "proxy" parameter is not applied in zabbix 7.0

### ISSUE THREAD

**Issue by oit933** [ansible-collections/community.zabbix#1330]
##### SUMMARY
I create (or update) a host with the "proxy" parameter on the zabbix server. This parameter is not applied.
I think the error is related to the new "[monitored_by](https://www.zabbix.com/documentation/current/en/manual/api/reference/host/object#host)" parameter in zabbix 7.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_host

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.7]
  config file = /home/user/ansible/environments/production/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/user/ansible/environments/production/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/user/ansible/environments/production/ansible.cfg) = True
CALLBACKS_ENABLED(/home/user/ansible/environments/production/ansible.cfg) = ['ansible.posix.profile_tasks']
CONFIG_FILE() = /home/user/ansible/environments/production/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/home/user/ansible/environments/production/ansible.cfg) = ['/home/user/ansible/plugins/filter']
DEFAULT_FORCE_HANDLERS(/home/user/ansible/environments/production/ansible.cfg) = True
DEFAULT_GATHERING(/home/user/ansible/environments/production/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/user/ansible/environments/production/ansible.cfg) = merge
DEFAULT_MANAGED_STR(/home/user/ansible/environments/production/ansible.cfg) = This file is managed by Ansible.%n
template: {file}
from: {uid}@{host}
DEFAULT_REMOTE_USER(/home/user/ansible/environments/production/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/user/ansible/environments/production/ansible.cfg) = ['/home/user/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/user/ansible/environments/production/ansible.cfg) = yaml
DEFAULT_VAULT_ID_MATCH(/home/user/ansible/environments/production/ansible.cfg) = true
DEFAULT_VAULT_PASSWORD_FILE(/home/user/ansible/environments/production/ansible.cfg) = /home/user/ansible/vault_password
INJECT_FACTS_AS_VARS(/home/user/ansible/environments/production/ansible.cfg) = True
INTERPRETER_PYTHON(/home/user/ansible/environments/production/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT / Zabbix Version

community.zabbix=3.0.2/ Zabbix-Server 7.0.0

##### STEPS TO REPRODUCE

```yaml
- name: Create a new host
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: "{{ zabbix_api_server_host }}"
  community.zabbix.zabbix_host:
    host_name: "{{ zabbix_agent_hostname }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{ zabbix_agent_link_templates }}"
    status: enabled
    state: present
    interfaces: "{{ zabbix_agent_interfaces }}"
    proxy: "proxy_name"
```

##### EXPECTED RESULTS

Host monitoring via proxy applies if you specify a proxy name

##### ACTUAL RESULTS

The "proxy" parameter is not applied

```paste below
No error in terminal
```
