### ISSUE TITLE
community.zabbix.zabbix_host failed with -32602 error code

### ISSUE THREAD

**Issue by exray** [ansible-collections/community.zabbix#1368]
##### SUMMARY

I'm trying to run task:
```
- name: Add host to zabbix
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: zabbix.example.com
    ansible_user: admin
    ansible_httpapi_pass: password
  become: false
  community.zabbix.zabbix_host:
    host_name: ExampleHost
    host_groups:
      - Example group1
      - Example group2
    state: present
```
The error (formatted) is:
```
{
  'code': -32602,
  'message': 'Invalid params.',
  'data': 'Invalid parameter "/1/groups/1": unexpected parameter "name".'
} when sending {
  "jsonrpc": "2.0",
  "method": "host.create",
  "id": "eed709f4-fd3b-4521-a5aa-49bef3b8b82a",
  "params": {
    "host": "ExampleHost",
    "interfaces": [],
    "groups": [{
      "groupid": "22",
      "name": "Example group1",
      "flags": "0",
      "uuid": "87be8e1bc8ef33baa8d90e782bfd1fd8"
    }, {
      "groupid": "23",
      "name": "Example group2",
      "flags": "0",
      "uuid": "c4ec0805e40011369ae9b77bbc41c92b"
    }],
    "status": 0
  },
  "auth": "592249ceb7aa95f11efe05b7c658c050"
}
```

I also tried using `interfaces` block like #1355 but it gives the same error. I tried using `ansible_zabbix_auth_key` instead of user/password, I tried using `delegate_to` instead of `ansible_host` but it gives the same error too.

Other modules (e.g. `zabbix_group`) work fine, so there are no API issues in my environment.

I tried `community.zabbix 2.5.1` and `community.zabbix 3.1.0`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_host module on Zabbix 7.0

##### ANSIBLE VERSION
```paste below
ansible [core 2.16.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION
```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT / Zabbix Version
I'm running Ubuntu 24.04 LTS and Zabbix 7.0.2
