### ISSUE TITLE
If there is a comma in the host group name, two groups are created

### ISSUE THREAD

**Issue by djdejawu** [ansible-collections/community.zabbix#1375]
##### SUMMARY
There is a comma in my host group name. When using `community.zabbix.zabbix_group:` not one group is created, but two. Example:
```
Dataline 1,16 = Dataline 1 + 16 (two groups)
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_group

```
community.zabbix                         3.1.1
```

##### ANSIBLE VERSION
```
ansible [core 2.17.2]
  config file = /home/dejawu/venv/ansible.cfg
  configured module search path = ['/home/dejawu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dejawu/venv/lib64/python3.12/site-packages/ansible
  ansible collection location = /home/dejawu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dejawu/venv/bin/ansible
  python version = 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)] (/home/dejawu/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION
```
CONFIG_FILE() = /home/dejawu/venv/ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/home/dejawu/venv/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
OS: Fedora 39
Zabbix: 6.0.33 (Docker)

##### STEPS TO REPRODUCE
```
tasks:
  - name: Add host group
    community.zabbix.zabbix_group:
      host_groups:
        - DataLine 1,2
        - DataLine 1,3
        - DataLine 1,5
        - etc
```

##### EXPECTED RESULTS
One group with comma in name

##### ACTUAL RESULTS
Two groups delimited by comma
