### ISSUE TITLE
zabbix_agent on windows Include path not valid

### ISSUE THREAD

**Issue by MatthieuLeboeuf** [ansible-collections/community.zabbix#1378]
##### SUMMARY
With zabbix_agent on windows the Include in zabbix_agent2.conf is invalid

The value is
```
Include=/etc/zabbix/zabbix_agent2.d/*.conf
Include=/etc/zabbix/zabbix_agent2.d/plugins.d/*.conf
```

But the correct value is
```
Include=C:\Zabbix\conf\zabbix_agent2.d\*.conf
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent role

##### ANSIBLE VERSION

```
ansible [core 2.17.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.5 (main, Aug  7 2024, 19:15:55) [GCC 13.2.1 20240309] (/usr/local/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION

```
CONFIG_FILE() = None
DEPRECATION_WARNINGS(env: ANSIBLE_DEPRECATION_WARNINGS) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Windows Server 2022 / Zabbix 6.4

##### STEPS TO REPRODUCE
```yaml
- name: Install Zabbix Agent
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_agent
  vars:
    zabbix_agent2: true
    zabbix_agent_server: zabbix.xxxxx.com
    zabbix_agent_serveractive: zabbix.xxxxx.com
    zabbix_api_server_host: zabbix.xxxxx.com
    zabbix_api_use_ssl: true
    zabbix_api_server_port: 443
    zabbix_api_login_user: "{{ zabbix_login_user }}"
    zabbix_api_login_pass: "{{ zabbix_login_pass }}"
    zabbix_api_create_hosts: true
    zabbix_agent_host_state: present
    zabbix_agent_visible_hostname: "{{ visible_hostname }}"
    zabbix_host_groups: "{{ host_groups }}"
    zabbix_agent_link_templates: "{{ link_templates }}"
    zabbix_agent_tlsconnect: "unencrypted"
    zabbix_agent_tlsaccept: "unencrypted"
    zabbix_agent_interfaces:
      - type: 'agent'
        main: 1
        useip: 1
        ip: "{{ zabbix_agent_ip }}"
        port: "{{ zabbix_agent_listenport }}"
```
