### ISSUE TITLE
Zabbix Server installs fails on RHEL9: Unsupported parameters for (ansible.legacy.dnf) module: install_recommends

### ISSUE THREAD

**Issue by david-sieg** [ansible-collections/community.zabbix#1392]
##### SUMMARY
I try to deploy zabbix-server with no success on RHEL9, run fails on Install zabbix-server packages".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- name: Install zabbix-server packages
  ansible.builtin.package:
    name: "{{ _zabbix_server_packages }}"
    state: "{{ zabbix_server_package_state }}"
    update_cache: true
    disablerepo: "{{ zabbix_server_disable_repo | default(_zabbix_server_disable_repo | default(omit)) }}"
    install_recommends: "{{ zabbix_server_install_recommends | default(_zabbix_server_install_recommends | default(omit)) }}"
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: _zabbix_server_package_installed
  until: _zabbix_server_package_installed is succeeded
  become: true
  tags:
    - install

##### ANSIBLE VERSION

```
ansible-playbook [core 2.17.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.12.5 (tags/v3.12.5-3-g09eb333-dirty:09eb333, Sep  6 2024, 04:16:40) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
No config file found; using defaults

```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 7.0
RHEL 9.4

##### STEPS TO REPRODUCE

```

---

- hosts: all
  become: true

  tasks:

    - name: "Include community.zabbix.zabbix_server [zabbix_server]"
      include_role:
        name: 'community.zabbix.zabbix_server'
      when:
        - "'zabbix_server' in group_names"
      tags:
        - zabbix_server
        - zabbix_install

```

##### EXPECTED RESULTS

Fresh installed Zabbix Server.

##### ACTUAL RESULTS

```
fatal: [zabbix-server.domain.local]:
FAILED! => {"attempts": 3, "changed": false, "msg": "Unsupported parameters for (ansible.legacy.dnf) 
module: install_recommends. 
Supported parameters include: allow_downgrade, allowerasing, autoremove, bugfix, cacheonly, conf_file, disable_excludes, disable_gpg_check, disable_plugin, disablerepo, download_dir, download_only, enable_plugin, enablerepo, exclude, install_repoquery, install_weak_deps, installroot, list, lock_timeout, name, nobest, releasever, security, skip_broken, sslverify, state, update_cache, update_only, use_backend, validate_certs (expire-cache, pkg)."}
```
