### ISSUE TITLE
Debian 10 not supported by zabbix-agent role

### ISSUE THREAD

**Issue by hollier95** [ansible-collections/community.zabbix#1396]
##### SUMMARY

We can't use zabbix-agent role on Debian 10 servers
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix-agent role

##### ANSIBLE VERSION

```
ansible [core 2.16.3]
  config file = /builds/VDBuilding/system/deploy/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
CACHE_PLUGIN(/builds/test/system/deploy/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/builds/test/system/deploy/ansible/ansible.cfg) = /tmp/ansible-fact-cache
CACHE_PLUGIN_TIMEOUT(/builds/test/system/deploy/ansible/ansible.cfg) = 3600
CONFIG_FILE() = /builds/test/system/deploy/ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/builds/test/system/deploy/ansible/ansible.cfg) = ['/builds/test/system/deploy/ansible/filter_plugins']
DEFAULT_HOST_LIST(/builds/test/system/deploy/ansible/ansible.cfg) = ['/builds/test/system/deploy/ansible/inventories/devel']
DEFAULT_MANAGED_STR(/builds/test/system/deploy/ansible/ansible.cfg) = "File managed by ansible automation system"
DEFAULT_ROLES_PATH(/builds/test/system/deploy/ansible/ansible.cfg) = ['/builds/test/system/deploy/ansible/roles']
DEFAULT_TIMEOUT(/builds/test/system/deploy/ansible/ansible.cfg) = 12000
DEFAULT_VERBOSITY(env: ANSIBLE_VERBOSITY) = 0
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(/builds/test/system/deploy/ansible/ansible.cfg) = False
YAML_FILENAME_EXTENSIONS(/builds/test/system/deploy/ansible/ansible.cfg) = ['.json', '.yaml', '.yml', '.vault']
```

##### OS / ENVIRONMENT / Zabbix Version

Debian 10 server
##### STEPS TO REPRODUCE

Just try to run zabbix-agent role on Debian 10 server

##### EXPECTED RESULTS

```
TASK [community.zabbix.zabbix_agent : Check that version is supported] *********
ok: [prod-macif] => {
    "changed": false,
    "msg": "All assertions passed"
}
```
##### ACTUAL RESULTS

```
TASK [community.zabbix.zabbix_agent : Check that version is supported] *********
fatal: [test]: FAILED! => {"msg": "The conditional check 'zabbix_agent_version | float in zabbix_valid_agent_versions[ansible_distribution_major_version]' failed. The error was: error while evaluating conditional (zabbix_agent_version | float in zabbix_valid_agent_versions[ansible_distribution_major_version]): 'dict object' has no attribute '10'. 'dict object' has no attribute '10'"}
```

##### SUGGESTION
Just add Debian 10 support on [roles/zabbix_agent/vars/Debian.yml](https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/vars/Debian.yml)

##### TEMPORARY FIX
Create this extra vars file  :
```yaml
---
# vars file for zabbix_agent (Debian)

zabbix_agent: zabbix-agent

zabbix_valid_agent_versions:
  # Debian
  "12":
    - 7.0
    - 6.4
    - 6.0

  "11":
    - 7.0
    - 6.4
    - 6.0

  "10":
    - 7.0
    - 6.4
    - 6.0

  "9":
    - 7.0
    - 6.4
    - 6.0
  # Ubuntu
  "24":
    - 7.0
    - 6.4
    - 6.0

  "22":
    - 7.0
    - 6.4
    - 6.0

  "20":
    - 7.0
    - 6.4
    - 6.0
```
And call it from your playbook : 
```
ansible-playbook zabbix-agent.yml --extra-vars "@zabbix-agent-extravars.yml"
```
