### ISSUE TITLE
Variable settings in AutoPSK breaks Windows agent installation code

### ISSUE THREAD

**Issue by aloforte** [ansible-collections/community.zabbix#1402]
##### SUMMARY
In multiple places within role zabbix_agent, flow is broken for windows installation by reuse of the same "register" variable.
Since Subsequent non-windows task registers the same, the variable doesn't contain the expected data on Windows, but the "skip" information from the non-windows step immediately after it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent role, at least in `psk_identity` and `psk_secret` task files. Sample below.

##### ANSIBLE VERSION
```paste below
ansible [core 2.17.3]
  config file = None
  configured module search path = ['/Users/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.3.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/10.3.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION
Code excerpt
```
   - name: AutoPSK | Check for existing TLS PSK identity | Windows
      ansible.windows.win_stat:
        path: "{{ zabbix_agent_tlspskidentity_file }}"
      register: zabbix_agent_tlspskidentity_check_windows
      when:
        - ansible_os_family == "Windows"

    - name: AutoPSK | Check for existing TLS PSK identity | Linux
      ansible.builtin.stat:
        path: "{{ zabbix_agent_tlspskidentity_file }}"
      register: zabbix_agent_tlspskidentity_check_linux
      become: true
      when:
        - ansible_os_family != "Windows"

    - name: Set zabbix_agent_tlspskidentity_check
      ansible.builtin.set_fact:
        zabbix_agent_tlspskidentity_check: "{{ zabbix_agent_tlspskidentity_check_windows if ansible_os_family == 'Windows' else zabbix_agent_tlspskidentity_check_linux }}"
```

##### OS / ENVIRONMENT / Zabbix Version
OS Target Version: any windows

##### STEPS TO REPRODUCE
Run zabbix_agent playbook with default settings against any windows host.

##### EXPECTED RESULTS
Zabbix agent installed and configured.

##### ACTUAL RESULTS
Multiple occurrences like this one:
```
fatal: [********] FAILED! =>
  msg: |-
    The conditional check 'zabbix_agent_tlspskidentity_check.stat.exists' failed. The error was: error while evaluating conditional (zabbix_agent_tlspskidentity_check.stat.exists): 'dict object' has no attribute 'stat'
...
    The offending line appears to be:

    - name: AutoPSK | Read existing TLS PSK identity file
```
Though this is not the only place.
