### ISSUE TITLE
zabbix_user_directory is not idempotent

### ISSUE THREAD

**Issue by ohmer1** [ansible-collections/community.zabbix#1407]
##### SUMMARY
The zabbix_user_directory module is not idempotent. It always report a change when I run the task you will find in the steps to reproduce section bellow.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_user_directory

##### ANSIBLE VERSION

```paste below
  config file = /home/user/git/conformite/ansible.cfg
  configured module search path = ['/home/user/git/conformite/library']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/git/conformite/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### CONFIGURATION

```paste below
NSIBLE_FORCE_COLOR(/home/user/git/conformite/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/user/git/conformite/ansible.cfg) = True
CALLBACKS_ENABLED(/home/user/git/conformite/ansible.cfg) = ['profile_roles', 'timer', 'profile_tasks']
COLLECTIONS_PATHS(/home/user/git/conformite/ansible.cfg) = ['/home/user/git/conformite/collections']
COLOR_CHANGED(/home/user/git/conformite/ansible.cfg) = yellow
COLOR_DEBUG(/home/user/git/conformite/ansible.cfg) = dark gray
COLOR_DEPRECATE(/home/user/git/conformite/ansible.cfg) = purple
COLOR_DIFF_ADD(/home/user/git/conformite/ansible.cfg) = green
COLOR_DIFF_LINES(/home/user/git/conformite/ansible.cfg) = cyan
COLOR_DIFF_REMOVE(/home/user/git/conformite/ansible.cfg) = red
COLOR_ERROR(/home/user/git/conformite/ansible.cfg) = red
COLOR_HIGHLIGHT(/home/user/git/conformite/ansible.cfg) = white
COLOR_OK(/home/user/git/conformite/ansible.cfg) = green
COLOR_SKIP(/home/user/git/conformite/ansible.cfg) = cyan
COLOR_UNREACHABLE(/home/user/git/conformite/ansible.cfg) = red
COLOR_VERBOSE(/home/user/git/conformite/ansible.cfg) = blue
COLOR_WARN(/home/user/git/conformite/ansible.cfg) = bright purple
CONFIG_FILE() = /home/user/git/conformite/ansible.cfg
DEFAULT_BECOME_ASK_PASS(/home/user/git/conformite/ansible.cfg) = True
DEFAULT_FORKS(/home/user/git/conformite/ansible.cfg) = 8
DEFAULT_GATHERING(/home/user/git/conformite/ansible.cfg) = smart
DEFAULT_GATHER_TIMEOUT(/home/user/git/conformite/ansible.cfg) = 120
DEFAULT_HOST_LIST(/home/user/git/conformite/ansible.cfg) = ['/home/user/git/conformite/inventaire']
DEFAULT_JINJA2_NATIVE(/home/user/git/conformite/ansible.cfg) = False
DEFAULT_MANAGED_STR(/home/user/git/conformite/ansible.cfg) = Généré par Ansible - vos modifications seront détectées et écrasées!
DEFAULT_MODULE_PATH(/home/user/git/conformite/ansible.cfg) = ['/home/user/git/conformite/library']
DEFAULT_MODULE_UTILS_PATH(/home/user/git/conformite/ansible.cfg) = ['/home/user/git/conformite/module_utils']
DEFAULT_ROLES_PATH(/home/user/git/conformite/ansible.cfg) = ['/home/user/git/conformite/roles']
DEFAULT_STDOUT_CALLBACK(/home/user/git/conformite/ansible.cfg) = default
DEFAULT_TIMEOUT(/home/user/git/conformite/ansible.cfg) = 60
DIFF_ALWAYS(/home/user/git/conformite/ansible.cfg) = True
DIFF_CONTEXT(/home/user/git/conformite/ansible.cfg) = 3
GALAXY_SERVER(/home/user/git/conformite/ansible.cfg) = https://galaxy.ansible.com
HOST_KEY_CHECKING(/home/user/git/conformite/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/git/conformite/ansible.cfg) = auto
INVENTORY_IGNORE_EXTS(/home/user/git/conformite/ansible.cfg) = ['.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '~', '.orig', '.ini', '.c>
MAX_FILE_SIZE_FOR_DIFF(/home/user/git/conformite/ansible.cfg) = 1000000
SHOW_CUSTOM_STATS(/home/user/git/conformite/ansible.cfg) = True
```

##### STEPS TO REPRODUCE
Here a task always running with a changed state.

```yaml
- name: 'serveur/configuration | user directory'
  community.zabbix.zabbix_user_directory:
    name: 'AD {{ item }}'
    idp_type: 'ldap'
    host: '{{ zabbix_ldap_host[item] }}'
    port: '{{ zabbix_ldap_port }}'
    base_dn: '{{ zabbix_ldap_base_dn }}'
    group_basedn: '{{ zabbix_ldap_group_basedn }}'
    search_attribute: 'sAMAccountName'
    group_name: 'sAMAccountName'
    group_member: 'member'
    user_ref_attr: 'distinguishedName'
    group_filter: '(&(objectclass=group)(%{groupattr}:1.2.840.113556.1.4.1941:=%{ref}))'
    user_username: 'givenName'
    user_lastname: 'sn'
    bind_dn: '{{ zabbix_ldap_bind_dn }}'
    bind_password: '{{ zabbix_bind_password }}'
    search_filter: '{{ zabbix_ldap_search_filter }}'
    provision_status: yes
    provision_groups:
      - name: 'acces_zabbix_admin'
        role: 'Admin role'
        user_groups:
          - 'Zabbix administrators'
      - name: 'acces_zabbix_superadmin'
        role: 'Super admin role'
        user_groups:
          - 'Zabbix administrators'
    provision_media:
      - name: 'Courriel'
        mediatype: 'Email (HTML)'
        attribute: 'mail'
  loop:
    - 'principal'
    - 'secondaire'
 ```

##### EXPECTED RESULTS

The task should return OK if there is no change.

##### ACTUAL RESULTS

```paste below
changed: [server] => (item=principal) => 
    ansible_loop_var: item
    changed: true
   ...
```

**Comment by Nihlus** [comment]
I'm also experiencing this issue. 
```
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/jarl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/jarl/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
Installed collections:
```yml
collections:
  - name: collections/ondrejhome-ha_cluster-1.0.3.tar.gz
    version: 1.0.3
  - name: collections/freeipa-ansible_freeipa-1.14.2.tar.gz
    version: 1.14.2
  - name: collections/fedora-linux_system_roles-1.93.0.tar.gz
    version: 1.93.0
  - name: collections/ansible-posix-2.0.0.tar.gz
    version: 2.0.0
  - name: collections/containers-podman-1.16.2.tar.gz
    version: 1.16.2
  - name: collections/community-general-10.1.0.tar.gz
    version: 10.1.0
  - name: collections/community-zabbix-3.2.0.tar.gz
    version: 3.2.0
  - name: collections/ansible-windows-2.6.0.tar.gz
    version: 2.6.0
  - name: collections/ansible-netcommon-7.1.0.tar.gz
    version: 7.1.0
  - name: collections/ansible-utils-5.1.2.tar.gz
    version: 5.1.2
  - name: collections/community-mysql-3.11.0.tar.gz
    version: 3.11.0
  - name: collections/community-postgresql-3.9.1.tar.gz
    version: 3.9.1
  - name: collections/nextcloud-admin-2.1.0.tar.gz
    version: 2.1.0
```
