### ISSUE TITLE
Add support to configure severity on provision_media

### ISSUE THREAD

**Issue by ohmer1** [ansible-collections/community.zabbix#1408]
##### SUMMARY
Zabbix 7.0 allow to provision media and to enable it only for some severity instead of all events. Unfortunately, the zabbix_user_directory module doesn't allow to configure that at this moment.

See https://support.zabbix.com/browse/ZBXNEXT-8760.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_user_directory

##### ADDITIONAL INFORMATION

This could be used something like that:

```yaml
- community.zabbix.zabbix_user_directory:
    ...
    provision_media:
       - name: 'Email (HTML)'
         mediatype: 'Email (HTML)'
         attribute: 'mail'
         severity:
           - 'High'
           - 'Disaster'
```
