### ISSUE TITLE
Add hostnames option in inventory plugin

### ISSUE THREAD

**Issue by Fairy-** [ansible-collections/community.zabbix#1417]
##### SUMMARY
Allow the usage of jinja templates to compose inventory_hostname

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.zabbix.zabbix_inventory

##### ADDITIONAL INFORMATION
This would allow customizing the Hostname for better interoperability with other inventories.

Some other dynamic inventory plugins already have this feature: 
- community.vmware.vmware_vm_inventory
- amazon.aws.aws_ec2 inventory

```yaml
plugin: community.zabbix.zabbix_inventory
server_url: zabbix
login_user: ...
login_password: ...
hostnames:
 - inventory_hostname | lower
```
