### ISSUE TITLE
task "Ensure proxy definition is up-to-date (added/updated/removed)" in "zabbix_proxy" module seems to be not compatible with zabbix 7

### ISSUE THREAD

**Issue by dshuffin** [ansible-collections/community.zabbix#1418]
##### SUMMARY

When I try to register a passive proxy with zabbix_proxy role the play fails at "Ensure proxy definition is up-to-date (added/updated/removed)" task. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

"Ensure proxy definition is up-to-date (added/updated/removed)" in zabbix_proxy role
##### ANSIBLE VERSION

```paste below
ansible [core 2.17.5]
  config file = /home/<>/infrastructure/ansible.cfg
  configured module search path = ['/home/<>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/<>/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/<>/infrastructure/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/<>/infrastructure/ansible.cfg) = True
DEFAULT_MANAGED_STR(/home/<>/infrastructure/ansible.cfg) = $Managed with Ansible$
DEFAULT_ROLES_PATH(/home/<>/infrastructure/ansible.cfg) = ['/home/<>/infrastructure/galaxy_roles', '/home/<>/infrastructure/roles']
DEFAULT_STDOUT_CALLBACK(/home/<>/infrastructure/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/<>/infrastructure/ansible.cfg) = 60

```

##### OS / ENVIRONMENT / Zabbix Version

zabbix 7 on ubuntu 24.04

##### STEPS TO REPRODUCE

try to register zabbix 7 proxy to zabbix 7 host with zabbix_proxy role using 3.1.2 version of collection 

in proxy inventory:
```yaml
zabbix_api_create_proxy: true
zabbix_proxy_status: passive
zabbix_proxy_name: "{{ inventory_hostname }}"
zabbix_proxy_interface:
  useip: 0
  dns: "{{ inventory_hostname }}"
  port: 10051
zabbix_api_server_host: zabbix.webserver.hostname
zabbix_api_server_port: 443
zabbix_api_login_user: Admin
zabbix_api_login_pass: zabbix
zabbix_api_use_ssl: true
zabbix_proxy_tlspskfile: /home/zabbix/zabbix_proxy.psk
zabbix_proxy_tlspskidentity: "PSK {{ inventory_hostname }}"
zabbix_proxy_tlsaccept: psk # required for psk to work

```

##### EXPECTED RESULTS

Task succeeds and registers proxy

##### ACTUAL RESULTS

Task fails. Even though zabbix_proxy_status set to passive from output below it's clear that task sets operating_mode to active. This causes other parameters incompatibility which causes task to fail

```paste below

TASK [community.zabbix.zabbix_proxy : Ensure proxy definition is up-to-date (added/updated/removed)] **************************************************************************************************************************************
task path: /home/<>/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_proxy/tasks/main.yml:128
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /usr/lib/python3/dist-packages/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /usr/lib/python3/dist-packages/ansible_collections/ansible/utils
<zabbix.webserver.hostname> attempting to start connection
<zabbix.webserver.hostname> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /usr/bin/ansible-connection
<zabbix.webserver.hostname> local domain socket does not exist, starting it
<zabbix.webserver.hostname> control socket path is /home/<>/.ansible/pc/58b18c7e2e
<zabbix.webserver.hostname> Loading collection ansible.builtin from
<zabbix.webserver.hostname> redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<zabbix.webserver.hostname> Loading collection ansible.netcommon from /usr/lib/python3/dist-packages/ansible_collections/ansible/netcommon
<zabbix.webserver.hostname> Loading collection ansible.utils from /usr/lib/python3/dist-packages/ansible_collections/ansible/utils
<zabbix.webserver.hostname> Loading collection community.zabbix from /home/<>/.ansible/collections/ansible_collections/community/zabbix
<zabbix.webserver.hostname> local domain socket listeners started successfully
<zabbix.webserver.hostname> loaded API plugin ansible_collections.community.zabbix.plugins.httpapi.zabbix from path /home/<>/.ansible/collections/ansible_collections/community/zabbix/plugins/httpapi/zabbix.py for platform type community.zabbix.zabbix
<zabbix.webserver.hostname> Loading collection ansible.builtin from
<zabbix.webserver.hostname> local domain socket path is /home/<>/.ansible/pc/58b18c7e2e
<zabbix.webserver.hostname> ESTABLISH LOCAL CONNECTION FOR USER: <>
<zabbix.webserver.hostname> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk `"&& mkdir "` echo /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/ansible-tmp-1730988480.1149783-75066-203804066132421 `" && echo ansible-tmp-1730988480.1149783-75066-203804066132421="` echo /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/ansible-tmp-1730988480.1149783-75066-203804066132421 `" ) && sleep 0'
Using module file /home/<>/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_proxy.py
<zabbix.webserver.hostname> PUT /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/tmpmc7efzyi TO /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/ansible-tmp-1730988480.1149783-75066-203804066132421/AnsiballZ_zabbix_proxy.py
<zabbix.webserver.hostname> EXEC /bin/sh -c 'chmod u+x /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/ansible-tmp-1730988480.1149783-75066-203804066132421/ /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/ansible-tmp-1730988480.1149783-75066-203804066132421/AnsiballZ_zabbix_proxy.py && sleep 0'
<zabbix.webserver.hostname> EXEC /bin/sh -c '/usr/bin/python3 /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/ansible-tmp-1730988480.1149783-75066-203804066132421/AnsiballZ_zabbix_proxy.py && sleep 0'
<zabbix.webserver.hostname> EXEC /bin/sh -c 'rm -f -r /home/<>/.ansible/tmp/ansible-local-74710jf6o48dk/ansible-tmp-1730988480.1149783-75066-203804066132421/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.zabbix.zabbix_proxy_payload_95makeya/ansible_community.zabbix.zabbix_proxy_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 29, in _httpapi_error_handle
    code, response = self.connection.send_request(data=payload)
  File "/tmp/ansible_community.zabbix.zabbix_proxy_payload_95makeya/ansible_community.zabbix.zabbix_proxy_payload.zip/ansible/module_utils/connection.py", line 199, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [zabbix.proxy.hostname -> zabbix.webserver.hostname]: FAILED! => changed=false
  invocation:
    module_args:
      address: null
      allowed_addresses: null
      ca_cert: null
      custom_timeouts: 0
      description: null
      http_login_password: null
      http_login_user: null
      interface:
        dns: zabbix.proxy.hostname
        ip: ''
        port: '10051'
        useip: 0
      local_address: null
      local_port: '10051'
      operating_mode: active
      port: '10051'
      proxy_address: null
      proxy_group: null
      proxy_name: zabbix.proxy.hostname
      state: present
      status: passive
      timeout_browser: null
      timeout_db_monitor: null
      timeout_external_check: null
      timeout_http_agent: null
      timeout_script: null
      timeout_simple_check: null
      timeout_snmp_agent: null
      timeout_ssh_agent: null
      timeout_telnet_agent: null
      timeout_zabbix_agent: null
      tls_accept: no_encryption
      tls_connect: PSK
      tls_psk: null
      tls_psk_identity: PSK zabbix.proxy.hostname
      tls_subject: null
  msg: 'connection error occurred: REST API returned {''code'': -32602, ''message'': ''Invalid params.'', ''data'': ''Invalid parameter "/1/tls_connect": value must be 1.''} when sending {"jsonrpc": "2.0", "method": "proxy.create", "id": "bf79f396-f690-4f0d-91a8-1285ff85604d", "params": {"name": "zabbix.proxy.hostname", "operating_mode": "0", "tls_connect": "2", "tls_accept": "1", "tls_psk_identity": "PSK zabbix.proxy.hostname", "port": "10051", "local_port": "10051"}, "auth": "994610155a61a4726ee770cc3345f200"}'


```

**Comment by fionnb** [comment]
I am having the very same problem against a Zabbix 6 Server! All Details can be found [in this posting on the Zabbix forums](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/498967-zabbix-6-0-adding-proxy-via-api-fails-server-does-not-accept-tls_accept-2-psk). 
The issue is surprising to me, mainly because that task has been running flawlessly in the past and I am pretty sure we did not change any major components in the last months.
Could it be that "2" is sent as a string but expected as an integer in zabbix_proxy.py ??

**Comment by fionnb** [comment]
@dshuffin looking closer, your error message reveals that zabbix_proxy.py seemingly did not send a "tls_psk" data field in its API request. Either this is a bug or your "tlspskfile" was not readable. Anyway, without getting a PSK the server might rightfully answer "can't do".

**Comment by fionnb** [comment]
@dshuffin also, in your task you mixed the new 7.0 parameter "operating_mode" with its predecessor "status", one of them being set to "active" and one to "passive" (contradiction). That is confusing at least.

**Comment by manuello1996** [comment]
Same problem here with Zabbix 7.0.9. 
I have figured out that if you create a proxy element via API with no encryption (do not specify the PSK) it work. For the moment i have 3 task creating without enc (with proxy role) a second one setting the psk (with proxy role) and a third one modify the proxy via API with the proxy module. 
So i can fully automate tue deploy of new proxy

**Comment by fionnb** [comment]
> Same problem here with Zabbix 7.0.9. I have figured out that if you create a proxy element via API with no encryption (do not specify the PSK) it work. For the moment i have 3 task creating without enc (with proxy role and api_create_proxy) a second one setting the psk (with proxy role just to configure the procy locally api_create_proxy: false) and a third one modify the proxy via API with the proxy module. So i can fully automate tue deploy of new proxy

Although uncomfortably complicated, this sounds like a valid workaround. Would you mind to share example tasks? :-)

**Comment by BGmot** [comment]
This https://github.com/ansible-collections/community.zabbix/pull/1466 should help.
Try changing your code to:
```
zabbix_api_create_proxy: true
zabbix_proxy_status: passive
zabbix_proxy_name: "{{ inventory_hostname }}"
zabbix_proxy_interface:
  useip: 0
  dns: "{{ inventory_hostname }}"
  port: 10051
zabbix_api_server_host: zabbix.webserver.hostname
zabbix_api_server_port: 443
zabbix_api_login_user: Admin
zabbix_api_login_pass: zabbix
zabbix_api_use_ssl: true
zabbix_proxy_tlspskfile: /home/zabbix/zabbix_proxy.psk
zabbix_proxy_tlspskidentity: "PSK {{ inventory_hostname }}"
zabbix_proxy_tlsconnect: psk # required for psk to work
zabbix_proxy_tlspsk_secret: <your_32_hex_string>
```
The above should work for 7.x too.

Note:
For passive Zabbix proxy you need to define `zabbix_proxy_tlsconnect` not `zabbix_proxy_tlsaccept` as this works from Zabbix server perspective - connect to passive proxy and accept from active proxy.

**Comment by manuello1996** [comment]
> > Same problem here with Zabbix 7.0.9. I have figured out that if you create a proxy element via API with no encryption (do not specify the PSK) it work. For the moment i have 3 task creating without enc (with proxy role and api_create_proxy) a second one setting the psk (with proxy role just to configure the procy locally api_create_proxy: false) and a third one modify the proxy via API with the proxy module. So i can fully automate tue deploy of new proxy
> 
> [@manuello1996](https://github.com/manuello1996) Although a bit uncomfortably complicated, this sounds like a valid workaround. Would you mind to share example tasks? :-)
> 
> [@BGmot](https://github.com/BGmot) Problem also occurs with Zabbix 6.

I Was able to reduce it to "just" two tasks. 
```
- name: Install & configure zabbix proxy
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_proxy
  vars:
    zabbix_proxy_include_dir: "/etc/zabbix/zabbix_proxy.conf.d"
    selinux_allow_zabbix_can_http: true
    selinux_allow_zabbix_can_network: true
    become: false
    zabbix_proxy_version: "{{ zabbix_hvrz_version }}"
    zabbix_proxy_version_minor: "{{ zabbix_hvrz_version_minor }}"
    zabbix_proxy_ip: "{{ net[iface_mgmt].ip }}"
    zabbix_proxy_server: "{{ zabbix_hvrz_server }}"
    zabbix_proxy_database: pgsql
    zabbix_proxy_dbuser: zabbix_proxy
    zabbix_proxy_dbpassword: "{{ all_vault_zabbix_proxy_db_password }}"
    zabbix_proxy_listenport: 10051
    zabbix_api_server_host: "{{ zabbix_hvrz_api_server_url }}" 
    zabbix_api_login_user: "{{ zabbix_hvrz_api_ansible_user }}" 
    zabbix_api_login_pass: "{{ all_vault_ansibleapi_pw }}"
    zabbix_api_server_port: "{{ zabbix_hvrz_api_ansible_httpapi_port }}" 
    zabbix_api_use_ssl: "{{ zabbix_hvrz_api_ansible_httpapi_use_ssl }}" 
    zabbix_api_validate_certs: no
    zabbix_proxy_name: "{{ inventory_hostname }}"
    zabbix_api_create_proxy: true
    zabbix_proxy_state: present
    ansible_zabbix_url_path: "{{ zabbix_hvrz_api_ansible_zabbix_url_path }}"
    zabbix_repo_rpm_gpg_key_url: "{{ zabbix_hvrz_rpm_gpg_key }}"
    zabbix_repo_yum: "{{ zabbix_hvrz_repo_yum }}"
  tags:
   - r09zabbixproxy
 
- name: configure zabbix proxy psk
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_proxy
  vars:
    zabbix_proxy_include_dir: "/etc/zabbix/zabbix_proxy.conf.d"
    selinux_allow_zabbix_can_http: true
    selinux_allow_zabbix_can_network: true
    become: false
    zabbix_proxy_ip: "{{ net[iface_mgmt].ip }}"
    zabbix_proxy_server: "{{ zabbix_hvrz_server }}"
    zabbix_proxy_database: pgsql
    zabbix_proxy_dbuser: zabbix_proxy
    zabbix_proxy_dbpassword: "{{ all_vault_zabbix_proxy_db_password }}"
    zabbix_proxy_listenport: 10051
  
    zabbix_api_server_host: "{{ zabbix_hvrz_api_server_url }}" 
    zabbix_api_login_user: "{{ zabbix_hvrz_api_ansible_user }}" 
    zabbix_api_login_pass: "{{ all_vault_ansibleapi_pw }}"
    zabbix_api_server_port: "{{ zabbix_hvrz_api_ansible_httpapi_port }}" 
    zabbix_api_use_ssl: "{{ zabbix_hvrz_api_ansible_httpapi_use_ssl }}" 
    zabbix_api_validate_certs: no
    zabbix_proxy_name: "{{ inventory_hostname }}"
    zabbix_api_create_proxy: true
    zabbix_proxy_state: present
    ansible_zabbix_url_path: "{{ zabbix_hvrz_api_ansible_zabbix_url_path }}"
    
    zabbix_manage_repo: false
    #PSK
    zabbix_proxy_tlsaccept: "psk"
    zabbix_proxy_tlsconnect: "psk"
    zabbix_proxy_tlspskfile: "/etc/zabbix/zabbix_proxy.psk"
    zabbix_proxy_tlspsk_secret: "{{ all_vault_zabbix_psk }}"
    zabbix_proxy_tlspskidentity: "{{ inventory_hostname }}-psk"
  tags:
   - r09zabbixproxy
   - r09zabbixproxy:psk
```

**Comment by manuello1996** [comment]
Hi, Thank you for the work in release 3.3.0
I'm still gatting the same problem with Zabbix 7.0.10

https://github.com/ansible-collections/community.zabbix/blob/bd86d7d029f9d4022b84c86aa7f21abb95c30bae/roles/zabbix_proxy/tasks/main.yml#L155


```
TASK [community.zabbix.zabbix_proxy : Ensure proxy definition is up-to-date (added/updated/removed) for Zabbix >= 7.0] ***
fatal: [hostxt4844-mgt.domain.priv -> zabbix-ha-pilot.domain.priv]: FAILED! => {"changed": false, "msg": "connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter \"/1/tls_connect\": value must be 1.'} when sending {'jsonrpc': '2.0', 'method': 'proxy.create', 'id': '5f275a2f-44f0-4b9e-9e78-a4245f046921', 'params': {'name': 'hostxt4844.domain.priv', 'operating_mode': '0', 'tls_connect': '2', 'tls_accept': '2', 'tls_psk_identity': 'hostxt4844.domain.priv-psk', 'tls_psk': '********', 'address': '127.0.0.1', 'port': '10051', 'local_port': '10051'}}"}
fatal: [hostxt4845-mgt.domain.priv -> zabbix-ha-pilot.domain.priv]: FAILED! => {"changed": false, "msg": "connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter \"/1/tls_connect\": value must be 1.'} when sending {'jsonrpc': '2.0', 'method': 'proxy.create', 'id': '562d606c-0e68-40fd-a25b-66c57a937fa4', 'params': {'name': 'hostxt4845.domain.priv', 'operating_mode': '0', 'tls_connect': '2', 'tls_accept': '2', 'tls_psk_identity': 'hostxt4845.domain.priv-psk', 'tls_psk': '********', 'address': '127.0.0.1', 'port': '10051', 'local_port': '10051'}}"}

```

```
- name: Install & configure zabbix proxy
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_proxy
  vars:
    zabbix_proxy_include_dir: "/etc/zabbix/zabbix_proxy.conf.d"
    selinux_allow_zabbix_can_http: true
    selinux_allow_zabbix_can_network: true
    selinux_allow_daemons_enable_cluster_mode: true

    zabbix_proxy_version: "7.0"
    zabbix_proxy_version_minor: "10"
    zabbix_proxy_ip: "{{ net[iface_mgmt].ip }}"
    zabbix_proxy_server: "{{ zabbix_hvrz_server }}"
    zabbix_proxy_name: "{{ ansible_hostname }}.{{ ansible_domain }}"
    zabbix_proxy_hostname: "{{ ansible_hostname }}.{{ ansible_domain }}"
    zabbix_proxy_database: pgsql
    zabbix_proxy_dbuser: zabbix_proxy
    zabbix_proxy_dbpassword: "{{ all_vault_zabbix_proxy_db_password }}"
    zabbix_proxy_listenport: 10051
    zabbix_proxy_status: "{{ zabbix_hvrz_proxy_status | default('active') }}" #Set the value in Hostvars to deploy passive proxy 
    zabbix_api_server_host: "{{ zabbix_hvrz_api_server_url }}" 
    zabbix_api_login_user: "{{ zabbix_hvrz_api_ansible_user }}" 
    zabbix_api_login_pass: "{{ all_vault_ansibleapi_pw }}"
    zabbix_api_server_port: "{{ zabbix_hvrz_api_ansible_httpapi_port }}" 
    zabbix_api_use_ssl: "{{ zabbix_hvrz_api_ansible_httpapi_use_ssl }}" 
    zabbix_api_validate_certs: no
    zabbix_api_create_proxy: true
    zabbix_proxy_state: present
    ansible_zabbix_url_path: "{{ zabbix_hvrz_api_ansible_zabbix_url_path }}"
    zabbix_proxy_tlsaccept: "psk"
    zabbix_proxy_tlsconnect: "psk"
    zabbix_proxy_tlspskfile: "/etc/zabbix/zabbix_proxy.psk"
    zabbix_proxy_tlspsk_secret: "{{ all_vault_zabbix_psk }}"
    zabbix_proxy_tlspskidentity: "{{ ansible_hostname }}.{{ ansible_domain }}-psk"
    
    zabbix_repo_rpm_gpg_key_url: "{{ zabbix_hvrz_rpm_gpg_key }}"
    zabbix_repo_yum: "{{ zabbix_hvrz_repo_yum }}"
```

Is this a problem on the API side? 
Thank you!
