### ISSUE TITLE
agent roles failed when multiple addresses set to zabbix_agent_listenip

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.zabbix#1429]
### Summary

Role fails when zabbix_agent_listenip is set to multiple IPs seperated by comma. According to the Zabbix Documentation it is possible to set multiple IPs. And since the role defaults to 0.0.0.0 when zabbix_agent_listenip is not defined it comes with alot of side effects. So either the zabbix_agent_listenip has to support multiple IPs or the default behavior should be changed when not defined ListenIP is not set in the agent config as that then would result in the expect bahavior during Autoregistration of a host that the Host IP is used and not the ListenIP as Agent IP on the server. 

### Issue Type

Bug Report

### Component Name

Zabbix-agent role

### Ansible Version

```console
$ ansible --version
core 2.15.0
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL8

### Steps to Reproduce

```yaml (paste below)
- set zabbix_agent_listenip to 192.168.1.101,127.0.0.1
```

### Expected Results

The ListenIP value in config is set to the value given. As per Zabbix Documentation the ListenIP value can have multiple IPs seperated by comma. Role shouldn't fail when the variable is set to multiple ListenIPs

### Actual Results

```console
The Role fails and says zabbix_agen_listenip isn't set
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by BGmot** [comment]
Please provide a log of the failure.

**Comment by Akasurde** [comment]
@bufanda ^^

**Comment by bufanda** [comment]
[zabbix_agent.log](https://github.com/user-attachments/files/18035121/zabbix_agent.log)

Log is attached

The playbook snippet:
```yaml
- name: Install zabbix agent 2
  hosts:
    - zabbix_agent2
  become: true
  roles:
    - role: community.zabbix.zabbix_agent
      tags:
        - monitoring
        - infrastructure
        - zabbix
```

The group_vars
```yaml
---
# code: language=ansible
zabbix_agent2: true
zabbix_agent_version: 7.0
zabbix_timezone: Europe/Berlin

zabbix_agent_server: 10.146.18.225
zabbix_agent_serveractive: 10.146.18.225
zabbix_agent_hostnameitem: system.hostname
zabbix_agent_hostmetadata: Linux
zabbix_agent_statusport:

zabbix_install_pip_packages: false
zabbix_agent_dont_detect_ip: true
zabbix_agent_listenip: "{{ ansible_default.ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
```

The host_vars for the host `sunna`
```yaml
---
# code: language=ansible
zabbix_agent_listenip: "{{ ansible_default.ipv4.address | default(ansible_all_ipv4_addresses[0]) }},127.0.0.1" # noqa: yaml[line-too-long]
```
