### ISSUE TITLE
httpapi not working with Zabbix 7.2.0

### ISSUE THREAD

**Issue by czertique** [ansible-collections/community.zabbix#1431]
##### SUMMARY

Authentication (both user/password and API token) not working with Zabbix 7.2.0.

This is happening because `auth` payload property has been deprecated ever since Zabbix 6.4 and finally removed in Zabbix 7.2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`httpapi`

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.7]
  config file = /etc/ansible/ansible.cfg
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 1000
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 1000
```

##### OS / ENVIRONMENT / Zabbix Version

I'm doing this on Ubuntu 22.04 but I believe it will behave the same on any other OS

##### STEPS TO REPRODUCE

Try to add new host to Zabbix (but will likely happen with any other API call against Zabbix). Tested both username/password and API auth key

```yaml
- name: Add zabbix host to zabbix server
  delegate_to: zabbix_host
  tags:
    - zabbix
    - addhost
  vars:
    zabbix_interfaces:
      - type: 1
        ip: "1.2.3.4"
        dns: "host.domain"
        useip: "0"
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_zabbix_url_path: ''
    ansible_zabbix_auth_key: abc123
    # ansible_user: _ansible
    # ansible_httpapi_pass: ansible_pass
  community.zabbix.zabbix_host:
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    state: present
    status: enabled
    interfaces: "{{ zabbix_interfaces }}"
    link_templates:
      - Linux by Zabbix agent
    host_groups:
      - Linux servers
```

##### EXPECTED RESULTS

Host is added to Zabbix server

##### ACTUAL RESULTS

Task fails with error: `'message': 'Invalid request.', 'data': 'Invalid parameter \"/\": unexpected parameter \"auth\".'}`

```paste below
    "msg": "connection error occurred: REST API returned {'code': -32600, 'message': 'Invalid request.', 'data': 'Invalid parameter \"/\": unexpected parameter \"auth\".'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"template.get\", \"id\": \"090b5f4c-a0b9-437f-84d0-442a378f25b1\", \"params\": {\"output\": [\"templateid\"], \"filter\": {\"host\": \"Linux by Zabbix agent\"}}, \"auth\": \"e6f472a89054c8246177864547e905b1a3bee93af69b854a580d242c7d0df1db\"}"
```
