### ISSUE TITLE
Auth_token does not work properly in Zabbix 6.0.

### ISSUE THREAD

**Issue by yuslee80** [ansible-collections/community.zabbix#1434]
##### SUMMARY

I created an API token in Zabbix 6.0. After that, I added auth_token to the playbook as shown below and removed login_user and login_password. However, when I run the playbook, it fails to import the inventory. Interestingly, if I enter any value for login_user and login_password, the inventory synchronization works correctly. What kind of bug is this?
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
core 2.15.13
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT / Zabbix Version

OpenSource AWX, zabbix 6.0

##### STEPS TO REPRODUCE

```yaml
#### Works well
plugin: community.zabbix.zabbix_inventory
server_url: https://zabbix.test.net
add_zabbix_groups: true
login_user: test     # Correct user
login_password: 1234   # incorrect password
auth_token: b2f2731a084e2ae92a83397e19bccfd0e63e64b48b6a70d7925cdfdf55bfddfdf
host_zapi_query:
  output: ['host']
  selectInterfaces: ['ip']
  selectParentTemplates: ['name','templateid']
  selectGroups: ['name','groupid']
  selectInventory: ['os','hardware']
validate_certs: false
timeout: 120

#### Does not work
plugin: community.zabbix.zabbix_inventory
server_url: https://zabbix.test.net
add_zabbix_groups: true
auth_token: b2f2731a084e2ae92a83397e19bccfd0e63e64b48b6a70d7925cdfdf55bfddfdf
host_zapi_query:
  output: ['host']
  selectInterfaces: ['ip']
  selectParentTemplates: ['name','templateid']
  selectGroups: ['name','groupid']
  selectInventory: ['os','hardware']
validate_certs: false
timeout: 120
```

##### ACTUAL RESULTS

```
#### Originally, the configuration below should work properly.

plugin: community.zabbix.zabbix_inventory
server_url: https://zabbix.test.net
add_zabbix_groups: true
auth_token: b2f2731a084e2ae92a83397e19bccfd0e63e64b48b6a70d7925cdfdf55bfddfdf
host_zapi_query:
  output: ['host']
  selectInterfaces: ['ip']
  selectParentTemplates: ['name','templateid']
  selectGroups: ['name','groupid']
  selectInventory: ['os','hardware']
validate_certs: false
timeout: 120
```
