### ISSUE TITLE
Creating host group and host does not work with Zabbix Server 7.0 and zabbix_agent role community.zabbix 2.5.1

### ISSUE THREAD

**Issue by PrismaComputer** [ansible-collections/community.zabbix#1437]
##### SUMMARY
Creating host group and host does not work with Zabbix Server 7.0 and zabbix_agent role community.zabbix 2.5.1

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.2]
  config file = /mnt/c/Users/x/y/z/ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/x/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /homex/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/x/.local/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /mnt/c/Users/x/y/z/ansible.cfg
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = True
DEFAULT_HOST_LIST(/mnt/c/Users/x/y/z/ansible.cfg) = ['/mnt/c/Users/x/y/z/hosts']
EDITOR(env: EDITOR) = nano
HOST_KEY_CHECKING(/mnt/c/Users/x/y/z/ansible.cfg) = False
INTERPRETER_PYTHON(/mnt/c/Users/x/y/z/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/mnt/c/Users/x/y/z/ansible.cfg) = True
```

##### OS / ENVIRONMENT / Zabbix Version
Zabbix Server 7.0 (docker) on Ubuntu
Zabbix Agent Role community.zabbix 2.5.1 on Windows 10 WSL2

##### STEPS TO REPRODUCE
Try to execute role with creating host group and host

```yaml
    - name: Install zabbix-agent2
      role: zabbix_agent
      zabbix_agent2: true
      zabbix_agent_server: '127.0.0.1'
      zabbix_agent_serveractive: '{{ zabbix_server }}'
      zabbix_agent_hostname: '{{ ansible_host }}'
      zabbix_agent_tlsaccept: psk
      zabbix_agent_tlsconnect: psk
      zabbix_agent_tlspskidentity: '{{ enc_zabbix_agent_tlspskidentity }}'
      zabbix_agent_tlspskfile: '{{ zabbix_win_install_dir }}\zabbix_agentd.psk'
      zabbix_agent_tlspsk_secret: '{{ enc_zabbix_agent_tlspsk_secret  }}'
      zabbix_agent_visible_hostname: '{{ ansible_hostname }}'
      zabbix_agent_interfaces:
        - type: '1'
          main: True
          useip: True
          ip: 127.0.0.1
      zabbix_agent_inventory_mode: automatic
      zabbix_agent_link_templates:
        - Template OS Windows Active
      zabbix_host_groups:
        - "{{ host_group }}"
        - "{{ hosted_by }}"
      zabbix_api_server_host: '{{ zabbix_server }}'
      zabbix_api_login_user: '{{ enc_zabbix_api_user }}'
      zabbix_api_login_pass: '{{ enc_zabbix_api_pass }}'
      zabbix_api_use_ssl: true
      zabbix_api_server_port: 443
      zabbix_api_create_hosts: true
      zabbix_api_create_hostgroup: true
```

##### EXPECTED RESULTS
works

##### ACTUAL RESULTS
does not work

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: </body></html>
fatal: [somehost -> yyy.xxx.de]: FAILED! => {"attempts": 10, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/xxx/.ansible/tmp/ansible-local-11004d574wkqz/ansible-tmp-1735323404.6562107-11203-202111666747619/AnsiballZ_zabbix_group.py\", line 107, in <mo
dule>\n    _ansiballz_main()\n  File \"/home/xxx/.ansible/tmp/ansible-local-11004d574wkqz/ansible-tmp-1735323404.6562107-11203-202111666747619/AnsiballZ_zabbix_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/xxx/.ansible/tmp/ansible-l
ocal-11004d574wkqz/ansible-tmp-1735323404.6562107-11203-202111666747619/AnsiballZ_zabbix_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modul
es.zabbix_group', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \
"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_mvg76igs/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py\", line 181, in <module>\n  File \"
/tmp/ansible_community.zabbix.zabbix_group_payload_mvg76igs/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py\", line 153, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_mvg76igs/ansible_community.zabbix.zabbix_group_
payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 20, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_mvg76igs/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, i
n api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_mvg76igs/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py\", line 199, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 
2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n<hr>\n<address>Apache/2.4.62 (Unix) Server at yyy.xxx.de Port 443</address>\n</body></html>\n\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee
 stdout/stderr for the exact error", "rc": 1}
```
