### ISSUE TITLE
Unsupported Parameter for server_url

### ISSUE THREAD

**Issue by dilip400590** [ansible-collections/community.zabbix#1445]
Hello,

Im trying to delete the default zabbix configuration and i have created the plabook as below:

Zabbix Version : 7.0.8
OS Release: RHEL 8.10 
Python 3.9 
Ansible-core: 2.15.13

---

- name: Delte default zabbix configuration
  hosts: zabbix_server
  connection: local
  become: false

  collections:
    - community.zabbix
    - community.mysql

  tasks:
    - name: Remove 'Zabbix server'
      community.zabbix.zabbix_host:
        zabbix_api_server_url: "{{ zabbix_api_server_url }}"
        http_login_user: "{{ zabbix_api_login_user }}"
        http_login_password: "{{ zabbix_api_login_pass }}"
        ca_cert: "{{ zabbix_api_validate_certs }}"
        host_name: 'Zabbix server'
        state: absent

    - name: Remove default templates and mediatypes
      command: "{{ ansible_python_interpreter }} /opt/cspzabbix/ansible/playbooks/zabbix/playbooks/config/removetemplates.py -s '{{ zabbix_api_server_url }}' -l '{{ zabbix_api_login_user }}' -p '{{ zabbix_api_login_pass }}' {{ zabbix_api_validate_certs | ternary('', '-n') }}"

While running the playbook im getting the below error:

(python) [root@cspzabbix zabbix]# ansible-playbook -i inventory -e @rhel_vars.yml playbooks/config/zabbix-delete-default.yml

PLAY [Delte default zabbix configuration] *************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [cspzabbix]

TASK [Remove 'Zabbix server'] *************************************************************************************************************************************************************************************
fatal: [cspzabbix]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.********.********_host) module: ********_api_server_url. Supported parameters include: ca_cert, description, force, host_groups, host_name, http_login_password, http_login_user, interfaces, inventory_mode, inventory_********, ipmi_authtype, ipmi_password, ipmi_privilege, ipmi_username, link_templates, macros, monitored_by, proxy, proxy_group, state, status, tags, tls_accept, tls_connect, tls_psk, tls_psk_identity, tls_subject, visible_name (host_tags, tls_issuer, user_macros)."}

PLAY RECAP ********************************************************************************************************************************************************************************************************
cspzabbix                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Please help me to resolve the issue

**Comment by eb4x** [comment]
It's a bit hard to tell from this text output, try putting it in a code block using three backticks (\`\`\`)

But by the looks of it, you're not indenting your yaml correctly.

**Comment by dilip400590** [comment]
Im still getting the same error.

"fatal: [cspzabbix]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.********.********_host) module: server_url. Supported parameters include: ca_cert, description, force, host_groups, host_name, http_login_password, http_login_user, interfaces, inventory_mode, inventory_********, ipmi_authtype, ipmi_password, ipmi_privilege, ipmi_username, link_templates, macros, monitored_by, proxy, proxy_group, state, status, tags, tls_accept, tls_connect, tls_psk, tls_psk_identity, tls_subject, visible_name (host_tags, tls_issuer, user_macros)."}"

Please provide me the valid parameter for server_url

**Comment by eb4x** [comment]
Depending on whether the api is running on `zabbix_server`, it looks like you want to try something like this.

```
- name: Delete default zabbix configuration
  hosts: zabbix_server

  tasks:
    - name: Remove 'Zabbix server'
      community.zabbix.zabbix_host:
        host_name: 'Zabbix server'
        state: absent
      delegate_to: "{{ zabbix_api_server_url }}"
    vars:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_use_ssl: true
      ansible_user: "{{ zabbix_api_login_user }}"
      ansible_httpapi_pass: "{{ zabbix_api_login_pass }}"
      ansible_httpapi_port: 443
      ansible_zabbix_url_path: ''

    ...
```
