### ISSUE TITLE
zabbix agent role with version 7 not working on Ubuntu 22

### ISSUE THREAD

**Issue by mcguppy** [ansible-collections/community.zabbix#1456]
##### SUMMARY
when setting the variable` zabbix_agent_version: "7.0"` on Ubuntu 22 I am getting the message `"Zabbix version 7.0 is not supported on Ubuntu 22"`

Conserning the file https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md this should work

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix Agent Role

##### ANSIBLE VERSION
```
ansible [core 2.17.7]
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### CONFIGURATION

```
CONFIG_FILE() = /home/ubuntu/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/ubuntu/ansible/ansible.cfg) = ['/home/ubuntu/ansible/inventory']
DEFAULT_MANAGED_STR(/home/ubuntu/ansible/ansible.cfg) = ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
```

##### OS / ENVIRONMENT / Zabbix Version
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
```
Zabbix Server: 7.0.3

##### STEPS TO REPRODUCE

```yaml
---
- name: Ubuntu base setup
  hosts: os_ubuntu
  become: true
  gather_facts: yes

  roles:
    - role: community.zabbix.zabbix_agent
      when: zabbix_agent_enabled | default(false)
```

in group_vars/all.yml:

```yaml
---
# Zabbix Agent
# see https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md
zabbix_agent_enabled: true
zabbix_agent_version: "7.0" 
zabbix_agent2: True # useing Agent 2 instead of Agent 1
zabbix_agent_server: "192.168.130.55"
```

##### EXPECTED RESULTS

Installation of the zabbix agent in version 7.0

##### ACTUAL RESULTS

```paste below
TASK [community.zabbix.zabbix_agent : Check that version is supported] ************************************************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ zabbix_agent_version|float in
zabbix_valid_agent_versions[ansible_distribution_major_version] }}
fatal: [10.10.10.151]: FAILED! => {
    "assertion": "{{ zabbix_agent_version|float in zabbix_valid_agent_versions[ansible_distribution_major_version] }}",
    "changed": false,
    "evaluated_to": false,
    "msg": "Zabbix version 7.0 is not supported on Ubuntu 22"
}
```
When not setting the variable `zabbix_agent_version: "7.0"`  Zabbix Agent in version 6.4 is installed without errors.
