### ISSUE TITLE
Impossible to use Discovery rule with SNMP check in Discovery action condition

### ISSUE THREAD

**Issue by BGmot** [ansible-collections/community.zabbix#1459]
##### SUMMARY
Currently if you try to use Discovery rule with SNMP check in Discovery action condition the zabbix_action module will fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action module

##### ANSIBLE VERSION
Any
```
$ ansible --version
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/home/ey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ey/env_py312_ans216/lib/python3.12/site-packages/ansible
  ansible collection location = /home/ey/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ey/env_py312_ans216/bin/ansible
  python version = 3.12.2 (main, Feb 25 2024, 16:36:57) [GCC 9.4.0] (/home/ey/env_py312_ans216/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

##### OS / ENVIRONMENT / Zabbix Version
Any supported Zabbix version

##### STEPS TO REPRODUCE
```yaml
    - name: test - create discovery rule
      community.zabbix.zabbix_discovery_rule:
        state: present
        status: enabled
        name: Test discovery rule
        iprange: 127.0.0.1
        dchecks:
          - type: SNMPv2
            ports: 161
            key: '.1.3.6.1.2.1.1.1.0'
            snmp_community: public
        delay: 24h

    - name: test - create discovery action with SNMP discovery check
      community.zabbix.zabbix_action:
        conditions:
          - type: discovery_check
            operator: '='
            value: 'Test discovery rule: SNMPv2 agent ".1.3.6.1.2.1.1.1.0"'
        operations:
          - type: add_to_host_group
            host_groups:
              - Zabbix servers
```

##### EXPECTED RESULTS
Discovery action properly created/updated.

##### ACTUAL RESULTS
```
TASK [test_zabbix_action : test - create discovery rule] ***********************
changed: [testhost] => {"changed": true, "drule": "Test discovery rule", "druleid": "4", "msg": "Discovery Rule created: Test discovery rule, ID: 4", "state": "present"}

TASK [test_zabbix_action : test - create discovery action with SNMP discovery check] ***
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Discovery check type: SNMPv2 agent \".1.3.6.1.2.1.1.1.0\" does not exist"}
```
