### ISSUE TITLE
zabbix-web selinux not applied - centos 9 cloud image

### ISSUE THREAD

**Issue by anthony-redactus** [ansible-collections/community.zabbix#1468]
##### SUMMARY

selinux settings not applied, while set to enforcing, blocking apache connecting to the db and probably other components.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix-web
##### ANSIBLE VERSION

```paste below
ansible [core 2.16.14]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.1 (main, Dec  9 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/nano
```

##### OS / ENVIRONMENT / Zabbix Version

host: Fedora release 41 (Forty One)
target: Rocky Linux release 9.5 (Blue Onyx)
target_image: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
##### STEPS TO REPRODUCE

ansible-playbook zabbix-web.yml -i inventory

```yaml
---
- name: Install Zabbix Web
  hosts: zabbix_web
  become: true
  vars:
    zabbix_api_server_url: zabbix-web.domain
    zabbix_server_hostname: zabbix-server
    zabbix_server_database: pgsql
    zabbix_db_type_long: postgresql
    zabbix_server_dbhost: zabbix-db
    zabbix_server_dbname: zabbix-server
    zabbix_server_dbuser: zabbix
    zabbix_server_dbpassword: password
    selinux_allow_httpd_can_network_connect_db: true
    selinux_allow_httpd_can_connect_zabbix: true
    zabbix_server_dbport: 5432

  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - community.zabbix.zabbix_web
```

##### EXPECTED RESULTS

selinux settings applied

**Works for zabbix-server:**
TASK [community.zabbix.zabbix_server : RedHat | Configure SELinux when enabled] ****************************************************
included: /usr/lib/python3.13/site-packages/ansible_collections/community/zabbix/roles/zabbix_server/tasks/selinux.yml for zabbix-server.domain

TASK [community.zabbix.zabbix_server : SELinux | Install related SELinux packages] *************************************************
ok: [zabbix-server.domain]

TASK [community.zabbix.zabbix_server : SELinux | Set booleans] *********************************************************************
changed: [zabbix-server.domain] => (item={'name': 'httpd_can_connect_zabbix', 'state': True})
changed: [zabbix-server.domain] => (item={'name': 'zabbix_can_network', 'state': True})

TASK [community.zabbix.zabbix_server : SELinux | RedHat | Add SEmodule to fix SELinux issue: zabbix_server_alerter.sock] ***********
changed: [zabbix-server.domain]

##### ACTUAL RESULTS

selinux settings skipped

```paste below
TASK [community.zabbix.zabbix_web : Configure SELinux when enabled] ****************************************************************
task path: /usr/lib/python3.13/site-packages/ansible_collections/community/zabbix/roles/zabbix_web/tasks/RedHat.yml:61
skipping: [zabbix-web.domain] => {
    "changed": false,
    "false_condition": "zabbix_web_selinux | bool",
    "skip_reason": "Conditional result was False"
}

```
