### ISSUE TITLE
Error on parameter "tls_connect" in module community.zabbix.zabbix_proxy

### ISSUE THREAD

**Issue by ZzenlD** [ansible-collections/community.zabbix#1482]
##### SUMMARY
Creating a proxy with PSK fails because a supposedly incorrect value is passed for tls_connect.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_proxy

##### ANSIBLE VERSION
```
ansible [core 2.17.2]
  config file = /home/user/project/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/user/project/ansible.cfg) = True
CALLBACKS_ENABLED(/home/user/project/ansible.cfg) = ['profile_roles']
CONFIG_FILE() = /home/user/project/ansible.cfg
DEFAULT_HOST_LIST(/home/user/project/ansible.cfg) = ['/home/user/project/inventory/hosts']
DISPLAY_SKIPPED_HOSTS(/home/user/project/ansible.cfg) = False
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/home/user/project/ansible.cfg) = False
VARIABLE_PLUGINS_ENABLED(/home/user/project/ansible.cfg) = ['host_group_vars', 'community.sops.sops']
```

##### OS / ENVIRONMENT / Zabbix Version
Zabbix version 7.2.4 operated with docker-compose on a Linux host

##### STEPS TO REPRODUCE
According to the documentation, a Zabbix proxy with PSK should be able to be created with the following task:

```yaml
- name: Create proxies
    community.zabbix.zabbix_proxy:
      proxy_name: Test-Proxy
      description: My proxy description
      local_address: test-proxy.local
      tls_psk_identity: Test-Proxy
      tls_accept: PSK
      tls_connect: PSK
      tls_psk: <secret>
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: true
    ansible_zabbix_url_path: ""
    ansible_user: Admin
    ansible_httpapi_pass: <admin-password>
    ansible_host: zabbix.local
```

##### EXPECTED RESULTS
A new proxy called "Test proxy" with PSK enabled should be created.

##### ACTUAL RESULTS
Instead, the task fails with the error `Invalid parameter "/1/tls_connect": value must be 1.`:

```
msg: 'connection error occurred: REST API returned {''code'': -32602, ''message'':
        ''Invalid params.'', ''data'': ''Invalid parameter "/1/tls_connect": value must
        be 1.''} when sending {''jsonrpc'': ''2.0'', ''method'': ''proxy.create'', ''id'':
        ''ff311757-c057-460d-a06d-38e811e0329d'', ''params'': {''name'': ''Test-Proxy'',
        ''description'': ''My proxy description"',
        ''operating_mode'': ''0'', ''tls_connect'': ''2'', ''tls_accept'': ''2'', ''tls_psk_identity'':
        ''Test-Proxy'', ''tls_psk'': ''********'', ''address'':
        ''127.0.0.1'', ''port'': ''10051'', ''local_address'': ''test-proxy.local'',
        ''local_port'': ''10051''}}'
```

EDIT: The same problem may also exist with `tls_accept`.
