### ISSUE TITLE
Using any Playbook with gathering Facts runs into an issue

### ISSUE THREAD

**Issue by Hornochs** [ansible-collections/community.zabbix#1486]
##### SUMMARY
Using any Task while gathering Facts runs into an issue

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_proxy

##### ANSIBLE VERSION
```
ansible [core 2.18.3]
  config file = /Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.3.0_1/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/stephan.schaffner/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] (/opt/homebrew/Cellar/ansible/11.3.0_1/libexec/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### CONFIGURATION
```
CONFIG_FILE() = /Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = 10
DEFAULT_GATHERING(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = merge
DEFAULT_LOG_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = /Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra->
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = Attention: This file is managed by Ansible and will be over>
DEFAULT_MODULE_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/usr/share/ansible']
DEFAULT_POLL_INTERVAL(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = 15
DEFAULT_PRIVATE_KEY_FILE(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = /Users/stephan.schaffner/.ssh/id_ed25519_sk
DEFAULT_REMOTE_PORT(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = stephanschaffner
DEFAULT_ROLES_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/Users/stephan.schaffner/Documents/Operations/Ansible/oit->
DEFAULT_STDOUT_CALLBACK(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = 120
DEFAULT_TRANSPORT(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ssh
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = True
DEFAULT_VARS_PLUGIN_PATH(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['/usr/share/ansible_plugins/vars_plugins']
DEFAULT_VAULT_IDENTITY_LIST(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['zd@.zd_vault_password', 'cluster@.vault_password']
DEPRECATION_WARNINGS(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = False
INVENTORY_ENABLED(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['ini']
PAGER(env: PAGER) = less
PARAMIKO_LOOK_FOR_KEYS(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = False
SYSTEM_WARNINGS(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = True
VARIABLE_PRECEDENCE(/Users/stephan.schaffner/Documents/Operations/Ansible/oit-fra-hq/ansible.cfg) = ['all_plugins_play', 'all_inventory', 'all_plugins_inventor>

```

##### OS / ENVIRONMENT / Zabbix Version
Client:

MacOS 15.3.2

Server: Zabbix 7.2

##### STEPS TO REPRODUCE

```yaml
- name: Create or update a proxy with proxy type active (Zabbix version >= 7.0)
  community.zabbix.zabbix_proxy:
    proxy_name: "{{ host.system.hostname }}"
    description: "Proxy installed on {{ host.system.hostname }}"
    operating_mode: active
    state: present
    allowed_addresses: "{{ zabbix.sourceip }}"
    tls_accept: "PSK"
    tls_psk: "{{ zabbix.proxypsk }}"
    tls_psk_identity: "PSKProxy"
  delegate_to: localhost
```

##### EXPECTED RESULTS
Adding Zabbix Proxy to Zabbix Master

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [zabbix.test.local]: FAILED! => changed=false 
  msg: No fact modules available and we could not find a fact module for your network OS (community.zabbix.zabbix), try setting one via the `FACTS_MODULES` configuration.
```

**Comment by eb4x** [comment]
I think you're using this module wrong, and sorry it's really poorly documented under [#usage](https://galaxy.ansible.com/ui/repo/published/community/zabbix/docs/)

You probably want to do some thing like;
```yaml
- name: Create or update a proxy with proxy type active (Zabbix version >= 7.0)
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: false  # Set to true for HTTPS
    ansible_httpapi_port: 80
    ansible_user: Admin
    ansible_httpapi_pass: zabbix
    ansible_httpapi_validate_certs: false  # For HTTPS et to true to validate server's certificate
  community.zabbix.zabbix_proxy:
    proxy_name: "{{ host.system.hostname }}"
    description: "Proxy installed on {{ host.system.hostname }}"
    operating_mode: active
    state: present
    allowed_addresses: "{{ zabbix.sourceip }}"
    tls_accept: "PSK"
    tls_psk: "{{ zabbix.proxypsk }}"
    tls_psk_identity: "PSKProxy"
  delegate_to: zabbix-api.example.com
```
To avoid all this clutter in your playbooks, you'd put it in the inventory instead;

```yaml
---
zabbix:
  hosts:
    zabbix-api.example.com:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_use_ssl: true
      ansible_user: Admin
      ansible_httpapi_pass: zabbix
      ansible_host: zabbix-api.example.com
      ansible_httpapi_port: 443
      ansible_zabbix_url_path: ''
```
And either delegate those individual tasks to that host, or just run a whole playbook of zabbix module tasks against that host.
