### ISSUE TITLE
Debian arm repository  broken

### ISSUE THREAD

**Issue by Chr1s70ph** [ansible-collections/community.zabbix#1491]
##### SUMMARY

I tried installing the zabbix agent with the zabbix_agent role, but it would throw an error when trying to update the apt cache

##### ISSUE TYPE
Package manager sources

##### COMPONENT NAME

zabbix_agent role

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.4]
  config file = /Users/me/Documents/Coding/ansible/ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.4.0/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] (/opt/homebrew/Cellar/ansible/11.4.0/libexec/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/me/Documents/Coding/ansible/ansible.cfg
DEFAULT_HOST_LIST(/Users/me/Documents/Coding/ansible/ansible.cfg) = ['/Users/me/Documents/Coding/ansible/inventory']
DEFAULT_MANAGED_STR(/Users/me/Documents/Coding/ansible/ansible.cfg) = This machine is ansible managed. Think before you change things by hand.
DEFAULT_REMOTE_USER(/Users/me/Documents/Coding/ansible/ansible.cfg) = root
DIFF_ALWAYS(/Users/me/Documents/Coding/ansible/ansible.cfg) = True
EDITOR(env: EDITOR) = nvim
INTERPRETER_PYTHON(/Users/me/Documents/Coding/ansible/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT / Zabbix Version

Target OS: debian bookworm on a raspberry-pi 4B 6.1.0-32-arm64

##### STEPS TO REPRODUCE

```yaml
---
- name: Minimal Test Case - Zabbix Agent 2
  hosts: all
  become: true

  roles:
    - role: community.zabbix.zabbix_agent
      vars:
        zabbix_agent2: true
        zabbix_agent_hostname: "{{ ansible_fqdn }}"
        zabbix_agent_package_remove: "true"
        zabbix_agent_server: "{{ __zabbix_agent_server }}"
        zabbix_agent_serveractive: "{{ __zabbix_agent_server_active }}"
        zabbix_agent_package_state: "latest"
```

##### EXPECTED RESULTS

Zabbix agent will be installed and setup as normal

##### ACTUAL RESULTS

`apt-update` fails and playbook exits

```bash
Err:6 http://repo.zabbix.com/zabbix/7.2/stable/debian-arm64 bookworm Release
  404  Not Found [IP: 2604:a880:2:d0::2062:d001 80]
Reading package lists... Done
E: The repository 'http://repo.zabbix.com/zabbix/7.2/stable/debian-arm64 bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
