### ISSUE TITLE
Unexpected parameter name when sending group id's

### ISSUE THREAD

**Issue by jeroendev-one** [ansible-collections/community.zabbix#1501]
##### SUMMARY
When filling in the 'host_groups' parameter, it seems to pass more variables and thus make the json-rpc not accept the data. Its seems like it sends the group id, and name

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix.host

##### ANSIBLE VERSION

```
ansible [core 2.15.13]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True

```

##### CONFIGURATION

```
CONFIG_FILE() = None

```

##### OS / ENVIRONMENT / Zabbix Version

OS: RHEL9
Zabbix version: 7.0.11-release1.el9
##### STEPS TO REPRODUCE

```yaml
---
- name: Set API token
  ansible.builtin.set_fact:
    ansible_zabbix_auth_key: XXXXXX

- name: Create a new host or rewrite an existing host's info (Zabbix <= 7.0)
# Set task level following variables for Zabbix Server host in task
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8080
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ''
    ansible_host: zabbix.domain.local
  become: false
  community.zabbix.zabbix_host:
    host_name: test
    description: Added by Ansible
    host_groups: 
      - 'Linux servers'
    link_templates:
      - Linux template
    status: enabled
    state: present
    inventory_mode: manual
    interfaces:
      - type: 1
        main: 1
        useip: 0
        ip: "{{ ansible_default_ipv4.address }}"
        dns: "{{ inventory_hostname }}"
        port: "10050"
```

##### EXPECTED RESULTS

Host to be added

##### ACTUAL RESULTS

```
TASK [Set API token] *************************************************************************************************************************************************************************
ok: [container01.domain.local]

TASK [Create a new host or rewrite an existing host's info (Zabbix <= 7.0)] ******************************************************************************************************************
fatal: [container01.domain.local]: FAILED! => {"changed": false, "msg": "connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter \"/1/groups/1\": unexpected parameter \"name\".'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"host.create\", \"id\": \"de4e39dc-75ba-4277-903b-34f0f58e89d3\", \"params\": {\"host\": \"test\", \"interfaces\": [{\"type\": 1, \"main\": 1, \"useip\": 0, \"ip\": \"10.x.x.160\", \"dns\": \"host.domain.local\", \"port\": \"10050\", \"details\": {}}], \"groups\": [{\"groupid\": \"2\", \"name\": \"Linux servers\", \"flags\": \"0\", \"uuid\": \"dc579cd7a1a34222933f24f52a68bcd8\"}], \"status\": 0, \"description\": \"Added by Ansible\"}, \"auth\": \"13158
xxxx8c7d8f039f37291c20\"}"}
```

```paste below

```
