### ISSUE TITLE
Auto PSK fail on Windows

### ISSUE THREAD

**Issue by patrik-plastik** [ansible-collections/community.zabbix#1502]
##### SUMMARY
While using role community.zabbix.zabbix_agent on windows machines nad also using zabbix_agent_tlspsk_auto: true, it won't read the file on task step AutoPSK | read existing TLS PSK file in roles/zabbix_agent/tasks/psk_secret.yml because there is become: true and that is not allowed for powershell family hosts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent/tasks/psk_secret.yml 

##### ANSIBLE VERSION
```paste below
ansible [core 2.16.14]
  config file = /home/*/ansible.cfg
  configured module search path = ['/*/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /*/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING() = True
CONFIG_FILE() = /*/ansible.cfg
DEFAULT_FORKS() = 40
DEFAULT_ROLES_PATH() = ['/*/roles']
DEFAULT_SELINUX_SPECIAL_FS() = ['nfs', 'vboxsf', 'fuse', 'ramfs', '9p', 'vxfs', 'ecryptfs']
DEFAULT_TIMEOUT() = 60
DEFAULT_VAULT_IDENTITY_LIST() = ['zabbix@zabbix.vault', 'patrikp@personal.vault']
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/*/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Windows Server 2022 21H2 / 6.4.21

##### STEPS TO REPRODUCE
First run on windows goes as expected. But when run re-run, it fails at this step: AutoPSK | read existing TLS PSK file because become is not supported for windows machines

host vars:
```yaml
zabbix_agent2: true
zabbix_agent_dont_detect_ip: true
# zabbix_agent_userparameters:
#   - name: custom.userparameter
#     scripts_dir: custom.userparameter
zabbix_agent_tlspsk_auto: true
zabbix_agent_tlsconnect: psk
zabbix_agent_tlsaccept: psk
zabbix_agent_host_state: present
zabbix_agent_host_update: true
ansible_host: ip_to_host_hidden
ansible_port: 5986
ansible_user: admin
ansible_password: password_in_vault
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 30
ansible_winrm_read_timeout_sec: 60
```
step in playbook:
```yaml
- name: Install Zabbix Agent For Windows
  hosts: zabbix_agents_windows
  roles:
    - role: community.zabbix.zabbix_agent
      ansible_zabbix_url_path: ''
```

##### EXPECTED RESULTS
AutoPSK working with Windows machines even after first start

##### ACTUAL RESULTS
This is the result after second run:

```paste below
TASK [community.zabbix.zabbix_agent : AutoPSK | read existing TLS PSK file] *****************************************************************************************************
task path: /*/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/psk_secret.yml:33
redirecting (type: modules) ansible.builtin.slurp to ansible.windows.slurp
Using module file /*/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/slurp.ps1
Pipelining is enabled.
fatal: [host.local]: FAILED! => {
    "msg": "The powershell shell family is incompatible with the sudo become plugin"
}
```

**Comment by patrik-plastik** [comment]
Hello @eb4x,

I have tried simple fix like this:
```yml
- name: AutoPSK | read existing TLS PSK file
  ansible.builtin.slurp:
    src: "{{ zabbix_agent_tlspskfile }}"
  register: zabbix_agent_tlspsk_base64
  become: "{{ ansible_os_family != 'Windows' }}"
  when:
    - zabbix_agent_tlspskcheck.stat.exists
  no_log: "{{ ansible_verbosity < 3 }}"
  tags:
    - config
```
and it works.

**Comment by patrik-plastik** [comment]
Now I have noticed that it's in zabbix_agent/tasks/psk_secret.yml as well.

```yml
- name: AutoPSK | Read existing TLS PSK identity file
  ansible.builtin.slurp:
    src: "{{ zabbix_agent_tlspskidentity_file }}"
  register: zabbix_agent_tlspskidentity_base64
  become: "{{ ansible_os_family != 'Windows' }}"
  when: zabbix_agent_tlspskidentity_check.stat.exists
  no_log: "{{ ansible_verbosity < 3 }}"
  tags:
    - config
```

With this it runs as expected and won't fail.
