### ISSUE TITLE
zabbix_agent windows bug >  6.0.39rc1, 7.0.10rc1, 7.2.4rc1, 7.4.0alpha1

### ISSUE THREAD

**Issue by patrik-plastik** [ansible-collections/community.zabbix#1503]
##### SUMMARY
There is a bug, where sometimes agent refuse to start up. There is a bug, where this was fixed:
https://support.zabbix.com/projects/ZBX/issues/ZBX-25530
I am not sure if this is a bug, or should I request to add new feature...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Windows | Set service startup mode to auto, ensure it is started and set auto-recovery

##### ANSIBLE VERSION
```paste below
ansible [core 2.16.14]
  config file = /home/*/ansible.cfg
  configured module search path = ['/*/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /*/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING() = True
CONFIG_FILE() = /*/ansible.cfg
DEFAULT_FORKS() = 40
DEFAULT_ROLES_PATH() = ['/*/roles']
DEFAULT_SELINUX_SPECIAL_FS() = ['nfs', 'vboxsf', 'fuse', 'ramfs', '9p', 'vxfs', 'ecryptfs']
DEFAULT_TIMEOUT() = 60
DEFAULT_VAULT_IDENTITY_LIST() = ['zabbix@zabbix.vault', 'patrikp@personal.vault']
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/*/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Windows Server 2022 21H2 / 6.4.21

##### STEPS TO REPRODUCE
When running script for windows machines, sometimes it happens that agent service refuse to start because of a bug in agents. These versions fixed the issue:
6.0.39rc1, 7.0.10rc1, 7.2.4rc1, 7.4.0alpha1
Check for more information below:
https://support.zabbix.com/projects/ZBX/issues/ZBX-25530

the issue is intermittent and not replicable all the time. Maybe simple retry would be sufficent? I have manually started the service without changing anything and it worked.

host vars:
```yaml
zabbix_agent2: true
zabbix_agent_dont_detect_ip: true
# zabbix_agent_userparameters:
#   - name: custom.userparameter
#     scripts_dir: custom.userparameter
zabbix_agent_tlspsk_auto: true
zabbix_agent_tlsconnect: psk
zabbix_agent_tlsaccept: psk
zabbix_agent_host_state: present
zabbix_agent_host_update: true
ansible_host: ip_to_host_hidden
ansible_port: 5986
ansible_user: admin
ansible_password: password_in_vault
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 30
ansible_winrm_read_timeout_sec: 60
```
step in playbook:
```yaml
- name: Install Zabbix Agent For Windows
  hosts: zabbix_agents_windows
  roles:
    - role: community.zabbix.zabbix_agent
      ansible_zabbix_url_path: ''
```

##### EXPECTED RESULTS
Start / restart zabbix agent on windows machine without issues

##### ACTUAL RESULTS
Zabbix Agent won't start and fails the procedure.

```paste below
TASK [community.zabbix.zabbix_agent : Windows | Set service startup mode to auto, ensure it is started and set auto-recovery] **********************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 1064
fatal: [fores071.fores.local]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Failed to start service 'Zabbix Agent 2 (Zabbix Agent 2)'."}

```

**Comment by patrik-plastik** [comment]
In the ./roles/zabbix_agent/tasks/Windows_conf.yml I adjusted the task Windows | Set service startup mode to auto, ensure it is started and set auto-recovery to look like this and it won't fail again. Most of the times it happens after first start-up.

```yml
- name: "Windows | Set service startup mode to auto, ensure it is started and set auto-recovery"
  ansible.windows.win_service:
    name: "{{ zabbix_win_svc_name }}"
    start_mode: auto
    state: started
    failure_actions:
      - type: restart
        delay_ms: 5000
      - type: restart
        delay_ms: 10000
      - type: restart
        delay_ms: 20000
    failure_reset_period_sec: 86400
  register: _zabbix_windows_win_service_restarted
  retries: 5
  delay: 5
  until: _zabbix_windows_win_service_restarted is succeeded
  tags:
    - config
```
