### ISSUE TITLE
community.zabbix.zabbix_authentication module not updating and / or create LDAP

### ISSUE THREAD

**Issue by patrik-plastik** [ansible-collections/community.zabbix#1505]
##### SUMMARY
community.zabbix.zabbix_authentication not working properly updating LDAP settings

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_authentication

##### ANSIBLE VERSION
```paste below
ansible [core 2.16.14]
  config file = /home/*/ansible.cfg
  configured module search path = ['/*/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /*/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING() = True
CONFIG_FILE() = /*/ansible.cfg
DEFAULT_FORKS() = 40
DEFAULT_ROLES_PATH() = ['/*/roles']
DEFAULT_SELINUX_SPECIAL_FS() = ['nfs', 'vboxsf', 'fuse', 'ramfs', '9p', 'vxfs', 'ecryptfs']
DEFAULT_TIMEOUT() = 60
DEFAULT_VAULT_IDENTITY_LIST() = ['zabbix@zabbix.vault', 'patrikp@personal.vault']
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/*/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Fedora 41 / 6.4.21

##### STEPS TO REPRODUCE
I try to use the module to setup the authentification method and add ldap. When there is not set up any LDAP server, it is asking for ldap_userdirectory parameter, which its description is not clean to understand. After long time of digging into zabbix api documentation and testing I found out that it is a LDAP server name, equivalent to this:

![Image](https://github.com/user-attachments/assets/3452e46c-6cde-4252-ac68-1f9c39b5a01c)

But, when I tried to "add" new LDAP connection to the server, it always just say that User directory name does not exist.

I have tried all combinations of authentication_type, ldap_auth_enabled and ldap_configured but I was never sucessfull.

I get either this:
```paste below
TASK [Setup LDAP Authentication] *******************************************************************************************************************************************************************************************************************************
fatal: [hostname]: FAILED! => {"changed": false, "msg": "value of authentication_type must be one of: internal, ldap, got: indernal"}
```
Or this:
```paste below
TASK [Setup LDAP Authentication] *******************************************************************************************************************************************************************************************************************************
fatal: [hostname]: FAILED! => {"changed": false, "msg": "Canot find user directory with name: LDAP Directory"}
```

After manually creating the connection in UI, was not getting any error and had filled whole task like this:
```yaml
    - name: Setup LDAP Authentication
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_user: "{{ zabbix_api_login_user }}"
        ansible_httpapi_password: "{{ zabbix_api_login_pass }}"
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: '' 
      community.zabbix.zabbix_authentication:
        authentication_type: internal
        http_auth_enabled: false
        ldap_auth_enabled: true
        ldap_configured: true
        saml_auth_enabled: false
        ldap_host: ip_to_host
        ldap_port: 389
        ldap_base_dn: DC=some,DC=local
        ldap_search_attribute: sAMAccountName
        ldap_bind_dn: CN=user,OU=acc,OU=fr,DC=some,DC=local
        ldap_case_sensitive: false
        ldap_userdirectory: LDAP Directory
        ldap_bind_password: psswd
        passwd_min_length: 12
        passwd_check_rules:
          - contain_uppercase_and_lowercase_letters
          - contain_digits
          - contain_special_characters
          - avoid_easy_to_guess
```

But when I change ANY variable related to ldap (except of ldap_auth_enabled, ldap_configured and ldap_userdirectory) no changes are applied. Other parameters like passwd_min_length, passwd_check_rules and authentication_type are updated but none of the LDAP.

##### EXPECTED RESULTS
Create and update LDAP settings for authentication. 

##### ACTUAL RESULTS
I changed almost every value in ldap parameters and none of them where updated.

```paste below
TASK [Setup LDAP Authentication] *******************************************************************************************************************************************************************************************************************************
task path: /*setup_playbook.yml:248
Trying secret FileVaultSecret(filename='/*') for vault_id=zabbix
Tried to use the vault secret (zabbix) to decrypt (None) but it failed. Error: HMAC verification failed: Signature did not match digest.
Trying secret FileVaultSecret(filename='/*') for vault_id=patrikp
Trying secret FileVaultSecret(filename='/*') for vault_id=zabbix
Tried to use the vault secret (zabbix) to decrypt (None) but it failed. Error: HMAC verification failed: Signature did not match digest.
Trying secret FileVaultSecret(filename='/*') for vault_id=patrikp
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /usr/lib/python3.13/site-packages/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /usr/lib/python3.13/site-packages/ansible_collections/ansible/utils
<10.208.2.35> attempting to start connection
<10.208.2.35> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /bin/ansible-connection
<10.208.2.35> local domain socket does not exist, starting it
<10.208.2.35> control socket path is /*/.ansible/pc/64e3f08b39
<10.208.2.35> Loading collection ansible.builtin from 
<10.208.2.35> redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<10.208.2.35> Loading collection ansible.netcommon from /usr/lib/python3.13/site-packages/ansible_collections/ansible/netcommon
<10.208.2.35> Loading collection ansible.utils from /usr/lib/python3.13/site-packages/ansible_collections/ansible/utils
<10.208.2.35> Loading collection community.zabbix from /*/.ansible/collections/ansible_collections/community/zabbix
<10.208.2.35> local domain socket listeners started successfully
<10.208.2.35> loaded API plugin ansible_collections.community.zabbix.plugins.httpapi.zabbix from path /*/.ansible/collections/ansible_collections/community/zabbix/plugins/httpapi/zabbix.py for platform type community.zabbix.zabbix
<10.208.2.35> Loading collection ansible.builtin from 
<10.208.2.35> local domain socket path is /*/.ansible/pc/64e3f08b39
Trying secret FileVaultSecret(filename='/*') for vault_id=zabbix
Trying secret FileVaultSecret(filename='/*') for vault_id=zabbix
Using module file /*/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_authentication.py
Pipelining is enabled.
<10.208.2.35> ESTABLISH LOCAL CONNECTION FOR USER: patrikp
<10.208.2.35> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Trying secret FileVaultSecret(filename='/*') for vault_id=zabbix
ok: [hostname] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authentication_type": "internal",
            "disabled_usrgroup": null,
            "http_auth_enabled": false,
            "http_case_sensitive": null,
            "http_login_form": null,
            "http_login_password": null,
            "http_login_user": null,
            "http_strip_domains": null,
            "jit_provision_interval": "1h",
            "ldap_auth_enabled": true,
            "ldap_base_dn": "DC=else,DC=local",
            "ldap_bind_dn": "CN=user",
            "ldap_bind_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ldap_case_sensitive": false,
            "ldap_configured": true,
            "ldap_host": "someip",
            "ldap_jit_status": null,
            "ldap_port": 389,
            "ldap_search_attribute": "sAMAccountName",
            "ldap_userdirectory": "LDAP Directory",
            "passwd_check_rules": [
                "contain_uppercase_and_lowercase_letters",
                "contain_digits",
                "contain_special_characters",
                "avoid_easy_to_guess"
            ],
            "passwd_min_length": 12,
            "saml_auth_enabled": false,
            "saml_case_sensitive": null,
            "saml_encrypt_assertions": null,
            "saml_encrypt_nameid": null,
            "saml_idp_entityid": null,
            "saml_jit_status": null,
            "saml_nameid_format": null,
            "saml_sign_assertions": null,
            "saml_sign_authn_requests": null,
            "saml_sign_logout_requests": null,
            "saml_sign_logout_responses": null,
            "saml_sign_messages": null,
            "saml_slo_url": null,
            "saml_sp_entityid": null,
            "saml_sso_url": null,
            "saml_username_attribute": null
        }
    },
    "result": "Authentication setting is already up to date"
}
```
