### ISSUE TITLE
Problem with --check in Community.zabbix.zabbix_trigger module

### ISSUE THREAD

**Issue by gmaxm3** [ansible-collections/community.zabbix#1520]
##### SUMMARY
After adding a trigger to Zabbix via the community.zabbix.zabbix_trigger module, it constantly shows that there are changes with --check.

##### COMPONENT NAME
community.zabbix.zabbix_trigger module 
https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_trigger_module.html#ansible-collections-community-zabbix-zabbix-trigger-module

##### ANSIBLE VERSION
```ansible [core 2.17.5]
  config file = /home/sysray/IdeaProjects/ansible/ansible.cfg
  configured module search path = ['/home/sysray/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sysray/ansible-env/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/sysray/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sysray/ansible-env/venv/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/home/sysray/ansible-env/venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/home/sysray/IdeaProjects/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/sysray/IdeaProjects/ansible/ansible.cfg) = True
CONFIG_FILE() = /home/sysray/IdeaProjects/ansible/ansible.cfg
DEFAULT_LOCAL_TMP(/home/sysray/IdeaProjects/ansible/ansible.cfg) = /tmp/ansible-local-1748808d_jjwboi
DEFAULT_REMOTE_PORT(/home/sysray/IdeaProjects/ansible/ansible.cfg) = 26
DEFAULT_ROLES_PATH(/home/sysray/IdeaProjects/ansible/ansible.cfg) = ['/home/sysray/IdeaProjects/ansible/roles']
DEPRECATION_WARNINGS(/home/sysray/IdeaProjects/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/sysray/IdeaProjects/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/sysray/IdeaProjects/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/sysray/IdeaProjects/ansible/ansible.cfg) = auto_silent
INVENTORY_ENABLED(/home/sysray/IdeaProjects/ansible/ansible.cfg) = ['ini']
MAX_FILE_SIZE_FOR_DIFF(/home/sysray/IdeaProjects/ansible/ansible.cfg) = 512000
RETRY_FILES_ENABLED(/home/sysray/IdeaProjects/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Server zabbix 7.0 / my OS Ubuntu 22.04.5 LTS

##### STEPS TO REPRODUCE

```
role_zabbix.yml
---
- name: Config | Get secrets for zabbix monitoring
  ansible.builtin.set_fact:
    zabbix_monitoring: >
      {{
        zabbix_monitoring | default({}) |
        combine(
          lookup('community.hashi_vault.hashi_vault', 'secret={{ item }} token={{ VAULT_TOKEN }} url={{ vault_url }}')
        )
      }}
  with_items: "{{ zabbix_agent_monitoring_creds_vault_path }}"
  when:
    - zabbix_agent_monitoring_creds_vault_path is defined
  tags:
    - zabbix_agent

- name: Config | Set API token
  ansible.builtin.set_fact:
    ansible_zabbix_auth_key: "{{ zabbix_agent_monitoring_zabbix_user_api }}"
  when: conf_host_in_zabbix is defined
  tags:
    - zabbix_agent_trigger
    - zabbix_agent

- name: Config | Ensure host has triggers
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: true
    ansible_zabbix_url_path: '/'
    ansible_host: "{{ zabbix_agent_server_host }}"
  community.zabbix.zabbix_trigger:
    host_name: "{{ item.host_name }}"
    name: "{{ item.trigger_name }}"
    desc: "{{ item.trigger_description | default('') }}"
    dependencies: "{{ item.trigger_dependencies | default([]) }}"
    params:
      expression: "{{ item.trigger_expression }}"
      severity: "{{ item.trigger_priority | default('average') }}"
      comments: "{{ item.trigger_comments | default('') }}"
      event_name: "{{ item.trigger_event_name | default('') }}"
    state: present
  with_items: "{{ conf_triggers_in_zabbix }}"
  when: conf_triggers_in_zabbix is defined
  become: false
  tags:
    - zabbix_agent_trigger
    - zabbix_agent
   
host_vars
marketing-mysql-1b.yml

## zabbix
zabbix_agent_monitoring_creds_vault_path:
  - 'DevOps/data/zabbix_monitoring_user/credentials'
zabbix_agent_monitoring_zabbix_user_api: "{{ zabbix_monitoring['zabbix_monitoring_user_api'] }}"
conf_triggers_in_zabbix:
  - host_name: "{{ zabbix_agent_hostname }}"
    trigger_name: "TEST"
    trigger_expression: "min(/marketing-mysql-1b.aws/system.cpu.util,5m)>90"
    trigger_priority: "disaster"
```

##### EXPECTED RESULTS
I expected that after adding a trigger, if I pass with --check it will not show that it is changing, because I did not add any changes there.

##### ACTUAL RESULTS

```
changed: [marketing-mysql-1b] => (item={'host_name': 'marketing-mysql-1b.aws', 'trigger_name': 'TEST', 'trigger_expression': 'min(/marketing-mysql-1b.aws/system.cpu.util,5m)>90', 'trigger_priority': 'disaster'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "dependencies": [],
            "desc": "",
            "host_name": "marketing-mysql-1b.aws",
            "http_login_password": null,
            "http_login_user": null,
            "name": "TEST",
            "params": {
                "comments": "",
                "dependencies": [],
                "event_name": "",
                "expression": "min(/marketing-mysql-1b.aws/system.cpu.util,5m)>90",
                "priority": 5,
                "triggerid": "4766643"
            },
            "state": "present",
            "template_name": null
        }
    },
    "item": {
        "host_name": "marketing-mysql-1b.aws",
        "trigger_expression": "min(/marketing-mysql-1b.aws/system.cpu.util,5m)>90",
        "trigger_name": "TEST",
        "trigger_priority": "disaster"
    }
}
```

```
changed: [marketing-mysql-1b] => (item={'host_name': 'marketing-mysql-1b.aws', 'trigger_name': 'TEST', 'trigger_expression': 'min(/marketing-mysql-1b.aws/system.cpu.util,5m)>90', 'trigger_priority': 'disaster'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "dependencies": [],
            "desc": "",
            "host_name": "marketing-mysql-1b.aws",
            "http_login_password": null,
            "http_login_user": null,
            "name": "TEST",
            "params": {
                "comments": "",
                "dependencies": [],
                "event_name": "",
                "expression": "min(/marketing-mysql-1b.aws/system.cpu.util,5m)>90",
                "priority": 5,
                "triggerid": "4766643"
            },
            "state": "present",
            "template_name": null
        }
    },
    "item": {
        "host_name": "marketing-mysql-1b.aws",
        "trigger_expression": "min(/marketing-mysql-1b.aws/system.cpu.util,5m)>90",
        "trigger_name": "TEST",
        "trigger_priority": "disaster"
    }
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
marketing-mysql-1b         : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 

```
