### ISSUE TITLE
zabbix_agent setup broken in debian trixie / ansible 12

### ISSUE THREAD

**Issue by pravi** [ansible-collections/community.zabbix#1523]
##### SUMMARY
zabbix agent setup no longer works after upgrading to debian trixie.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent

##### ANSIBLE VERSION

```paste below
ansible --version
ansible [core 2.19.0b2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.3 (main, Apr 10 2025, 21:38:51) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT / Zabbix Version

This is working fine with both debian bullseye (ansible 2) and bookworm (ansible 7). Broken in debian trixie - which will be released soon as stable (currently in freeze).

##### STEPS TO REPRODUCE

It is a very simple setup with only zabbix server and a ufw firewall configured

```yaml
# zabbix_agent/meta/main.yml 
---
dependencies:
  - role: community.zabbix.zabbix_agent
    vars:
      zabbix_agent_server: "{{ purism_zabbix_server }}"
      zabbix_agent_serveractive: "{{ purism_zabbix_server }}" 
# zabbix_agent/tasks/main.yml 
---
- name: Allow zabbix agent access from zabbix server
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    src: "{{ lookup('dig', '{{ purism_zabbix_server }}')}}"
    to_port: '10050'
#zabbix_agent/vars/main.yml 
purism_zabbix_server: monitoring.puri.sm

```

##### EXPECTED RESULTS
This should continue working like with earlier ansible versions or suggest a different way to setting up zabbix_agent with newer ansible version.

##### ACTUAL RESULTS

```paste below
TASK [community.zabbix.zabbix_agent : AutoPSK | Default tlsaccept to enforce
 PSK when zabbix_agent_tlsaccept is not defined] ***
skipping: [dev-keys.puri.sm]

TASK [community.zabbix.zabbix_agent : AutoPSK | Default tlsaccept to enforce
 PSK when zabbix_agent_tlsaccept is defined] ***
skipping: [dev-keys.puri.sm]

TASK [community.zabbix.zabbix_agent : Set Variables] ***********************
****
[ERROR]: Task failed: Finalization of task args for 'ansible.builtin.set_fac
t' failed: Error while resolving value for 'zabbix_agent_include_dir': 'zabb
ix_agent_include_dir' is undefined

Task failed.
Origin: /root/.ansible/collections/ansible_collections/community/zabbix/role
s/zabbix_agent/tasks/main.yml:48:3

46     - config
47
48 - name: Set Variables
     ^ column 3

<<< caused by >>>

Finalization of task args for 'ansible.builtin.set_fact' failed.
Origin: /root/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml:49:3

47
48 - name: Set Variables
49   ansible.builtin.set_fact:
     ^ column 3

<<< caused by >>>

Error while resolving value for 'zabbix_agent_include_dir': 'zabbix_agent_include_dir' is undefined
Origin: /root/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml:50:31

48 - name: Set Variables
49   ansible.builtin.set_fact:
50     zabbix_agent_include_dir: "{{ zabbix_agent_include_dir is defined | ternary(zabbix_agent_include_dir, _include...
                                 ^ column 31

                                 ^ column 31

fatal: [dev-keys.puri.sm]: FAILED! => {"changed": false, "msg": "Task failed
: Finalization of task args for 'ansible.builtin.set_fact' failed: Error while resolving value for 'zabbix_agent_include_dir': 'zabbix_agent_include_dir' is undefined"}

PLAY RECAP *********************************************************************
dev-keys.puri.sm           : ok=8    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

```

**Comment by pravi** [comment]
Originally we were using comunity.zabbix 2.1.0 but that fails with another error so tried 3.3.0 which failed with this error.

**Comment by masa-orca** [comment]
ansible-core 2.12 is EoL. We don't check the installing test against the version now.
Please use latest ansible-core.

**Comment by masa-orca** [comment]
In addition, The Zabbix LLC does not publish package for trixie.
You cannot install zabbix-server to trixie now

**Comment by pravi** [comment]
> The Zabbix LLC does not publish package for trixie. You cannot install zabbix-agent to trixie now

My target system is bookworm. I'm only running ansible-playbook from trixie.

**Comment by eb4x** [comment]
The agent received a pretty big refactor about 2 months back. The code that errors out doesn't look like anything we've got in the repo currently.

Would you be willing to try running the collection straight from git?
```yaml
---
collections:
  - name: "https://github.com/ansible-collections/community.zabbix"
    type: git
    version: main
    #version: "bdf31fe2b4a47a1c697d74ffce27b2e0a3d76222"
```

(PS. Maybe we should cut a new release soon?)

**Comment by pravi** [comment]
> The agent received a pretty big refactor about 2 months back. The code that errors out doesn't look like anything we've got in the repo currently.
> 
> Would you be willing to try running the collection straight from git?

Now it fails to download the gpg key, after changing to git version. Btw, can we have an option to just use the version provided by Debian?

```
TASK [community.zabbix.zabbix_repo : Debian | Download gpg key] ****************
FAILED - RETRYING: [dev-keys.puri.sm]: Debian | Download gpg key (3 retries left).
FAILED - RETRYING: [dev-keys.puri.sm]: Debian | Download gpg key (2 retries left).
FAILED - RETRYING: [dev-keys.puri.sm]: Debian | Download gpg key (1 retries left).
[ERROR]: Task failed: Module failed: Request failed: <urlopen error [Errno -2] Name or service not known>
Origin: /home/pravi/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_repo/tasks/Debian.yml:31:3

29       (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] < "12")
30
31 - name: "Debian | Download gpg key"
     ^ column 3

fatal: [dev-keys.puri.sm]: FAILED! => {"attempts": 3, "changed": false, "dest": "/etc/apt/keyrings/zabbix-repo.asc", "elapsed": 0, "gid": 0, "group": "root", "mode": "0644", "msg": "Request failed: <urlopen error [Errno -2] Name or service not known>", "owner": "root", "size": 9033, "state": "file", "uid": 0, "url": "http://repo.zabbix.com/zabbix-official-repo.key"}

PLAY RECAP *********************************************************************
dev-keys.puri.sm           : ok=13   changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   

```

Same works fine when run from bookworm and manually running wget on the url on server works too.

**Comment by eb4x** [comment]
Yeah, I think you can make it work if you apply

```yaml
zabbix_agent_version_check: false
zabbix_manage_repo: false
zabbix_agent_install_agent_only: true
```
