### ISSUE TITLE
[BUG] Windows scripts for the zabbix_agent are not copied

### ISSUE THREAD

**Issue by jdsl007** [ansible-collections/community.zabbix#1524]
```
      block:
        - name: Windows | Install user-defined userparameters
          ansible.windows.win_template:
            src: "{{ zabbix_agent_userparameters_templates_src }}/{{ item.name }}.j2"
            dest: '{{ zabbix_agent_win_include }}\{{ item.name }}.conf'
          loop: "{{ zabbix_agent_userparameters | rejectattr('scripts_dir', 'defined') }}"

        - name: Windows | Install user-defined scripts
          ansible.windows.win_copy:
            src: "{{ zabbix_agent_userparameters_scripts_src }}/{{ item.scripts_dir }}"
            dest: '{{ zabbix_win_install_dir }}\scripts\'
          loop: "{{ zabbix_agent_userparameters | selectattr('scripts_dir', 'defined') }}"
```
Why .j2 files are not copied if they have "script_dir", but are the "script_dir" itself copied in the next task?

**Comment by pyrodie18** [comment]
Not sure I understand what you're saying.  Can you please post your vars file for those variables.

**Comment by pyrodie18** [comment]
No reply...closing

**Comment by jdsl007** [comment]
Apologies for the late reply — reopening with the vars file that was asked for, plus a proper reproducer. My original report was badly worded: I described it as "scripts are not copied", but the scripts *are* copied fine. What is missing is the userparameter **`.conf` file**. Let me restate the whole thing.

### Summary

In `roles/zabbix_agent/tasks/userparameter.yml` the Windows branch installs userparameter `.conf` files only for entries **without** `scripts_dir`, while the non-Windows branch installs them for **every** entry. So any userparameter that ships a scripts directory gets its scripts copied to the Windows host, but its `.conf` file is never written — the userparameter silently does not exist on Windows.

The two branches disagree because of #1336 ("Always install userparameters files, do not skip items when scripts_dir is defined", merged 2024-07-09). That PR changed exactly this `loop:` from `rejectattr('scripts_dir', 'defined')` to the full list — but only in the non-Windows block. The Windows block was left untouched and still has the old, pre-#1336 behaviour. This is still the case in `main` today (the variable names in my original post have since been renamed by #1587, but the `loop:` line is unchanged).

The documented example in `docs/ZABBIX_AGENT_ROLE.md` ("Deploying Userparameters") is itself affected:

```yaml
zabbix_agent_userparameters:
  - name: mysql
    scripts_dir: mysql
  - name: galera
```

Run that against a Windows host and `mysql.conf` is never created — only `galera.conf` is. The docs mention no Windows-specific restriction, and the description of `scripts_dir` ("Directory name of the custom scripts needed for userparameters") gives no hint that supplying it suppresses the template.

### Versions

* ansible-core 2.17.14, jinja 3.1.6, python 3.12.12
* community.zabbix 4.2.0 (also reproduced on 4.1.1; `main` is identical for this file)
* Controller: macOS. Targets: Windows Server 2019/2022 over WinRM, and any Linux host for comparison
* Zabbix agent 7.0 / 7.4

Nothing config-related is involved — the bug is visible from the task file alone.

### Steps to reproduce

Layout:

```
templates/userparameters/withscript.j2      ->  UserParameter=demo.withscript,echo 1
templates/userparameters/noscript.j2        ->  UserParameter=demo.noscript,echo 1
files/scripts/demo/demo.ps1                 ->  (any file)
```

The vars file, applied identically to a Windows host and a Linux host:

```yaml
- hosts: win_target:linux_target
  tasks:
    - include_role:
        name: community.zabbix.zabbix_agent
      vars:
        zabbix_agent_server: zabbix.example.com
        zabbix_agent_userparameters:
          - name: withscript
            scripts_dir: demo
          - name: noscript
```

### Expected results

Both hosts get both userparameter files, since both entries name a template and neither branch documents any difference:

* Linux: `/etc/zabbix/zabbix_agent.d/userparameter_withscript.conf`, `userparameter_noscript.conf`, plus `/etc/zabbix/scripts/demo/`
* Windows: `withscript.conf`, `noscript.conf` in the include dir, plus `<install_dir>\scripts\demo\`

### Actual results

Linux — correct, both `.conf` files present.

Windows — `withscript.conf` is **missing**. The scripts directory `demo\` is copied, so the play looks like it succeeded; only `noscript.conf` was written. The task just reports one fewer item, with no warning and no failure:

```
TASK [community.zabbix.zabbix_agent : Windows | Install user-defined userparameters] ***
changed: [win_target] => (item={'name': 'noscript'})
        # <- no item for 'withscript'

TASK [community.zabbix.zabbix_agent : Windows | Install user-defined scripts] ***
changed: [win_target] => (item={'name': 'withscript', 'scripts_dir': 'demo'})
```

The cause is directly visible in `roles/zabbix_agent/tasks/userparameter.yml` in current `main` — the two `loop:` lines that serve the same purpose:

```yaml
        - name: Windows | Install user-defined userparameters
          ansible.windows.win_template:
            src: "{{ zabbix_agent_userparameters_templates_src }}/{{ item.name }}.j2"
            dest: '{{ zabbix_agent_include_dirs | first }}\{{ item.name }}.conf'
          loop: "{{ zabbix_agent_userparameters | rejectattr('scripts_dir', 'defined') }}"   # <-- filtered
...
        - name: Install user-defined userparameters
          ansible.builtin.template:
            src: "{{ zabbix_agent_userparameters_templates_src }}/{{ item.name }}.j2"
            dest: "{{ zabbix_agent_include_dirs | first }}/userparameter_{{ item.name }}.conf"
          loop: "{{ zabbix_agent_userparameters }}"                                          # <-- not filtered
```

### Suggested fix

Apply to the Windows task the same one-line change #1336 already applied to the Unix one:

```diff
-          loop: "{{ zabbix_agent_userparameters | rejectattr('scripts_dir', 'defined') }}"
+          loop: "{{ zabbix_agent_userparameters }}"
```

I am happy to open the PR if you agree with the direction.

### Current workaround, and why it is bad

The only way to get the `.conf` onto Windows today is to list every scripted module twice — once with `scripts_dir` to deliver the scripts, once name-only so it survives the `rejectattr` filter:

```yaml
zabbix_agent_userparameters:
  - name: withscript
    scripts_dir: demo
  - name: withscript      # duplicate purely to satisfy the Windows branch
```

Since #1336 this makes the Unix branch render the same template twice into the same destination — harmless but wasteful — and the duplicated entries are very easy to "clean up" by mistake, which silently breaks Windows monitoring with no error at apply time. We maintain ~8 such duplicated entries plus a comment block explaining why they must never be removed.


---

@pyrodie18 could you please reopen this issue? I do not have permission to reopen it myself, since it was closed by a maintainer rather than by me.
