### ISSUE TITLE
Add Propagation flag to Host Group and Template Group

### ISSUE THREAD

**Issue by manuello1996** [ansible-collections/community.zabbix#1525]
##### SUMMARY

In Zabbix is possible to create sub-HostGroups using the "/". For example you can create the host group "master" and the group "master/sub-master". The sub groups can be used to ihneritence permissions for UserGroup access managemnt. 
The same logic can be applied to Template Group. 

The actual collection allow to create groups and subgroups, but no not trigger a Permission propagation. 
Without this propagation if a User Group have access to the "master" group, will not have access to the "master/sub-master" group, until in frontedn you force a propagation (Data collectio -> Host groups -> Click on HostGroup name -> Check the box for "Apply permissions and tag filters to all subgroups" -> update) 

Same concept for Temalte Groups and Template Access for User Groups 

##### ISSUE TYPE
New Features of existing module 

##### COMPONENT NAME

 community.zabbix.zabbix_group:

##### ADDITIONAL INFORMATION

In my opinion will be greate to have the possibilit to use a vars "propagte" (bool) to decide if propagate the permission of masters groups after the creation of a Host Groups. 

For the moment i solve this problem with an Ansible task that run a pure API Call. 

```yaml
#
# propagate permission for HostGroups to mantain access to automatically generated sub HostGroups
#

# aggregated_zabbix_host_groups is a list of Hostgroups 

- name: Extract only the master group names
  ansible.builtin.set_fact:
    master_zabbix_host_groups: >-
      {{ aggregated_zabbix_host_groups
         | map('split', '/')
         | map('first')
         | list
         | unique }}
		 

- name: Get hostgroup IDs
  vars:
    ansible_user: "{{ api_ansible_user }}"
    ansible_httpapi_pass: "{{ all_vault_ansibleapi_pw }}"
    ansible_network_os: "{{ api_ansible_network_os }}"
    ansible_connection: "{{ api_ansible_connection }}"
    ansible_httpapi_port: "{{ api_ansible_httpapi_port }}"
    ansible_httpapi_use_ssl: "{{ api_ansible_httpapi_use_ssl }}"
    ansible_httpapi_validate_certs: "{{ api_ansible_httpapi_validate_certs }}"
    ansible_zabbix_url_path: "{{ api_ansible_zabbix_url_path }}"
    ansible_host: "{{ api_ansible_host }}"
  community.zabbix.zabbix_group_info:
    hostgroup_name: "{{ master_zabbix_host_groups }}"
  register: group_info
  run_once: true

- name: Build list of hostgroup IDs
  ansible.builtin.set_fact:
    my_group_ids: "{{ group_info.host_groups | map(attribute='groupid') | list }}"
  run_once: true

- name: Build list of objects for propagation
  ansible.builtin.set_fact:
    my_group_objects: "{{ (my_group_objects | default([])) + [{'groupid': item}] }}"
  loop: "{{ my_group_ids }}"

- name: Get Zabbix API Auth
  vars:
    ansible_host: "{{ api_ansible_host }}"
  ansible.builtin.uri:
    url: "{{ api_endpoint }}"
    method: POST
    headers:
      Content-Type: application/json
    body_format: json
    body:
      jsonrpc: "2.0"
      method: user.login
      params:
        username: "{{ api_ansible_user }}"
        password: "{{ all_vault_ansibleapi_pw }}"
      id: 1
    return_content: true
    validate_certs: false
  register: login_resp
  run_once: true

- name: Set auth token fact
  ansible.builtin.set_fact:
    zabbix_auth: "{{ login_resp.json.result }}"
  run_once: true

- name: Propagate group permission
  vars:
    ansible_host: "{{ api_ansible_host }}"
  ansible.builtin.uri:
    url: "{{ api_endpoint }}"
    method: POST
    headers:
      Content-Type: application/json
    body_format: json
    body:
      jsonrpc: "2.0"
      method: hostgroup.propagate
      params:
        groups: "{{ my_group_objects }}"
        permissions: true
        tag_filters: true
      auth: "{{ zabbix_auth }}"
      id: 2
    return_content: true
    validate_certs: false
  run_once: true

```

Is probably not the best approch but actually i need the progation done if i create a sub host group

https://www.zabbix.com/documentation/7.0/en/manual/api/reference/hostgroup/propagate

I do not know where to start to change the API call that the actuall community.zabbix.zabbix_group do, but i will be happy to help in the developing.
