### ISSUE TITLE
[DEPRECATION WARNING]: The `ansible_managed` variable is deprecated.

### ISSUE THREAD

**Issue by pravi** [ansible-collections/community.zabbix#1536]
##### SUMMARY
```
TASK [community.zabbix.zabbix_agent : Configure zabbix-agent] ********************
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: The `ansible_managed` variable is deprecated. This feature will be removed from the 'ansible.builtin.template' action plugin (requested as 'ansible_collections.ansible.builtin.plugins.action.template') in version 2.23.
Origin: /home/pravi/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/templates/agent.conf.j2

Define and use a custom variable instead.
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent

##### ANSIBLE VERSION

```paste below
ansible [core 2.19.0b2]
  config file = None
  configured module search path = ['/home/pravi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/pravi/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.3 (main, Apr 10 2025, 21:38:51) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT / Zabbix Version

Target Debian trixie - ansible-playbook run from Debian Trixie

##### STEPS TO REPRODUCE

```yaml
$ cat zabbix_agent/meta/main.yml 
---
dependencies:
  - role: community.zabbix.zabbix_agent
    vars:
      zabbix_agent_server: "{{ purism_zabbix_server }}"
      zabbix_agent_serveractive: "{{ purism_zabbix_server }}"
      zabbix_agent_version_check: false
      zabbix_manage_repo: false
      zabbix_agent_install_agent_only: true
```

##### EXPECTED RESULTS

There should not be a deprecation warning - this can fail in next ansible-core update.

##### ACTUAL RESULTS

deprecation warning shown by ansible

```paste below

```
