### ISSUE TITLE
zabbix_token.py wrong status token during creation and update

### ISSUE THREAD

**Issue by micorx** [ansible-collections/community.zabbix#1540]
##### SUMMARY
The creation/update of token has a wrong behaviour.
During creation "status: true" create the token and enable it.
During update "status: true" disable the token.
Moreover the release 3.3.0 does not contain the latest fix:
https://github.com/ansible-collections/community.zabbix/commit/f54e99f27c1c94e1f51bc928ac4258d5f3c39bdf

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_token.py
https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_token.py

##### ANSIBLE VERSION
```
ansible [core 2.18.5]
  config file = /Users/user/ansible/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/11.5.0/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.13.3 (main, Apr  8 2025, 13:54:08) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/usr/local/Cellar/ansible/11.5.0/libexec/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### CONFIGURATION
```
CONFIG_FILE() = /Users/user/ansible/ansible.cfg
DEFAULT_HOST_LIST(/Users/user/ansible/ansible.cfg) = ['/Users/user/ansible/inventory.yml']
DEFAULT_ROLES_PATH(/Users/user/ansible/ansible.cfg) = ['/Users/user/ansible/roles']
HOST_KEY_CHECKING(/Users/user/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/user/ansible/ansible.cfg) = auto_silent

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT / Zabbix Version
MacOS 13.7.6 (22H625)
Homebrew 4.5.2

##### STEPS TO REPRODUCE
```
- name: "Create Zabbix token"
  vars:
    ansible_network_os: "---"
    ansible_connection: "---"
    ansible_httpapi_port: "---"
    ansible_httpapi_use_ssl: "---"
    ansible_httpapi_validate_certs: "---"
    ansible_zabbix_url_path: "---"
    ansible_host: "---"
  community.zabbix.zabbix_token:
    name: "---"
    description: "---"
    username: "---"
    status: true
    expires_at: "---"
    generate_token: true
    state: present
```

##### EXPECTED RESULTS

Creation:
status: true --> Enable the token
status: false --> Disable the token
Update:
status: true --> Enable the token
status: false --> Disable the token

```
[...]
            if isinstance(status, bool):
                if status:
                    params["status"] = "0"
                else:
                    params["status"] = "1"
[...]
            if isinstance(status, bool):
                if status:
                    if token["status"] != "0":
                        params["status"] = "0"
                else:
                    if token["status"] != "1":
                        params["status"] = "1"
[...]
```

##### ACTUAL RESULTS
In the latest release (3.3.0) this is the behaviour:
Creation:
status: true --> Disable the token - Wrong
status: false --> Enable the token - Wrong
Update:
status: true --> Enable the token - Correct
status: false --> Disable the token - Correct

```
[...]
            if isinstance(status, bool):
                if status:
                    params["status"] = "1"
                else:
                    params["status"] = "0"
[...]
            if isinstance(status, bool):
                if status:
                    if token["status"] != "0":
                        params["status"] = "0"
                else:
                    if token["status"] != "1":
                        params["status"] = "1"
[...]
```

In the latest commit (f54e99f - not released) this is the behaviour:
Creation:
status: true --> Enable the token - Correct
status: false --> Disable the token - Correct
Update:
status: true --> Disable the token - Wrong
status: false --> Enable the token - Wrong

```
[...]
            if isinstance(status, bool):
                if status:
                    params["status"] = "0"
                else:
                    params["status"] = "1"
[...]
            if isinstance(status, bool):
                if status:
                    if token["status"] != "1":
                        params["status"] = "1"
                else:
                    if token["status"] != "0":
                        params["status"] = "0"
[...]
```
