### ISSUE TITLE
Module zabbix_mediatype don't work add templates

### ISSUE THREAD

**Issue by dimonbaly** [ansible-collections/community.zabbix#1544]
##### SUMMARY

Adding templates doesn't work. If I do everything as in the examples, it says that digital values ​​are needed, if I put digital values, it says that strings are needed, I put strings, it says that numbers are needed
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_mediatype
##### ANSIBLE VERSION

```
ansible [core 2.18.5]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/sbin/ansible
  python version = 3.13.3 (main, Apr  9 2025, 07:44:25) [GCC 14.2.1 20250207] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

7.2.2

##### STEPS TO REPRODUCE

```yaml
- name: Configure complete Discord media type with all templates
      community.zabbix.zabbix_mediatype:
        name: "Discord {{ host_group }}"
        type: webhook
        status: enabled
        webhook_params:
          - name: discord_endpoint
            value: "{{ discord_webhook }}"
          - name: alert_message
            value: "{ALERT.MESSAGE}"
          - name: alert_subject
            value: "{ALERT.SUBJECT}"
          - name: event_date
            value: "{EVENT.DATE}"
          - name: event_id
            value: "{EVENT.ID}"
          - name: event_name
            value: "{EVENT.NAME}"
          - name: event_nseverity
            value: "{EVENT.NSEVERITY}"
          - name: event_opdata
            value: "{EVENT.OPDATA}"
          - name: event_recovery_date
            value: "{EVENT.RECOVERY.DATE}"
          - name: event_recovery_time
            value: "{EVENT.RECOVERY.TIME}"
          - name: event_severity
            value: "{EVENT.SEVERITY}"
          - name: event_source
            value: "{EVENT.SOURCE}"
          - name: event_tags
            value: "{EVENT.TAGS}"
          - name: event_time
            value: "{EVENT.TIME}"
          - name: event_update_action
            value: "{EVENT.UPDATE.ACTION}"
          - name: event_update_date
            value: "{EVENT.UPDATE.DATE}"
          - name: event_update_message
            value: "{EVENT.UPDATE.MESSAGE}"
          - name: event_update_status
            value: "{EVENT.UPDATE.STATUS}"
          - name: event_update_time
            value: "{EVENT.UPDATE.TIME}"
          - name: event_update_user
            value: "{USER.FULLNAME}"
          - name: event_value
            value: "{EVENT.VALUE}"
          - name: host_ip
            value: "{HOST.IP}"
          - name: host_name
            value: "{HOST.NAME}"
          - name: trigger_description
            value: "{TRIGGER.DESCRIPTION}"
          - name: trigger_id
            value: "{TRIGGER.ID}"
          - name: use_default_message
            value: "false"
          - name: zabbix_url
            value: "https://zabbix.imbalanced.tech"
          - name: HTTPProxy
            value: ""
        message_templates:
          # Проблема (trigger operations)
          - eventsource: "triggers"
            recovery: "operations"
            subject: "Problem: {TRIGGER.NAME}"
            body: "Problem started at {EVENT.TIME} on {EVENT.DATE}\nProblem name: {EVENT.NAME}\nHost: {HOST.NAME}\nSeverity: {EVENT.SEVERITY}\nOperational data: {EVENT.OPDATA}\nOriginal problem ID: {EVENT.ID}\n{TRIGGER.URL}"
          
          # Восстановление (trigger recovery)
          - eventsource: "triggers"
            recovery: "recovery_operations"
            subject: "Resolved: {TRIGGER.NAME}"
            body: "Problem has been resolved in {EVENT.DURATION} at {EVENT.RECOVERY.TIME} on {EVENT.RECOVERY.DATE}\nProblem name: {EVENT.NAME}\nHost: {HOST.NAME}\nSeverity: {EVENT.SEVERITY}\nOriginal problem ID: {EVENT.ID}\n{TRIGGER.URL}"
          
          # Обновление проблемы (update operations)
          - eventsource: "triggers"
            recovery: "update_operations"
            subject: "Updated: {TRIGGER.NAME}"
            body: "{USER.FULLNAME} {EVENT.UPDATE.ACTION} problem at {EVENT.UPDATE.DATE} {EVENT.UPDATE.TIME}.\n{EVENT.UPDATE.MESSAGE}\nCurrent problem status is {EVENT.STATUS}, acknowledged: {EVENT.ACK.STATUS}."
          
          # Проблема сервиса (internal operations)
          - eventsource: "internal"
            recovery: "operations"
            subject: "Service problem: {EVENT.NAME}"
            body: "Service problem started at {EVENT.TIME} on {EVENT.DATE}\nService problem name: {EVENT.NAME}\nService: {SERVICE.NAME}\nSeverity: {EVENT.SEVERITY}\nOriginal problem ID: {EVENT.ID}\nService description: {SERVICE.DESCRIPTION}\n{SERVICE.ROOTCAUSE}"
          
          # Восстановление сервиса (internal recovery)
          - eventsource: "internal"
            recovery: "recovery_operations"
            subject: "Service resolved: {SERVICE.NAME}"
            body: "Service \"{SERVICE.NAME}\" has been resolved at {EVENT.RECOVERY.TIME} on {EVENT.RECOVERY.DATE}\nProblem name: {EVENT.NAME}\nProblem duration: {EVENT.DURATION}\nSeverity: {EVENT.SEVERITY}\nOriginal problem ID: {EVENT.ID}\nService description: {SERVICE.DESCRIPTION}"
          
          # Обновление сервиса (update operations)
          - eventsource: "internal"
            recovery: "update_operations"
            subject: "Service update: {SERVICE.NAME}"
            body: "Changed \"{SERVICE.NAME}\" service status to {EVENT.UPDATE.SEVERITY} at {EVENT.UPDATE.DATE} {EVENT.UPDATE.TIME}.\nCurrent problem age is {EVENT.AGE}.\nService description: {SERVICE.DESCRIPTION}\n{SERVICE.ROOTCAUSE}"
          
          # Обнаружение (discovery)
          - eventsource: "discovery"
            recovery: "operations"
            subject: "Discovery: {DISCOVERY.RULE.NAME}"
            body: "Discovery rule: {DISCOVERY.RULE.NAME}\nDevice IP: {DISCOVERY.DEVICE.IPADDRESS}\nDevice DNS: {DISCOVERY.DEVICE.DNS}\nDevice status: {DISCOVERY.DEVICE.STATUS}\nDevice uptime: {DISCOVERY.DEVICE.UPTIME}\nDevice service name: {DISCOVERY.SERVICE.NAME}\nDevice service port: {DISCOVERY.SERVICE.PORT}\nDevice service status: {DISCOVERY.SERVICE.STATUS}\nDevice service uptime: {DISCOVERY.SERVICE.UPTIME}"
          
          # Авторегистрация (autoregistration)
          - eventsource: "autoregistration"
            recovery: "operations"
            subject: "Autoregistration: {HOST.HOST}"
            body: "Host name: {HOST.HOST}\nHost IP: {HOST.IP}\nAgent port: {HOST.PORT}"
```

##### ACTUAL RESULTS

```paste below

```
