### ISSUE TITLE
Wrong examples in documentation (community.zabbix.zabbix_user module)

### ISSUE THREAD

**Issue by Axsiow** [ansible-collections/community.zabbix#1547]
##### SUMMARY

There are errors in the documentation (latest), on the page [community.zabbix.zabbix_user module](https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_user_module.html#return-values). 
Some examples are wrong, it is marked "yes" or "no" but, it is expected a boolean "true" or "false"

Here are the errors:
```yaml
autologin: no

not_classified: no
information: yes
warning: yes
average: yes
high: yes
disaster: yes

active: no
```

##### ISSUE TYPE
- Bug Report
