### ISSUE TITLE
TLS parameters not passed into the Zabbix Agent config when installing Zabbix Agent 2 instead of Zabbix Agent

### ISSUE THREAD

**Issue by kladderadeng** [ansible-collections/community.zabbix#1552]
##### SUMMARY
When intalling Zabbix Agent 2 instead of Zabbix Agent, the TLS parameters are not honored, the zabbix_agent2.conf file does also not get the TLS parameters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_agent role

##### ANSIBLE VERSION
```
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION
```
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT / Zabbix Version
Target is an Debian LXC Container running under Proxmox.
cat /etc/debian_version reads 12.11.

##### STEPS TO REPRODUCE
I run the following playbook against Debian 12 system, which gets the Zabbix Agent2 installed, but without setting the TLS parameters, nor creating the zabbix_agent_pskfile.psk file.
When changing `zabbix_agent2: true` to `zabbix_agent: true`, which installs the Zabbix Agent 1, TLS parameters get set in the Agent config as expected.

Playbook:
```yaml
---
# file: pb_zabbixagent.yml
- name: Install Zabbix Agent on host group zabbixagents
  hosts: zabbixagents
  roles:
    - role: community.zabbix.zabbix_agent
```

group_vars
```yaml
zabbix_agent2: true
zabbix_agent_server: <ip>
zabbix_agent_serveractive: <ip>
zabbix_agent_tlspskidentity: "PSK1"
zabbix_agent_tlsconnect: psk
zabbix_agent_tlsaccept: psk
zabbix_agent_tlspsk_secret: "01234567890123456789012345678901"
zabbix_agent_tlspskfile: /etc/zabbix/zabbix_agent_pskfile.psk
```

##### EXPECTED RESULTS
I expected, that no matter if I install the Zabbix Agent or the Zabbix Agent 2 with this module, that the TLS parameters get set / configured.

##### ACTUAL RESULTS
When using Zabbix Agent 2 instead of 1, no TLS parameters are configured, despite configured in the Playbook / Vars.
There are not error messages when running the playbook.

**Comment by pyrodie18** [comment]
Can you share a copy of the config file that gets spit out?

**Comment by eb4x** [comment]
Get the configuration file from the server you're trying to configure.

Also, just a quick glance of your description, setting `zabbix_agent: true` is not the way you change agent version. You'd probably want to set `zabbix_agent2: false` to run the old agent.

**Comment by pyrodie18** [comment]
If you can copy/,paste the agent2.conf that gets produced

**Comment by kladderadeng** [comment]
@eb4x @pyrodie18 Thanks to both of you! I was not sure which config you wanted to see, but of course the zabbix_agent*.conf makes sense.
BUT!
Yesterday, while trying to solve other problems, I have seen that there is a new version of the Galaxy collection out and I switched to version 4.0.0. At the same time, I made sure all the requirements are on the latest version also.

The 3.3.0 Docs up until 5 days ago mentioned:
```
---
collections:
  - name: community.zabbix
    version: 3.3.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
```

The 4.0.0 Docs now mention:
```
---
collections:
  - name: community.zabbix
    version: 4.0.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
```

And I changed it to:
```
---
# file: /roles/requirements.yml
collections:
  - name: community.zabbix
    version: 4.0.0
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 10.7.0
```

I am not sure if the last 2 make a difference, because I had issues that the zabbix_agent2.conf was not populated with the TLS parameters. Probably switching to 4.0.0 alone would have fixed it.

But now when using `zabbix_agent2: true` it not only populates the zabbix_agent2.conf with the TLS parameters, but also seem to include all kind of parameters and the ones which are not configured are just commented out (#) instead of left out entirely, which is nice.

My issue is solved by adjusting the Requirements. Thanks to everyone who looked into it!
