### ISSUE TITLE
when zabbix-agent from official debian repos is used, wrong log file path is configured

### ISSUE THREAD

**Issue by pravi** [ansible-collections/community.zabbix#1555]
##### SUMMARY
/etc/zabbix/zabbix_agentd.conf generated by community.zabbix role has a wrong value for log file path and this makes zabbix agent service to fail.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

Debian Trixie but target is on debian bookworm - but it should not be dependent on zabbix version

##### STEPS TO REPRODUCE

```yaml
---
dependencies:
  - role: community.zabbix.zabbix_agent
    vars:
      zabbix_agent_server: "{{ purism_zabbix_server }}"
      zabbix_agent_serveractive: "{{ purism_zabbix_server }}"
      zabbix_agent_version_check: false
      zabbix_manage_repo: false
      zabbix_agent_install_agent_only: true
```

##### EXPECTED RESULTS

/etc/zabbix/zabbix_agentd.conf should have 

`LogFile=/var/log/zabbix-agent/zabbix_agentd.log`

##### ACTUAL RESULTS

But is has wrong configuration

```paste below
`LogFile=/var/log/zabbix/zabbix_agentd.log`

```
Changing this fixes the problem and starts zabbig agent correctly.
