### ISSUE TITLE
Problem with host item creation

### ISSUE THREAD

**Issue by Eugenemdk** [ansible-collections/community.zabbix#1573]
In ansible community docs specified that  **community.zabbix.zabbix_item** module supports item type **http_agent** however parameters such as **URL** and **headers** are missed, is there any documented examples of the "http_agent" item type usage?

Below is the current code that i am using:
```
    - name: Add item to Zabbix host
      community.zabbix.zabbix_item:
        host_name: "{{ item.host_name }}"
        http_login_user: "{{username}}"
        http_login_password: "{{password}}"
        name: "Total Requests"
        params:
          status: enabled
          interval: 15m
          key: "total_requests"
          type: "http_agent"
          value_type: numeric_unsigned
          url: "https://api.dnsfilter.com/v1/traffic_reports/total_requests?bucket_size=1m&network_ids={{item.networkId}}&organization_ids={{item.org_id}}&show_individual_networks=true"
          headers:
            Authorization: "{{ api_key }}"
            Accept: application/json
          preprocessing:
            type: "jsonpath"
            params: $.data.values[0].total
        state: present
      loop: "{{ networks }}"
      ignore_errors: true
```

after execution it fails with the error message:
**TypeError: string indices must be integers, not 'str'**

**Comment by Eugenemdk** [comment]
Solution: 
- **preprocessing** parameter must be the list of dictionaries
- **headers** parameter must be represented as an array
- string properties needs to be converted to integer, in my case:` {{ item.networkId | int }}`

Edited task code:
 ```
- name: Add item to Zabbix host
      community.zabbix.zabbix_item:
        host_name: "{{ item.host_name }}"
        http_login_user: "{{username}}"
        http_login_password: "{{password}}"
        name: "Total Requests"
        params:
          status: enabled
          interval: 15m
          key: "total_requests"
          type: "http_agent"
          value_type: numeric_unsigned
          url: "https://api.dnsfilter.com/v1/traffic_reports/total_requests?bucket_size=1min&network_ids={{ item.networkId | int }}&organization_ids={{item.org_id}}&show_individual_networks=true"
          headers:
            - name: Authorization 
              value: "{{ dnsfilter_api_key }}"
            - name: Accept
              value: "application/json"
          preprocessing:
            - type: jsonpath
              params: '$.data.values[0].total'
              error_handler: zabbix_server
        state: present
      loop: "{{ networks }}"
      ignore_errors: true
```
