### ISSUE TITLE
httpapi not working after upgrade to 3.3.0,4.0.0

### ISSUE THREAD

**Issue by dshleg** [ansible-collections/community.zabbix#1574]
##### SUMMARY
Role fails with error
connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Not authorized.'} when sending {'jsonrpc': '2.0', 'method': 'template.get', 'id': '6143a544-cf93-4c09-8594-ddd3a656c4a0', 'params': {'output': ['templateid'], 'filter': {'host': 'Chassis by IPMI'}}}

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.17.7]
  config file = /home/user/work/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /srv/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections/ansible_collections:/usr/share/ansible/collections/ansible_collections
  executable location = /srv/ansible/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/srv/ansible/bin/python3)
  jinja version = 3.1.4
  libyaml = True

```

##### OS / ENVIRONMENT / Zabbix Version
Zabbix 7.0.5

##### STEPS TO REPRODUCE

Playbook
```yaml

- hosts:
   - "hypervisors"

  roles:
    - community.zabbix.zabbix_agent

```
Variables:
```yaml

#required for windows
zabbix_win_install_dir: 'C:\Program Files\Zabbix'
zabbix_version_long: 7.0.12
zabbix_agent_win_include: 'C:\Program Files\Zabbix\conf\zabbix_agent2.d\userparameters'
#

zabbix_agent_package_remove: True
zabbix_agent_apt_priority: 1001
zabbix_agent_dont_detect_ip: True #Need ansible > 2.13.5
zabbix_agent2: True
zabbix_agent_version: 7.0

zabbix_agent_userparameters_templates_src: "{{ inventory_dir }}/roles_data/templates/zabbix"
zabbix_agent_userparameters_scripts_src: "{{ inventory_dir }}/roles_data/files/scripts"


#Configure host monitoring
zabbix_useuip: 1
ansible_zabbix_url_path: '' #Fix for api

#ansible_connection: restconf
zabbix_api_use_ssl: true
zabbix_api_server_host: zabbix7.domain.info
zabbix_api_server_port: 443
zabbix_api_login_user: "{{ zbx_api_login_user }}"
zabbix_api_login_pass: "{{ zbx_api_login_pass }}"
zabbix_api_create_hostgroup: false
zabbix_api_create_hosts: true
zabbix_agent_host_state: present

#Configure host agent parameters
zabbix_agent_server: proxy1-zbx-med2, proxy2-zbx-med2, proxy3-zbx-med2
zabbix_agent_serveractive: proxy1-zbx-med2, proxy2-zbx-med2, proxy3-zbx-med2

#Interface types: 1 - agent, 2 - snmp, 3 - ipmi, 4 jmx
zabbix_agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ ansible_host }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ zabbix_agent_listenport }}"

#####
#Configure host monitoring via API
zabbix_useuip: 1
#zabbix_server', 'proxy', and 'proxy_group'
zabbix_agent_monitored_by: proxy_group
zabbix_agent_proxy_group: DEP-MED2
zabbix_agent_host_state: present

#Interface types: 1 - agent, 2 - snmp, 3 - ipmi, 4 jmx
zabbix_agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ ansible_host }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ zabbix_agent_listenport }}"
  - type: 3
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ ipmi_address }}"
    port: "{{ ipmi_port }}"
    dns: "{{ ipmi_fqdn | default ('') }}"

#IPMI authentication algorithm. Possible values are -1 (default), 0 (none), 1 (MD2), 2 (MD5), 4 (straight), 5 (OEM), 6 (RMCP+), with -1 being the API default.
zabbix_agent_ipmi_authtype: 6
zabbix_agent_ipmi_username: "{{ zbx_agent_ipmi_user}}"
zabbix_agent_ipmi_password: "{{ zbx_agent_ipmi_pwd }}"
#IPMI privilege level. Possible values are 1 (callback), 2 (user), 3 (operator), 4 (admin), 5 (OEM), with 2 being the API default.
zabbix_agent_ipmi_privilege: 2
zabbix_host_groups:
  - MY/Hypervisors/Linux
  - MY/Hardware/Servers


zabbix_agent_link_templates:
  - Chassis by IPMI
  - Template OS Linux
  - Template KVM-Proxmox
  - ZFS on Linux

zabbix_agent_userparameters:
  - name: ZFS
  - name: smartctl
    scripts_dir: smartctl


zabbix_agent_aliases:
  - "net.if.discovery[*]:net.if.discovery"
  - "proxmox.net.if.in[*]:net.if.in[*]"
  - "proxmox.net.if.out[*]:net.if.out[*]"

#Overriding default template variable values
zabbix_agent_macros:
  - macro_key: "{$MEMORY.UTIL.MAX}"
    macro_value: 95
    macro_type: text
  - macro_key: "{$SMART.TEMPERATURE.MAX.WARN}"
    macro_value: 65
    macro_type: text
  - macro_key: "{$SMART.TEMPERATURE.MAX.CRIT}"
    macro_value: 70
    macro_type: text
  - macro_key: "{$NET.IF.IFNAME.NOT_MATCHES}"
    macro_value: "(^Software Loopback Interface|^NULL[0-9.]*$|^[Ll]o[0-9.]*$|^[Ss]ystem$|^Nu[0-9.]*$|^veth[0-9A-z]+$|docker[0-9]+|br-[a-z0-9]{12}|^tap[0-9]{3,4}i[0-9]+$|^fw(br|pr|ln)[0-9]{3,4}(i|p)[0-9]+$)"
    macro_type: text
  - macro_key: "{$VFS.DEV.DEVNAME.NOT_MATCHES}"
    macro_value: "^(loop[0-9]*|sd[a-z][0-9]+|nbd[0-9]+|sr[0-9]+|fd[0-9]+|dm-[0-9]+|ram[0-9]+|ploop[a-z0-9]+|md[0-9]*|hcp[0-9]*|zram[0-9]*|zd[0-9]+)"
    macro_type: text



zabbix_agent_tags:
  - tag: environment
    value: production
  - tag: OS
    value: Linux
  - tag: role
    value: Hypervisor



```

##### ACTUAL RESULTS

Role failed on task 
TASK [community.zabbix.zabbix_agent : API | Create a new host or update an existing host's info] 

```paste below

```
