### ISSUE TITLE
Wrong zabbix_agent_include permissions IMHO

### ISSUE THREAD

**Issue by indreek** [ansible-collections/community.zabbix#181]
##### SUMMARY

```
- name: "Create include dir zabbix-agent"
  file:
    path: "{{ zabbix_agent_include }}"
    owner: root
    group: zabbix
    mode: 0750
    state: directory
  become: yes
  tags:
    - config
    - include
```

IMHO permissions on zabbix_agent_include (/etc/zabbix/zabbix_agentd.d/ shouldn't be different from /etc/zabbix/ folder. Because regular user can access with read main folder and I don't see any reasons why they shouldn't be able to access this folder. I cannot user zabbix_sender functions if I don't have access to zabbix-agentd.d folder.

```
# zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k import.%s.last_import -o 1
# zabbix_sender [12855]: /etc/zabbix/zabbix_agentd.d: [13] Permission denied
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix-agent
