### ISSUE TITLE
zabbix_server: fails to populate mariadb if innodb_default_row_format is not dynamic

### ISSUE THREAD

**Issue by 1977er** [ansible-collections/community.zabbix#198]
##### SUMMARY
When you use zabbix_server to populate a new MariaDB database, you may run into "Error 1709: Index column size too large." errors. innodb_default_row_format=dynamic is a workaround.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_server role

##### ANSIBLE VERSION
```
ansible 2.9.12
 config file = /etc/ansible/ansible.cfg
 configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
 ansible python module location = /usr/lib/python2.7/dist-packages/ansible
 executable location = /usr/bin/ansible
 python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION
```
(empty)
```

##### OS / ENVIRONMENT / Zabbix Version
Installing Zabbix server 5.0 on a Debian Buster 
using an external DBHost with 10.1.45-MariaDB-0+deb9u1 on a Debian 9.12

##### STEPS TO REPRODUCE
mysqladmin create myzabbix
Creation of zabbixuser for mysql with sufficient privs were done manually.

```yaml
zabbix_server_version: "5.0"
zabbix_server_database: "mysql"
zabbix_server_database_long: "mysql"
zabbix_server_dbhost: "dbhost.example.com "
zabbix_server_dbport: 3306
zabbix_server_dbname: "myzabbix"
zabbix_server_dbuser: "zabbixuser"
zabbix_server_dbpassword: "secret"
```

##### EXPECTED RESULTS
Role should complete without errors.

##### ACTUAL RESULTS
```
TASK [community.zabbix.zabbix_server : MySQL | Create database and import file >= 3.0]

fatal: [<REDACTED> -> <REDACTED>]: FAILED! => {
   "changed": false,
   "invocation": {
       "module_args": {
           "ca_cert": null,
           "client_cert": null,
           "client_key": null,
           "collation": "utf8_bin",
           "config_file": "/root/.my.cnf",
           "connect_timeout": 30,
           "encoding": "utf8",
           "ignore_tables": [],
           "login_host": "localhost",
           "login_password": null,
           "login_port": 3306,
           "login_unix_socket": null,
           "login_user": null,
           "name": [
               "zabbix-2"
           ],
           "quick": true,
           "single_transaction": false,
           "state": "import",
           "target": "/usr/share/doc/zabbix-server-mysql/create.sql.gz"
       }
   }
}

MSG:
gzip: stdout: Broken pipe
```

MariaDB prior to 10.2.2 uses COMPACT innodb_default_row_format instead of DYNAMIC. Piping the create.sql,gz into the database fails with an "Error 1709: Index column size too large.".
Setting innodb_default_row_format=dynamic globally circumvents the problem.

##### WORKAROUND
Add the following stanza in roles/zabbix_server/tasks/mysql.yml around line 78:

```
- name: "MySQL | Set innodb_default_row_format to dynamic"
 mysql_variables:
   variable: innodb_default_row_format
   value: dynamic
 when:
   - zabbix_version is version('3.0', '>=')
   - zabbix_database_sqlload | bool
   - zabbix_repo != "epel"
   - not done_file.stat.exists
 delegate_to: "{{ delegated_dbhost }}"
 tags:
   - zabbix-server
   - database
```

TODO: Check the version of MariaDB and if this setting is necessary.
