### ISSUE TITLE
The task includes an option with an undefined variable

### ISSUE THREAD

**Issue by MaartenMol** [ansible-collections/community.zabbix#205]
##### SUMMARY

Trying the Zabbix roles for the first time. Rolled out fresh CentOS 8 boxes using Ansible and VMware modules. Upon task "TASK [community.zabbix.zabbix_web : RedHat | Install zabbix-web-pgsql]" getting undefined variable error.

Already tried to quote the pkg line (line 80) but that didn't solve it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_web

##### ANSIBLE VERSION

```paste below
2.9.11
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

CentOS 8 fresh install on VMware

##### STEPS TO REPRODUCE

```yaml
- name: Configure Zabbix Web
  hosts: ZabbixWeb
  gather_facts: yes
  roles:
    - geerlingguy.apache
    - community.zabbix.zabbix_web
  vars:
    zabbix_server_version: 5.0
    zabbix_web_centos_release: True
    zabbix_url: XXXXX
    zabbix_timezone: Europe/Amsterdam
    zabbix_server_name: XXXXX
    zabbix_server_hostname: XXXXX
    zabbix_server_listenport: 10051
    zabbix_server_database: pgsql
    zabbix_server_database_long: postgresql
    zabbix_server_dbhost: XXXXX
    zabbix_server_dbport: 5432
    zabbix_server_dbname: zabbix
    zabbix_server_dbuser: zabbix
    zabbix_server_dbpassword: XXXXX
```

##### EXPECTED RESULTS

To install Zabbix Web Server

##### ACTUAL RESULTS

```paste below
{
    "msg": "The task includes an option with an undefined variable. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.\n\nThe error appears to be in '/var/lib/awx/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_web/tasks/RedHat.yml': line 76, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"RedHat | Install zabbix-web-{{ zabbix_server_database }}\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n",
    "_ansible_no_log": false
}
```
