### ISSUE TITLE
Failed to connect to Zabbix server: urllib2.URLError - Precondition Failed

### ISSUE THREAD

**Issue by ironbishop** [ansible-collections/community.zabbix#218]
##### SUMMARY
module `zabbix_host_info` (and all other modules too) fails with error: `Failed to connect to Zabbix server: urllib2.URLError - Precondition Failed`

On Zabbix Frontend, no Content Type is received: that's why it replies with error 412.

* Could be related to Zabbix 5.0.3.
* Error does not occur using `humao.rest-client`. 
* Error does not occur using `pyzabbix`.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.12
  config file = /home/***/ansible/ansible.cfg
  configured module search path = ['/home/***/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/***/ansible/venv/lib64/python3.6/site-packages/ansible
  executable location = /home/**/ansible/venv/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```
DEFAULT_CALLBACK_WHITELIST(/home/***/ansible/ansible.cfg) = ['profile_tasks', 'timer']
HOST_KEY_CHECKING(/home/***/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/***/ansible/ansible.cfg) = ['script', 'host_list', 'yaml', 'ini', 'vmware_vm_inventory']
USE_PERSISTENT_CONNECTIONS(/home/***/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT / Zabbix Version

```
zabbix-server 5.0.3

zabbix-api==0.5.4

CentOS Linux release 8.2.2004 (Core)
```

##### STEPS TO REPRODUCE

```yaml
- name: gets info from Zabbix Server
  check_mode: yes
  environment:
    no_proxy: "127.0.0.1,localhost,.local,{{zabbix_server_host}}"
  local_action:
    module: zabbix_host_info
    server_url: "{{zabbix_api_url}}"
    validate_certs: no
    login_user: "{{zabbix_api_user}}"
    login_password: "{{zabbix_api_pass}}"
    host_name: "{{inventory_hostname}}"
  retries: 2
  delay: 2
  throttle: 1
  register: zabbix_host_infos
  until: zabbix_host_infos is not failed
```

##### EXPECTED RESULTS
Module should connect to Zabbix Server.

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_zabbix_host_info_payload_4k4yw381/ansible_zabbix_host_info_payload.zip/ansible/modules/monitoring/zabbix/zabbix_host_info.py", line 215, in main
  File "/home/***/ansible/venv/lib64/python3.6/site-packages/zabbix_api.py", line 207, in login
    result = self.do_request(obj)
  File "/home/***/ansible/venv/lib64/python3.6/site-packages/zabbix_api.py", line 274, in do_request
    raise ZabbixAPIException("urllib2.URLError - %s" % e)
fatal: [***]: FAILED! => {
    "attempts": 2,
    "changed": false,
    "invocation": {
        "module_args": {
            "exact_match": false,
            "host_inventory": [],
            "host_ip": [],
            "host_name": "***",
            "http_login_password": null,
            "http_login_user": null,
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "ansible-api",
            "remove_duplicate": true,
            "server_url": "http://***/zabbix/api_jsonrpc.php",
            "timeout": 10,
            "validate_certs": false
        }
    },
    "msg": "Failed to connect to Zabbix server: urllib2.URLError - Precondition Failed"
}
```
