### ISSUE TITLE
Rework CI for merged roles

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#22]
##### SUMMARY
Current candidate -  Github Actions from previous Travis CI. Example of working CI with Actions:
https://github.com/ericsysmin/ansible-collection-system/tree/master/.github/workflows

More information in:
- [comment1](https://github.com/ansible-collections/community.zabbix/issues/16#issuecomment-621652303)
- [comment2](https://github.com/dj-wasabi/ansible-zabbix-agent/issues/341#issuecomment-620886308)

Dependent on the completion of #20.

We should look at how the whole CI operates after this is solved. There is probably no need to run tests for plugins when a change to role occurs.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
.github/workflows/roles.yml

**Comment by ericsysmin** [comment]
working example from one of my new collections 
```
name: "Role: ericsysmin.system.chrony Molecule Test"
on:
  push:
    paths:
      - roles/chrony/**
      - .github/workflows/chrony.yml
  pull_request:
    paths:
      - roles/chrony/**
      - .github/workflows/chrony.yml
jobs:
  roles_test:
    runs-on: ubuntu-18.04
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        molecule_distro:
          - distro: centos:7
            command: /usr/sbin/init
          - distro: centos:8
            command: /usr/sbin/init
        collection_role:
          - chrony
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/ericsysmin/system

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install molecule yamllint ansible-lint docker

      - name: Run role test
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test -s ${{ matrix.collection_role }}
```
