### ISSUE TITLE
Unable to export template ascii codec can't encode character

### ISSUE THREAD

**Issue by exc1te** [ansible-collections/community.zabbix#233]
##### SUMMARY
I'm trying to do export template, but template cannot be exported.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_template
zabbix_template_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /home/dskryminskiy/ansible/ansible.cfg
  configured module search path = [u'/home/dskryminskiy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dskryminskiy/virtualenv/ansible2910-python27/lib/python2.7/site-packages/ansible
  executable location = /home/dskryminskiy/virtualenv/ansible2910-python27/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### OS / ENVIRONMENT / Zabbix Version
Centos 7.8
Python 2.7.5
Zabbix 5.0.3

##### STEPS TO REPRODUCE
1. Do a fresh install of Zabbix 5.0.3
2. Make a dump of template:

```yaml
  - name: template dump
    local_action:
      module: community.zabbix.zabbix_template
      server_url: http://192.168.253.17
      login_user: Admin
      login_password: zabbix
      template_name: "Template DB MySQL"
      state: dump
      dump_format: xml

```
or

```yaml
  - name: template dump
    local_action:
      module: community.zabbix.zabbix_template_info
      server_url: http://192.168.253.17
      login_user: Admin
      login_password: zabbix
      template_name: "Template DB MySQL"
      format: xml

```

##### EXPECTED RESULTS
Template should be exported without errors.

##### ACTUAL RESULTS

```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_community.zabbix.zabbix_template_payload_CYl4qE/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py", line 470, in dump_template
fatal: [test]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "clear_templates": null, 
            "dump_format": "xml", 
            "http_login_password": null, 
            "http_login_user": null, 
            "link_templates": null, 
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "login_user": "Admin", 
            "macros": null, 
            "omit_date": false, 
            "server_url": "http://192.168.253.17", 
            "state": "dump", 
            "template_groups": null, 
            "template_json": null, 
            "template_name": "Template DB MySQL", 
            "template_xml": null, 
            "timeout": 10, 
            "validate_certs": false
        }
    }, 
    "msg": "Unable to export template: 'ascii' codec can't encode character u'\\xa0' in position 2853: ordinal not in range(128)"

```
Same behavior was with zabbix_template and zabbix_template_info modules.
