### ISSUE TITLE
zabbix_http_proxy and zabbix_https_proxy shouldn't be used together

### ISSUE THREAD

**Issue by Gwynnbleid1** [ansible-collections/community.zabbix#257]
##### SUMMARY

When you provide both variables (zabbix_http_proxy and zabbix_https_proxy) as described here:
https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md#proxy
then playbook won't work when trying to download things from repo

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_agent

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
  config file = /ansible/ansible.cfg
  configured module search path = [u'/home/mberkieta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/ansible/ansible.cfg) = [u'/ansible/collections']
DEFAULT_BECOME(/ansible/ansible.cfg) = False
DEFAULT_JINJA2_EXTENSIONS(/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = [u'/ansible/roles']
RETRY_FILES_ENABLED(/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

provide both variables:
zabbix_http_proxy: http://localhost:3128
zabbix_https_proxy: http://localhost:3128
when you have only http proxy present
 

```yaml

```

##### EXPECTED RESULTS

Playbook should try https proxy and if this failed three times then it should fall-back to http proxy, or documentation should be updated with information that you should not provide both variables.

##### ACTUAL RESULTS

```paste below
FAILED - RETRYING: Debian | Installing zabbix-agent (3 retries left).
FAILED - RETRYING: Debian | Installing zabbix-agent (2 retries left).
FAILED - RETRYING: Debian | Installing zabbix-agent (1 retries left).
fatal: [host.example.com]: FAILED! => {"attempts": 3, "changed": false, "msg": "Failed to update apt cache: "}
```

**Comment by Gwynnbleid1** [comment]
I think that problem lies in file /community/zabbix/roles/zabbix_agent/tasks/Debian.yml: 
I have changed task "Debian | Installing gnupg" to this (it was missing environment section which I copied from task "Debian | Installing deb-src repository Debian"):
```
- name: "Debian | Installing gnupg"
  apt:
    pkg: gnupg
    update_cache: yes
    cache_valid_time: 3600
    force: yes
    state: present
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: gnupg_installed
  until: gnupg_installed is succeeded
  become: yes
```

with this the error mentioned above is not showing anymore regardless of apt cache state.
