### ISSUE TITLE
Zabbix Agent install on Suse 12 SP2 does not work

### ISSUE THREAD

**Issue by chofstede** [ansible-collections/community.zabbix#263]
##### SUMMARY
When trying to install Zabbix Agent on Suse Linux Enterprise Server 12 SP2 the Playbook exists with an error:

The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '12'\n\nThe error appears to be in '/tmp/awx_284_kwr_2kqd/requirements_collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Suse.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Suse | Install basic repo file\"\n  ^ here\n

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent role

##### ANSIBLE VERSION

```paste below
Ansible 2.9.14 
```

##### CONFIGURATION

```paste below
empty output
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 5.0 LTS on Debian GNU/Linux 10

##### STEPS TO REPRODUCE

```yaml
---
- name: Deploy Zabbix Agent
  hosts: all
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_api_use: True
      zabbix_api_create_hosts: True
      zabbix_create_host: present
      zabbix_url: "{{ zabbix_url }}"
      zabbix_api_user: "{{ zusr }}"
      zabbix_api_pass: "{{ zpwd }}"
      zabbix_agent_hostname: "{{ ansible_hostname }}"
      zabbix_visible_hostname: "{{ config.name }}"
      zabbix_agent_server: "{{ zabbix_ip }}"
      zabbix_agent_serveractive: "{{ zabbix_ip }}"
```

##### EXPECTED RESULTS

Zabbix Agent is being installed

##### ACTUAL RESULTS

Error Message appears

```paste below
SSH password: 
BECOME password[defaults to SSH password]: 
PLAY [Deploy Zabbix Agent] *****************************************************
TASK [Gathering Facts] *********************************************************
ok: [SusServer]
TASK [community.zabbix.zabbix_agent : Set variables specific for Zabbix Agent 2] ***
skipping: [SusServer]
TASK [community.zabbix.zabbix_agent : Fix facts for linuxmint - distribution release] ***
skipping: [SusServer]
TASK [community.zabbix.zabbix_agent : Fix facts for linuxmint - family] ********
skipping: [SusServer]
TASK [community.zabbix.zabbix_agent : Fix facts for XCP-ng - family] ***********
skipping: [SusServer]
TASK [community.zabbix.zabbix_agent : Include OS-specific variables] ***********
ok: [SusServer]
TASK [community.zabbix.zabbix_agent : Install the correct repository] **********
included: /tmp/awx_284_kwr_2kqd/requirements_collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Suse.yml for SusServer
TASK [community.zabbix.zabbix_agent : Include Zabbix gpg ids] ******************
ok: [SusServer]
TASK [community.zabbix.zabbix_agent : Install zypper repo dependency] **********
ok: [SusServer]
TASK [community.zabbix.zabbix_agent : Suse | Install basic repo file] **********
fatal: [SusServer]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '12'\n\nThe error appears to be in '/tmp/awx_284_kwr_2kqd/requirements_collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Suse.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Suse | Install basic repo file\"\n  ^ here\n"}
PLAY RECAP *********************************************************************
SusServer : ok=5    changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0
```
