### ISSUE TITLE
zabbix_web php-fpm does not refer to zabbix.conf 

### ISSUE THREAD

**Issue by senyoltw** [ansible-collections/community.zabbix#270]
##### SUMMARY

php-fpm does not refer to zabbix.conf created by zabbix_web role

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_web

##### ANSIBLE VERSION
```
2.9.15
```

##### OS / ENVIRONMENT / Zabbix Version
RHEL 7.4 / rh-php72-php-fpm / zabbix_server (Zabbix) 5.0.5 

##### STEPS TO REPRODUCE
```yaml
- name: Install Zabbix Server
  hosts: zabbix_servers
  become: yes
  roles:
    - role: geerlingguy.apache
    - role: community.zabbix.zabbix_web
       zabbix_websrv: apache
       zabbix_php_fpm: True
```

##### EXPECTED RESULTS

php-fpm refers to the generated zabbix.conf
```
/etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
```
##### ACTUAL RESULTS
https://github.com/ansible-collections/community.zabbix/blob/bdc020b19b010704c988b6766f6b33ff66a5aa4c/roles/zabbix_web/tasks/RedHat.yml#L90-L101

php-fpm does not refer to the generated zabbix.conf

```paste below
# Where zabbix.conf is created by role
/etc/opt/rh/rh-php72/zabbix.conf
# Directory referenced by php-fpm. 
/etc/opt/rh/rh-php72/php-fpm.d/*.conf
```
