### ISSUE TITLE
Buggy documentation for zabbix_proxy role

### ISSUE THREAD

**Issue by KarlikB** [ansible-collections/community.zabbix#282]
##### SUMMARY

Zabbix proxy documentation https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_PROXY_ROLE.md
The documentation pro zabbix_proxy role  is buggy and misleading. It looks like it is cut'n'paste problem from zabbix_server role documentation. 
Documentation for sqlite3 completely missing, but the sqlite3 support working, I tested it using reverse engineered information and installation of zabbix proxy sqlite3 works with minor flaws. 

The example playbook for zabbix proxy is incorrect:
```
- hosts: zabbix-server
    roles:
      - role: community.zabbix.zabbix_server
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
```
The last two variables are incorrectly named, the right names are zabbix_proxy_database and zabbix_proxy_database_long

The documentation contains 22 occurrences of the phrase "zabbix server", mostly at the inappropriate place.
E.g. on line: 
**zabbix_proxy_dbname:** The database name which is used by the **Zabbix Server**.

The documentation need corrections and add documentation for sqlite3.

##### ISSUE TYPE
- Bug Report (documentation)
