### ISSUE TITLE
Escalation problem in zabbix_proxy role

### ISSUE THREAD

**Issue by KarlikB** [ansible-collections/community.zabbix#283]
##### SUMMARY
The playbook run for installation zabbix_proxy for sqlite3 fails on missing right escalation on these two tasks:
roles/zabbix_proxy/tasks/main.yml - task "Configure zabbix-proxy"
roles/zabbix_proxy/tasks/sqlite3.yml - task "Sqlite3 | Create database"
Both tasks manipulates with file ownership and fails on missing "become: yes" directive.

As a workaround it is possible to set "become: yes" at the playbook level but this approach also escalates right for other tasks

Also the role does not check/install sqlite3 binary necessary for creation of DB instance. I do not know if it is intentional behaviour or not.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_proxy role

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```
empty output of "ansible-config dump --only-changed"

```

##### OS / ENVIRONMENT / Zabbix Version

CentOS Linux release 8.2.2004 (Core), Zabbix 5.0.5

##### STEPS TO REPRODUCE

executed playbook listed below

```yaml
---
- name: Install Zabbix Proxy
  hosts: proxydemo.mshome.net
  roles:
    - role: community.zabbix.zabbix_proxy
      zabbix_server_host: zabbix5.mshome.net
      zabbix_proxy_database: sqlite3
      zabbix_proxy_database_long: sqlite3
      zabbix_proxy_listenport: 10151
```

##### EXPECTED RESULTS

Zabbix proxy installed by playbook

##### ACTUAL RESULTS

Zabbix proxy installation failed.
When forementioned two tasks fixed, everything works.
