### ISSUE TITLE
Cannot set guest user as disabled

### ISSUE THREAD

**Issue by joshproehl** [ansible-collections/community.zabbix#312]
##### SUMMARY

Attempting to add the "Disabled" group to the system guest user results in errors.

First error was "User password is required. One or more groups are not LDAP based."
After attempting to set password to '', the error was "Not allowed to set language for user "guest"".
Upon further investigation, the JSON included in the error contains lang, timezone, and theme keys, which cannot be set manually for the guest user. (I am uncertain about if setting the password to '' is correct, or if the zabbix guest user implicitly has no password.)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_user

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /home/joshproehl/ansible/testproject/ansible.cfg
  configured module search path = ['/home/joshproehl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.0 (default, Oct  7 2020, 23:09:01) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/joshproehl/ansible/testproject/ansible.cfg) = ['/home/joshproehl/ansible/testproject/hosts.yml']
DEFAULT_PRIVATE_KEY_FILE(/home/joshproehl/ansible/testproject/ansible.cfg) = /home/joshproehl/.ssh/appropriate_key
DEFAULT_REMOTE_USER(/home/joshproehl/ansible/testproject/ansible.cfg) = root
DEFAULT_VAULT_PASSWORD_FILE(/home/joshproehl/ansible/testproject/ansible.cfg) = /home/joshproehl/ansible/testproject/.ansible_vault_pass
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix server 5.2 installed via docker container

##### STEPS TO REPRODUCE

```yaml
    - name: ensure zabbix guest user is deactivated
      local_action:
        module: community.zabbix.zabbix_user
        server_url: "https://my.zabbix.server.url"
        login_user: Admin
        login_password: "{{ zabbix_admin_user_password }}"
        alias: guest
        passwd: ''
        role_name: Guest role
        usrgrps:
          - Guests
          - Disabled
        type: Zabbix user
```

##### EXPECTED RESULTS

User "guest" is set to disabled by virtue of having been added to the disabled group.

##### ACTUAL RESULTS

An error is thrown. 

```paste below
TASK [ensure zabbix guest user is deactivated] *********************************************************************************************************************************************
fatal: [my.server.fqdn]: FAILED! => {"changed": false, "msg": "Failed to update user guest: ('Error -32602: Invalid params., Not allowed to set language for user \"guest\". while sending {\"jsonrpc\": \"2.0\", \"method\": \"user.update\", \"params\": {\"userid\": \"2\", \"alias\": \"guest\", \"name\": \"\", \"surname\": \"\", \"usrgrps\": [{\"usrgrpid\": \"8\"}, {\"usrgrpid\": \"9\"}], \"lang\": \"default\", \"theme\": \"default\", \"autologin\": \"0\", \"autologout\": \"0\", \"refresh\": \"30\", \"rows_per_page\": \"50\", \"url\": \"\", \"roleid\": \"4\", \"timezone\": \"default\"}, \"auth\": \"cb41e02fcf3343663175690c2898e543\", \"id\": 6}', -32602)"}
```
