### ISSUE TITLE
run zabbix_server role, deleted /tmp/snap.lxd

### ISSUE THREAD

**Issue by masakura** [ansible-collections/community.zabbix#315]
##### SUMMARY
if running zabbix_server role, /tmp/snap.lxd directory removed. After that, `lxc file push` or` pull` will fail.

`apt-get clean` task was all /tmp/* files and directories.

https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_server/tasks/Debian.yml#L97

```yaml
- name: apt-get clean
    shell: apt-get clean; rm -rf /tmp/*; apt-get update
  args:
    warn: False
  changed_when: False
  become: yes
  tags:
    - skip_ansible_lint
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`zabbix_server` role

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.5
  config file = None
  configured module search path = ['/home/masakura/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/masakura/works/development-services/venv/lib/python3.6/site-packages/ansible
  executable location = /home/masakura/works/development-services/venv/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT / Zabbix Version

- OS: Ubuntu 18.04 (WSL)

##### STEPS TO REPRODUCE

```yaml
# playbook.yml
- hosts: all
  roles:
    - name: zabbix_server
      vars:
         # ....
```

Run the playbook.yml.

```
$ ls -lad /tmp/snap.lxd
drwx------ 2 root root 4096 Jan 22 13:14 /tmp/snap.lxd

$ ansible-playbook -i hosts playbook.yml

...

$ ls -lad /tmp/snap.lxd
ls: cannot access '/tmp/snap.lxd': No such file or directory
```

`/tmp/snap.lxd` was removed.

##### EXPECTED RESULTS

`/tmp/snap.lxd` is not remove.

##### ACTUAL RESULTS

`/tmp/snap.lxd` was removed.
