### ISSUE TITLE
[Error in zabbix_web role] php-fpm is configured although it will not install

### ISSUE THREAD

**Issue by santiagomr** [ansible-collections/community.zabbix#317]
##### SUMMARY

I'm running on a host with Debian 10 the [simple example playbook](https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_WEB_ROLE.md#single-instance) (zabbix_server + zabbix_web) and `zabbix_php_fpm` set to `False`. I get the following error:
```
TASK [community.zabbix.zabbix_web : Debian | Install PHP] ************************************************************************************************************************************
fatal: [buster.example.com]: FAILED! => {"changed": false, "checksum": "4f60b1764f73c490c7d3ca2136afbe3d585225df", "msg": "Destination directory /etc/php/7.4/fpm/pool.d does not exist"}
```

When analyzing the code of the role I detect that this task is executed considering only the `zabbix_vhost` variable in the conditional:
https://github.com/ansible-collections/community.zabbix/blob/2f8c3a4b9a00dcf2fb8156c210d90c0ea45655af/roles/zabbix_web/tasks/Debian.yml#L77

Am I misunderstanding something or in this conditional should the `zabbix_php_fpm` variable also be considered?
```yaml
- name: "Debian | Install PHP"
  template:
    src: php-fpm.conf.j2
    dest: "{{ zabbix_php_fpm_dir }}/zabbix.conf"
    owner: "{{ _apache_user }}"
    group: "{{ _apache_group }}"
    mode: 0644
  become: yes
  when:
    - zabbix_vhost
    - zabbix_php_fpm
  notify:
    - restart php-fpm-version
```

I added this variable locally and the role runs completely without errors and leaving me a functional Zabbix web frontend.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`zabbix_web` role

##### ANSIBLE VERSION
```
ansible 2.10.2
  config file = None
  configured module search path = ['/home/santiagomr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/santiagomr/.local/lib/python3.8/site-packages/ansible
  executable location = /home/santiagomr/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
# Empty output
```

##### OS / ENVIRONMENT / Zabbix Version
- Target OS: Debian Buster
- `zabbix_server_version: 5.0`
- `zabbix_web_version: 5.0`

##### STEPS TO REPRODUCE
```yaml
- hosts: zabbix-server
  become: yes
  roles:
    - role: geerlingguy.apache
    - role: community.zabbix.zabbix_server
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbport: 3306
      zabbix_server_version: 5.0
    - role: community.zabbix.zabbix_web
      zabbix_url: zabbix.mydomain.com
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbport: 3306
      zabbix_php_fpm: False
      zabbix_web_version: 5.0
```

##### EXPECTED RESULTS
Run without error

##### ACTUAL RESULTS
```
TASK [community.zabbix.zabbix_web : Debian | Install PHP] ************************************************************************************************************************************
fatal: [buster.example.com]: FAILED! => {"changed": false, "checksum": "4f60b1764f73c490c7d3ca2136afbe3d585225df", "msg": "Destination directory /etc/php/7.4/fpm/pool.d does not exist"}
```

**Comment by D3DeFi** [comment]
Can confirm from my side also. Worked around it like so:

```yaml
  pre_tasks:
    - name: Install php-fpm on the server
      apt:
        name: php-fpm
        state: present

  roles:
    - role: community.zabbix.zabbix_web
      ...
      zabbix_php_version: 7.2
      zabbix_php_fpm_dir: /etc/php/7.2/fpm/pool.d
```

Had to override php_version to 7.2 due to running on Ubuntu 18, which seems to be defaulting to this version instead of 7.3.
