### ISSUE TITLE
Discrepancy of variable name/description, and variable function.

### ISSUE THREAD

**Issue by igloo777** [ansible-collections/community.zabbix#318]
Hello! 

##### SUMMARY

https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/userparameter.yml 

Task "Installing user-defined scripts" - 

```
- name: "Installing user-defined scripts"
    copy:
      src: "{{ zabbix_agent_userparameters_scripts_src }}/{{ item.scripts_dir }}"
      dest: "/etc/zabbix/scripts/"
      owner: zabbix
      group: zabbix
      mode: 0755
    notify:
      - restart zabbix-agent
      - restart mac zabbix agent
    become: yes
    with_items: "{{ zabbix_agent_userparameters }}"
    when: item.scripts_dir is defined
```

**scripts_dir** there is ugly name of key, because it's actually script name.

But in README.md 
```
scripts_dir: Directory name of the custom scripts needed for userparameters
```

Is it should be something like **script_name**?

If i'm wrong - just close this report.

##### COMPONENT NAME
community.zabbix.zabbix_agent role
