### ISSUE TITLE
Use the MSI installer for windows agent installation

### ISSUE THREAD

**Issue by Park0** [ansible-collections/community.zabbix#319]
##### SUMMARY
Zabbix provides a MSI installer that also supports openssl. (The zip files has no openssl support)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Zabbix agent (windows)

##### ADDITIONAL INFORMATION

```yaml
   - role: community.zabbix.zabbix_agent
     zabbix_agent_server: zabbix.server.lan
     zabbix_url: http://zabbix.server.lan
     zabbix_api_use: false
     zabbix_win_install_dir: "{{ ansible_env.ProgramData }}\\Zabbix"
     zabbix_agent_win_logfile: "{{zabbix_win_install_dir}}\\zabbix_agentd.log"
     zabbix_agent_win_include: "{{zabbix_win_install_dir}}\\zabbix_agent.d\\"
     zabbix_agent_hostname: "{{ ansible_facts.fqdn }}"
     zabbix_agent_tlspskidentity: "{{ ansible_facts.fqdn }}"
     zabbix_agent_tlspsk_secret: 00002843c2fba8b31b43474e9f30d369524d2beb50000039bf8c831000000000
     zabbix_agent_tlspskfile: "{{zabbix_win_install_dir}}\\psk.key"
     zabbix_agent_tlsaccept: psk
```
