### ISSUE TITLE
module_defaults group for zabbix modules

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#326]
##### SUMMARY
It should be now possible for collections to somehow define [module_defaults for groups](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html#module-defaults-groups). E.g.:
```yaml
module_defaults:
  group/zabbix:
    server_url: http://zabbix
    login_user: Admin
    timeout: 15
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins/

##### ADDITIONAL INFORMATION
Additional reference:
https://github.com/ansible/ansible/pull/69919
https://github.com/ansible/ansible/pull/67291

**Comment by D3DeFi** [comment]
This unfortunately never made it into the ansible as a feature. So it is not possible yet

**Comment by ansiballz** [comment]
@D3DeFi Maybe it's a good idea to reopen this once since it's available from version 2.12?
> In ansible-core 2.12, collections can define their own groups in the meta/runtime.yml file. module_defaults does not take the collections keyword into account, so the fully qualified group name must be used for new groups in module_defaults.

Ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html

**Comment by D3DeFi** [comment]
Yees, but! :) We are migrating away from zabbix-api into httpapi. With 1.9 this would be released as opt-in, with 2.0 zabbix-api will be dropped altogether. 

I am not sure that defining `module_defaults` group for community.zabbix would be necessary anymore as shared connection parameters for httpapi are set only once I think.

@BGmot can you share your opinion here when you have a little bit of time to spare please?

**Comment by BGmot** [comment]
I am not sure I understand the request. `module_defaults` is used on tasks level, so everybody is free to use it with our collection. And we do use this 'feature' in our modules tests.

**Comment by D3DeFi** [comment]
> I am not sure I understand the request. `module_defaults` is used on tasks level, so everybody is free to use it with our collection. And we do use this 'feature' in our modules tests.

Normally, you have to specify module_defaults per module:
```yaml
  module_defaults:
    community.zabbix.zabbix_host:
      server_url: ...
      login_user: ...
      login_pass: ...

    community.zabbix.zabbix_groupt:
      server_url: ...
      login_user: ...
      login_pass: ...
```

But implementing this in collections runtime.yml would allow users to provide:
```yaml
module_defaults:
  group/zabbix:
    server_url: http://zabbix
    login_user: Admin
    timeout: 15
```

and it would be inherited by all modules in the collection.

However, I am not sure if we still have need for this as login credentials will be set only once for httpapi if I understand it correctly, so they don't have to be repeated for each module as it was with zabbix-api.

Except `validate_certs` and `timeout` we may not have much more options to share. 

Anyway, as I am looking at it. This only requires keeping list of modules in runtime.yml from our side, I think we should implement it:
```yaml
# collections/ansible_collections/ns/coll/meta/runtime.yml
action_groups:
  groupname:
    - module
    - another.collection.module
```

Re-opening the issue.

**Comment by BGmot** [comment]
How is it different from modules parameters defaults?

**Comment by ansiballz** [comment]
> Yees, but! :) We are migrating away from zabbix-api into httpapi. With 1.9 this would be released as opt-in, with 2.0 zabbix-api will be dropped altogether.
> 
> I am not sure that defining `module_defaults` group for community.zabbix would be necessary anymore as shared connection parameters for httpapi are set only once I think.

This is amazing! I come to the same conclusion when I read the documentation for the httpapi connection plugin.

> Anyway, as I am looking at it. This only requires keeping list of modules in runtime.yml from our side, I think we should implement it:

Thanks a lot, appreciate it!

**Comment by D3DeFi** [comment]
> How is it different from modules parameters defaults?

We have 20+ modules, lets ignore httpapi for a moment and pretend that we will be using 15 modules in our playbook, each multiple times. We know that there will be lot of code duplicity due to `server_url`, `login_password`, `login_user` and more. **Without group** `module_defaults`, this would be:

```yaml
- hosts: all
  module_defaults:
    community.zabbix.zabbix_host:
      server_url: ...
      login_user: ...
      login_pass: ...

    community.zabbix.zabbix_group:
      server_url: ...
      login_user: ...
      login_pass: ...

    community.zabbix.zabbix_action:
      server_url: ...
      login_user: ...
      login_pass: ...

    community.zabbix.zabbix_service:
      server_url: ...
      login_user: ...
      login_pass: ...

   ... and so on for each module ...

  tasks:
    ...
```

Now, **with group** `module_defaults`, the same playbook will look like this:

```yaml
- hosts: all
  module_defaults:
    group/community.zabbix.zabbix:
      server_url: ...
      login_user: ...
      login_pass: ...
  tasks:
    ...
```

That's it. Now back to the httpapi - I know it will deprecate some of the stuff, instead of specifying `server_url`, `login_password`, `login_user`, etc without need to provide them under each module call. However, I think users may still benefit from having group module_defaults for a smaller use cases than I presented. Maybe I am not able to bring up more elaborate use case, but never underestimate users of your code! :smile: 

This small example also comes to my mind:
```yaml
# roles/myrole/tasks/setup-zabbix-resources.yml
module_defaults:
  group/community.zabbix.zabbix:
    state: present

- set_fact:
    ...httpapi parameters...

- zabbix_host:
    ...

- zabbix_group:
    ...
```
