### ISSUE TITLE
include_tasks: apache.yml runs before installing apache

### ISSUE THREAD

**Issue by barazbay** [ansible-collections/community.zabbix#329]
##### SUMMARY

the issue is that role invokes apachectl without check if apache is installed

```yaml
---
- name: "Apache | Get Apache version"
  shell: |
    PATH=/usr/sbin:$PATH
    set -o pipefail
    apachectl -v | grep 'version' | awk -F '/' '{ print $2 }'| awk '{ print $1 }' | cut -c 1-3
  changed_when: False
  register: apachectl_version
  check_mode: no
  args:
    executable: /bin/bash
  tags:
    - zabbix-web

```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

role zabbix_web
##### ANSIBLE VERSION

ansible 2.10.5
  config file = /home/ikarazbaev/Documents/projects_git/proj-zabbix/ansible/ansible.cfg
  configured module search path = ['/home/ikarazbaev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ikarazbaev/anaconda3/lib/python3.7/site-packages/ansible
  executable location = /home/ikarazbaev/anaconda3/bin/ansible
  python version = 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

OL7.5

##### STEPS TO REPRODUCE

just run playbook against the host without apache preinstalled

```yaml
---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
  - community.zabbix.zabbix_web
```

##### EXPECTED RESULTS

Role must gather service facts first in order to check with apachectl

##### ACTUAL RESULTS

```paste below

```

**Comment by dj-wasabi** [comment]
Hi @barazbay 

You need to provide a role that make sure that Apache is installed on the host before you can make use of the `zabbix_web` role. Or use a Nginx role when you want to make use of Nginx.

So I am not sure why we need to validate that Apache is installed.

Kind regards,
Werner

**Comment by barazbay** [comment]
in order to install zabbix web we don't need to preinstall apache
https://www.zabbix.com/download?zabbix=5.2&os_distribution=centos&os_version=8&db=postgresql&ws=apache
we just need to run step B from the manual
` # dnf install zabbix-server-pgsql zabbix-web-pgsql zabbix-apache-conf zabbix-agent `
so, this step is done here
redhat.yml
```yaml
- name: "RedHat | Install zabbix-web (Zabbix 5.x)"
  yum:
    pkg:
      - zabbix-apache-conf-scl
    state: "{{ zabbix_web_package_state }}"
    update_cache: yes
    disablerepo: "{{ '*' if (zabbix_repo_yum_enabled | length>0) else omit }}"
    enablerepo: "{{ zabbix_repo_yum_enabled if zabbix_repo_yum_enabled is iterable and (zabbix_repo_yum_enabled | length>0) else omit }}"
  environment:
    http_proxy: "{{ zabbix_http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ zabbix_https_proxy | default(None) | default(omit) }}"
  register: zabbix_web_package_install
  until: zabbix_web_package_install is succeeded
  become: yes
  when:
    - zabbix_version is version('5.0', '>=')
    - ansible_distribution_major_version != '8'
    - zabbix_websrv == 'apache'
  tags:
    - zabbix-web
 ```
