### ISSUE TITLE
Template import for perf_counter

### ISSUE THREAD

**Issue by Nostro-Dcx** [ansible-collections/community.zabbix#331]
##### SUMMARY
When I use zabbix_template for an import I have an Error -32500.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 community.zabbix.zabbix_template

##### ANSIBLE VERSION
```
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```
/
```

##### OS / ENVIRONMENT / Zabbix Version
CentOS 8, docker AWX 17 Latest version. Zabbix 5.0.8

##### STEPS TO REPRODUCE
Error -32500: Application error., Cannot read XML: (9) PCDATA invalid Char value 2 [Line: 3035 | Column: 39]
The line is:
                    <key>perf_counter[\2\250]</key>
I tried with 
                    <key>perf_counter[&quot;\2\250&quot;]</key>
But it doesn't work either.
With an older version of the module it worked perfectly and I changed nothing to my System.xml file.

```yaml
- name: "Import Zabbix System Template"
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_password }}"
    template_xml: "{{ lookup('file', 'System.xml') }}"
    state: present
```

##### EXPECTED RESULTS
Template Imported

##### ACTUAL RESULTS

```
{"changed": false, "details": "('Error -32500: Application error., Cannot read XML: (9) PCDATA invalid Char value 2 [Line: 3035 | Column: 39]. while sending {\\.......................................
```
