### ISSUE TITLE
Unable to simply remove host from Zabbix via API

### ISSUE THREAD

**Issue by carceneaux** [ansible-collections/community.zabbix#332]
##### SUMMARY

I want to be able to remove a host from Zabbix. This needs to happen with no connection to the ansible host where Zabbix agent is installed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_agent

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /root/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/root/ansible.cfg) = ['timer']
DEFAULT_HOST_LIST(/root/ansible.cfg) = ['/root/ansible_hosts']
DEFAULT_LOG_PATH(/root/ansible.cfg) = /var/log/ansible.log
DEFAULT_VAULT_PASSWORD_FILE(/root/ansible.cfg) = /root/.ansible_vault
HOST_KEY_CHECKING(/root/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 4.0

##### STEPS TO REPRODUCE

Run the below playbook calling out the `api` tag:

ansible-playbook zabbix-host-removal.yml --tags api

```yaml
  - name: Removing host from Zabbix monitoring
    gather_facts: yes
    hosts: localhost
    roles:
    - role: community.zabbix.zabbix_agent
      vars:
        zabbix_agent_hostname: "test.vm.lab"
        zabbix_create_host: absent
        zabbix_agent_ip: 127.0.0.1
        zabbix_link_templates:
```

##### EXPECTED RESULTS

I expect the zabbix host specified in `zabbix_agent_hostname` to be removed from Zabbix.

##### ACTUAL RESULTS

As is, today, nothing happens. The playbook runs and skips through most actions and no changes are made.
