### ISSUE TITLE
Add dependency linking to zabbix_service module

### ISSUE THREAD

**Issue by amartin3225** [ansible-collections/community.zabbix#335]
##### SUMMARY
Add support for linking [dependencies](https://www.zabbix.com/documentation/current/manual/it_services#configuration) to a service in zabbix. This is similar to how `zabbix_host` supports the `link_templates` parameter which allows you to link a template to a host.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_service

##### ADDITIONAL INFORMATION
It would be very useful to have the `zabbix_service` module support linking dependencies. It looks like the Zabbix API supports this via the [service.adddependencies](https://www.zabbix.com/documentation/current/manual/api/reference/service/adddependencies), [service.deletedependencies](https://www.zabbix.com/documentation/current/manual/api/reference/service/deletedependencies), and [service.update](https://www.zabbix.com/documentation/current/manual/api/reference/service/update) methods. This would allow you to define a list of dependencies for a server in its ansible role and then update those automatically, much like how `link_templates` in `zabbix_host` works now:

```yaml
- name: Manage services
  local_action:
        module: community.zabbix.zabbix_service
        server_url: "https://192.168.1.1"
        login_user: username
        login_password: password
        name: apache2 service
        sla: 99.99
        calculate_sla: yes
        algorithm: one_child
        trigger_name: apache2 service status
        trigger_host: webserver01
        state: present
        link_dependencies:
          - other service 1
          - other service 2
          - other service 3
```

Thank you for considering this feature!
