### ISSUE TITLE
rm /tmp/* -fr remove default ssh-agent session (zabbix_server on Debian 10)

### ISSUE THREAD

**Issue by fozodlen** [ansible-collections/community.zabbix#341]
##### SUMMARY

When you simply use zabbix_server, on **apt-get clean** task in the [roles/zabbix_server/tasks/Debian.yml](Debian.yml) task file,  the /tmp is cleared. But if you deploy on localhost, it also remove you temporary ssh-agent folder (something like /tmp/ssh-blablabla). Therefore, no ssh-agent available after that ... 

##### ISSUE TYPE
- Issue ???

##### COMPONENT NAME
zabbix_server

##### ADDITIONAL INFORMATION
I solved it by remove the rm /tmp/* -fr command. I believe, it can be improved by only remove the apt related directories/files?

#### EXAMPLE PLAY

```yaml
- name: ZABBIX on coreservers
  hosts: coreservers
  become: true
  roles:
    - community.zabbix.zabbix_server
```

Thanks for this project, zabbix online in 47s (^^)
