### ISSUE TITLE
zabbix_user unable to reset password for the same user

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#384]
##### SUMMARY
zabbix_user module is unable to change password for the user when `login_password` and `alias` are set to the same user. This prevents user from changing default 'zabbix' password from Admin user.

This is caused by `type` directive, which is `required=True` in the module argspec. Although it is required for `user.create`, it is not needed for `user.update` ZabbixAPI call.

@sky-joker do you agree with this being a bug?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_user

##### ANSIBLE VERSION
```
community.zabbix 1.3.0
```

##### OS / ENVIRONMENT / Zabbix Version
Zabbix 5.0

##### STEPS TO REPRODUCE

I am trying to reset pw on Admin like this:

```yaml
    - name: Verify if Zabbix is using default password for Admin
      zabbix_user_info:
        server_url: '{{ zabbix_url }}'
        login_user: '{{ zabbix_user }}'
        login_password: zabbix
        alias: Admin
      failed_when: False
      register: _zbx_default_pw_used

    - name: Ensure Zabbix Admin uses proper password
      zabbix_user:
        server_url: '{{ zabbix_url }}'
        login_user: '{{ zabbix_user }}'
        login_password: zabbix
        alias: Admin
        usrgrps: '{{ _zbx_default_pw_used | community.general.json_query("zabbix_user.usrgrps[*].name") }}'  # reuse groups found on user
        #type: Zabbix super admin
        passwd: '{{ zabbix_pass }}'
        override_passwd: yes
      when:
        - "'zabbix_user' in _zbx_default_pw_used"
        - _zbx_default_pw_used.zabbix_user.userid == "1"
```

##### EXPECTED RESULTS

```changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "after_login_url": "",
            "alias": "Admin",
            "autologin": false,
            "autologout": "0",
            "http_login_password": null,
            "http_login_user": null,
            "lang": "en_GB",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "name": "",
            "override_passwd": true,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "refresh": "30",
            "role_name": "User role",
            "rows_per_page": "50",
            "server_url": "https://zabbix.local",
            "state": "present",
            "surname": "",
            "theme": "default",
            "timeout": 10,
            "timezone": "default",
            "type": "null",
            "user_medias": null,
            "usrgrps": [
                "Zabbix administrators"
            ],
            "validate_certs": true
        }
    },
    "user_ids": {
        "userids": [
            "1"
        ]
    }
}
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after_login_url": "",
            "alias": "Admin",
            "autologin": false,
            "autologout": "0",
            "http_login_password": null,
            "http_login_user": null,
            "lang": "en_GB",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "name": "",
            "override_passwd": true,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "refresh": "30",
            "role_name": "User role",
            "rows_per_page": "50",
            "server_url": "https://zabbix.local",
            "state": "present",
            "surname": "",
            "theme": "default",
            "timeout": 10,
            "timezone": "default",
            "type": "Zabbix super admin",
            "user_medias": null,
            "usrgrps": [
                "Zabbix administrators"
            ],
            "validate_certs": true
        }
    },
    "msg": "Failed to update user Admin: ('Error -32602: Invalid params., User cannot change their user type. while sending {\"jsonrpc\": \"2.0\", \"method\": \"user.update\", \"params\": {\"userid\": \"1\", \"alias\": \"Admin\", \"name\": \"\", \"surname\": \"\", \"usrgrps\": [{\"usrgrpid\": \"7\"}], \"lang\": \"en_GB\", \"theme\": \"default\", \"autologin\": \"0\", \"autologout\": \"0\", \"refresh\": \"30\", \"rows_per_page\": \"50\", \"url\": \"\", \"passwd\": \"********\", \"type\": \"3\"}, \"auth\": \"XXXX\", \"id\": 4}', -32602)"
}

```
