### ISSUE TITLE
zabbix_host is not idempotent when called with two or more interfaces

### ISSUE THREAD

**Issue by smarrk** [ansible-collections/community.zabbix#389]
##### SUMMARY

When creating a host that has two or more interfaces ansible always returns "changed".
This should have been fixed by #309 but i'm still experiencing this issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/modules/zabbix_host.py

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/home/foobar/test/ansible.cfg) = False
LOCALHOST_WARNING(env: ANSIBLE_LOCALHOST_WARNING) = False
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 5.0 and 5.2  
zabbix-api 0.5.4  
community.zabbix 1.3.0  
Python 3.9.5  

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - name: create hosts
      zabbix_host:
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_pass }}"
        host_name: "host001"
        host_groups: ["Linux servers"]
        interfaces:
          - type: "1"
            main: 1
            useip: 1
            ip: 127.0.0.1
          - type: "1"
            useip: 1
            ip: 127.0.1.1
```

##### EXPECTED RESULTS

Ansible should show "ok" instead of "changed" when running twice.

##### ACTUAL RESULTS

Ansible always shows "changed".

```paste below
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "description": null,
            "force": true,
            "host_groups": [
                "Linux servers"
            ],
            "host_name": "host001",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": [
                {
                    "details": {},
                    "dns": "",
                    "interfaceid": "6",
                    "ip": "127.0.0.1",
                    "main": 1,
                    "port": "10050",
                    "type": 1,
                    "useip": 1
                },
                {
                    "details": {},
                    "dns": "",
                    "interfaceid": "10",
                    "ip": "127.0.1.1",
                    "main": 0,
                    "port": "10050",
                    "type": 1,
                    "useip": 1
                }
            ],
            "inventory_mode": null,
            "inventory_zabbix": null,
            "ipmi_authtype": null,
            "ipmi_password": null,
            "ipmi_privilege": null,
            "ipmi_username": null,
            "link_templates": null,
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "macros": null,
            "proxy": null,
            "server_url": "http://DebianVM4/zabbix/",
            "state": "present",
            "status": "enabled",
            "tags": null,
            "timeout": 10,
            "tls_accept": 1,
            "tls_connect": 1,
            "tls_psk": null,
            "tls_psk_identity": null,
            "tls_subject": null,
            "validate_certs": true,
            "visible_name": null
        }
    },
    "result": "Successfully update host host001 (127.0.1.1) and linked with template 'None'"
}
```
