### ISSUE TITLE
zabbix_web: several apache variables are undefined when not using geerlingguy.apache

### ISSUE THREAD

**Issue by maxhoesel** [ansible-collections/community.zabbix#393]
##### SUMMARY
I'm trying to install a Zabbix server using both the zabbix_server and zabbix_web roles on a host, but the installation fails due to several Apache SSL-related variables being undefined (`apache_ssl_protocol` and `apache_ssl_cipher_suite` for example):

```
...
TASK [community.zabbix.zabbix_web : Debian | Install PHP] *********************************************************************************************************************************************************
ok: [zabbix-server.admin.mydomain.tld]

TASK [community.zabbix.zabbix_web : Including Apache Configuration] ***********************************************************************************************************************************************
included: /home/max/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_web/tasks/apache_Debian.yml for zabbix-server.admin..mydomain.tld

TASK [community.zabbix.zabbix_web : Debian | Install legacy PHP integration for Apache] ***************************************************************************************************************************
ok: [zabbix-server.admin..mydomain.tld]

TASK [community.zabbix.zabbix_web : Debian | install apache vhost] ************************************************************************************************************************************************
fatal: [zabbix-server.admin.mydomain.tld]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'apache_ssl_protocol' is undefined"}

PLAY RECAP ********************************************************************************************************************************************************************************************************
zabbix-server.admin.mydomain.tld : ok=86   changed=0    unreachable=0    failed=1    skipped=73   rescued=0    ignored=0 
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_web

##### ANSIBLE VERSION
```
ansible 2.10.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/max/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/max/.local/lib/python3.9/site-packages/ansible
  executable location = /home/max/.local/bin/ansible
  python version = 3.9.4 (default, Apr 20 2021, 15:51:38) [GCC 10.2.0]
```

##### CONFIGURATION
```
No changes
```

##### OS / ENVIRONMENT / Zabbix Version
- Target host: Ubuntu 20.04 LTS
- Zabbix Version: 5.0 LTS

##### STEPS TO REPRODUCE
Inventory (truncated to only show relevant variables):
```yaml
zabbix_server_version: "5.0"

zabbix_server_cert_dir: /etc/ssl/zabbix
zabbix_server_tlsconnect: cert
zabbix_server_tlsaccept: cert
zabbix_server_tlscafile: "{{ zabbix_server_cert_dir }}/ca.crt"
zabbix_server_tlscertfile: "{{ zabbix_server_cert_dir }}/zabbix.crt"
zabbix_server_tlskeyfile: "{{ zabbix_server_cert_dir }}/zabbix.key"

zabbix_web_version: "5.0"
zabbix_url: "{{ ansible_fqdn }}"
zabbix_timezone: Europe/Berlin

zabbix_apache_tls: yes
zabbix_apache_redirect: yes
zabbix_apache_tls_crt: "{{ zabbix_server_tlscertfile }}"
zabbix_apache_tls_key: "{{ zabbix_server_tlskeyfile }}"
```

Playbook:
```yaml
- hosts: zabbix_servers
  become: yes
  tasks:
    - name: Requirements are installed
      apt:
        name:
          - apache2
          - python3-pymysql
          - php-fpm
        state: present
    # tasks to create and install ssl certificates + zabbix_server
    # ...
    - name: Install Webhost
      include_role:
        name: community.zabbix.zabbix_web
```

##### EXPECTED RESULTS
The role completes its install sucessfully

##### ACTUAL RESULTS
The role install fails with the error message shown above.

Looking at the role, it seems like the the variables are not defined in the collection at all and are only referenced in the vhost template:

```
❯ pwd
/home/max/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_web
❯ grep -rn ./ -e "apache_ssl"
./templates/apache_vhost.conf.j2:106:  SSLCipherSuite {{ apache_ssl_cipher_suite }}
./templates/apache_vhost.conf.j2:107:  SSLProtocol {{ apache_ssl_protocol }}
```

I noticed that the missing variables seem to come from [geerlingguys apache role](https://github.com/geerlingguy/ansible-role-apache), which I don't use in my playbook. I couldn't find any mention of that role being an official requirement for zabbix_web though.

As a workaround, I've added the required variables to my inventory, which seems to fix the errors:
```yaml
apache_ssl_cipher_suite: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
apache_ssl_protocol: all -SSLv3 -TLSv1 -TLSv1.1
apache_vhosts_version: "2.4"
```

I'm not sure if the dependency on geerlingguy.apache is intentional here - if it is, then I think it should be referenced in the README. If not, then it might be a good idea to set a default for these variables instead.
