### ISSUE TITLE
Windows auto psk enable

### ISSUE THREAD

**Issue by BayramGrbz45** [ansible-collections/community.zabbix#396]
##### SUMMARY

- I wanted to enable psk for windows server.
- I tried using the psk auto-activation method for this process.

##### ISSUE TYPE
Unable to create required files for psk.

##### COMPONENT NAME

zabbix_agent

##### ANSIBLE VERSION

```paste below
2.10
```

##### CONFIGURATION

```paste below
zabbix_agent_tlsconnect: psk
zabbix_agent_tlsaccept: psk
zabbix_agent_tlspsk_auto: True
```

##### OS / ENVIRONMENT / Zabbix Version

5.2

##### STEPS TO REPRODUCE

```yaml
---
- hosts: zbx_agent_win:zbx_agent2_win
  roles:
    - role: community.zabbix.zabbix_agent

```

##### ACTUAL RESULTS

```paste below
  msg: The powershell shell family is incompatible with the sudo become plugin
```
