### ISSUE TITLE
remove.yml tasks don't work properly

### ISSUE THREAD

**Issue by fourstepper** [ansible-collections/community.zabbix#401]
The variable `zabbix_agent_service` used in the remove.yml tasks file will return and act upon the string `zabbix-agent2`, if the following variables are set as follows:
```
zabbix_agent2: true
zabbix_agent_package_remove: true
```

https://github.com/ansible-collections/community.zabbix/blob/0e94f2ef6329e5f3fcb3f7ecc18167fd050374b7/roles/zabbix_agent/tasks/remove.yml#L5

I believe this is not the intended behaviour - I suggest we set a fact for another variable, such as `old_zabbix_agent_service` in here: 

https://github.com/ansible-collections/community.zabbix/blob/0e94f2ef6329e5f3fcb3f7ecc18167fd050374b7/roles/zabbix_agent/tasks/main.yml#L4

and use that instead.

If you agree, I can send a PR. Alternatively, we could just hardcode the service name, too

EDIT: hardcoding the service name throws an error if the service is not defined at all, thus cannot be stopped.

**Comment by dj-wasabi** [comment]
Hi @fourstepper 

That makes sense. 👍 
Maybe the "remove.yml" should only be imported/executed if we have some logic that the role checks if the agent is installed. If it is installed, then I guess we can hardcode the service name right? (Or am I missing some other logic with this approach?)

**Comment by fourstepper** [comment]
I think we can either limit only the excution of stopping the agent service, or the whole remove.yml - I think the first method could be cleaner. This is how I would implement it:

```
---
- name: Pull service facts
  service_facts:

- name: "Remove | Make sure the \"old\" zabbix-agent service is running"
  service:
    name: "{{ zabbix_agent_service }}"
    state: stopped
    enabled: no
  become: yes
  when: |
    ansible_facts.services["zabbix-agent.service"] is defined or
    ansible_facts.services["zabbix-agent"] is defined

- name: "Remove | package removal"
  package:
    name: "zabbix-agent"
    state: absent
  become: yes

- name: "Remove | Remove the agent-include-dir"
  file:
    path: "{{ zabbix_agent_include  }}"
    state: absent
  become: yes
```

What do you think?
