### ISSUE TITLE
Add the ability to specify minor version release of Ansible agent/send/get

### ISSUE THREAD

**Issue by isuftin** [ansible-collections/community.zabbix#414]
##### SUMMARY
Need a way to specify the minor version of the Zabbix agent, sender and get packages. Currently, at least on RedHat, there's no way for a user to specify the installation of any Zabbix package that isn't the latest in the repository.

For example, I want to install 5.0.11 from https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/

Unfortunately, because of how the yum repositories are set up, I can't do this without also passing in the entire "zabbix_repo_yum" dict to the agent role.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Update variables that feed into the package module

##### ADDITIONAL INFORMATION
This works (Bento CentOS 7 VM):

```yaml
- name: Install agent
  include_role:
    name: community.zabbix.zabbix_agent
  vars:
    zabbix_agent_version: 5.0.11-1
    zabbix_agent2: True
    zabbix_version:  5.0
    zabbix_repo_yum:
      - name: zabbix
        description: Zabbix Official Repository - $basearch
        baseurl: "https://repo.zabbix.com/zabbix/5.0/rhel/7/$basearch/"
        mode: '0644'
        gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
        state: present
      - name: zabbix-non-supported
        description: Zabbix Official Repository non-supported - $basearch
        baseurl: "https://repo.zabbix.com/non-supported/rhel/7/$basearch/"
        mode: '0644'
        gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
        state: present
```

I would appreciate the ability to specify a fully qualified Zabbix version (5.0.11) instead of just 5.0 and having the role choose the latest.

The issue is because of the use of `zabbix_version` here - https://github.com/ansible-collections/community.zabbix/blob/1.4.0/roles/zabbix_agent/defaults/main.yml#L46 

So if I don't override `zabbix_repo_yum`, it tries to install the yum repo `https://repo.zabbix.com/zabbix/5.0.11/rhel/7/x86_64/`
 which is not a thing
