### ISSUE TITLE
[role-zabbix-agent] No deployment of zabbix agent 2 possible for Windows systems

### ISSUE THREAD

**Issue by david-sieg** [ansible-collections/community.zabbix#432]
##### SUMMARY

No deployment of zabbix agent2 possible, because of wrong path to zabbix_agent2.exe which is set in task.
There are some other permanent paths used by other tasks.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

role-zabbix-agent

Zabbix agent 2 rollout

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.13
  config file = /tmp/awx_33992_f7skrqso/project/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### OS / ENVIRONMENT / Zabbix Version

Windows Server 2016

##### STEPS TO REPRODUCE

```yaml
---
- hosts: windows_host
  become: no
  collections:
    - community.zabbix

  tasks:

   - name: Include role role-zabbix-agent
      include_role:
        name: community.zabbix.zabbix_agent
...

```

##### EXPECTED RESULTS

Zabbix agent 2 should be deployable as discribed in documentation.

##### ACTUAL RESULTS

{
    "changed": false,
    "cmd": "\"C:\\Program Files\\Zabbix Agent\\\\bin\\zabbix_agentd.exe\" --config \"C:\\Program Files\\Zabbix Agent\\\\zabbix_agentd.conf\" --install",
    "msg": "Exception calling \"SearchPath\" with \"1\" argument(s): \"Could not find file 'C:\\Program Files\\Zabbix Agent\\\\bin\\zabbix_agentd.exe'.\"",
    "rc": 2,
    "_ansible_no_log": false
}

```paste below

```
