### ISSUE TITLE
About the module name in the Example block

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#44]
##### SUMMARY

The module name of the example block of existing modules is not FQCN.  
I think I should change the module name to FQCN.

For example, before

```yaml
- name: Get Zabbix template as JSON
  zabbix_template_info:
(snip)
```

after

```
- name: Get Zabbix template as JSON
  community.zabbix.zabbix_template_info:
(snip)
```

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```
