### ISSUE TITLE
Have error with privellege

### ISSUE THREAD

**Issue by HenryAndry** [ansible-collections/community.zabbix#440]
Have error with permisiions dont understand why? Can somemone help if meet similar error before) Thank you! 
![erore](https://user-images.githubusercontent.com/16820171/129355769-1f43b9bb-17dc-4fa4-930c-77b7240d183b.png)

**Comment by D3DeFi** [comment]
Hello @HenryAndry, it is very hard to deduce just from the following error and no additional information.

First of all, I believe this is not related to the Zabbix community per see, but something is missing on the host where you are trying to install Zabbix itself and `become` doesn't work for you. 

From the quick googling around I've found that you may be missing a sudo on the managed system - https://github.com/georchestra/ansible/issues/55

or an ACL package is missing:
https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary

Perhaps you can even try to replicate this by running something as simple as:

```yaml
- hosts: myhost
  user: myuser
  become: True
  become_method: sudo
  become_user: root
  tasks:
    - command:
        cmd: whoami
```

and try to debug further from there.
