### ISSUE TITLE
Agent role error on windows when running the role second time

### ISSUE THREAD

**Issue by ChaotX** [ansible-collections/community.zabbix#441]
##### SUMMARY
Error occurre when running zabbix_agent role on a windows second time

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent

##### ANSIBLE VERSION
```
ansible 2.9.10
```

##### OS / ENVIRONMENT / Zabbix Version
target os: Windows server 2019

##### STEPS TO REPRODUCE

requirement.yml
```
collections:
- name: community.general
  version: "3.5.0"
- name: community.zabbix
  version: '1.4.0'
```

```
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_package_state: present
      zabbix_agent_server: '192.168.20.112'
      zabbix_agent_serveractive: '192.168.20.112'
      zabbix_version_long: '5.4.3'
```

##### EXPECTED RESULTS
The play on second run should finish with no change

##### ACTUAL RESULTS
Error 

```
TASK [community.zabbix.zabbix_agent : Windows | Set service startup mode to auto and ensure it is started] *****************************************************************************************
task path: /mnt/c/.../ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Windows.yml:161
Using module file /home/.../.local/lib/python3.6/site-packages/ansible/modules/windows/win_service.ps1
Pipelining is enabled.
<some_win_host> ESTABLISH WINRM CONNECTION FOR USER: XXXX on PORT 5985 TO some_win_host
EXEC (via pipeline wrapper)
fatal: [some_win_host]: FAILED! => {
    "changed": false,
    "exists": false,
    "msg": "Service 'Zabbix Agent' is not installed, need to set 'path' to create a new service"
}
```
