### ISSUE TITLE
Zabbix 5.4 template import fails with "Template already exists"

### ISSUE THREAD

**Issue by nerijus** [ansible-collections/community.zabbix#449]
Using community.zabbix 1.4.0, zabbix 5.4.4.
Similar issue as https://github.com/ansible-collections/community.zabbix/pull/407#issuecomment-868505133 - while trying to import a template, I get:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: zabbix_api.Already_Exists: ('Error -32602: Invalid params., Template "check dev-games-backend.example.com_v1_ab-kiron-vf_version HIGH" already exists.
```
How do I overwrite existing template without deleting it first?
The playbook code is like this:
```
- name: Import {{ item.vhost }} zabbix service health-checks template
  local_action:
    module: zabbix_template
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_server_user }}"
    login_password: "{{ zabbix_server_password }}"
    template_groups: "nginx-common"
    template_json: "{{ lookup('template', 'zabbix_proxy_service_health_check.json.j2') }}"
    state: present
  vars:
    checks: "{{ item.proxy_config.include_services | dict2items | map(attribute='value') | flatten | map(attribute='zabbix_healthcheck') | select('defined') | rejectattr('path', 'eq', 'SKIP') }}"
  when: item.proxy_config.include_services | dict2items | map(attribute='value') | flatten | map(attribute='zabbix_healthcheck') | select('defined') | rejectattr('path', 'eq', 'SKIP') |  length > 0
```
