### ISSUE TITLE
send_to_users of zabbix_action module is not working on zabbix 5.4

### ISSUE THREAD

**Issue by miettal** [ansible-collections/community.zabbix#468]
##### SUMMARY

I used zabbix_action module on zabbix 5.4.
but argument send_to_users is not working.

because I set "admin" user on argument, but actually "guest" is setted.

probably, the reason is alias attribution of "user" is obsoluted from zbx 5.4. and "username" attribution is appeared from zbx 5.4,
I think change this , will be resoved.

https://www.zabbix.com/documentation/current/manual/api/reference/user/get

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_action

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.4]
  config file = None
  configured module search path = ['/Users/taisyo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/taisyo/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/taisyo/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/taisyo/.pyenv/versions/3.9-dev/bin/ansible
  python version = 3.9.6+ (heads/3.9:7ef0673, Aug 21 2021, 14:13:55) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 2.11.3
  libyaml = False
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/Users/taisyo/repository/xxx/ansible/ansible.cfg) = ['/Users/taisyo/repository/xxx/ansible/galaxy_collections']
DEFAULT_FORKS(/Users/taisyo/repository/xxx/ansible/ansible.cfg) = 64
DEFAULT_GATHERING(/Users/taisyo/repository/xxx/ansible/ansible.cfg) = smart
DEFAULT_REMOTE_USER(/Users/taisyo/repository/xxx/ansible/ansible.cfg) = ubuntu
DEFAULT_ROLES_PATH(/Users/taisyo/repository/xxx/ansible/ansible.cfg) = ['/Users/taisyo/repository/xxx/ansible/galaxy_roles']
DEFAULT_TIMEOUT(/Users/taisyo/repository/xxx/ansible/ansible.cfg) = 60
HOST_KEY_CHECKING(/Users/taisyo/repository/xxxansible/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/taisyo/repository/xxx/ansible/ansible.cfg) = /usr/bin/python
```

##### OS / ENVIRONMENT / Zabbix Version

Ubuntu 20.04 arm64, zabbix 5.4.5

##### STEPS TO REPRODUCE

```yaml
      - name: "All -> Slack"
        zabbix_action:
          name: "All -> Slack"
          event_source: 'trigger'
          esc_period: 60s
          operations:
            - type: send_message
              media_type: 'Slack'
              send_to_users:
                - 'Admin'
          acknowledge_operations:
            - type: send_message
              media_type: 'Slack'
              send_to_users:
                - 'Admin'
          recovery_operations:
            - type: send_message
              media_type: 'Slack'
              send_to_users:
                - 'Admin'
        delegate_to: localhost
        become: no
```

##### EXPECTED RESULTS

the user is set to "Admin"

##### ACTUAL RESULTS

the user is set to "guest"

```paste below

```
