### ISSUE TITLE
--skip-tags="always"

### ISSUE THREAD

**Issue by emper0r** [ansible-collections/community.zabbix#473]
##### SUMMARY
Hi we are using the module and works fine... is just this kind option we are getting some issue.

##### ISSUE TYPE
in our deployment we use a playbook where load many others groups of playbooks... and we need to add by force this 
'  --skip-tags="always"  ' on runtime when we not deploy zabbix ... and if we need to config zabbix for some server then remove it to can use module correctly with our variables, otherwise the other playbook when ansible load zabbix module get error trying to install zabbix on hosts and of course playbooks ends failed

##### COMPONENT NAME
zabbix-agent from community.zabbix      1.3.0

##### ANSIBLE VERSION
```
ansible 4.3.0
```

##### CONFIGURATION

```
COLLECTIONS_PATHS(/home/emper0r/ansible/ansible.cfg) = ['/home/emper0r/ansible/collections']
DEFAULT_HOST_LIST(/home/emper0r/ansible/ansible.cfg) = ['/home/emper0r/ansible/inventories/devel>
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/emper0r/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
HOST_KEY_CHECKING(/home/emper0r/ansible/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

```yaml
- name: import aws config (infra)
  import_playbook: aws_devel.yml
  tags: [ infra ]

- name: import aws config (zabbix agent)
  import_playbook: aws_devel_zabbix.yml
  tags: [ zabbix_agent ]


ansible-playbook -u root main_playbook.yml --limit="host_without_zabbix_agent" --tags="infra" --skip-tags="always"  
ansible-playbook -u root main_playbook.yml --limit="host_with_zabbix_agent"
```

##### EXPECTED RESULTS
No use on runtime  '  --skip-tags="always"  ' 

##### ACTUAL RESULTS
Trying to install zabbix-agent into all hosts where isn't zabbix agent configured.

```paste below

```
