### ISSUE TITLE
Find better way to handle signing keys for Zabbix

### ISSUE THREAD

**Issue by dj-wasabi** [ansible-collections/community.zabbix#511]
##### SUMMARY

Each role has a `zabbix.yml` file in the `vars/` directory containing the version of Zabbix, the name of the OS and the signing key. It not maintainance friendly to update the file with new OS's with signing keys and maintain them over de 5 roles. Something smarter should either be used, or ....

##### ISSUE TYPE
- Feature Idea

**Comment by dj-wasabi** [comment]
If someone is interested in picking this up, please let me know and I will assign it to you. This also means that people see that there is someone working on it. 👍

**Comment by dopice** [comment]
I've been looking and thinking about about this and maybe I can help out with this. I do have a couple of questions that we maybe can answer together on why and how we would like to proceed.

1. Is there a reason why we import the signing keys for Debian based distributions but not for Enterprise Linux (EL) based? In the defaults/main.yml we have `zabbix_repo_yum_gpgcheck` set to `0` which disable the GPG check.
2. What is the benefit of specifying the ID when importing the key? If we import the whole chain we don't need to manage the list of IDs per distribution.

Overall I think the repo installation could be done easier where we don't need to keep track of too much information. E.g. for Debian based:
```yaml
- name: Ensure Zabbix signing key is trusted
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Ensure Zabbix repository is present
  apt:
    deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+ubuntu{{ ansible_distribution_version }}_all.deb"
    state: present
```
The second task is a bit messy but we could keep a list of the different repository packages if that is preferred.
