### ISSUE TITLE
Role Zabbix Agent (linux): do not create PSK directory and file on false-ish key file value

### ISSUE THREAD

**Issue by shk3bq4d** [ansible-collections/community.zabbix#515]
##### SUMMARY

At the moment, the only way to not create the passive linux agent PSK key file is to have variable zabbix_agent2_tlspskfile left undefined.

This is sometimes a difficult requirement when inventory is complex.

My case: I'd like to set a default value in group_vars/all.yml and override this in other group_vars, however having the default value in group_vars gives me no way to reset it to undefined (as far as my ansible knowledge goes).

P.S.:
The templating of the conf file already has the logic to ignore defined yet fals'ish value

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_agent (role)

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by shk3bq4d** [comment]
https://github.com/shk3bq4d/community.zabbix/commit/44016f6dc570b289a01faec30dc82a26060b3500 would satisfy my feature request

**Comment by benaryorg** [comment]
Does setting the `zabbix_agent2_tlspskfile` to *null* explicitly in YAML (within the `host_vars` for instance) solve your problem?

```yaml
# explicit null
zabbix_agent2_tlspskfile: null
# null syntax sugar
zabbix_agent2_tlspskfile: ~
# implicit null
zabbix_agent2_tlspskfile:
```
