### ISSUE TITLE
set_fact error in 1.5.0 with new syntaxe 

### ISSUE THREAD

**Issue by But4ler** [ansible-collections/community.zabbix#516]
##### SUMMARY
Hello
Since the switch to ansible 1.5.0, host creation fails when creating a new TLS PSK

##### ISSUE TYPE
- Bug Report

- commit bug: https://github.com/ansible-collections/community.zabbix/commit/623cc606023304ca05c5e44ac69aaa5e6e8cd193

##### COMPONENT NAME
zabbix_agent
https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/tlspsk_auto_agent2.yml#L48

Task name: community.zabbix.zabbix_agent : AutoPSK | Generate new TLS PSK identity

##### ANSIBLE VERSION
```
ansible --version
ansible [core 2.11.6] 
  config file = /home/mrkw3241/work/infra-build/ansible.cfg
  configured module search path = ['/home/mrkw3241/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mrkw3241/virtenv/infra-build/lib/python3.9/site-packages/ansible
  ansible collection location = /home/mrkw3241/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mrkw3241/virtenv/infra-build/bin/ansible
  python version = 3.9.6 (default, Aug 25 2021, 18:50:24) [GCC 7.5.0]
  jinja version = 3.0.2
  libyaml = True

```

##### CONFIGURATION
no special change

##### OS / ENVIRONMENT / Zabbix Version
Zabbix agent 5.2

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    zabbix_agent_visible_hostname: "{{ inventory_hostname }}"
    zabbix_agent2: true
    zabbix_agent2_hostname: "{{ inventory_hostname }}"
    zabbix_agent_hostname: "{{ inventory_hostname }}"

  tasks:
    - name: AutoPSK | Generate new TLS PSK identity
      set_fact:
        zabbix_agent2_tlspskidentity: >
          {{
            zabbix_agent_visible_hostname
            | ((zabbix_agent2 == True) | default(ternary(zabbix_agent2_hostname, zabbix_agent_hostname)))
            + '_'
            + lookup('password', '/dev/null chars=hexdigits length=4')
          }}
```

##### ACTUAL RESULTS

```
fatal: [agent-bldl-prp.toto.net]: FAILED! => {
    "msg": "template error while templating string: expected token 'name', got '('. String: {{\n  zabbix_agent_visible_hostname\n  | ((zabbix_agent2 == True) | default(ternary(zabbix_agent2_hostname, zabbix_agent_hostname)))\n  + '_'\n  + lookup('password', '/dev/null chars=hexdigits length=4')\n}}\n"
}

```

Fix:
rollback to
```
      set_fact:
        zabbix_agent2_tlspskidentity: >
            zabbix_agent_visible_hostname
            | ((zabbix_agent2 == True) | default(ternary(zabbix_agent2_hostname, zabbix_agent_hostname)))
            + '_'
            + lookup('password', '/dev/null chars=hexdigits length=4')
```

Thanks !
