### ISSUE TITLE
Error with vars when generating PSK files for windows

### ISSUE THREAD

**Issue by doyl54** [ansible-collections/community.zabbix#530]
##### SUMMARY
When you install agent version 2 on windows the secret file is not created because the when condition is never filled (he is waiting for agent version 1's vars and not the agent version 2)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
PSK setting up on Windows

##### ANSIBLE VERSION

```
ansible [core 2.11.6] 
  config file = /home/xxxx/XXXX/ansible.cfg
  configured module search path = ['/home/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxxx/virtenv/XXXX/lib/python3.8/site-packages/ansible
  ansible collection location = /home/xxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxxx/virtenv/XXXX/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### CONFIGURATION

```
ansible-config dump --only-changed
CACHE_PLUGIN(/home/xxxx/infra-build/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/xxxx/infra-build/ansible.cfg) = .ansible_fact_cache
CACHE_PLUGIN_TIMEOUT(/home/xxxx/infra-build/ansible.cfg) = 7200
CALLBACKS_ENABLED(/home/xxxx/infra-build/ansible.cfg) = ['ansible.posix.profile_roles', 'ansible.posix.profile_tasks']
DEFAULT_GATHERING(/home/xxxx/infra-build/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/xxxx/infra-build/ansible.cfg) = ['/home/xxxx/infra-build/inventory']
DEFAULT_ROLES_PATH(/home/xxxx/infra-build/ansible.cfg) = ['/home/xxxx/infra-build/roles']
DIFF_ALWAYS(/home/xxxx/infra-build/ansible.cfg) = True
HOST_KEY_CHECKING(/home/xxxx/infra-build/ansible.cfg) = False
INTERPRETER_PYTHON(/home/xxxx/infra-build/ansible.cfg) = auto
INVENTORY_IGNORE_EXTS(/home/xxxx/infra-build/ansible.cfg) = ['.vhost']
RETRY_FILES_ENABLED(/home/xxxx/infra-build/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix agent 5.4.*

##### STEPS TO REPRODUCE

```
Installing an agent with the role and PSK encryption on

########### Windows_conf.yml
- name: "Windows | Place TLS-PSK file"
  ansible.windows.win_copy:
    content: "{{ zabbix_agent2_tlspsk_secret }}"
    dest: "{{ zabbix_agent2_tlspskfile }}"
  when:
    - zabbix_agent_tlspskfile is defined
    - zabbix_agent_tlspsk_secret is defined
  notify: restart win zabbix agent


I FIXED IT LIKE THIS
- name: "Windows | Place TLS-PSK file"
  ansible.windows.win_copy:
    content: "{{ zabbix_agent2_tlspsk_secret }}"
    dest: "{{ zabbix_agent2_tlspskfile }}"
  when:
    - zabbix_agent2_tlspskfile is defined
    - zabbix_agent2_tlspsk_secret is defined
  notify: restart win zabbix agent

But this is not a long term fix for a communatary role
```

##### EXPECTED RESULTS
secret file stored on install directory

##### ACTUAL RESULTS
nothing is stored because it awaits an agentv1 vars
