### ISSUE TITLE
AutoTLSPSK configuration is broken

### ISSUE THREAD

**Issue by ragingpastry** [ansible-collections/community.zabbix#533]
##### SUMMARY
https://github.com/ansible-collections/community.zabbix/pull/495 has broken autotlspsk configuration for the role

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/tlspsk_auto.yml#L48-L58

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/home/crepe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/crepe/venv/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /home/crepe/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/crepe/venv/ansible/bin/ansible
  python version = 3.9.6 (default, Jun 28 2021, 08:57:49) [GCC 10.3.0]
  jinja version = 3.0.2
  libyaml = True
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT / Zabbix Version
N/A

##### STEPS TO REPRODUCE
Run the role with the following parameters defined
```
zabbix_agent_tlsaccept: psk
zabbix_agent_tlsconnect: psk
zabbix_agent_tlspsk_auto: True
```

OR run this playbook. Reference his to see where I got this from: https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/tlspsk_auto.yml#L48-L58

```yaml
---
- name: Test
  hosts: localhost
  connection: local
  vars:
    zabbix_agent_hostname: "{{ inventory_hostname }}"
    zabbix_agent_visible_hostname: "{{ inventory_hostname }}"
    zabbix_agent2: True
    zabbix_agent2_hostname: "{{ inventory_hostname }}"
  tasks:
    - name: AutoPSK | Generate new TLS PSK identity
      set_fact:
        zabbix_agent_tlspskidentity: >
          {{
            zabbix_agent_visible_hostname
            | ((zabbix_agent2 == True) | default(ternary(zabbix_agent2_hostname, zabbix_agent_hostname)))
            + '_'
            + lookup('password', '/dev/null chars=hexdigits length=4')
          }}
    - debug:
        msg: "{{ zabbix_agent_tlspskidentity }}"
```

##### EXPECTED RESULTS
TLS PSK is configured correctly

##### ACTUAL RESULTS
The role fails to run with the following error
```
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: expected token 'name', got '('. String: {{ \n  zabbix_visible_hostname\n  | ((zabbix_agent2 == true ) | default(ternary(zabbix_agent2_hostname, zabbix_agent_hostname)))\n  + '_'\n  + lookup('password', '/dev/null chars=hexdigits length=4')\n}}\n"}
```

I have submitted a merge request which fixes this issue: #534 

Also I would suggest a version be released so that my team can pin to that version
