### ISSUE TITLE
zabbix_user module requires a password on "disabled" authentication types

### ISSUE THREAD

**Issue by ragingpastry** [ansible-collections/community.zabbix#542]
##### SUMMARY
Currently the zabbix_user Ansible module will require a password to be set on any new user that is a member of a usergroup using any authentication type other than "LDAP". I believe it should be required for "internal" authentication types only

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_user module

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT / Zabbix Version
N/A

##### STEPS TO REPRODUCE

```yaml
- name: Create ReadOnly UserGroup
   community.zabbix.zabbix_usergroup:
       server_url: "{{ vars_server_url }}"
        login_user: Admin
        login_password: "{{ vars_zabbix_password }}"
        name: ReadOnly
        gui_access: disable
        rights: "{{ hostgroup_rights }}"
        validate_certs: False
        state: present

      - name: Create zabbix users
        community.zabbix.zabbix_user:
          server_url: "{{ vars_server_url }}"
          login_user: Admin
          login_password: "{{ vars_zabbix_password }}"
          alias: "opsgenie"
          name: "opsgenie"
          validate_certs: False
          usrgrps: "ReadOnly"
          state: present
          type: "Zabbix user"
```

##### EXPECTED RESULTS
The user can be created without a password because the authentication type for the usergroup is set to "disabled"

##### ACTUAL RESULTS
The password is required because "disabled" is not "LDAP" authentication type
