### ISSUE TITLE
introduce string representations for zabbix_host parameters

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#544]
##### SUMMARY
tl;dr instead of having
```
...
- zabbix_host:
    tls_accept: 1
    tls_connect: 1
    interfaces:
      - main: 1
        useip: 0
...
```

It would be much prettier to have:

...
- zabbix_host:
    tls_accept: certificate
    tls_connect: PSK
    interfaces:
      - main: true
        useip: false
...
```

But this needs to be introduced in a way that will NOT break backwards compatibility as everyone is using those integers currently.

For example, zabbix_proxy plugin has some values like this already (for example tls_accept). 

And there may be more modules that will needs this adjustment.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins/modules/zabbix_host.py
maybe others
