### ISSUE TITLE
zabbix_agent_tlspsk_auto usage not documented

### ISSUE THREAD

**Issue by juresaht2** [ansible-collections/community.zabbix#547]
##### SUMMARY

The usage of the variable `zabbix_agent_tlspsk_auto` is not documented beyond simply mentioning that it exists.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix-agent role

##### ADDITIONAL INFORMATION

The following was determined by reading the source code:

`zabbix_agent_tlspsk_auto` is false by default. If set to true and if `zabbix_agent_tlspskfile` and `zabbix_agent_tlspsk_secret` are undefined, it generates the files `/etc/zabbix/tls_psk_auto.identity` and `/etc/zabbix/tls_psk_auto.secret`, which are populated by values automatically (identity is set to hostname, underscore and 4 random alphanumeric digits; secret is 64 random alphanumeric digits) in such a way that the values are generated once and are never overwritten.

The results are stored in the Ansible variables `zabbix_agent_tlspskidentity` and `zabbix_agent_tlspsk_secret`, so that they may be used later in the code, for example with [zabbix_host](https://docs.ansible.com/ansible/2.10/collections/community/zabbix/zabbix_host_module.html) to configure the Zabbix server or with `debug: msg:` to display them to the user.

Example configuration:
```yaml
zabbix_agent_tlsaccept: psk
zabbix_agent_tlsconnect: psk
zabbix_agent_tlspsk_auto: yes
#zabbix_agent_tlspskfile / zabbix_agent_tlspsk_secret must not be set for this to work
```

Hopefully this issue will do as a google hit until proper documentation for this exists.
