### ISSUE TITLE
Zabbix-agent AutoPSK fails with a syntax error

### ISSUE THREAD

**Issue by juresaht2** [ansible-collections/community.zabbix#549]
##### SUMMARY

AutoPSK fails with a syntax error if `zabbix_agent_visible_hostname` is not defined.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix-agent role

##### ANSIBLE VERSION

```paste below
ansible 2.10.6
  config file = /home/username/.ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/home/username/.ansible.cfg) = memcached
DEFAULT_GATHERING(/home/username/.ansible.cfg) = smart
```

##### OS / ENVIRONMENT / Zabbix Version

CentOS 8 Stream

##### STEPS TO REPRODUCE

Install Zabbix Agent with parameters:

```yaml
zabbix_agent_tlsaccept: psk
zabbix_agent_tlsconnect: psk
zabbix_agent_tlspsk_auto: yes

zabbix_agent_server: "192.168.1.2"
zabbix_agent_serveractive: "{{ zabbix_agent_server }}"
zabbix_agent_version: 5.0
```

Minimal variables are configured, so parameters not mentioned here are not set.

##### EXPECTED RESULTS

Role to execute without errors and generate the PSK key and identity (based on hostname).

##### ACTUAL RESULTS

```yaml
fatal: [host.test.local]: FAILED! =>
  msg: |-
    template error while templating string: expected token 'name', got '('. String: {{
      zabbix_agent_visible_hostname
      | ((zabbix_agent2 == True) | default(ternary(zabbix_agent2_hostname, zabbix_agent_hostname)))
      + '_'
      + lookup('password', '/dev/null chars=hexdigits length=4')
    }}
```
