### ISSUE TITLE
zabbix_template unlink templates when configure macros

### ISSUE THREAD

**Issue by mit0223** [ansible-collections/community.zabbix#563]
##### SUMMARY
zabbix_template unlink templates when configure macros on the existing Zabbix template without link_templates parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_template

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/Users/mitsuru/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mitsuru/.pyenv/versions/3.9.5/envs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/mitsuru/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/mitsuru/.pyenv/versions/ansible/bin/ansible
  python version = 3.9.5 (default, Jun  7 2021, 21:55:20) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION
default configuration

##### OS / ENVIRONMENT / Zabbix Version
OS: Mac OS Monterey 12.0.1
docker desktop: version 4.0.1

```
$ ansible-galaxy collection list

# /Users/mitsuru/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 2.0.1  
community.zabbix 1.5.1  

$ pip list | grep zabbix
zabbix-api   0.5.4

$ docker-compose exec zabbix-server zabbix_server --version
zabbix_server (Zabbix) 5.4.8
Revision 65b505c 29 November 2021, compilation time: Nov 30 2021 13:13:37

Copyright (C) 2021 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1l  24 Aug 2021
Running with OpenSSL 1.1.1l  24 Aug 2021
```

###### 1. put files
docker-compose.yml:
```
version: "3.4"
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_ROOT_PASSWORD: "zabbix"
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    ports:
      - "10051:10051"
  zabbix-db:
    image: mariadb:10.4
    container_name: zabbix-db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "zabbix"
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    command:
    - "--character-set-server=utf8mb3"
    - "--collation-server=utf8mb3_unicode_ci"
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/
    hostname: mariadb
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest 
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_ROOT_PASSWORD: "zabbix"
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    ports:
      - "10052:8080"

volumes:
  data:
  config:
```

set-macro.yml :
```yaml
- hosts: localhost
  tasks:
  - name: Configure macros on the Linux by Zabbix agent
    zabbix_template:
      server_url: http://localhost:10052
      login_user: admin
      login_password: zabbix
      template_name: Linux by Zabbix agent
      macros:
        - macro: '{$VFS.FS.FSNAME.NOT_MATCHES}'
          value: ^(/dev|/sys|/run|/proc|.+/shm$|/var/lib/docker)
      state: present
```

###### 2. start servers
```
docker-compose up -d
```
wait few minutes for database is setup.

###### 3. check links for 'Linux by Zabbix agent'
```
$ docker-compose exec zabbix-server /bin/ash
/var/lib/zabbix $ mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h $DB_SERVER_HOST $MYSQL_DATABASE
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 16
Server version: 10.4.20-MariaDB-1:10.4.20+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [zabbix]> select * from hosts_templates where hostid = 10001;
+----------------+--------+------------+
| hosttemplateid | hostid | templateid |
+----------------+--------+------------+
|              4 |  10001 |      10050 |
|            248 |  10001 |      10272 |
|            250 |  10001 |      10273 |
|            252 |  10001 |      10274 |
|            249 |  10001 |      10275 |
|            253 |  10001 |      10276 |
|            251 |  10001 |      10277 |
+----------------+--------+------------+
7 rows in set (0.001 sec)

MariaDB [zabbix]> quit
Bye
/var/lib/zabbix $ exit
```

###### 4. execute playbook
```
$ ansible-playbook set-macro.yml 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [Configure macros on the Linux by Zabbix agent] *********************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

###### 5. re-check links for 'Linux by Zabbix agent'
```
$ docker-compose exec zabbix-server /bin/ash
/var/lib/zabbix $ mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h $DB_SERVER_HOST $MYSQL_DATABASE
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 16
Server version: 10.4.20-MariaDB-1:10.4.20+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [zabbix]> select * from hosts_templates where hostid = 10001;
Empty set (0.001 sec)

MariaDB [zabbix]> quit
Bye
/var/lib/zabbix $ exit
```

##### EXPECTED RESULTS

Template links should remain if no link_templates parameter is specified.

```
MariaDB [zabbix]> select * from hosts_templates where hostid = 10001;
+----------------+--------+------------+
| hosttemplateid | hostid | templateid |
+----------------+--------+------------+
|              4 |  10001 |      10050 |
|            248 |  10001 |      10272 |
|            250 |  10001 |      10273 |
|            252 |  10001 |      10274 |
|            249 |  10001 |      10275 |
|            253 |  10001 |      10276 |
|            251 |  10001 |      10277 |
+----------------+--------+------------+
```

##### ACTUAL RESULTS
Template links removed.

```paste below
MariaDB [zabbix]> select * from hosts_templates where hostid = 10001;
Empty set (0.001 sec)
```
