### ISSUE TITLE
Add Slack zabbix_mediatype - Zabbix 6.0

### ISSUE THREAD

**Issue by lpossamai** [ansible-collections/community.zabbix#572]
I'm trying to setup a Slack Media Type using the `zabbix_mediatype` plugin.

The media type already exists, but I need to modify it in order to be able to use it. I need to modify, for example, the `bot_token`.

How can I achieve this using `community.zabbix.zabbix_mediatype`? I noticed that the `webhook_script` is required, but it only supports `.js`?

```
- name: 'Create a webhook mediatype'
  community.zabbix.zabbix_mediatype:
    name: "Slack"
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_web_user }}"
    login_password: "{{ zabbix_web_password }}"
    type: 'webhook'
    webhook_script: "{{ lookup('file', 'slack.js') }}"
    webhook_params:
      - name: alert_message
        value: '{ALERT.MESSAGE}'
      - name: zabbix_url
        value: '{$ZABBIX.URL}'
    process_tags: True
    event_menu: true
    event_menu_name: "Open in Slack: '{EVENT.TAGS.__channel_name}'"
    event_menu_url: '{EVENT.TAGS.__message_link}'
```
