### ISSUE TITLE
[Discussion] Modify Zabbix Versions in integration tests

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#576]
##### SUMMARY

Currently we test against

```yaml
        zabbix_container:
          - version: "3.0"
          - version: "4.0"
          - version: "4.4"
          - version: "5.0"
          - version: "5.2"
```

and the tests taking pretty long now - also 6.0 is upcoming.

What if we only test against the LTS Versions and the latest not LTS version?

Currently this would be (already with 6.0 as example):
```yaml
        zabbix_container:
          - version: "4.0"
          - version: "5.0"
          - version: "5.4"
          - version: "6.0"
```

With 6.2 this:
```yaml
        zabbix_container:
          - version: "4.0"
          - version: "5.0"
          - version: "6.0"
          - version: "6.2"
```

##### ISSUE TYPE
- Discussion

##### COMPONENT NAME
- integration testing

##### ADDITIONAL INFORMATION
- Zabbix Lifecycle : https://www.zabbix.com/life_cycle_and_release_policy
