### ISSUE TITLE
zabbix_user no longer working with default authentication

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#578]
##### SUMMARY
Patch #542 broke creating users that have authentication defaulting to the global setting (if that global setting is internal authentication).

```
Possible values:
0 - (default) use the system default authentication method;
1 - use internal authentication;
2 - use LDAP authentication;
3 - disable access to the frontend.
```

![image](https://user-images.githubusercontent.com/9269600/146740325-f5405969-776f-4b52-a796-a97ed1151669.png)

I have module failing on:

```yaml
failed: [zabbix -> localhost] (item=user1) => changed=false 
  msg: 'Failed to create user tjd: (''Error -32602: Invalid params., Incorrect value for field "passwd": cannot be empty. while sending {"jsonrpc": "2.0", "method": "user.create", "params": {"alias": "user1", "usrgrps": [{"usrgrpid": "15"}], "theme": "dark-theme", "type": "1"}, "auth": "XYZ", "id": 4}'', -32602)'
```

So for me the snippet from the #542 
```python
internal_auth = bool([g for g in res if g['gui_access'] == '1'])
```

results in `False` as `gui_access == '0'` when defaulting the authentication system-wide to internal.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/modules/zabbix_user

**Comment by D3DeFi** [comment]
Yeah, I was also not sure about this. Thus, I've created issue instead of the PR.

At first, the `or g['gui_access'] == '0'` was my thought as well, but then I noticed that LDAP can be system default authentication as well. In that case if user switches to LDAP and leaves groups at '0 - default', we would still ask for password.

Ia it even possible to access global settings with 4.0? I haven't found any obvious endpoint and `configuration.export` doesn't seem to be capable of that.

We can maybe check if gui_access is set to 0 and then:
- if zabbix_version >= 5.2 -> do lookup of system default
- if zabbix_version < 5.2 -> assume internal auth

User will still have some control over this (either explicitly setting LDAP on groups, or providing bogus passwords). What do you think?

**Comment by ragingpastry** [comment]
Unfortunately I don't think there is a way to access global settings via the API with 4.0. We actually had to do some DB modifications to configure LDAP via ansible in our previous versions of the zabbix server role we host internally.

I think your solution makes the most sense for this scenario. Eventually it just won't become a problem if/when we stop supporting older Zabbix versions

**Comment by badfiles** [comment]
I use this task on fresh Zabbix 5.4.9 instance, it does not work after patch #542
How should I create a user on a fresh installation now?

```
- name: Creating zabbix-api user
  community.zabbix.zabbix_user:
    server_url: "{{ zabbix_server_url }}"
    login_user: Admin
    login_password: zabbix
    alias: "{{ zabbix_api_user }}"
    name: Zabbix
    surname: API
    usrgrps:
      - Zabbix administrators
    passwd: "{{ zabbix_api_password }}"
    role_name: Super admin role
    state: present
  ```
