### ISSUE TITLE
User tasks fail

### ISSUE THREAD

**Issue by badfiles** [ansible-collections/community.zabbix#608]
Simple user task fails in 49ff79e8faf5859bf4dce4beb5511515404106c3

```
- name: Block default superuser
  community.zabbix.zabbix_user:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_password }}"
    alias: Admin
    passwd: zabbix
    usrgrps:
      - Disabled
      - Zabbix administrators
    role_name: Super admin role
    state: present
  ignore_errors: yes
  ```
  ```
  fatal: [*]: FAILED! => {
  "changed": false,
  "module_stderr": "Shared connection to * closed.
",
  "module_stdout": "
Traceback (most recent call last):
  File \"/home/*/.ansible/tmp/ansible-tmp-1641808042.5033112-1763667-178828434308541/AnsiballZ_zabbix_user.py\", line 107, in <module>
    _ansiballz_main()
  File \"/home/*/.ansible/tmp/ansible-tmp-1641808042.5033112-1763667-178828434308541/AnsiballZ_zabbix_user.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/*/.ansible/tmp/ansible-tmp-1641808042.5033112-1763667-178828434308541/AnsiballZ_zabbix_user.py\", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_community.zabbix.zabbix_user_payload_z8p8isp_/ansible_community.zabbix.zabbix_user_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_user.py\", line 742, in <module>
  File \"/tmp/ansible_community.zabbix.zabbix_user_payload_z8p8isp_/ansible_community.zabbix.zabbix_user_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_user.py\", line 698, in main
  File \"/tmp/ansible_community.zabbix.zabbix_user_payload_z8p8isp_/ansible_community.zabbix.zabbix_user_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_user.py\", line 334, in get_usergroups_by_name
  File \"/tmp/ansible_community.zabbix.zabbix_user_payload_z8p8isp_/ansible_community.zabbix.zabbix_user_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_user.py\", line 302, in get_default_authentication
AttributeError: 'dict' object has no attribute 'authentication_type'
",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1
}```

**Comment by ragingpastry** [comment]
Thanks for the report I will look into this.

Can you give some more details on your environment? What is the default authentication type for your Zabbix server?

**Comment by badfiles** [comment]
Server OS: AlmaLinux 8.5
Zabbix-server: 5.4 
Auth type: Normal
Control node: Ubuntu 20.04

**Comment by ragingpastry** [comment]
Thanks! I see where the problem is. Once I get back to my room ill open up
an MR

**Comment by dj-wasabi** [comment]
@badfiles In the future, please create a proper "bug report". Because @ragingpastry is already working on it, I keep this issue open for now.

**Comment by ragingpastry** [comment]
Alrighty I think I have this fixed here: https://github.com/ragingpastry/community.zabbix/tree/fix-608

Can you try this out by pointing your requirements.yml to my branch @badfiles ? I will be working on improving testing for this module next, however until then I can only test locally (and ask others to test)

```yaml
---
collections:
  - name: git+https://github.com/ragingpastry/community.zabbix.git
    type: git
    version: fix-608
```
