### ISSUE TITLE
zabbix_agent2_role for windows: bug in  task "Windows | Set facts current zabbix agent installation (agent 2)"

### ISSUE THREAD

**Issue by weetalyg** [ansible-collections/community.zabbix#612]
##### SUMMARY

https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/Windows.yml

bug in  task "Windows | Set facts current zabbix agent installation (agent 2)"
```
- name: "Windows | Set facts current zabbix agent installation (agent 2)"
  set_fact:
    zabbix_agent_2_binary_exist: true
    zabbix_agent_2_version: zabbix_win_exe_info.results[1].win_file_version.product_version
  when:
    - zabbix_win_exe_info.results[1] is defined
    - zabbix_win_exe_info.results[1].item.stat.exists
    - zabbix_win_exe_info.results[1].item.stat.path == zabbix_win_exe_path
    - zabbix_win_exe_info.results[1].win_file_version.product_version
```

I think  "when condition" 3 row should be: 
`    - zabbix_win_exe_info.results[1].item.stat.path == zabbix2_win_exe_path`

because it is agent 2 version

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

roles/zabbix_agent/tasks/Windows.yml
