### ISSUE TITLE
The conditional check 'zabbix_agent2_tlspskfile' failed

### ISSUE THREAD

**Issue by PrismaComputer** [ansible-collections/community.zabbix#613]
##### SUMMARY
The conditional check 'zabbix_agent2_tlspskfile' failed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix:1.5.1

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /root/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```
##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/root/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/ansible.cfg) = ['/root/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/hosts']
HOST_KEY_CHECKING(/root/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/ansible.cfg) = False
INTERPRETER_PYTHON(/root/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/root/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/ansible.cfg) = True
```

##### OS / ENVIRONMENT / Zabbix Version

Ubuntu 20.04

##### STEPS TO REPRODUCE

We had the role configured same same on other servers. See yml below. Worked before. Then updated community.zabbix:1.4.0 -> community.zabbix:1.5.1 -> Error

```yaml
     - name: Install zabbix-agent2
       role: zabbix_agent
       zabbix_agent2: true
       zabbix_agent_server: '127.0.0.1'
       zabbix_agent_serveractive: '{{ zabbix_server }}'
       zabbix_agent_hostname: '{{ ansible_host }}'
       zabbix_agent2_hostname: '{{ ansible_host }}'
       zabbix_visible_hostname: '{{ ansible_hostname }}'
       zabbix_url: 'https://{{ zabbix_server }}'
       zabbix_api_user: '{{ enc_zabbix_api_user }}'
       zabbix_api_pass: '{{ enc_zabbix_api_pass }}'
       zabbix_api_create_hosts: true
       zabbix_api_create_hostgroup: true
       zabbix_create_host: present
       zabbix_host_groups:
         - "{{ host_group }}"
         - "{{ hosted_by }}"
       zabbix_link_templates:
         - Template OS Linux Active
         - MySQL by Zabbix agent 2 active
         - Website certificate by Zabbix agent 2 active
       zabbix_agent2_tlsaccept: psk
       zabbix_agent2_tlsconnect: psk
       zabbix_agent2_tlspskidentity: '{{ enc_zabbix_agent_tlspskidentity }}'
       zabbix_agent2_tlspskfile: '/etc/zabbix/zabbix_agentd.psk'
       zabbix_agent2_tlspsk_secret: '{{ enc_zabbix_agent_tlspsk_secret  }}'
       zabbix_agent_interfaces:
         - type: '1'
           main: True
           useip: True
           ip: 127.0.0.1
       zabbix_inventory_mode: automatic
       zabbix_macros:
         - macro_key: "{$MYSQL.DSN}"
           macro_value: "tcp://127.0.0.1:3306"
         - macro_key: "{$MYSQL.USER}"
           macro_value: '{{ enc_zabbix_mysql_monitor_user }}'
         - macro_key: "{$MYSQL.PASSWORD}"
           macro_value: '{{ enc_zabbix_mysql_monitor_password }}'
         - macro_key: "{$CERT.WEBSITE.HOSTNAME}"
           macro_value: '{{ ansible_host }}'
```

##### EXPECTED RESULTS

OK

##### ACTUAL RESULTS

fatal

```paste below
[DEPRECATION WARNING]: evaluating 'zabbix_agent2_tlspskfile' as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature
 will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [ionos1]: FAILED! => {"msg": "The conditional check 'zabbix_agent2_tlspskfile' failed. The error was: template error while templating string: unexpected '/'. String: {% if /etc/zabbix/zabbix_agentd.psk %} True {% else %} False {% endif %}\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Linux.yml': line 140, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Create directory for PSK file if not exist (zabbix-agent2)\"\n  ^ here\n"}
```
