### ISSUE TITLE
Import Zabbix 5.4 - 6.0 Template format YAML

### ISSUE THREAD

**Issue by smejdil** [ansible-collections/community.zabbix#618]
Deafult templates in Zabbix 5.4 and 6.0 are in YAML format. For automated import of templates this format is needed. (XML and JSON is ready)

##### SUMMARY
Add parametr template_yaml

##### COMPONENT NAME
Modules: zabbix_template

**Comment by dutrajulio** [comment]
As a temporary workaround you can use the "from_yaml" Ansible filter.

**Comment by heyzling** [comment]
"from_yaml" usage example.

```yaml
- name: Import Zabbix template from Ansible dict variable
  community.zabbix.zabbix_template:
    template_json: "{{ lookup('file', 'my-template.yaml') | from_yaml }}"
    state: present
```
