### ISSUE TITLE
macro_type support in zabbix_agent role

### ISSUE THREAD

**Issue by barzog** [ansible-collections/community.zabbix#620]
##### SUMMARY
Currently in zabbix_agent/agent2 template there is no support for macro type (i.e. macros created always with type text)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
roles/zabbix_agent/tasks/api.yml

##### ADDITIONAL INFORMATION
We should use

```yaml
- name: "API | Updating host configuration with macros"
  zabbix_hostmacro:
    server_url: "{{ zabbix_api_server_url }}"
    http_login_user: "{{ zabbix_api_http_user | default(zabbix_http_user | default(omit)) }}"
    http_login_password: "{{ zabbix_api_http_password | default(zabbix_http_password | default(omit)) }}"
    login_user: "{{ zabbix_api_login_user }}"
    login_password: "{{ zabbix_api_login_pass }}"
    host_name: "{{ (zabbix_agent2 | bool) | ternary(zabbix_agent2_hostname, zabbix_agent_hostname) }}"
    macro_name: "{{ item.macro_key }}"
    macro_value: "{{ item.macro_value }}"
    macro_type: "{{ item.macro_type|default('text') }}"
    validate_certs: "{{ zabbix_api_validate_certs | default(omit) }}"
    timeout: "{{ zabbix_api_timeout }}"
  with_items: "{{ zabbix_agent_macros | default([]) }}"
  when:
    - zabbix_agent_macros is defined
    - item.macro_key is defined
  register: zabbix_api_hostmarcro_created
  until: zabbix_api_hostmarcro_created is succeeded
  delegate_to: localhost
  become: false
  tags:
    - api
```
 
instead of
```yaml
- name: "API | Updating host configuration with macros"
  zabbix_hostmacro:
    server_url: "{{ zabbix_api_server_url }}"
    http_login_user: "{{ zabbix_api_http_user | default(zabbix_http_user | default(omit)) }}"
    http_login_password: "{{ zabbix_api_http_password | default(zabbix_http_password | default(omit)) }}"
    login_user: "{{ zabbix_api_login_user }}"
    login_password: "{{ zabbix_api_login_pass }}"
    host_name: "{{ (zabbix_agent2 | bool) | ternary(zabbix_agent2_hostname, zabbix_agent_hostname) }}"
    macro_name: "{{ item.macro_key }}"
    macro_value: "{{ item.macro_value }}"
    validate_certs: "{{ zabbix_api_validate_certs | default(omit) }}"
    timeout: "{{ zabbix_api_timeout }}"
  with_items: "{{ zabbix_agent_macros | default([]) }}"
  when:
    - zabbix_agent_macros is defined
    - item.macro_key is defined
  register: zabbix_api_hostmarcro_created
  until: zabbix_api_hostmarcro_created is succeeded
  delegate_to: localhost
  become: false
  tags:
    - api
```
