### ISSUE TITLE
Can't create maintenance on Zabbix 6

### ISSUE THREAD

**Issue by polcape** [ansible-collections/community.zabbix#637]
##### SUMMARY
Launch creation of maintenance failed 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix maintenance

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Nov  9 2021, 13:31:27) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True

```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix version 6
Os Rocky Linux 8.5
Python 3.9

##### STEPS TO REPRODUCE

Launch playbook to create maintenance I get this error, seems cast error on time string

```
- hosts: server
  tasks:
  - name: Test
    community.zabbix.zabbix_maintenance:
      name: Test
      host_groups:
        - Test
      state: present
      collect_data: yes
      server_url: https://zabbix
      login_user: xxx
      login_password: xxx
```

##### EXPECTED RESULTS

Maintenance created without error

##### ACTUAL RESULTS

I get this error

```
fatal: [server]: FAILED! => {"changed": false, "msg": "Failed to create maintenance: (u'Error -32602: Invalid params., Invalid parameter \"/1/active_since\": an unsigned integer is expected. while sending {\"params\": {\"maintenance_type\": 0, \"active_since\": \"1645364880.0\", \"active_till\": \"1645365660.0\", \"groupids\": [\"32\"], \"timeperiods\": [{\"timeperiod_type\": \"0\", \"start_date\": \"1645365060.0\", \"period\": \"600\"}], \"description\": \"Created by Ansible\", \"hostids\": [], \"name\": \"Test\"}, \"jsonrpc\": \"2.0\", \"method\": \"maintenance.create\", \"auth\": \"dd0f5d574072ce6bc66d511b\", \"id\": 4}', -32602)"}
```
