### ISSUE TITLE
Sangoma support should be included in zabbix_proxy role

### ISSUE THREAD

**Issue by barzog** [ansible-collections/community.zabbix#638]
##### SUMMARY
Currently zabbix_agent role supports Sangoma, but zabbix_proxy role lacks that kind of support
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
roles/zabbix_proxy/tasks/main.yml

##### ADDITIONAL INFORMATION
This definition should be enough (in the beginning of main.yml)
```yaml
    - name: Replace Sangoma with RedHat task
      set_fact: ansible_os_family='RedHat'
      when: ansible_os_family == 'Sangoma'
```
