### ISSUE TITLE
The desc param didn't update of zabbix_maintenance module

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#64]
##### SUMMARY

I tried description update of maintenance but it didn't update.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

plugins/modules/zabbix_maintenance.py

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.10.0.dev0
```

##### CONFIGURATION

```
# ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

```
CentOS Linux release 7.6.1810 (Core)
```

##### STEPS TO REPRODUCE

I have executed the following playbook.

```yaml
---
- name: test
  hosts: localhost
  gather_facts: no
  collections:
    - community.zabbix
  vars:
    zabbix_server_url: http://127.0.0.1:8080
    zabbix_login_user: Admin
    zabbix_login_password: zabbix
  tasks:
    - name: "test - Update maintenance with a desc param"
      zabbix_maintenance:
        server_url: "{{ zabbix_server_url }}"
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        name: maintenance
        host_name: example
        desc: "test description"
        state: present
      register: update_maintenance_desc_result
```

I changed the desc parameter and re-execute it.

```yaml
---
- name: test
  hosts: localhost
  gather_facts: no
  collections:
    - community.zabbix
  vars:
    zabbix_server_url: http://127.0.0.1:8080
    zabbix_login_user: Admin
    zabbix_login_password: zabbix
  tasks:
    - name: "test - Update maintenance with a desc param"
      zabbix_maintenance:
        server_url: "{{ zabbix_server_url }}"
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        name: maintenance
        host_name: example
        desc: "test description2"
        state: present
      register: update_maintenance_desc_result
```

##### EXPECTED RESULTS

The maintenance description will be updated.

##### ACTUAL RESULTS

The maintenance description didn't update.
