### ISSUE TITLE
zabbix_action: wrong error msg when user has no admin access

### ISSUE THREAD

**Issue by valintinr** [ansible-collections/community.zabbix#660]
Hello, this issue created from #600 

Code example:
```
    - name: Add discovery action old servers
      community.zabbix.zabbix_action:
        server_url: SOME_URL
        login_user: "api2"
        login_password: SOME_PASSWORD
        event_source: "discovery"
        state: present
        status: enabled
        name: "{{ item.name }}"
        conditions:
          - type: "host_IP"
            operator: "="
            value: "{{ item.host_ip_equals }}"
        operations:
          - type: "add_to_host_group"
            host_groups: "{{ item.hostgroup }}"
          - type: "link_to_template"
            templates: "{{ item.templates }}"
      with_items:
        - "{{ zabbix_server_data_discovery }}"
```

Var example:
```
zabbix_server_data_discovery:
  - { name: "Servers/Old-inap", hostgroup: "Servers/Old", host_ip_equals: SOME_IPs, templates: [old] }
```

Playbook result:
```
TASK [Add discovery action old servers] ***************************************************************************************************************************************************************************************************************************************************************
failed: [zabbix-otto] (item={'name': 'Servers/Old-inap', 'hostgroup': 'Servers/Old', 'host_ip_equals': SOME_IPs, 'templates': ['old']}) => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "ansible_loop_var": "item", "changed": false, "item": {"host_ip_equals": SOME_IPs, "hostgroup": "Servers/Old", "name": "Servers/Old-inap", "templates": ["old"]}, "msg": "Host group not found: Servers/Old"}
```

I think this error happens during ```hostgroup.get``` request:
```
REQUEST
{"jsonrpc": "2.0", "method": "hostgroup.get", "params": {"output": "extend", "filter": {"name": ["Servers/Old"]}}, "auth": "e724bfd461f91a4ef26c94d768d17722", "id": 2}

RESPONSE
{
    "id": 2,
    "jsonrpc": "2.0",
    "result": []
}
```
right after this request I see ```user.logout``` request

User access screenshot attached, when changed User role to Super admin role the error goes away
![screenshot_614](https://user-images.githubusercontent.com/3368964/159261536-03513094-d5ba-470c-a434-cb54fd2fabaa.png)
