### ISSUE TITLE
PostgreSQL | Delegated | Create database: unable to initialize policy plugin

### ISSUE THREAD

**Issue by patsevanton** [ansible-collections/community.zabbix#669]
Hello! Thanks for role zabbix

##### SUMMARY
PostgreSQL | Delegated | Create database: unable to initialize policy plugin

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_server

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

##### CONFIGURATION

```
ansible-config dump --only-changed
CALLBACKS_ENABLED(/home/user/github/infrastructure-as-a-code-example/zabbix-cluster/ansible.cfg) = ['profile_tasks']
DEFAULT_GATHERING(/home/user/github/infrastructure-as-a-code-example/zabbix-cluster/ansible.cfg) = smart
DEFAULT_STDOUT_CALLBACK(/home/user/github/infrastructure-as-a-code-example/zabbix-cluster/ansible.cfg) = yaml
```

##### requirements.yml
```
---
collections:
  - name: community.zabbix
    version: 1.5.1
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
```

##### STEPS TO REPRODUCE
Playbook
```yaml
---

- hosts: zabbix_database
  become: true
  roles:
    - role: geerlingguy.postgresql

- name: Installing Zabbix
  hosts: zabbix_server
  become: true
  collections:
    - community.zabbix
  roles:
    - role: zabbix_server
    - role: geerlingguy.apache
    - role: wdijkerman.php
    - role: zabbix_web
```

##### Inventory
```
all:
  children:
    zabbix:
      hosts:
        zabbix_server:
          ansible_host: xxxxx
          vars:
            zabbix_server_dbhost: yyyyy
            zabbix_server_real_dbhost: yyyyy
            zabbix_server_dbpassword: supersecure
        zabbix_database:
          ansible_host: yyyy
          vars:
            postgresql_users:
              - name: postgres
                password: supersecure
            postgresql_hba_entries:
              - { type: local, database: all, user: postgres, auth_method: peer }
              - { type: local, database: all, user: all, auth_method: peer }
              - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
              - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
              - { type: host, database: all, user: all, address: 'xxxxx/32', auth_method: md5 }

  vars:
    ansible_user:  ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
```

RUN
```
ansible-galaxy collection install -r requirements.yml
ansible-galaxy collection install community.postgresql
ansible-galaxy install geerlingguy.postgresql
ansible-playbook -i inventory.yml playbook.yml
```

##### ACTUAL RESULTS
```paste below
TASK [community.zabbix.zabbix_server : PostgreSQL | Delegated | Create database] **********************************************************************
Tuesday 12 April 2022  14:41:53 +0600 (0:00:00.015)       0:02:59.789 *********
fatal: [zabbix_server]: FAILED! => changed=false
  module_stderr: |-
    sudo: unknown user: postgres
    sudo: unable to initialize policy plugin
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
