### ISSUE TITLE
Debian | Install gpg key failed

### ISSUE THREAD

**Issue by possebon** [ansible-collections/community.zabbix#673]
##### SUMMARY

```
TASK [community.zabbix.zabbix_agent : Debian | Installing gnupg] *************************************************************************************************************************************************************
ok: [myhost-watch-proxy]

TASK [community.zabbix.zabbix_agent : Debian | Install gpg key] **************************************************************************************************************************************************************
fatal: [myhost-watch-proxy]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '60'\n\nThe error appears to be in '/Users/possebon/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Debian.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Debian | Install gpg key\"\n  ^ here\n"}

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ROLE: zabbix_agent

##### ANSIBLE VERSION

```
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/Users/possebon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/possebon/.pyenv/versions/3.8.5/envs/apps3/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/possebon/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/possebon/.pyenv/versions/apps3/bin/ansible
  python version = 3.8.5 (default, Aug 14 2020, 10:23:42) [Clang 11.0.3 (clang-1103.0.32.62)]
  jinja version = 3.0.1
  libyaml = True

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 6.0.3

The host where issue occurs runs:

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

##### STEPS TO REPRODUCE

```yaml

---
- hosts: '{{ playbook_hosts }}'
  collections:
    - community.zabbix
  vars:
    watch_credentials: "{{ lookup('hashi_vault', 'secret=kv/data/mysecrets') }}"
  tasks:
    - name: Import zabbix-agent role
      import_role:
        name: zabbix_agent

```

### group_vars
```yaml
---
zabbix_agent_version: 6.0
zabbix_proxy_version: 6.0
```

##### ACTUAL RESULTS

```paste below

```

**Comment by pantherra** [comment]
i have the same issue.
By default zabbix agent version installed is 5.4
But when im using zabbix_agent_version: 6.0

fatal: [host1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '6'\n\nThe error appears to be in '/usr/local/lib/python3.9/dist-packages/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Debian.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Debian | Install gpg key\"\n  ^ here\n"}

**Comment by TakaseNochi** [comment]
proxy?
https://github.com/ansible-collections/community.zabbix/blob/b2d30089011ee7a85d63e2ef7ff84912df4ba6ba/roles/zabbix_agent/tasks/Debian.yml#L30

**Comment by possebon** [comment]
> proxy?
> 
> https://github.com/ansible-collections/community.zabbix/blob/b2d30089011ee7a85d63e2ef7ff84912df4ba6ba/roles/zabbix_agent/tasks/Debian.yml#L30-L32

Not my case, I don't have proxy HTTP/HTTPS proxy.

**Comment by kjaquier** [comment]
Same issue here.

Ansible version:
```
$ ansible --version
ansible [core 2.12.1]
  config file = /home/kjr/workspace/infra/ansible/ansible.cfg
  configured module search path = ['/home/kjr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/kjr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, Nov 18 2021, 16:00:48) [GCC 10.3.0]
  jinja version = 2.11.2
  libyaml = True
```

Output:
```
TASK [community.zabbix.zabbix_agent : Debian | Install gpg key] ******************
fatal: [mps]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'jammy'\n\nThe error appears to be in '/home/kjr/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Debian.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Debian | Install gpg key\"\n  ^ here\n"}
```

Playbook (relevant part)
```yml
    - role: community.zabbix.zabbix_agent
      vars:
        zabbix_agent2: true
        zabbix_agent2_version: 5.4
        zabbix_agent2_server: "{{ zabbix_server }}"
        zabbix_agent2_hostname: "{{ inventory_hostname }}"
        zabbix_agent_firewall_enable: true
```

Host:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```
