### ISSUE TITLE
default repo configuration for zabbix server has regex that doesn't work.

### ISSUE THREAD

**Issue by damo2929** [ansible-collections/community.zabbix#686]
##### SUMMARY
{{ zabbix_version | regex_search('^[0-9]+.[0-9]+') }} crashes ansible

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix.server role 

##### ANSIBLE VERSION

```
[root@zabbix1 ~]# ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov  9 2021, 14:44:26) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

```

##### CONFIGURATION
```
[root@zabbix1 ~]# ansible-config dump --only-changed
[root@zabbix1 ~]#

```

##### OS / ENVIRONMENT / Zabbix Version
Rocky linux 8.5 x84_64

##### STEPS TO REPRODUCE
```
---
# Required Ansible collections
#  collections:
#  - name: community.general
#  - name: community.mysql
#  - name: community.zabbix


- name: Zabbix Server installation
  become: yes
  hosts: zabbixservers

  roles:

    - role: community.zabbix.zabbix_server
     
      zabbix_repo: zabbix
      zabbix_service_state: started
      zabbix_service_enabled: True
      zabbix_selinux: true
      zabbix_server_package_state: latest
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbname: zabbixmonitoring
      zabbix_server_dbuser: zabbixserver
      zabbix_server_dbpassword: ILoveToMonitorStuff!!
      zabbix_server_dbsocket: /tmp/socket
      zabbix_server_startpollers: 10
      zabbix_server_startipmipollers: 1
      zabbix_server_startlldprocessors: 2
      zabbix_server_startpreprocessors: 10
      zabbix_server_startpollersunreachable: 2
      zabbix_server_starttrappers: 5
      zabbix_server_startpingers: 5
      zabbix_server_startdiscoverers: 2
      zabbix_server_starthttppollers: 5
      zabbix_server_starttimers: 5
      zabbix_server_startescalators: 5
      zabbix_server_startproxypollers: 1
      zabbix_server_startjavapollers: 0
      zabbix_server_startvmwarecollectors: 5
      zabbix_server_vmwarefrequency: 60
      zabbix_server_vmwareperffrequency: 120
      zabbix_server_vmwarecachesize: 32M
      zabbix_server_vmwaretimeout: 120
      zabbix_server_housekeepingfrequency: 6
      zabbix_server_maxhousekeeperdelete: 150000
      zabbix_server_cacheupdatefrequency: 300
      zabbix_server_startdbsyncers: 4
      zabbix_server_timeout: 30
      zabbix_server_trappertimeout: 30
      zabbix_server_problemhousekeepingfrequency: 300
      zabbix_server_hanodename: "{{ ansible_hostname }}"

```

to get past this issue I had to redefine the variable in the playbook like so by removing the regex.
note the regex is missing from the agent role but is also present on the server,proxy and javagateway roles.

```
    - role: community.zabbix.zabbix_server
      zabbix_repo_yum:
         - name: zabbix
           description: Zabbix Official Repository - $basearch
           baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/"
           gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
           mode: '0644'
           gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
           state: present
         - name: zabbix-non-supported
           description: Zabbix Official Repository non-supported - $basearch
           baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/"
           mode: '0644'
           gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
           gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
           state: present


##### EXPECTED RESULTS
expected to create repo.


##### ACTUAL RESULTS
```
TASK [community.zabbix.zabbix_server : RedHat | Install basic repo file] ********************************************************************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_server/tasks/RedHat.yml:91
fatal: [zabbix1.internal.zone]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '[{'name': 'zabbix', 'description': 'Zabbix Official Repository - $basearch', 'baseurl': \"{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_version | regex_search('^[0-9]+.[0-9]+') }}/rhel/{{ ansible_distribution_major_version }}/$basearch/\", 'gpgcheck': '{{ zabbix_repo_yum_gpgcheck }}', 'mode': '0644', 'gpgkey': 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX', 'state': 'present'}, {'name': 'zabbix-non-supported', 'description': 'Zabbix Official Repository non-supported - $basearch', 'baseurl': '{{ zabbix_repo_yum_schema }}://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/', 'mode': '0644', 'gpgcheck': '{{ zabbix_repo_yum_gpgcheck }}', 'gpgkey': 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX', 'state': 'present'}]'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_version | regex_search('^[0-9]+.[0-9]+') }}/rhel/{{ ansible_distribution_major_version }}/$basearch/): expected string or bytes-like object"
}
```
