### ISSUE TITLE
esc_step_from and esc_step_to are cleared if esc_period is set only on the action level

### ISSUE THREAD

**Issue by gregolsky** [ansible-collections/community.zabbix#692]
##### SUMMARY

The `esc_period` is available to set on the action level (which sets the default operation `esc_period`) and on the specific operation level.
Now `esc_step_from` and `esc_step_to` parameters are cleared if it's not set *explicitly* on the operation level, but only on the action level:

https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_action.py#L1266

Now on every action operation we need to set `esc_period` separately, which is not ideal.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`zabbix_action`

##### ANSIBLE VERSION
```paste below
2.12.5 core
```

##### STEPS TO REPRODUCE
```yaml
zabbix_action:
    url: "{{ url }}"
    login_user: "{{ lookup('env','ZBX_USER') }}"
    login_password: "{{ lookup('env','ZBX_PASS') }}"
    name: "Send alerts"
    event_source: trigger
    state: present
    status: enabled
    esc_period: 900                  <---- defined but not taken into consideration in https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_action.py#L1266
    conditions:
      - type: event_tag_value
        operator: '='
        value2: "Off"
        value: "True"
        formulaid: A
    formula: A
    operations:
      - type: send_message
        esc_step_from: 2
        esc_step_to: 2
```

It starts working when you set `esc_period` on the operation level:
```
    operations:
      - type: send_message
        esc_period: 900              <----------------- was not needed before
        esc_step_from: 2
        esc_step_to: 2
```

##### EXPECTED RESULTS
Operations should be added with steps from 2 to 2.

##### ACTUAL RESULTS
Operations are added with escalation steps from 1 to 1.
