### ISSUE TITLE
Zabbix_Agent deploy fails under Windows

### ISSUE THREAD

**Issue by david-sieg** [ansible-collections/community.zabbix#703]
##### SUMMARY
Deploy of Zabbix Agent isn't possible since release of Collection 1.7.

Variable 'ansible_distribution_release' isn't provided by Windows systems, so it breaks deployment.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix Agent role

##### ANSIBLE VERSION
```
2.10.7
```

##### OS / ENVIRONMENT / Zabbix Version
Windows Server 2016/2019/2022
Zabbix version 6 

##### STEPS TO REPRODUCE
Install agent on Windows systems.

##### EXPECTED RESULTS
Runing Zabbix-Agent2 V6

##### ACTUAL RESULTS
```
fatal: [tst-bt02-dmpr.gkv-sv-dmz.local]: FAILED! => {"msg": "The conditional check 'ansible_distribution_release == \"jammy\"' failed. The error was: error while evaluating conditional (ansible_distribution_release == \"jammy\"): 'ansible_distribution_release' is undefined\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Reset zabbix_agent_version for Ubuntu 22.04 to 6.0\"\n  ^ here\n"}

```

**Comment by keeganquinn** [comment]
I ran into this problem as well. There appears to be a missing `ansible_distribution_release is defined` conditional in zabbix_agent/tasks/main.yml. Until that gets fixed, this can be worked around by setting a dummy value.

I also needed to set `zabbix_win_firewall_management: false` to get the role to finish successfully; this may be another separate issue or something specific to my environment. I didn't need the firewall management feature so I didn't investigate further.

Thus, currently a working playbook for me running Zabbix Agent on Windows looks like this:

```
- name: Zabbix agent configuration for Windows hosts
  hosts: internal_win
  collections:
    - community.zabbix

  roles:
    - role: zabbix_agent
      ansible_distribution_release: none
      zabbix_agent_server: your.zabbix.server
      zabbix_win_firewall_management: false
      zabbix_win_install_dir: C:\Program Files\Zabbix Agent
```

HTH!
