### ISSUE TITLE
Zabbix Agent installs with --check flag

### ISSUE THREAD

**Issue by piotrkochan** [ansible-collections/community.zabbix#705]
##### SUMMARY

Ansible role zabbix_agent installs Zabbix when --check flag is provided. This is very dangerous as --check is used usually to determine what the playbook will do and it definitely should not make changes to the system.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
https://github.com/ansible-collections/community.zabbix/tree/2287bc4165a03e2ae8a2ed94ec1088428b29dad9/roles/zabbix_agent

##### ANSIBLE VERSION
not revelant

##### CONFIGURATION
not revelant

##### OS / ENVIRONMENT / Zabbix Version

Ubuntu/Debian

##### STEPS TO REPRODUCE

```yaml
- name: Zabbix Agent Playbook
  hosts: zabbix_agent
  become: true
  tasks:
    - name: Ensure host is monitored by Zabbix
      community.zabbix.zabbix_host:
```
ansible-playbook -i ... playbook.yml --check

##### EXPECTED RESULTS

Playbook result without actual changes to the system

##### ACTUAL RESULTS

My friends panicked and cried

##### POSSIBLE FIX

Remove `check_mode: false` from line 200 and 224 

https://github.com/ansible-collections/community.zabbix/blob/2287bc4165/roles/zabbix_agent/tasks/Debian.yml#L200
