### ISSUE TITLE
AWX - Passing credentials as variables doesn't work

### ISSUE THREAD

**Issue by marek1712** [ansible-collections/community.zabbix#713]
Hi.

I still have issues in AWX (tried i.e. under 19.4.0) - see #423.
Unless I embed credentials in the playbook that uses inventory plugin, my custom creds (assigned to dynamic inventory) aren't used.

I defined them like this:

Input configuration:
```
fields:
  - id: ZABBIX_USERNAME
    type: string
    label: Username
  - id: ZABBIX_PASSWORD
    type: string
    label: Password
    secret: true
  - id: ZABBIX_SERVER
    type: string
    label: Zabbix Server Address
  - id: ZABBIX_VALIDATE_CERTS
    type: boolean
    label: Validate Zabbix Certificates
required:
  - ZABBIX_USERNAME
  - ZABBIX_PASSWORD
  - ZABBIX_SERVER
  - ZABBIX_VALIDATE_CERTS
```

Injector configuration:
```
env:
  ZABBIX_SERVER: '{{ ZABBIX_SERVER }}'
  ZABBIX_PASSWORD: '{{ ZABBIX_PASSWORD }}'
  ZABBIX_USERNAME: '{{ ZABBIX_USERNAME }}'
  ZABBIX_VALIDATE_CERTS: '{{ ZABBIX_VALIDATE_CERTS }}'
```

Any idea what could be wrong? I'm updating the plugin via requirements.yml.
I see that current version of the collection downloads just fine:
`community.zabbix:1.7.0 was installed successfully`

If I check through API (`api/v2/inventory_updates/4072/`), I see that environmental variables are attached under `job_env`:
```
"ZABBIX_SERVER": "https://zabbix.company.com/",
"ZABBIX_PASSWORD": "**********",
"ZABBIX_USERNAME": "Admin",
"ZABBIX_VALIDATE_CERTS": "False",
```
Yet it seems they aren't automatically used.

_Originally posted by @marek1712 in https://github.com/ansible-collections/community.zabbix/issues/423#issuecomment-1151004979_
