### ISSUE TITLE
zabbix_host: Handling of macros is not idempotent

### ISSUE THREAD

**Issue by mzoff** [ansible-collections/community.zabbix#715]
##### SUMMARY
I run task for update host macros. When I run this task again, it will changed again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_host
##### ANSIBLE VERSION

```
ansible [core 2.12.6]
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True

```

##### CONFIGURATION
```
HOST_KEY_CHECKING(/home/vagrant/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix-server: Debian 11, zabbix version 6.0, DB postgres
Zabbix-agent: Debian 10, zabbix-agent2 version 6.0

##### STEPS TO REPRODUCE

```yaml
- name: "New macros apply"
  community.zabbix.zabbix_host:
    server_url: "{{ zabbix_server_url_protocol}}{{ zabbix_server_url_hostname }}"
    login_user: "{{ zabbix_server_login_user }}"
    login_password: "{{ zabbix_server_login_password }}"
    host_name: "{{ zabbix_agent_config_Hostname }}"
    visible_name: "{{ zabbix_agent_config_Hostname }}"
    timeout: 25
    force: false
    macros:
      -  macro: '{$SMARTCTL_STATIC_DISKS}'
         value: "test"
    status: enabled
    state: present
```

##### EXPECTED RESULTS

It will changed only once, at first run.

##### ACTUAL RESULTS

It is always cnanged.
