### ISSUE TITLE
Zabbinx Inventory is imported into Ansible Inventory, but when you run PlayBook, the error "Could not resolve hostname" is displayed.

### ISSUE THREAD

**Issue by sohwaje** [ansible-collections/community.zabbix#717]
##### ISSUE TYPE
- Bug report

##### COMPONENT NAME

community.zabbix.zabbix_inventory

##### ADDITIONAL INFORMATION

```
ansible --version
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

```

```yaml
- hosts: "{{ hosts }}"
  gather_facts: false
  vars:
    ansible_port: 2222

  tasks:
  - name: ping
    ping:
```
```
Below is what I got from the host registered with Zabbix in the Ansible inventory 
{
  "zbx_auto_compress": "1",
  "zbx_custom_interfaces": "1",
  "zbx_description": "",
  "zbx_flags": "4",
  "zbx_host": "API sysk8stest01",
  "zbx_hostid": "11319",
  "zbx_interfaces": [
    {
      "ip": "10.10.10.1"
    }
  ],
  "zbx_inventory_mode": "-1",
  "zbx_ipmi_authtype": "-1",
  "zbx_ipmi_password": "",
  "zbx_ipmi_privilege": "2",
  "zbx_ipmi_username": "",
  "zbx_lastaccess": "0",
  "zbx_maintenance_from": "0",
  "zbx_maintenance_status": "0",
  "zbx_maintenance_type": "0",
  "zbx_maintenanceid": "0",
  "zbx_name": "API sysk8stest01",
  "zbx_proxy_address": "",
  "zbx_proxy_hostid": "11307",
  "zbx_status": "0",
  "zbx_templateid": "0",
  "zbx_tls_accept": "1",
  "zbx_tls_connect": "1",
  "zbx_tls_issuer": "",
  "zbx_tls_subject": "",
  "zbx_uuid": ""
}
```

![스크린샷 2022-06-18 오후 4 08 37](https://user-images.githubusercontent.com/19942049/174427052-aa3d375c-e726-48af-a1a6-50eb400f5352.png)
![스크린샷 2022-06-18 오후 4 16 08](https://user-images.githubusercontent.com/19942049/174427386-edc9bfbd-523e-4b5d-8eb9-29e78e677a76.png)

![스크린샷 2022-06-18 오후 4 17 38](https://user-images.githubusercontent.com/19942049/174427361-d61774b4-ed69-4295-bb69-1d708ba0ee6c.png)
f-05abd7ee56db.png)

Zabbinx Inventory was imported into Ansible Inventory, but there was no item "ansible_ssh_host", so when you run the playbook, it is called "Could not resolve hostname". How can I have the Playbook run on the Zabbinx host?
 

I tried as below but failed.
![스크린샷 2022-06-18 오후 4 23 07](https://user-images.githubusercontent.com/19942049/174427511-5c3ff8db-015c-49f6-a332-d909c100b5cc.png)

Please help me @D3DeFi

**Comment by D3DeFi** [comment]
@sohwaje in your screenshot with inventory configuration and variables definition `ansible_ssh_host: "{{ zbx_interfaces.item }}"`. Did you try something like `{{ zbx_interfaces[0].ip }}` also?

I am sorry, but I have no way of testing/replicating this myself at this point. 

Maybe you can even try something like this (may not have correct syntax, I've typed it from my head)?
```yaml
- hosts: "{{ hosts }}"
  gather_facts: false
  tasks:
    - add_host:
        name: '{{ zbx_host }}'
        group: playgroup
        ansible_ssh_host: '{{ zbx_interfaces[0].ip }}'

- hosts: playgroup
  tasks:
  - name: ping
    ping:
```
