### ISSUE TITLE
'contains' and 'does not contain' not supported

### ISSUE THREAD

**Issue by niklasweimann** [ansible-collections/community.zabbix#746]
##### SUMMARY
The zabbix_action module does not support the 'contains' and 'does not contain' as operator.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.4]
  config file = None
  configured module search path = ['/Users/niklasweimann/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/niklasweimann/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:28:31) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.0.1
  libyaml = True
```

##### STEPS TO REPRODUCE
```yaml
- name: Create auto register action for zabbix server
  local_action:
    module: community.zabbix.zabbix_action
    server_url: "https://{{zabbix_host_url}}"
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_user_password }}"
    name: "Auto register zabbix server hosts"
    event_source: 'auto_registration'
    state: present
    status: enabled
    esc_period: 60
    conditions:
      - type: host_metadata
        operator: 'contains' # contians is not supported
        value: 'zabbix-server' 
    operations:
      - type: add_to_host_group
        host_groups:
          - Zabbix servers
      - type: link_to_template
        templates:
          - SSH Service
```

##### EXPECTED RESULTS
I can use 'contains' and 'does not contain' as a operation since it is listed in the zabbix-api (https://www.zabbix.com/documentation/current/en/manual/api/reference/action/object).

##### ACTUAL RESULTS
```paste below
fatal: [zabbix1 -> localhost]: FAILED! => {"changed": false, "msg": "Unsupported value 'contains' for operator."}
```
