### ISSUE TITLE
No hosts found belongin to all given groups

### ISSUE THREAD

**Issue by qq516249940** [ansible-collections/community.zabbix#772]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.17
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

zabbix5.0
centos7.9

##### STEPS TO REPRODUCE

error:
```yaml
# Create/update a screen.
- name: Create a new screen or update an existing screen's items 5 in a row
  local_action:
    module: community.zabbix.zabbix_screen
    server_url: http://monitor.example.com
    login_user: username
    login_password: password
    screens:
      - screen_name: ExampleScreen1
        host_group: 
           - Example group1
           -  test   #add my host group,but tips me! No hosts found belongin to all given groups!!!
        state: present
        graph_names:
          - Example graph1
          - Example graph2
        graph_width: 200
        graph_height: 100
        graphs_in_row: 5
```
work:
```yaml
# Base create host groups example
- name: Create host groups
  local_action:
    module: community.zabbix.zabbix_group
    server_url: http://monitor.example.com
    login_user: username
    login_password: password
    state: present
    host_groups:
      - Example group1   # work
      - Example group2   # work
```

##### ACTUAL RESULTS

```paste below

```
