### ISSUE TITLE
Adjust permissions to allow system.hw.chassis to display

### ISSUE THREAD

**Issue by dgibbs64** [ansible-collections/community.zabbix#784]
##### SUMMARY
Currently to allow Zabbix Agent to get system.hw.chassis data you need to do the following:
```
chown root:zabbix /sys/firmware/dmi/tables/DMI
chmod 440 /sys/firmware/dmi/tables/DMI
```
It would be helpful if the Zabbix Agent role updated the permissions as part of its process

https://www.zabbix.com/documentation/current/en/manual/config/items/itemtypes/zabbix_agent

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix agent

##### ADDITIONAL INFORMATION

by default I either need to manually set permissions or create my own task to update permissions. Integrating this in to the zabbix agent role will simplify the install process further and save people having to dig around in docs to sort it out.

```yaml

```

**Comment by mu1f407** [comment]
Not sure if it's good to tweak user's system as much. Is this procedure recommended in Zabbix documentation? Maybe as an opt-in feature. @pyrodie18 your opinion?

**Comment by pyrodie18** [comment]
I could support an opt-in.  Default the task when condition to False and let them purposely change it.  @dgibbs64 is there documentation that supports that configuration or is this something you came up with?

**Comment by D3DeFi** [comment]
+1 for the opt-in, but not a default

**Comment by dgibbs64** [comment]
I agree an opt-in would be great @pyrodie18 the solution is based on a few scattered forum posts with changing the group to zabbix being the best solution.

Here is the task I use to get it working
```
# Allows system.hw.chassis info to be displayed in zabbix
- name: ensure zabbix can access DMI info
  ansible.builtin.file:
    path: /sys/firmware/dmi/tables/DMI
    owner: root
    group: zabbix
    mode: "440"
```
