### ISSUE TITLE
`zabbix_host` with `tls_psk` is always `changed: true`

### ISSUE THREAD

**Issue by Vanav** [ansible-collections/community.zabbix#785]
On current versions of `community.zabbix` (v1.8.0) and Zabbix (v6.2) task `zabbix_host` with `tls_psk` always has status `changed: true` — not idempotent. This may be related to: #741, #739, #481, #460.

Task:
```
- name: "API | Create a new host using agent2 or update an existing host's info"
  delegate_to: localhost
  zabbix_host:
    server_url: '{{ zabbix_api_server_url }}'
    login_user: '{{ lookup("env", "zabbix_api_login_user") or zabbix_api_login_user }}'
    login_password: '{{ lookup("env", "zabbix_api_login_pass") or zabbix_api_login_pass }}'
    host_name: '{{ zabbix_agent_hostname }}'
    host_groups: '{{ zabbix_host_groups }}'
    link_templates: '{{ zabbix_link_templates }}'
    interfaces:
    - type: agent
      main: 1
      useip: 1
      ip: '{{ ansible_host }}'
      port: '{{ zabbix_port }}'
    tls_psk: '{{ zabbix_agent2_tlspsk_secret }}'
    tls_psk_identity: '{{ zabbix_agent_hostname }}'
    tls_accept: 2     # PSK
    tls_connect: 2    # PSK
  ignore_errors: '{{ ansible_check_mode }}'    # host_groups may not be available in check mode yet
```

Result:
```
redirecting (type: modules) ansible.builtin.zabbix_host to community.zabbix.zabbix_host
redirecting (type: modules) ansible.builtin.zabbix_host to community.zabbix.zabbix_host
Using module file /root/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/opt/pipx/venvs/ansible/bin/python && sleep 0'

TASK [zabbix : API | Create a new host using agent2 or update an existing host's info] *************************************************************
task path: /srv/Project/infra/roles/zabbix/tasks/main.yml:162
changed: [dev_host_node -> localhost] => 
    changed: true
    invocation:
        module_args:
            ca_cert: null
            description: null
            force: true
            host_groups:
            - xxx
            host_name: xxx
            http_login_password: null
            http_login_user: null
            interfaces:
            -   details: {}
                dns: ''
                hostid: '10274'
                interfaceid: '98'
                ip: xxx
                main: 1
                port: '10050'
                type: 1
                useip: 1
            inventory_mode: null
            inventory_zabbix: null
            ipmi_authtype: null
            ipmi_password: null
            ipmi_privilege: null
            ipmi_username: null
            link_templates:
            - Linux by Zabbix agent
            login_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
            login_user: zabbix-api-user
            macros: null
            proxy: null
            server_url: xxx
            state: present
            status: enabled
            tags: null
            timeout: 10
            tls_accept: 2
            tls_connect: 2
            tls_psk: xxx
            tls_psk_identity: xxx
            tls_subject: null
            validate_certs: true
            visible_name: null
    result: Successfully update host xxx (xxx) and linked with template
        '['Linux by Zabbix agent']'
```

**Comment by mu1f407** [comment]
Yes, it's not a bug, it's a feature. Zabbix doesn't return these parameters in host.get response anymore, so there is no way to tell by the module if it was changed or not. It is in documentation of these parameters. I think this is best we can do.

I would recommend to separate setting of tls parameters in another task and execute it only when necessary (using tag or condition for example).

Any ideas how to solve it better @Vanav?

**Comment by D3DeFi** [comment]
Indeed, as of the Zabbix 6.0 (or was it 5.4?) we only have one of two possibilities:
- always update secret and return changed=False to not break idempotency
- always return changed=True when updating secrets, which breaks idempotency, but doesnt lie to a user

we opted for a second version as it is a bit less confusing

**Comment by Vanav** [comment]
Thank you.
So, if you don't want to see `changed` stage, a workaround with `changed_when: false`:

```
- name: "API | Create a new host using agent2 or update an existing host's info"
  delegate_to: localhost
  zabbix_host:
    server_url: '{{ zabbix_api_server_url }}'
    login_user: '{{ lookup("env", "zabbix_api_login_user") or zabbix_api_login_user }}'
    login_password: '{{ lookup("env", "zabbix_api_login_pass") or zabbix_api_login_pass }}'
    host_name: '{{ zabbix_agent_hostname }}'
    host_groups: '{{ zabbix_host_groups }}'
    link_templates: '{{ zabbix_link_templates }}'
    interfaces:
    - type: agent
      main: 1
      useip: 1
      ip: '{{ ansible_host }}'
      port: '{{ zabbix_port }}'
  ignore_errors: '{{ ansible_check_mode }}'    # host_groups may not be available in check mode yet

# Zabbix API for PSK is write-only, so Ansible will always mark as "changed". Ignore "changed" state for PSK.
- name: "API | PSK keys"
  delegate_to: localhost
  zabbix_host:
    server_url: '{{ zabbix_api_server_url }}'
    login_user: '{{ lookup("env", "zabbix_api_login_user") or zabbix_api_login_user }}'
    login_password: '{{ lookup("env", "zabbix_api_login_pass") or zabbix_api_login_pass }}'
    host_name: '{{ zabbix_agent_hostname }}'
    tls_accept: 2     # PSK
    tls_connect: 2    # PSK
    tls_psk: '{{ zabbix_agent2_tlspsk_secret }}'
    tls_psk_identity: '{{ zabbix_agent_hostname }}'
  changed_when: false
```
