### ISSUE TITLE
zabbix_host: bug in deduplicating macros when using force: no

### ISSUE THREAD

**Issue by shk3bq4d** [ansible-collections/community.zabbix#802]
##### SUMMARY
In module zabbix_host , using force: no, it is not possible to set macros that already exists

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_host

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.7]
  config file = /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible.cfg
  configured module search path = ['/home/shk3bq4d/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/shk3bq4d/.virtualenvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/shk3bq4d/git/shk3bq4d/myproject/ans
  executable location = /home/shk3bq4d/.virtualenvs/ansible/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

Zabbix Server 6.08

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: no
  vars:
      zabbix_server_url:            https://myzabbix
      zabbix_server_login_user:     myuser
      zabbix_server_login_password: mypassword
      zabbix_server_validate_certs: no
      host_name:        zabbix-ansible-bug
      status:           enabled
      description:      mydescription
  tasks:

  - name: create host
    community.zabbix.zabbix_host:
      server_url:     "{{ zabbix_server_url }}"
      login_user:     "{{ zabbix_server_login_user }}"
      login_password: "{{ zabbix_server_login_password }}"
      validate_certs: "{{ zabbix_server_validate_certs }}"
      host_name:      "{{ host_name }}"
      status:         "{{ status }}"
      description:    "{{ description }}"
      host_groups:
      - Templates
      interfaces:
      - type: agent
        main:  1
        useip: 1
        ip:    127.0.0.1
        dns:   localhost

      force: yes
      macros:
      - macro: mykey
        value: value step 1

  - name: update macros with force no and long format
    community.zabbix.zabbix_host:
      server_url:     "{{ zabbix_server_url }}"
      login_user:     "{{ zabbix_server_login_user }}"
      login_password: "{{ zabbix_server_login_password }}"
      validate_certs: "{{ zabbix_server_validate_certs }}"
      host_name:      "{{ host_name }}"
      status:         "{{ status }}"
      description:    "{{ description }}"
      force: no
      macros:
      - macro: '{$MYKEY}'
        value: value step 2

  - name: update macros with force no and short format
    community.zabbix.zabbix_host:
      server_url:     "{{ zabbix_server_url }}"
      login_user:     "{{ zabbix_server_login_user }}"
      login_password: "{{ zabbix_server_login_password }}"
      validate_certs: "{{ zabbix_server_validate_certs }}"
      host_name:      "{{ host_name }}"
      status:         "{{ status }}"
      description:    "{{ description }}"
      force: no
      macros:
      - macro: mykey
        value: value step 3
```

##### EXPECTED RESULTS

* playbook doesn't crash
* hosts exists with a macro {$MYKEY} of value of "value step 3"
* macro {$MYKEY} had a value of "value step 2" if third task is skipped

##### ACTUAL RESULTS

* second task fails
* third task fails

```paste below
HOME is /home/shk3bq4d, user is shk3bq4d
vaults_args are --vault-id myproject@secrets/ansible-vault-myproject
ansible-playbook [core 2.12.7]
  config file = /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible.cfg
  configured module search path = ['/home/shk3bq4d/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/shk3bq4d/.virtualenvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/shk3bq4d/git/shk3bq4d/myproject/ans
  executable location = /home/shk3bq4d/.virtualenvs/ansible/bin/ansible-playbook
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
Using /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/shk3bq4d/git/shk3bq4d/myproject/ans/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/shk3bq4d/git/shk3bq4d/myproject/ans/inventory.yml as it did not pass its verify_file() method
Skipping empty key (hosts) in group (python36)
Skipping empty key (hosts) in group (python38)
Skipping empty key (hosts) in group (python39)
Skipping empty key (children) in group (linux_pingable)
Parsed /home/shk3bq4d/git/shk3bq4d/myproject/ans/inventory.yml inventory source with yaml plugin
Loading collection community.zabbix from /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible_collections/community/zabbix
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading collection community.general from /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible_collections/community/general
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading callback plugin community.general.yaml of type stdout, v2.0 from /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible_collections/community/general/plugins/callback/yaml.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: zabbix-bug.yml *******************************************************
Positional arguments: zabbix-bug.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/shk3bq4d/git/shk3bq4d/myproject/ans/inventory.yml',)
vault_ids: ('myproject@secrets/ansible-vault-myproject',)
forks: 25
1 plays in zabbix-bug.yml

PLAY [localhost] ***************************************************************
META: ran handlers

TASK [create host] *************************************************************
task path: /home/shk3bq4d/git/shk3bq4d/myproject/ans/zabbix-bug.yml:13
File lookup using /home/shk3bq4d/git/shk3bq4d/myproject/secrets/zabbix/url as file
File lookup using /home/shk3bq4d/git/shk3bq4d/myproject/secrets/zabbix/username as file
File lookup using /home/shk3bq4d/git/shk3bq4d/myproject/secrets/zabbix/password as file
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: shk3bq4d
<127.0.0.1> EXEC /bin/sh -c 'echo ~shk3bq4d && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/shk3bq4d/.ansible/tmp `"&& mkdir "` echo /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144370.9486167-668628-238175545597557 `" && echo ansible-tmp-1663144370.9486167-668628-238175545597557="` echo /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144370.9486167-668628-238175545597557 `" ) && sleep 0'
Using module file /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<127.0.0.1> PUT /home/shk3bq4d/.ansible/tmp/ansible-local-668597sjybrtft/tmpjk24gmz3 TO /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144370.9486167-668628-238175545597557/AnsiballZ_zabbix_host.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144370.9486167-668628-238175545597557/ /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144370.9486167-668628-238175545597557/AnsiballZ_zabbix_host.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/shk3bq4d/.virtualenvs/ansible/bin/python3.10 /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144370.9486167-668628-238175545597557/AnsiballZ_zabbix_host.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144370.9486167-668628-238175545597557/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => changed=false
  invocation:
    module_args:
      ca_cert: null
      description: mydescription
      force: true
      host_groups:
      - Templates
      host_name: zabbix-ansible-bug
      http_login_password: null
      http_login_user: null
      interfaces:
      - details: {}
        dns: localhost
        hostid: '10415'
        interfaceid: '266'
        ip: 127.0.0.1
        main: 1
        port: '10050'
        type: 1
        useip: 1
      inventory_mode: null
      inventory_zabbix: null
      ipmi_authtype: null
      ipmi_password: null
      ipmi_privilege: null
      ipmi_username: null
      link_templates: null
      login_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      login_user: ansible
      macros:
      - description: ''
        macro: '{$MYKEY}'
        type: '0'
        value: value step 1
      proxy: null
      server_url: https://zabbix.kmydomain/api_jsonrpc.php
      state: present
      status: enabled
      tags: null
      timeout: 10
      tls_accept: null
      tls_connect: null
      tls_psk: null
      tls_psk_identity: null
      tls_subject: null
      validate_certs: true
      visible_name: null

TASK [update macros with force no and long format] *****************************
task path: /home/shk3bq4d/git/shk3bq4d/myproject/ans/zabbix-bug.yml:36
File lookup using /home/shk3bq4d/git/shk3bq4d/myproject/secrets/zabbix/url as file
File lookup using /home/shk3bq4d/git/shk3bq4d/myproject/secrets/zabbix/username as file
File lookup using /home/shk3bq4d/git/shk3bq4d/myproject/secrets/zabbix/password as file
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: shk3bq4d
<127.0.0.1> EXEC /bin/sh -c 'echo ~shk3bq4d && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/shk3bq4d/.ansible/tmp `"&& mkdir "` echo /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144380.3913288-668945-47246611893956 `" && echo ansible-tmp-1663144380.3913288-668945-47246611893956="` echo /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144380.3913288-668945-47246611893956 `" ) && sleep 0'
Using module file /home/shk3bq4d/git/shk3bq4d/myproject/ans/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<127.0.0.1> PUT /home/shk3bq4d/.ansible/tmp/ansible-local-668597sjybrtft/tmph7q8ox17 TO /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144380.3913288-668945-47246611893956/AnsiballZ_zabbix_host.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144380.3913288-668945-47246611893956/ /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144380.3913288-668945-47246611893956/AnsiballZ_zabbix_host.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/shk3bq4d/.virtualenvs/ansible/bin/python3.10 /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144380.3913288-668945-47246611893956/AnsiballZ_zabbix_host.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/shk3bq4d/.ansible/tmp/ansible-tmp-1663144380.3913288-668945-47246611893956/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_fw_91o0e/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 549, in update_host
  File "/home/shk3bq4d/.virtualenvs/ansible/lib/python3.10/site-packages/zabbix_api.py", line 341, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/home/shk3bq4d/.virtualenvs/ansible/lib/python3.10/site-packages/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/home/shk3bq4d/.virtualenvs/ansible/lib/python3.10/site-packages/zabbix_api.py", line 348, in do_request
    return self.parent.do_request(req)
  File "/home/shk3bq4d/.virtualenvs/ansible/lib/python3.10/site-packages/zabbix_api.py", line 297, in do_request
    raise Already_Exists(msg, jobj['error']['code'])
fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
      ca_cert: null
      description: mydescription
      force: false
      host_groups: null
      host_name: zabbix-ansible-bug
      http_login_password: null
      http_login_user: null
      interfaces:
      - available: '0'
        details:
          authpassphrase: ''
          authprotocol: 0
          bulk: 1
          community: ''
          contextname: ''
          privpassphrase: ''
          privprotocol: 0
          securitylevel: 0
          securityname: ''
          version: 2
        disable_until: '0'
        dns: localhost
        error: ''
        errors_from: '0'
        hostid: '10415'
        interfaceid: '266'
        ip: 127.0.0.1
        main: 1
        port: '10050'
        type: 1
        useip: 1
      inventory_mode: null
      inventory_zabbix: null
      ipmi_authtype: null
      ipmi_password: null
      ipmi_privilege: null
      ipmi_username: null
      link_templates: null
      login_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      login_user: ansible
      macros:
      - description: ''
        macro: '{$MYKEY}'
        type: '0'
        value: value step 2
      - description: ''
        macro: '{$MYKEY}'
        type: '0'
        value: value step 1
      proxy: null
      server_url: https://zabbix.kmydomain/api_jsonrpc.php
      state: present
      status: enabled
      tags: null
      timeout: 10
      tls_accept: null
      tls_connect: null
      tls_psk: null
      tls_psk_identity: null
      tls_subject: null
      validate_certs: true
      visible_name: null
  msg: 'Failed to update host zabbix-ansible-bug: (''Error -32602: Invalid params., Invalid parameter "/1/macros/2": value (macro)=({$MYKEY}) already exists. while sending {"jsonrpc": "2.0", "method": "host.update", "params": {"hostid": "10415", "groups": [{"groupid": "1", "name": "Templates", "internal": "0", "flags": "0", "uuid": "7df96b18c230490a9a0a9e2307226338"}], "status": 0, "proxy_hostid": 0, "description": "mydescription", "macros": [{"macro": "{$MYKEY}", "value": "value step 2", "description": "", "type": "0"}, {"macro": "{$MYKEY}", "value": "value step 1", "description": "", "type": "0"}], "interfaces": [{"main": 1, "useip": 1, "ip": "127.0.0.1", "dns": "localhost", "port": "10050", "interfaceid": "266", "hostid": "10415", "type": 1, "available": "0", "error": "", "errors_from": "0", "disable_until": "0", "details": {"version": 2, "bulk": 1, "community": "", "securityname": "", "contextname": "", "securitylevel": 0, "authprotocol": 0, "authpassphrase": "", "privprotocol": 0, "privpassphrase":
    ""}}]}, "auth": "1f459eb7c3186b2ddbd9b2c97304fd4b", "id": 10}'', -32602)'

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
