### ISSUE TITLE
Userparameter task is not executed

### ISSUE THREAD

**Issue by linceaerian** [ansible-collections/community.zabbix#803]
Hello Maintainers

##### SUMMARY

When launching ansible to reconfigure the userparameter on installed agent the task is skipped while it should be executed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community/zabbix/roles/zabbix_agent/tasks/main.yml`

##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.13.2]
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/lince/ansible.cfg) = ['/home/lince/collections']
DEFAULT_FORKS(/home/lince/ansible.cfg) = 5
DEFAULT_HOST_LIST(/home/lince/ansible.cfg) = ['/home/lince/hosts.ini']
DEFAULT_LOG_PATH(/home/lince/ansible.cfg) = /home/lince/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/lince/ansible.cfg) = ['/usr/share/ansible/plugins/lookup']
DEFAULT_MODULE_PATH(/home/lince/ansible.cfg) = ['/home/lince/modules']
DEFAULT_ROLES_PATH(/home/lince/ansible.cfg) = ['/home/lince/roles', '/home/lince/local-roles', '/home/lince/git/zabbix/cookbooks/client/dir/local-roles']
DEFAULT_STDOUT_CALLBACK(/home/lince/ansible.cfg) = yaml
DEFAULT_VARS_PLUGIN_PATH(/home/lince/ansible.cfg) = ['/usr/share/ansible/plugins/vars']
DEFAULT_VAULT_PASSWORD_FILE(/home/lince/ansible.cfg) = /home/lince/ign_vault_pass.txt
HOST_KEY_CHECKING(/home/lince/ansible.cfg) = False
INVENTORY_ENABLED(/home/lince/ansible.cfg) = ['host_list', 'ini', 'vmware_vm_inventory']
RETRY_FILES_ENABLED(/home/lince/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version

* Venv Python 10
* Ansible ansible-playbook [core 2.13.2]
* Ubuntu latest stable

##### STEPS TO REPRODUCE

Create a zabbix agent ansible config with userparameter item and custom script, add a modification to the userparamter code, (ex: adding a new MDW), the tasks for userparameter are skipped in main.yaml

`ansible-playbook playbooks/<playbook_name>.yml -i hosts.ini -i inventory.yml -t userparameter`

```yaml
  vars:
    zabbix_user: "zabbix"
    mdw: ".linux. .ssh. .ping."
  collections:
    - community.zabbix

  pre_tasks:
    - name: "MDW for Postgres"
      ansible.builtin.set_fact:
        mdw: "{{ mdw + ' .pgsql.' }}"
      when: ('pgsql' in inventory_hostname) or (middlewares is defined and 'pgsql' in middlewares)
      tags:
        - config
        - userparameter
    - name: "MDW for Zabbix Server"
      ansible.builtin.set_fact:
        mdw: "{{ mdw + ' .zabbix_server.' }}"
      when: ('zbsrv' in inventory_hostname) or (middlewares is defined and 'zabbix_server' in middlewares)
      tags:
        - config
        - userparameter
  roles:
    - role: zabbix_agent
      become: true
      become_user: root
      zabbix_agent_ip: "{{ ansible_host }}"
      zabbix_agent2: true
      zabbix_agent_runas_user: "{{ zabbix_user }}"
      zabbix_agent_userparameters_templates_src: "../templates/zabbix_agent/userparameters"
      zabbix_agent_userparameters_scripts_src: "playbooks/files/zabbix_agent/scripts"
      zabbix_agent2_hostmetadataitem: "custom.autoregistration"
      zabbix_agent_userparameters:
        - name: autoregistration
```

hosts.ini
```
[minio_standalone]
a-qua-02 middlewares='["zabbix_server","nginx"]'
a-prd-02 middlewares='["zabbix_server","nginx"]'
a-qua-03 middlewares='["zabbix_server","nginx"]'
a-prd-03 middlewares='["zabbix_server","nginx"]'
```

autoregistration.j2
```
UserParameter=custom.autoregistration, echo "{{ mdw }}"; date +%H
```

##### EXPECTED RESULTS

```
TASK [community.zabbix.zabbix_agent : Installing user-defined userparameters] *************************************************************************************************************************************
changed: [a-qua-02] => (item={'name': 'autoregistration'})
changed: [a-prd-03] => (item={'name': 'autoregistration'})
changed: [a-prd-01] => (item={'name': 'autoregistration'})
changed: [a-prd-02] => (item={'name': 'autoregistration'})
changed: [a-qua-01] => (item={'name': 'autoregistration'})
changed: [a-qua-03] => (item={'name': 'autoregistration'})
```

##### ACTUAL RESULTS

Task is skipped with message below:

```paste below
TASK [community.zabbix.zabbix_agent : Including userparameters] ***************************************************************************************************************************************************
included: /home/lince/git/zabbix/cookbooks/client/dir/venv/lib/python3.10/site-packages/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/userparameter.yml for a-prd-01,a-prd-02, a-prd-03, a-qua-01, a-qua-02, a-qua-03

```

##### FIX PROPOSAL

Replace include_tasks per import_tasks

community/zabbix/roles/zabbix_agent/tasks/main.yml
```
- name: "Including userparameters"
  import_tasks: "userparameter.yml"
  when:
    - zabbix_agent_userparameters|length > 0
  tags:
    - zabbix-agent
    - userparameter
```

I think there's a problem during the evaluation of when / include task... Moving to static import task is working.
Not sure exactly of the behavior change, looked at https://serverfault.com/questions/875247/whats-the-difference-between-include-tasks-and-import-tasks for more details but even while commenting the 'when' it does not work with the includes...

Thanks for the module :)
