### ISSUE TITLE
zabbix_agent(2)_tlspsk_auto: true not working

### ISSUE THREAD

**Issue by solick** [ansible-collections/community.zabbix#816]
##### SUMMARY
zabbix_agent(2)_tlspsk_auto: true not working, agent will be configured without encryption. Using zabbix_agent_tlspsk_auto: true on the same config works fine.

##### ISSUE TYPE
auto Generation and configuration of psk config for zabbix_agent2 does not work. Task are skipped.

##### COMPONENT NAME
community.zabbix 1.7.0 + 1.8.0

##### ANSIBLE VERSION
```
ansible [core 2.13.0]

```

##### OS / ENVIRONMENT / Zabbix Version
executing on MacOS 12.6 target system Debian 11.

##### STEPS TO REPRODUCE
Setup a new machine with Debian 11.
Configure ansible for his host to use zabbix_agent2 with psk auto config.

**Comment by solick** [comment]
Ok i checked the task and found that everything with PSK is skipped if zabbix_agent2 is used:

```
- name: "Create directory for PSK file if not exist."
  file:
    path: "{{ zabbix_agent_tlspskfile | dirname }}"
    mode: 0755
    state: directory
  become: true 
  when:
    - zabbix_agent_tlspskfile is defined
    - zabbix_agent_tlspskfile  # https://github.com/ansible-collections/community.zabbix/issues/680
    - not (zabbix_agent2 | bool)
```

how is the process to use PSK with agent2 with the role?
