### ISSUE TITLE
zabbix_agent_tlspsk_auto does not work on macOS

### ISSUE THREAD

**Issue by nicoangelo** [ansible-collections/community.zabbix#830]
##### SUMMARY
`zabbix_agent_tlspsk_auto: true` does not work on macOS

This problem can be worked around by copying the `include_tasks: Darwin.yml` section **after**  `include_tasks: tlspsk_auto_agent2.yml`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.zabbix/roles/zabbix_agent`

##### ANSIBLE VERSION
```
ansible [core 2.12.4]
  config file = /home/na/.ansible.cfg
  configured module search path = ['/home/na/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/na/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/na/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/na/.local/bin/ansible
  python version = 3.10.7 (main, Oct  1 2022, 04:31:04) [GCC 12.2.0]
  jinja version = 3.1.1
  libyaml = True
```

##### CONFIGURATION
no special config

##### OS / ENVIRONMENT / Zabbix Version

Target system:
```
Mac mini (M1, 2020)
macOS 12.6
``` 

##### STEPS TO REPRODUCE

```yaml
# group_vars/zabbix.yml
zabbix_agent_tlspsk_auto: true
---
# main.yml
- hosts: zabbix
  tasks:
    - name: Install and configure Zabbix
      ansible.builtin.import_role:
        name: community.zabbix.zabbix_agent
```

##### EXPECTED RESULTS

/usr/local/etc/zabbix/zabbix_agentd.conf should look like
```
### Option: TLSPSKFile
#       Full pathname of a file containing the pre-shared key.
#
# Mandatory: no
# Default:
# TLSPSKFile=
TLSPSKFile=/etc/zabbix/tls_psk_auto.secret
```

##### ACTUAL RESULTS

```paste below
### Option: TLSPSKFile
#       Full pathname of a file containing the pre-shared key.
#
# Mandatory: no
# Default:
# TLSPSKFile=

```
