### ISSUE TITLE
zabbix-agent2 role API broken

### ISSUE THREAD

**Issue by barzog** [ansible-collections/community.zabbix#864]
Using latest git version of community.zabbix and latest zabbix 5.0. 
When using roles every API calls failed with following error (e.g. TASK [community.zabbix.zabbix_agent : API | Create a new host using agent2 or update an existing host's info] ********************************************************************************):

 FAILED! => {"attempts": 3, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-381735s7r1bj6h/ansible-tmp-1671725114.1689265-384994-83867217858558/AnsiballZ_zabbix_host.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-381735s7r1bj6h/ansible-tmp-1671725114.1689265-384994-83867217858558/AnsiballZ_zabbix_host.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-381735s7r1bj6h/ansible-tmp-1671725114.1689265-384994-83867217858558/AnsiballZ_zabbix_host.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_q47qzzlr/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1289, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_q47qzzlr/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1083, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_q47qzzlr/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 33, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_q47qzzlr/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_q47qzzlr/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'The \"apiinfo.version\" method must be called without the \"auth\" parameter.'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"apiinfo.version\", \"id\": \"b629b0d2-8828-4201-b728-6d93d8b97b8e\", \"params\": {}, **\"auth\": \"fake\"}**\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I think the reason is that with recent support of http auth following was introduced:
if self.get_option('http_login_user'):
            # Provide "fake" auth so netcommon.connection does not replace our headers
            self.connection._auth = {'auth': 'fake'}
        payload = self.payload_builder("user.login", user=username, password=password)

but zabbix api clearly says that apiinfo.version should NOT contain any auth tokens https://www.zabbix.com/documentation/current/en/manual/api/reference/apiinfo/version

**Comment by BGmot** [comment]
You use `http_login_user` and `http_login_password` variables, correct? Can you please post all other variables related to API you are using?
`apiinfo.version` call is made before `user.login` so at this point I can't understand how you get to `apiinfo.version` call with `self.connection._auth` being set.

**Comment by BGmot** [comment]
Though I have one dirty fix for you, would you please try https://github.com/BGmot/community.zabbix/tree/bgmot_fix_httpapi_basic_auth_2 ?

**Comment by barzog** [comment]
No, I don't use any of http_* variables. My role configuration consist of:
```
        zabbix_agent2: true
        zabbix_agent_version: 5.0
        zabbix_agent_package_state: latest
        zabbix_api_server_url: https://<server url>
        zabbix_api_login_user: <login>
        zabbix_api_login_pass: <password>
        zabbix_api_create_hosts: true
        zabbix_api_create_hostgroup: false
        zabbix_macros: <some macros>
        zabbix_agent2_listenip: "127.0.0.1, {{ zbx_agent_listenip|default(ansible_default_ipv4.address) }}"
        zabbix_agent2_server: "127.0.0.1, {{ zbx_server_ip }}"
        zabbix_agent2_allow_key: ['system.run[*]']
        zabbix_agent2_hostname: "{{ zbx_name }}"
        zabbix_agent2_zabbix_alias:
          - 'vfs.fs.discovery[*]:vfs.fs.discovery'
          - 'service.discovery:systemd.service.discovery'
          - 'service.info[*]:systemd.service.info[*]'
        zabbix_agent2_timeout: 20
        zabbix_agent2_include: '/etc/zabbix/zabbix_agent2.d'
        zabbix_agent2_logtype: 'system'
        zabbix_agent2_pidfile: '/var/run/zabbix/zabbix_agent2.pid'
        zabbix_agent2_tlsaccept: "{{ zbx_tls_accept|default(None) }}"
        zabbix_agent2_tlsconnect: "{{ zbx_tls_accept|default(None) }}"
        zabbix_agent2_tlspskfile: "{{ zbx_tls_psk_identity | default(false) | ternary('/etc/zabbix/zabbix_agentd2.psk', None) }}"
        zabbix_agent2_tlspskidentity: "{{ zbx_tls_psk_identity| default(None) }}"
        zabbix_agent2_tlspsk_secret: "{{ zbx_tls_psk_value | default(None) }}"
        zabbix_agent_userparameters_templates_src: zabbix-agent_config
        zabbix_agent_userparameters_scripts_src: zabbix-agent_config
        zabbix_agent_userparameters: "{{ zabbix_userparameters }}"
        zabbix_useuip: "{{ zbx_useip | default(0) }}"
        zabbix_agent_dont_detect_ip: true
        zabbix_host_groups: "{{ zabbix_hostgroups }}"
        zabbix_agent_link_templates: "{{ zabbix_templates }}"
        zabbix_agent_macros: "{{ zabbix_macros|default(None) }}"
        zabbix_agent_proxy: "{{ zabbix_proxy|default(None) }}"
```

I've tried you fix, same error still present:(
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'The "apiinfo.version" method must be called without the "auth" parameter.'} when sending {"jsonrpc": "2.0", "method": "apiinfo.version", "id": "68e161db-322e-422d-9484-bd8773536ec5", "params": {}, "auth": "fake"}
fatal: [awx.managed-it.a1.by -> zabbix.managed-it.a1.by]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-397797jmhmz31r/ansible-tmp-1671782110.1175923-401046-271326448160386/AnsiballZ_zabbix_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-397797jmhmz31r/ansible-tmp-1671782110.1175923-401046-271326448160386/AnsiballZ_zabbix_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-397797jmhmz31r/ansible-tmp-1671782110.1175923-401046-271326448160386/AnsiballZ_zabbix_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_group', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_agakst2s/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py\", line 193, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_agakst2s/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py\", line 165, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_agakst2s/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 33, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_agakst2s/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_group_payload_agakst2s/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'The \"apiinfo.version\" method must be called without the \"auth\" parameter.'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"apiinfo.version\", \"id\": \"68e161db-322e-422d-9484-bd8773536ec5\", \"params\": {}, \"auth\": \"fake\"}\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

I think that proposed fix is applied only when http_login_user is defined (not eq to -42), but in my case it is not defined.
If I change fix to:
```
    def login(self, username, password):
...
        if self.get_option('http_login_user') **and data['method'] != 'apiinfo.version'**:
            # Provide "fake" auth so netcommon.connection does not replace our headers
            self.connection._auth = {'auth': 'fake'}
...
```
then error is different
`fatal: [<control host> -> <zabbix host>]: FAILED! => {"attempts": 3, "changed": false, "msg": "connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Not authorised.'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"hostgroup.get\", \"id\": \"6bc40f2f-04fa-411a-a650-243652469b77\", \"params\": {\"output\": \"extend\", \"filter\": {\"name\": [\"ManagedIT HG\"]}}}"}`

so I assume apiinfo call is ok, but next call that should be with api auth (not basic auth, but zabbix api auth) is not authorized.
