### ISSUE TITLE
zabbix_group_info should be possible to list all available host and template groups

### ISSUE THREAD

**Issue by johansenha** [ansible-collections/community.zabbix#882]
##### SUMMARY

We would like to use zabbix_group_info to list all available groups in order add them to an array or list which can be later used to add/delete/update usergroup permissions. This applies to host and template groups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.zabbix.zabbix_group_info

##### ADDITIONAL INFORMATION

Something like:

```yaml

  - name: List host groups
    community.zabbix.zabbix_group_info:
      hostgroup_name:
        - '*'
      templategroup_name:
        - '*'
    register: groups

```

Todays' error message says

```
 msg: 'Hostgroup not found: [''*'']'
```

As a workaround I guess it should be possible to use httpapi calls natively without the community modules to get the required information.
