### ISSUE TITLE
adding hosts with httpapi plugin

### ISSUE THREAD

**Issue by jefvantongerloo** [ansible-collections/community.zabbix#885]
Could someone explain by full playbook example how to add hosts using the new httpapi plugin?
As the playbook has to run on the zabbix server host for the variables and connections, Ansible cannot be used as intended.
The only way is to use two inventories and loop over in a Ansible play only targeting the zabbix host?

```
---
- name: Create a new host or update an existing host's info
  community.zabbix.zabbix_host:
    host_name: <variable>
    visible_name: <variable>
    interfaces:
      - type: 2
        main: 1
        useip: 1
        ip: <variable>
        details:
          authpassphrase: <variable>
          authprotocol: 1
          securityname: snmpv3
          privpassphrase: <variable>
          privprotocol: 1
          securitylevel: 2
          version: 3
    host_groups:
      - switches
    link_templates:
      - switch template
```
