### ISSUE TITLE
Local python path passed for remote execution

### ISSUE THREAD

**Issue by adepretis** [ansible-collections/community.zabbix#892]
##### SUMMARY

`ansible_python_interpreter` fact set for local API execution interferes with installing user-defined userparameters.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_agent

##### OS / ENVIRONMENT / Zabbix Version

- Target OS: Debian 11

##### STEPS TO REPRODUCE

```yaml
zabbix_agent_userparameters_templates_src: "{{ playbook_dir }}/templates/zabbix/userparameters"
zabbix_agent_userparameters:
  - name: a
  - name: b
  - name: c
```

```yaml
  tasks:
    - name: load | community.zabbix.zabbix_agent
      import_role:
        name: community.zabbix.zabbix_agent
```

##### EXPECTED RESULTS

```yaml
TASK [community.zabbix.zabbix_agent : Installing user-defined userparameters] ***************************************************************************************************************************************************************************************************************************
ok: [my.host] => (item={'name': 'a'})
ok: [my.host] => (item={'name': 'b'})
ok: [my.host] => (item={'name': 'c'})
```

##### ACTUAL RESULTS

```yaml
TASK [community.zabbix.zabbix_agent : Installing user-defined userparameters] ***************************************************************************************************************************************************************************************************************************
ok: [my.host] => (item={'name': 'docker'})
fatal: [my.host]: FAILED! => {}

MSG:

Failed to get information on remote file (/etc/zabbix/zabbix_agentd.d/userparameter_a.conf): /bin/sh: 1: /opt/homebrew/Cellar/ansible/7.1.0/libexec/bin/python3.11: not found
```

##### ANALYSIS

With commit https://github.com/ansible-collections/community.zabbix/commit/ffafe678387f40d1758621744510064aa9ebfa3c the fact `ansible_python_interpreter` is set to the local playbook execution system's Python binary path.

This interferes with

```yaml
  - name: "Installing user-defined userparameters"
    template:
      src: "{{ zabbix_agent_userparameters_templates_src }}/{{ item.name }}.j2"
      dest: "{{ zabbix_agent_include }}/userparameter_{{ item.name }}.conf"
      owner: zabbix
      group: zabbix
      mode: 0644
    notify:
      - restart zabbix-agent
      - restart mac zabbix agent
    become: true
    with_items: "{{ zabbix_agent_userparameters }}"
```
