### ISSUE TITLE
Replace ansible_user with ansible_httpapi_user for httpapi plugin

### ISSUE THREAD

**Issue by niklasweimann** [ansible-collections/community.zabbix#896]
##### SUMMARY
Using ansible_user to determine the user for the zabbix api is not a great option. I would love to see something like ansible_httpapi_user for this.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
httpapi-plugin

##### ADDITIONAL INFORMATION
Using the ansible_user is not a great option, when executing multiple roles in the same playbook. Since the default user on a zabbix server is "Admin" I have to set the ansible_user variable to Admin when I configure the zabbix server, but to initially install the zabbix server I have to log into the server which has either ubuntu or root as the default username.

So to execute the zabbix-install, then the  zabbix-configuration and finally the zabbix-agent-setup I have to save the value of ansible_user (ubuntu/root) into a variable before starting the zabbix-configuration role. Change the value of ansible_user to Admin (for zabbix) and after the zabbix-configuration role I have to switch the value of ansible_user back to it initial value (root/ubuntu) using the second variable which seems to me like an unnecessary overhead, which could easily be resolved by a separate ansible_httpapi_user variable.

```yaml
- name: Init connection parameters
  ansible.builtin.set_fact:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: true
    ansible_httpapi_user: "{{ zabbix_admin_user }}" # new variable
    ansible_host: "{{ zabbix_host_url }}"
    ansible_httpapi_pass: "{{ zabbix_admin_user_password }}"
```
