### ISSUE TITLE
zabbix_user: add support for sendto to be a list (not only a string)

### ISSUE THREAD

**Issue by shk3bq4d** [ansible-collections/community.zabbix#903]
Hello!

##### SUMMARY

module zabbix_user treats medias' `sendto:` to be a string, whereas the zabbix has allowed this field to be a list since zabbix 4.0

sources:
* https://github.com/ansible-collections/community.zabbix/blob/a47fe01ab18954add074c8025f3b8f82d5b07ad0/plugins/modules/zabbix_user.py#L647
* https://www.zabbix.com/documentation/current/en/manual/api/reference/user/object
* https://www.zabbix.com/documentation/4.0/en/manual/api/reference/user/object
* https://www.zabbix.com/documentation/3.4/en/manual/api/reference/user/object

if a module users calls the module with a list, it leads to a zabbix server error due to the module's serialization to JSON

##### ISSUE TYPE
- Feature Idea
- Bugfix (well it's technically not a bug as no one ever claimed this was supported in the first place by the module, anyhow unsuspecting users might feel so)

##### COMPONENT NAME

zabbix_user

##### ADDITIONAL INFORMATION

```yaml
- name: create an user with a single media of type email which has multiple email addresses
  community.zabbix.zabbix_user:
    username: example
    usrgrps:
      - Guests
    passwd: password
    user_medias:
      - sendto:
        - my.first.email@example.com
        - my.second.email@example.com
```
