### ISSUE TITLE
privileges on nested hostgroups

### ISSUE THREAD

**Issue by dhoogfr** [ansible-collections/community.zabbix#905]
##### SUMMARY
Not sure if this is a question, bu, lacking feature or Zabbix API limitation but I'm create a usergroup with privileges on a hostgroup + the hostgroups under this hostgroup.
From the webconsole, you have the "include subgroups" option, but you don't have such an attribute in the usergroup module.

When I give a privilege from the usergroup module on a hostgroup, the child hostgroup gets the "none" privilege, causing the usergroup not getting privileges on that child hostgroup.

I also tried to add a wildcard to the host_group attribute in the usergroup module, but then I get a "host group not found" error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
usergroup

##### ANSIBLE VERSION

```
ansible [core 2.14.1]
  config file = /home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg
  configured module search path = ['/home/dhoogfr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dhoogfr/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/collections
  executable location = /home/dhoogfr/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = False

```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = True
CACHE_PLUGIN(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = 7200
CALLBACKS_ENABLED(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = ['profile_tasks']
COLLECTIONS_PATHS(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = ['/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/collections']
CONFIG_FILE() = /home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg
DEFAULT_GATHERING(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = smart
DEFAULT_ROLES_PATH(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = ['/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/roles', '/etc/ans>
DEFAULT_STDOUT_CALLBACK(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/dhoogfr/exitas/clients/exitas/OCI-DC/ansible_zabbix/code/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

* create hostgroup A
* create sub hostgroup A/B
* create usergroup X with read privileges on hostgroup A

```yaml
    - name: Create user groups
      community.zabbix.zabbix_usergroup:
        server_url: "{{ zabbix_api_server_url }}"
        login_user: "{{ zabbix_api_login_user }}"
        login_password: "{{ zabbix_api_login_pass }}"
        name: A
        rights:
          - host_group: A
            permission: read
        state: present
```

##### EXPECTED RESULTS

Option to provide privileges on hostgroup + include subgroups

##### ACTUAL RESULTS

privilege is correctly given to top hostgroup, but child hostgroup gets privilege "None"

```paste below

```

**Comment by BGmot** [comment]
Zabbix API does not support "include subgroups" option so you need to list all subgroups, like:
```
- name: Create user groups
  community.zabbix.zabbix_usergroup:
    name: X
    hostgroup_rights:
      - host_group: A
        permission: read
      - host_group: A/B
        permission: read
    state: present
```
Although I think it is doable and can be implemented in future.
