### ISSUE TITLE
Zabbix Action: created with wrong condition when using trigger name to id conversion

### ISSUE THREAD

**Issue by acropia** [ansible-collections/community.zabbix#906]
https://github.com/ansible-collections/community.zabbix/blob/c995e2d6682e0469a06cb1c55354b1953b1ac3cd/plugins/modules/zabbix_action.py#L640

### Problem
When creating a Zabbix Action using Ansible module community.zabbix.zabbix_action, and adding conditions with using a trigger name in the trigger type, the wrong trigger is returned and added as condition when you want to reference a specific host linked trigger.

### Details and research
I'm using the Ansible modules from the community.zabbix collection to manage the Zabbix configuration as Infra-as-Code. This working like a charm for various modules and tasks. Now I wanted to created Zabbix Actions, with trigger based conditions I ran into a quircky setup.

An example of a Ansible Playbook Task:
```
- name: Create Zabbix Action Send mail to Jira
  community.zabbix.zabbix_action:
    name: "Send mail to Jira"
    event_source: 'trigger'
    state: present
    status: enabled
    esc_period: 1m
    conditions:
      - type: 'trigger'
        operator: 'equals'
        value: 'Cert: SSL certificate {$CERT.HOSTNAME} expires soon (less than {$CERT.EXPIRY.WARN} days)'
        formulaid: A
      - type: 'trigger'
        operator: 'equals'
        value: 'Cert: SSL certificate {$CERT.HOSTNAME} expires in 4 day'
        formulaid: B
    formula: A or B
```

If I use thse conditions, the trigger name is parsed into an ID by the `get_trigger_by_trigger_name()` function. This should be very convenient for looking up IDs. But it requires the unparsed (with macro's) format to return any results. If I use this unparsed trigger name, a list of triggers is returned by the trigger.get API-call, and the first one is return as result (`return trigger_list[0]`).

In practise this leeds to kinda random behaviour, because the unparsed trigger references all child hosts of a template, and therefor you don't get a specific trigger for a specific host as result.

### What I've tried

- Using type=trigger_name and operator=contains, unwanted because I want to reference very specific host linked trigger
- Using trigger ID's in the value. ID and UUID not accepted.
