### ISSUE TITLE
Error -32500: Application error., Cannot update "groups" for a discovered host

### ISSUE THREAD

**Issue by ironbishop** [ansible-collections/community.zabbix#91]
##### SUMMARY
When disabling a Zabbix host, the task fails if the host has been created by a discovery (`host.flags=4`).

The same issue occours for properties: tls_connect, tls_accept, groups, proxy_hostid.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
https://github.com/ansible-collections/community.zabbix/blob/705bf3da8f04ceb352906410dfeae03fefc83044/plugins/modules/zabbix_host.py#L1123

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = ansible/ansible.cfg
  configured module search path = ['.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ansible/venv/lib64/python3.6/site-packages/ansible
  executable location = ansible/venv/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION
```
DEFAULT_CALLBACK_WHITELIST(ansible/ansible.cfg) = ['profile_tasks', 'timer']
HOST_KEY_CHECKING(ansible/ansible.cfg) = False
INVENTORY_ENABLED(ansible/ansible.cfg) = ['script', 'host_list', 'yaml', 'ini', 'vmware_vm_inventory']
USE_PERSISTENT_CONNECTIONS(ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
* `Linux *** 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* CentOS Linux release 7.6.1810 (Core) 

##### STEPS TO REPRODUCE
1. Use the `zabbix_host_info` to find some hosts.
2. Loop to disable them, leaving a note in the Description field.

```yaml
    - name: enable host in Zabbix Server
      when:
        - item.status == '1'
      environment:
        no_proxy: "127.0.0.1,localhost,.local,{{zabbix_server_host}}"
      local_action:
        module: zabbix_host
        server_url: "{{zabbix_api_url}}"
        validate_certs: no
        login_user: "{{zabbix_api_user}}"
        login_password: "{{zabbix_api_pass}}"
        host_name: "{{item.host}}"
        status: enabled
        description: "{{ item.description + '\n\n' if item.description else '' }}Enabled on {{ lookup('env','CURRENT_TIMESTAMP') }}{{ ' by ' + lookup('env','GITLAB_USER_NAME') + ', using Ansible through Gitlab (job ID: ' + lookup('env','CI_JOB_ID') + ').' if lookup('env','GITLAB_USER_NAME') else '' }}"
      retries: 2
      delay: 2
      throttle: 1
      register: result
      until: result is not failed
      loop: "{{ zabbix_host_infos.hosts }}"
```

##### EXPECTED RESULTS

The module should change only the requested property, in this case "status" and "description", not all of them. Or maybe use `flags` to discern which properties are read-only.

##### ACTUAL RESULTS

Error message: 

* Failed to update host ***omissis***: ('Error -32500: Application error., Cannot update "groups" for a discovered host "***omissis***". while sending {"jsonrpc": "2.0", "method": "host.update", "params": {"hostid": "25149", "groups": [{"groupid": "636"}], "status": 0, "tls_connect": 1, "tls_accept": 1, "proxy_hostid": 18862, "description": "Enabled on Tue Jun 16 18:01:56 CEST 2020"}, "auth": "2ab80fd1bccd459decb84e74049dd5d4", "id": 9}', -32500)
