### ISSUE TITLE
zabbix_authentication throws an exception "ldap_configured"

### ISSUE THREAD

**Issue by kkeane** [ansible-collections/community.zabbix#924]
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
Running the zabbix_authentication module against a Zabbix 6.4 server produces a cryptic exception that only says "Failed to update authentication setting, Exception: 'ldap_configured'".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_authentication. The problem seems to be in line 481

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
Seen in several different Ansible versions.

```
ansible [core 2.12.9]
  config file = /home/kkeane/ansible/ansible.cfg
  configured module search path = ['/home/kkeane/ansible/library/usd', '/home/kkeane/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kkeane/.virtualenvs/ansible5.4/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/kkeane/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/kkeane/.virtualenvs/ansible5.4/bin/ansible
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
CACHE_PLUGIN(/home/kkeane/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/kkeane/ansible/ansible.cfg) = /tmp/ansible_facts
CACHE_PLUGIN_PREFIX(/home/kkeane/ansible/ansible.cfg) = usd-
CACHE_PLUGIN_TIMEOUT(/home/kkeane/ansible/ansible.cfg) = 86400
DEFAULT_FORCE_HANDLERS(/home/kkeane/ansible/ansible.cfg) = True
DEFAULT_FORKS(/home/kkeane/ansible/ansible.cfg) = 120
DEFAULT_HOST_LIST(/home/kkeane/ansible/ansible.cfg) = ['/home/kkeane/ansible/inventory/linux.yaml', '/home/kkeane/ansible/inventory/inventory.foreman.yml', '/home/kkeane/ansible/inventory/satellite.foreman.yml']
DEFAULT_JINJA2_EXTENSIONS(/home/kkeane/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_MANAGED_STR(/home/kkeane/ansible/ansible.cfg) = This file is managed by Ansible.%n
Do not edit this file. Changes will be reverted.%n
template: {file}
user: {uid}
host: {host}
DEFAULT_MODULE_PATH(/home/kkeane/ansible/ansible.cfg) = ['/home/kkeane/ansible/library/usd', '/home/kkeane/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
DEFAULT_PRIVATE_KEY_FILE(/home/kkeane/ansible/ansible.cfg) = /.{{ lookup('env','HOME') }}/.ssh/ansible_ctlr
DEFAULT_REMOTE_USER(/home/kkeane/ansible/ansible.cfg) = svc-ansible
DEFAULT_ROLES_PATH(/home/kkeane/ansible/ansible.cfg) = ['/home/kkeane/ansible/roles', '/home/kkeane/ansible/download-roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
DEFAULT_TIMEOUT(/home/kkeane/ansible/ansible.cfg) = 300
DEFAULT_VAULT_PASSWORD_FILE(/home/kkeane/ansible/ansible.cfg) = /home/kkeane/ansible/vault-passwords
DISPLAY_SKIPPED_HOSTS(/home/kkeane/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/kkeane/ansible/ansible.cfg) = auto
INVENTORY_ENABLED(/home/kkeane/ansible/ansible.cfg) = ['host_list', 'yaml', 'script', 'ini', 'theforeman.foreman.foreman']
(
```

##### OS / ENVIRONMENT / Zabbix Version
Zabbix 6.4 on RedHat 9.1 and on AlmaLinux 9 (happens on both)


##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

It seems to happen regardless of the module parameters. Here are the ones I used:

<!--- Paste example playbooks or commands between quotes below -->
```yaml
 "module_args": {                                                                                                                                                                                                                                                                            "authentication_type": "internal",                                                                                                                                                                                                                                                      "http_auth_enabled": false,                                                                                                                                                                                                                                                             "http_case_sensitive": null,                                                                                                                                                                                                                                                            "http_login_form": null,                                                                                                                                                                                                                                                                "http_login_password": null,                                                                                                                                                                                                                                                            "http_login_user": null,                                                                                                                                                                                                                                                                "http_strip_domains": null,                                                                                                                                                                                                                                                             "ldap_base_dn": null,                                                                                                                                                                                                                                                                   "ldap_bind_dn": null,                                                                                                                                                                                                                                                                   "ldap_bind_password": null,                                                                                                                                                                                                                                                             "ldap_case_sensitive": null,                                                                                                                                                                                                                                                            "ldap_configured": false,                                                                                                                                                                                                                                                               "ldap_host": null,                                                                                                                                                                                                                                                                      "ldap_port": null,                                                                                                                                                                                                                                                                      "ldap_search_attribute": null,                                                                                                                                                                                                                                                          "ldap_userdirectory": null,                                                                                                                                                                                                                                                             "login_password": null,                                                                                                                                                                                                                                                                 "login_user": null,                                                                                                                                                                                                                                                                     "passwd_check_rules": [                                                                                                                                                                                                                                                                     "contain_uppercase_and_lowercase_letters",                                                                                                                                                                                                                                              "contain_digits",                                                                                                                                                                                                                                                                       "contain_special_characters",                                                                                                                                                                                                                                                           "avoid_easy_to_guess"                                                                                                                                                                                                                                                               ],                                                                                                                                                                                                                                                                                      "passwd_min_length": 70,                                                                                                                                                                                                                                                                "saml_auth_enabled": true,                                                                                                                                                                                                                                                              "saml_case_sensitive": true,                                                                                                                                                                                                                                                            "saml_encrypt_assertions": true,                                                                                                                                                                                                                                                        "saml_encrypt_nameid": true,                                                                                                                                                                                                                                                            "saml_idp_entityid": "",                                                                                                                                                                                                                                                                "saml_nameid_format": "urn:oasis:names:tc:SAML:2.0:nameid-format:entity",                                                                                                                                                                                                               "saml_sign_assertions": true,                                                                                                                                                                                                                                                           "saml_sign_authn_requests": true,                                                                                                                                                                                                                                                       "saml_sign_logout_requests": true,                                                                                                                                                                                                                                                      "saml_sign_logout_responses": true,                                                                                                                                                                                                                                                     "saml_sign_messages": true,                                                                                                                                                                                                                                                             "saml_slo_url": "<redacted>",                                                                                                                                                                                                            "saml_sp_entityid": "<redacted>",
"saml_sso_url": "<redacted>",
"saml_username_attribute": "uid",                                                                                                                                                                                                                                                       "server_url": null,                                                                                                                                                                                                                                                                     "timeout": null,                                                                                                                                                                                                                                                                        "validate_certs": null                                                                                                                                                                                                                                                              }
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
Module should return successfully.

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
Module reports an error "Failed to update authentication setting, Exception: 'ldap_configured'"

I did some debugging and found that the root cause is that current_authentication is obtained from the Zabbix API but not properly validated.

The actual exception occurs in line 481 of zabbix_authentication.py, because the current_authentication object does not contain a key "ldap_configured".

current_authentication is obtained from the Zabbix API. It should not blindly assume that the API returns the correct values.

To fix this, the following should be inserted into Authentication::get_authentication():

```
if not 'ldap_configured' in current_authentication:
    current_authentication['ldap_configured'] = '0'
```

This would make "false" the default if the Zabbix API does not return the correct value.

Of course, all other values of current_authentication should also be validated (and defaulted, if needed).
