### ISSUE TITLE
All role tests are failing

### ISSUE THREAD

**Issue by BGmot** [ansible-collections/community.zabbix#939]
Since Apr 3rd, 2023 all our role tests are failing https://github.com/ansible-collections/community.zabbix/actions. Does anybody know what is going on???

**Comment by dj-wasabi** [comment]
I only see: `The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest).` And If I look at https://github.com/actions/runner-images/issues/6002 then on April 3rd, the stopped with ubuntu-18. :) So that means updating the pipelines to ubuntu 20 or 22.

**Comment by BGmot** [comment]
Switching to ubuntu-latest broke all the tests -\ but at least I know what the issue was, thanks @dj-wasabi !

**Comment by dj-wasabi** [comment]
Sorry, I could have mentioned that. Yes, the gitlab runner os version.

**Comment by BGmot** [comment]
No problem -)
Now it just can't execute common nginx role https://github.com/BGmot/community.zabbix/actions/runs/4607572036/jobs/8142258299#step:7:242
/me puzzled

**Comment by BGmot** [comment]
Ansible dev is doing a very strict checking of documentation against real code during sanity tests run. I can fix most of the "errors" but I am stuck with this one:
```
ERROR: plugins/modules/zabbix_action.py:0:0: doc-choices-do-not-match-spec: Argument 'operator' in argument_spec found in conditions defines choices as ([]) but documentation defines choices as (['C(equals) or C(=)', 'C(does not equal) or C(<>)', 'C(contains) or C(like)', 'C(does not contain) or C(not like)', 'C(in)', 'C(is greater than or equals) or C(>=)', 'C(is less than or equals) or C(<=)', 'C(not in)', 'C(matches)', 'C(does not match)', 'C(Yes)', 'C(No)'])
```
Documentation defines:
```
            operator:
                description:
                    - Condition operator.
                    - When I(type) is set to C(time_period), the choices are C(in), C(not in).
                    - C(matches), C(does not match), C(Yes) and C(No) condition operators work only with >= Zabbix 4.0
                    - When I(type) is set to C(maintenance_status), the choices are C(Yes) and C(No) for Zabbix >= 6.0
                choices:
                    - C(equals) or C(=)
                    - C(does not equal) or C(<>)
                    - C(contains) or C(like)
                    - C(does not contain) or C(not like)
                    - C(in)
                    - C(is greater than or equals) or C(>=)
                    - C(is less than or equals) or C(<=)
                    - C(not in)
                    - C(matches)
                    - C(does not match)
                    - C(Yes)
                    - C(No)
```
How do I translate "or" into `argument_spec`, it does not seem to be possible to define `aliases` in `choices` list.
