### ISSUE TITLE
httpapi connections in community.zabbix, how to write task properly

### ISSUE THREAD

**Issue by duchenpaul** [ansible-collections/community.zabbix#957]
I am trying to adapt all my community.zabbix tasks to use httpapi, but I have no idea of how to do that in a good way, here are my plans:

## Plan I:
Import zabbix vars from file.

- httpapi.yml
```yaml
ansible_network_os: community.zabbix.zabbix
ansible_host: "{{ zabbix_host }}"
ansible_connection: httpapi
ansible_httpapi_port: 80
ansible_httpapi_use_ssl: false
ansible_httpapi_validate_certs: false
ansible_user: "{{ zabbix_username }}"
ansible_httpapi_pass: "{{ zabbix_password }}"
ansible_zabbix_url_path: ""
````

- main.yml
```yaml
- name: import zabbix vars
  ansible.builtin.include_vars:
    file: ../../../inventory/group_vars/zabbix/httpapi.yml

- name: Register {{ zabbix_host_hostname }} to zabbix server with {{ ansible_connection }}
  delegate_to: 127.0.0.1
  community.zabbix.zabbix_host:
    description: "Host server: {{ inventory_hostname }}"
    force: yes
    host_name: "{{ zabbix_host_hostname }}"
    visible_name: "{{ zabbix_host_alias | default(zabbix_host_hostname) }}"
    # inventory_mode: automatic
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        port: "10050"
    link_templates: "{{ zabbix_link_templates }}"
    host_groups: "{{ host_groups }}"
    timeout: 40
    proxy: "{{ zabbix_proxy | default() }}"
  retries: 10
  delay: 3
```

**Advantages**
- all zabbix settings can be put in `inventory/group_vars/zabbix/httpapi.yml`

**Disadvantages**
- All the following tasks will use zabbix vars, this is not what I want.

## Plan II:
Use vars in the task.

- main.yml
```yaml
- name: Register {{ zabbix_host_hostname }} to zabbix server with {{ ansible_connection }}
  delegate_to: 127.0.0.1
  community.zabbix.zabbix_host:
    description: "Host server: {{ inventory_hostname }}"
    force: yes
    host_name: "{{ zabbix_host_hostname }}"
    visible_name: "{{ zabbix_host_alias | default(zabbix_host_hostname) }}"
    # inventory_mode: automatic
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        port: "10050"
    link_templates: "{{ zabbix_link_templates }}"
    host_groups: "{{ host_groups }}"
    timeout: 40
    proxy: "{{ zabbix_proxy | default() }}"
  retries: 10
  delay: 3
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_host: "{{ zabbix_host }}"
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_user: "{{ zabbix_username }}"
    ansible_httpapi_pass: "{{ zabbix_password }}"
    ansible_zabbix_url_path: ""
```

**Advantages**
- vars only apply to this task, not the other tasks

**Disadvantages**
- I will have to add this var block to all the community.zabbix tasks, which adds the duplicates, not idea I think.

## Question: 
Do we have any better way to migrate to httpapi?

**Comment by flowerysong** [comment]
The intention behind httpapi connection plugins is that they be used for a host that exists in your inventory and you want to run tasks on, so anything that ignores that design and just tries to juggle variables is going to be a little awkward.

```yaml
all:
  children:
    zabbix:
      zabbix.example.com:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: false
        ansible_user: "{{ zabbix_username }}"
        ansible_httpapi_pass: "{{ zabbix_password }}"
        ansible_zabbix_url_path: ""
```

```yaml
- name: Register {{ zabbix_host_hostname }} to zabbix server
  delegate_to: zabbix.example.com
  community.zabbix.zabbix_host:
    description: "Host server: {{ inventory_hostname }}"
    force: yes
    host_name: "{{ zabbix_host_hostname }}"
    visible_name: "{{ zabbix_host_alias | default(zabbix_host_hostname) }}"
    # inventory_mode: automatic
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        port: "10050"
    link_templates: "{{ zabbix_link_templates }}"
    host_groups: "{{ host_groups }}"
    timeout: 40
    proxy: "{{ zabbix_proxy | default() }}"
```
You can also do things like dynamically add the host with a task:
```yaml
- add_host:
    name: "{{ zabbix_host }}"
    groups: zabbix
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: false
    ansible_user: "{{ zabbix_username }}"
    ansible_httpapi_pass: "{{ zabbix_password }}"
    ansible_zabbix_url_path: ""
```
