### ISSUE TITLE
Error due to missing "version" util module in Ansible 2.9

### ISSUE THREAD

**Issue by meis4h** [ansible-collections/community.zabbix#962]
##### SUMMARY

After updating from 1.9.2 to 1.9.3 we are getting the following error:
```
Could not find imported module support code for community.zabbix.zabbix_maintenance.  Looked for either LooseVersion.py or version.py
```
This error only happens on Ansible 2.9 and after a bit of research i found that this is due to the change from `ansible_collections.community.zabbix.plugins.module_utils.version` to `ansible.module_utils.compat.version` made in https://github.com/ansible-collections/community.zabbix/pull/907 since [`module_utils/compat/version.py`](https://github.com/ansible/ansible/blob/stable-2.14/lib/ansible/module_utils/compat/version.py) does not exist in 2.9.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

/plugins/module_utils/_version.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
```

##### OS / ENVIRONMENT / Zabbix Version

execution environment base image: registry.redhat.io/ansible-automation-platform/ee-29-rhel8:latest

##### STEPS TO REPRODUCE

```yaml
- name: Configure maintenance window
  delegate_to: localhost
  community.zabbix.zabbix_maintenance:
    name: "testing"
    desc: "testing"
    host_name: "{{ zabbix_hostname }}"
    state: "present"
    minutes: "60"
    server_url: "{{ zabbix_server  }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ zabbix_password }}"
```

##### EXPECTED RESULTS

The module is executed without error

##### ACTUAL RESULTS

```paste below
TASK [zabbix_maintenance : Configure maintenance window] ***********************
task path: /runner/project/roles/zabbix_maintenance/tasks/main.yaml:1
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/runner/.ansible/tmp `"&& mkdir "` echo /home/runner/.ansible/tmp/ansible-tmp-1681726198.3068151-26-231007270557151 `" && echo ansible-tmp-1681726198.3068151-26-231007270557151="` echo /home/runner/.ansible/tmp/ansible-tmp-1681726198.3068151-26-231007270557151 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/runner/.ansible/tmp/ansible-tmp-1681726198.3068151-26-231007270557151/ > /dev/null 2>&1 && sleep 0'
fatal: [sp-sppat-centos7 -> localhost]: FAILED! => {
    "msg": "Could not find imported module support code for community.zabbix.zabbix_maintenance.  Looked for either LooseVersion.py or version.py"
}
```
