### ISSUE TITLE
community.zabbix.zabbix_host module not working properly on zabbix 6.4

### ISSUE THREAD

**Issue by Skultey** [ansible-collections/community.zabbix#972]
##### SUMMARY
After updating to zabbix 6.4 our playbook started failing on adding zabbix hosts using community.zabbix.zabbix_host module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_host

##### ANSIBLE VERSION
ansible 2.9.6

##### OS / ENVIRONMENT / Zabbix Version
Ubuntu latest, Zabbix 6.4

##### STEPS TO REPRODUCE

```- name: Create a new host on Zabbix
    local_action:
      module: community.zabbix.zabbix_host
      server_url: "{{server_url}}"
      login_user: Tteam
      login_password: "{{ login_password }}"
      host_name: "{{ zabbix_hostname }}"
      host_groups:
        - P_hosts
      link_templates:
        - Basic_Template
      status: enabled
      state: present
      inventory_mode: manual
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{ ansible_host }}"
          port: "10050"
      tls_accept: 2
      tls_connect: 2
      tls_psk: "{{ tls_psk }}" 
      tls_psk_identity: "{{ tls_psk_id }}"

```

##### EXPECTED RESULTS
We are expected things done so this task is creating a host in zabbix using our parameters. 

##### ACTUAL RESULTS
FAILED! => {"changed": false, "msg": "Failed to connect to Zabbix server: ('Error -32602: Invalid params., Invalid parameter \"/\": unexpected parameter \"user\". while sending {\"jsonrpc\": \"2.0\", \"method\": \"user.login\", \"params\": {\"user\": \"Tteam\", \"password\": \"********\"}, \"id\": 0}', -32602)"}

**Comment by hackatoo** [comment]
We are patiently waiting for fixes, but our automatization based on this module. 
When it will be released, guys? Any info?

**Comment by pyrodie18** [comment]
What version of the collection are you using?

**Comment by masa-orca** [comment]
Hi, Reviewers.
Thank you for your reviewing. I appologize for taking much times to modify.
I read [creating-an-info-or-a-facts-module](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module) (@D3DeFi mentioned). 
The document says 
> Modules that query/return general information (and not ansible_facts) should be named _info. General information is non-host specific information, for example information on online/cloud services (you can access different accounts for the same online service from the same host), or information on VMs and containers accessible from the machine, or information on individual files or programs.

Therefor, I think it is `_info` module.

> To be honest I'd rename this module to either zabbix_api_info or zabbix_api_facts.

I agree it. I renamed module to `zabbix_api_info `.

**Comment by hackatoo** [comment]
@pyrodie18 community-zabbix-1.9.3 (currently)

**Comment by salfers** [comment]
It appears that the deprecated way of specifying `server_url`, `login_user` and does not and will never work with 6.4.
See here https://github.com/ansible-collections/community.zabbix/issues/950#issuecomment-1507302099

**Comment by Skultey** [comment]
I've downloaded the newest version of zabbix module but it has some issues 

`FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.zabbix.zabbix_host) module: login_password, login_user, server_url Supported parameters include: ca_cert, description, force, host_groups, host_name, http_login_password, http_login_user, interfaces, inventory_mode, inventory_zabbix, ipmi_authtype, ipmi_password, ipmi_privilege, ipmi_username, link_templates, macros, proxy, state, status, tags, tls_accept, tls_connect, tls_psk, tls_psk_identity, tls_subject, visible_name"}`

I've tried replacins login_password and login_user to the http version but I can't enter the server_url. 
There are no supported parameters out here.

**Comment by jirikotlin** [comment]
Same problem with fresh install of 2.0.0. 
At my older laptop everything works with 1.9.2 but downgrading this module did not help.

**Comment by jirikotlin** [comment]
Further investigation in my case is that password auth works in 2.0.0:

ansible_user: Admin
ansible_httpapi_pass: zabbix

But my playbooks with API token (ansible_zabbix_auth_key) does not work, it is omited, token not even sended to zabbix, and result:

ansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/username": a character string is expected.'} when sending {"jsonrpc": "2.0", "method": "user.login", "id": "6322c6f9-887e-4201-a301-a6ebfee3b337", "params": {"username": null, "password": null}}

**Comment by hackatoo** [comment]
Seems like in the new version there is no more variables as @Skultey metioned, so you need to update the params used for requesting data from Zabbix API, and also adding hosts.
_For those, who just want to make it working now_: update zabbix-api python library to 0.5.6, and rollback to 1.7.0 community.zabbix module version

**Comment by BGmot** [comment]
@tovoro we need to see how you set up all API related variables too. Please provide.

**Comment by tovoro** [comment]
thanks for the reply,  it was an credential issue on my side in conjunction with awx. It works now, sorry for that

> @tovoro we need to see how you set up all API related variables too. Please provide.

**Comment by BGmot** [comment]
Hi @Skultey @eliottcassidy2000 @hackatoo @jirikotlin @salfers!
Do any of you still have problems/questions about zabbix_host with Zabbix 6.4 using collection version 2.0? If nobody replies within a week I'll close this issue.

**Comment by Kulgar** [comment]
Hello @BGmot I still have the "Session terminated, re-login, please." error message on my part with collection v2.0 and Zabbix 6.4

My credentials seem right as I managed to perform an auth using curl

**Comment by eliottcassidy2000** [comment]
> Hi @Skultey @eliottcassidy2000 @hackatoo @jirikotlin @salfers! Do any of you still have problems/questions about zabbix_host with Zabbix 6.4 using collection version 2.0? If nobody replies within a week I'll close this issue.

honestly, I tried my best to get version 2.0.1 working but it just doesnt seem worth it. Kept it at 1.9.3 and just set zabbix-api to 0.5.6 and that worked perfectly. I don't think we will be upgrading to 2.x for the foreseeable future. In my opinion, using httpapi for the ansible connection and having to delegate the task to a zabbix server seems really silly. Our zabbix url is loadbalanced and so we don't really want to send traffic to a hardcoded zabbix server in our ansible playbooks. We send all traffic to the virtual IP for our zabbix instance and the loadbalancer sends it to whatever server, we would like all connections to our zabbix to follow that basic pattern. Also the new solution is much more cumbersome to write in code, and judging from the across the board confusion I've seen various github issues I would say it is also unclear. The documentation on docs.ansible.com is also pretty hard to decipher, if I hadn't spent hours reading through issues I would feel so lost looking at it. Out current use of this module is essentially just a clean wrapper for zabbix API calls for our playbooks (we only use the plugins, haven't touched the roles at all). The playbooks we run don't have our zabbix servers in the inventories, we mainly just use it to make a quick API call for a maintenance window. Not trying to hate, and I do really appreciate the fact that this module exists, but 2.x feels like a step backward. As far as i can tell, the roles of this collection and the plugins seemed to be two separate things. Maybe it made sense to change the plugins in this way to better mesh with existing code, but it seemed like the collections (whose primary purpose is to make API calls to a zabbix server) really meshed well with that zabbix-api python package, and I would have kept them straightforward like that. Thank you for your work on this module regardless

**Comment by tovoro** [comment]
> > Hi @Skultey @eliottcassidy2000 @hackatoo @jirikotlin @salfers! Do any of you still have problems/questions about zabbix_host with Zabbix 6.4 using collection version 2.0? If nobody replies within a week I'll close this issue.
> 
> honestly, I tried my best to get version 2.0.1 working but it just doesnt seem worth it. Kept it at 1.9.3 and just set zabbix-api to 0.5.6 and that worked perfectly. I don't think we will be upgrading to 2.x for the foreseeable future. In my opinion, using httpapi for the ansible connection and having to delegate the task to a zabbix server seems really silly. Our zabbix url is loadbalanced and so we don't really want to send traffic to a hardcoded zabbix server in our ansible playbooks. We send all traffic to the virtual IP for our zabbix instance and the loadbalancer sends it to whatever server, we would like all connections to our zabbix to follow that basic pattern. Also the new solution is much more cumbersome to write in code, and judging from the across the board confusion I've seen various github issues I would say it is also unclear. The documentation on docs.ansible.com is also pretty hard to decipher, if I hadn't spent hours reading through issues I would feel so lost looking at it. Out current use of this module is essentially just a clean wrapper for zabbix API calls for our playbooks (we only use the plugins, haven't touched the roles at all). The playbooks we run don't have our zabbix servers in the inventories, we mainly just use it to make a quick API call for a maintenance window. Not trying to hate, and I do really appreciate the fact that this module exists, but 2.x feels like a step backward. As far as i can tell, the roles of this collection and the plugins seemed to be two separate things. Maybe it made sense to change the plugins in this way to better mesh with existing code, but it seemed like the collections (whose primary purpose is to make API calls to a zabbix server) really meshed well with that zabbix-api python package, and I would have kept them straightforward like that. Thank you for your work on this module regardless

I completely agree.

**Comment by pyrodie18** [comment]
We appreciate your feedback @tovoro and @eliottcassidy2000

**Comment by Bigsmooth68** [comment]
Hello @eliottcassidy2000 
Despite few research, I did not find a proper way to rollback a collection. Would you please let me know how to do it?
Thanks,
Olivier

**Comment by J4RF** [comment]
Got my old task from a few years back to work with the new version, here's a snippet in case it helps anyone. Note that you have to have your Zabbix server as the host the playbook is running against, as it's no longer an option to provide it dynamically (one of many regressions in the new version, but maybe the most sensible of them).

Old version:
```
- name: Add host to Zabbix server
  zabbix_host:
    server_url: '{{zabbix_server_url}}'
    login_user: '{{zabbix_user}}'
    login_password: '{{zabbix_pass}}'
    host_name: '{{hostname}}'
    visible_name: '{{hostname}}'
    host_groups: '{{zabbix_groups}}'
    link_templates: '{{zabbix_templates}}'
    interfaces:
      - type: '{{interface_type}}'
        main: '{{interface_is_main}}'
        ip: '{{ip_address}}'
        useip: '{{use_interface_ip}}'
        dns: '{{hostname}}'
        port: '{{agent_port}}'
    status: enabled
    state: present
```

<br>

New version:
```
- name: Add host to Zabbix server
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_zabbix_url_path: ''
    ansible_user: '{{zabbix_user}}'
    ansible_httpapi_pass: '{{zabbix_pass}}'
  zabbix_host:
    host_name: '{{hostname}}'
    visible_name: '{{hostname}}'
    host_groups: '{{zabbix_groups}}'
    link_templates: '{{zabbix_templates}}'
    interfaces:
      - type: '{{interface_type}}'
        main: '{{interface_is_main}}'
        useip: '{{use_interface_ip}}'
        ip: '{{ip_address}}'
        dns: '{{hostname}}'
        port: '{{agent_port}}'
    status: enabled
    state: present
```

It seems many senseless changes have been made in newer releases. Probably the most alarming is the fact that, even though they are documented parameters, `http_login_user` and `http_login_password` do not actually get used. Instead, the module assumes the machine credential's username/password to be the HTTP API username/password for Zabbix (because that makes loads of sense). This introduces a vulnerability where, in the event of a failure, the machine credential can be read as plain text (even if it is a securely stored credential in AWX). 

I would open an issue to properly criticize this mess if I had the time.
