### ISSUE TITLE
community.zabbix.zabbix_host does not handle optional interfaces in Z 6.4 

### ISSUE THREAD

**Issue by sa-JanOldach** [ansible-collections/community.zabbix#975]
##### SUMMARY
With Zabbix 6.4 a host interface is no longer required for item types originating directly from the zabbix server such as Simple Checks, External Check etc. When creating hosts with interface using the zabbix_host module and assigning a template containing simple checks such as icmpping, the items on the hosts will spawn "not supported" as they default to Host Interface = None instead of picking up an interface created with the module. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_host

##### ANSIBLE VERSION
```
2.12.4
```

##### OS / ENVIRONMENT / Zabbix Version
Ubuntu Latest, Zabbix 6.4

##### STEPS TO REPRODUCE

```
- hosts: hosts
  connection: local
  tasks:
    - name: Create a new host or update an existing host's info
      community.zabbix.zabbix_host:
        host_name: '{{ inventory_hostname }}'
        validate_certs: false
        visible_name: '{{ inventory_hostname }}'
        server_url: "{{server_url}}"
        login_user: user
        login_password: password
        host_groups:
          - host_group
        link_templates:
          - Template ICMP Ping
        status: enabled
        state: present
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: '{{ ansible_host }}'
            dns: ""
            port: 10050
```

##### EXPECTED RESULTS
Check will try to use created interface

##### ACTUAL RESULTS
Items are created with option host interface = none and become not-supported shortly after. The field can - to my knowledge - not be mass updated nor automated using ansible modules.
