### ISSUE TITLE
ansible_zabbix_auth_key not propagated to httpapi

### ISSUE THREAD

**Issue by jirikotlin** [ansible-collections/community.zabbix#988]
##### SUMMARY

ansible_zabbix_auth_key not propagated to httpapi and therefor result is: 

ansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/username": a character string is expected.'} when sending {"jsonrpc": "2.0", "method": "user.login", "id": "6322c6f9-887e-4201-a301-a6ebfee3b337", "params": {"username": null, "password": null}}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.netcommon    5.0.0  
ansible.posix        1.5.2  
ansible.utils        2.10.1 
ansible.windows      1.14.0 
community.general    7.0.0  
community.mysql      3.7.0  
community.postgresql 2.4.1  
community.zabbix     2.0.0

##### ANSIBLE VERSION

```

ansible [core 2.14.5]
  config file = /Users/kotlinj/Documents/git/zabbix/ansible.cfg
  configured module search path = ['/Users/kotlinj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kotlinj/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/kotlinj/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/kotlinj/Library/Python/3.9/bin/ansible
  python version = 3.9.6 (default, Mar 10 2023, 20:16:38) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Library/Developer/CommandLineTools/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version
zabbix_server (Zabbix) 6.4.1
ansible running from MacOS Ventura 13.3.1

##### STEPS TO REPRODUCE

```yaml

  - name: Set connection specific variables
    set_fact:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: true
      ansible_httpapi_validate_certs: false
      ansible_zabbix_auth_key: xxxxxxxxxxxxxxxxxxxxx
      ansible_python_interpreter: '/usr/bin/python3'
      ansible_become: false
    delegate_to: zabbix.example.host
    delegate_facts: true      

  - name: Insert host into zabbix inventory
    community.zabbix.zabbix_host:
      host_name: "sometest"
      host_groups:
        - Linux servers
      status: enabled
      state: present
      inventory_mode: automatic
      proxy: "zabbix-proxy.name.example"
    delegate_to: zabbix.example.host
    delegate_facts: true  



##### EXPECTED RESULTS

Host added.

##### ACTUAL RESULTS

self.auth_key = self.get_option('zabbix_auth_key')
Not defined in https://github.com/ansible-collections/community.zabbix/blob/main/plugins/httpapi/zabbix.py#L77

And therefor error:

ansible.module_utils.connection.ConnectionError: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter "/username": a character string is expected.'} when sending {"jsonrpc": "2.0", "method": "user.login", "id": "6322c6f9-887e-4201-a301-a6ebfee3b337", "params": {"username": null, "password": null}}

**Comment by jirikotlin** [comment]
Workaround for me is redefine variable in **self.auth_key = self.get_option('zabbix_auth_key')**  httpapi\zabbix.py.
https://github.com/ansible-collections/community.zabbix/blob/main/plugins/httpapi/zabbix.py#L77

Still can not figure why **ansible_zabbix_auth_key** is not correctly propagated to httpapi.

**Comment by BGmot** [comment]
My full playbook 988_auth_key.yml (ls1 is the hostname of my Zabbix test instance):
```
---
- hosts: ls1
  gather_facts: false
  tasks:
  - name: Set connection specific variables
    set_fact:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 8080
      ansible_httpapi_use_ssl: false
      ansible_httpapi_validate_certs: false
      ansible_zabbix_auth_key: 49507a4d8763***6c7904ded608a
      ansible_become: false

  - name: Insert host into zabbix inventory
    community.zabbix.zabbix_host:
      host_name: "sometest"
      host_groups:
        - Linux servers
      status: enabled
      state: present
      inventory_mode: automatic
    delegate_to: ls1
```

Runs and adds the host without a problem:
```
~/ansible$ ansible-playbook -i ls1, 988_auth_key.yml

PLAY [ls1] *********************************************************************************************************************************************************************************************************

TASK [Set connection specific variables] ***************************************************************************************************************************************************************************
ok: [ls1]

TASK [Insert host into zabbix inventory] ***************************************************************************************************************************************************************************
[WARNING]: Persistent connection logging is enabled for ls1. This will log ALL interactions to /home/ey/tmp/ansible.log and WILL NOT redact sensitive configuration like passwords. USE WITH CAUTION!
changed: [ls1]

PLAY RECAP *********************************************************************************************************************************************************************************************************
ls1                        : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
