### ISSUE TITLE
Collection 2.0.0 - Zabbix agent installation on windows fails

### ISSUE THREAD

**Issue by xdkreij** [ansible-collections/community.zabbix#990]
https://github.com/ansible-collections/community.zabbix/issues/703
Somewhat similar issue.

##### SUMMARY
Any attempt to install the zabbix agent on Windows 11 (or 10 for that matter) fails. It contains 2 task related issues, both in main.yml of the zabbix_agent role

Issue 1: 'zabbix_valid_agent_versions' does not exists

fine.. so we set one up as a var `zabbix_valid_agent_versions=6.4`

Issue 2: float object has no attribute '10'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent/tasks/main.yml

##### ANSIBLE VERSION

```bash
ansible [core 2.14.5]
  config file = /home/ansible/projects/zabbix/ansible.cfg
  configured module search path = ['/home/ansible/projects/zabbix/library/modules']
  ansible python module location = /home/ansible/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/projects/zabbix/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.9.13 (main, Nov 16 2022, 15:31:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```bash
CACHE_PLUGIN(/home/ansible/projects/zabbix/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ansible/projects/zabbix/ansible.cfg) = cache
CACHE_PLUGIN_TIMEOUT(/home/ansible/projects/zabbix/ansible.cfg) = 300
COLLECTIONS_PATHS(/home/ansible/projects/zabbix/ansible.cfg) = ['/home/ansible/projects/zabbix/collecti>
CONFIG_FILE() = /home/ansible/projects/zabbix/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/home/ansible/projects/zabbix/ansible.cfg) = ['/home/ansible/projects/zabbix>
DEFAULT_CALLBACK_PLUGIN_PATH(/home/ansible/projects/zabbix/ansible.cfg) = ['/home/ansible/projects/zabb>
DEFAULT_FORKS(/home/ansible/projects/zabbix/ansible.cfg) = 5
DEFAULT_HOST_LIST(/home/ansible/projects/zabbix/ansible.cfg) = ['/home/ansible/projects/zabbix/inventor>
DEFAULT_MANAGED_STR(/home/ansible/projects/zabbix/ansible.cfg) = This file is managed with Ansible, your ch>
DEFAULT_MODULE_PATH(/home/ansible/projects/zabbix/ansible.cfg) = ['/home/ansible/projects/zabbix/librar>
DEFAULT_REMOTE_USER(/home/ansible/projects/zabbix/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/ansible/projects/zabbix/ansible.cfg) = ['/home/ansible/projects/zabbix/roles']
DEFAULT_STDOUT_CALLBACK(/home/ansible/projects/zabbix/ansible.cfg) = community.general.yaml
HOST_KEY_CHECKING(/home/ansible/projects/zabbix/ansible.cfg) = False
INTERPRETER_PYTHON(/home/ansible/projects/zabbix/ansible.cfg) = auto_silent
INVENTORY_ENABLED(/home/ansible/projects/zabbix/ansible.cfg) = ['constructed', 'yaml', 'ini']
RETRY_FILES_ENABLED(/home/ansible/projects/zabbix/ansible.cfg) = False

```

##### OS / ENVIRONMENT / Zabbix Version

target os: Windows 11

facts:
``` json
"ansible_distribution": "Microsoft Windows 11 Pro",
"ansible_distribution_major_version": "10",
"ansible_distribution_version": "10.0.22621.0",
```

##### STEPS TO REPRODUCE

1. get a basic (test) playbook to install the zabbix agent on windows 11 and kick it off

```yaml
- hosts: all
  gather_facts: yes
  roles:
     - role: community.zabbix.zabbix_agent
       zabbix_agent_server: <ip here>
       zabbix_agent_serveractive: <ip here>
       zabbix_api_server_host: <some fqdn>
       zabbix_api_login_user: Admin
       zabbix_api_login_pass: zabbix
       zabbix_api_create_hostgroup: true
       zabbix_api_create_hosts: true
       zabbix_agent_host_state: present
       zabbix_host_groups:
         - Windows Servers
       zabbix_agent_link_templates:
         - Template OS Windows
         - Apache APP Template
       zabbix_agent_macros:
         - macro_key: apache_type
           macro_value: reverse_proxy
           macro_type: text
       zabbix_agent_tags:
         - tag: environment
           value: production
```

##### EXPECTED RESULTS

1. zabbix_valid_agent_version**S** to exists per default, or either be documented...
2. A proper mapping between windows versions and supported agents (if even required..)
   side note: `ansible_distribution_major_version` does not contain floats?
3. the installation procedure to proceed installing on Windows (as version 1.9.3 does fine for me so far..)

##### ACTUAL RESULTS

```bash
TASK [community.zabbix.zabbix_agent : Set More Variables] ******************************************************
fatal: [lab-client1.domain.local]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'zabbix_valid_agent_versions' is undefined. 'zabbix_valid_agent_versions' is undefined
  
    The error appears to be in '/home/ansible/projects/zabbix/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml': line 23, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Set More Variables
      ^ here

```

AND

```bash
TASK [community.zabbix.zabbix_agent : Set More Variables] ******************************************************
fatal: [lab-client1.domain.local]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'float object' has no attribute '10'. 'float object' has no attribute '10'
  
    The error appears to be in '/home/ansible/projects/zabbix/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml': line 23, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Set More Variables
      ^ here
```
